### ISSUE TITLE
allowing camel-case props

### ISSUE THREAD

**Issue by mark-hahn** [yyx990803/vue#1000]
Wouldn't this ...

```
props: {
  'prop-a': String, // type check constructor
  'prop-b': null, // accept any type
  'prop-c': { // object descriptor
    type: Number,
    required: true,
    default: 100 // new: default value
  }
}
```

Match the other options more if it was ...

```
props: {
  propA: String, // type check constructor
  propB: null, // accept any type
  propC: { // object descriptor
    type: Number,
    required: true,
    default: 100 // new: default value
  }
}
```

The camel case would appear in the html as `prop-a` of course.

**Comment by mark-hahn** [comment]
Also, it would match the variable names where they are used.  Right now there is a mis-match that makes the code readability hard.

I think all html should be snake-case (prop-a) and all code should be camelcase (propA).  It is a consistency issue.

**Comment by yyx990803** [comment]
HTML attributes are case-insensitive. There's no way to differentiate `propA` vs. `propa` when you are passing a prop in the template.

**Comment by yyx990803** [comment]
HTML attributes are case-insensitive. There's no way to differentiate `propA` vs. `propa` when you are passing a prop in the template.

**Comment by mark-hahn** [comment]
> HTML attributes are case-insensitive.

I know it's weird but I don't like the ugliness of  'prop-a': value`.  This
isn't needed anywhere else in my code, even in the html.  My template
processor changes `propA` to `prop-a` even in the html.

I agree you shouldn't change it even though I wish it worked this way.
Making it an option would be nice.  When I'm done with my current project
maybe I'll issue a PR.

**Comment by yyx990803** [comment]
I gave it another thought and maybe this can be implemented with backwards compatibility. Vue could detect camel case props and look for hyphenated attributes in HTML.

**Comment by akralj** [comment]
+1
I get objects from a server model where I use camelCase and it would be great if i could use the same names without getting the warning from vue.
thanks

**Comment by young-steveo** [comment]
:+1:  Converting camelcase props to hyphenated attributes is a pretty standard/accepted convention.

**Comment by mark-hahn** [comment]
That was quick.  Thanks.

**Comment by simonmysun** [comment]
Although HTML attributes are case-insensitive, I think we still need to distinguish the letter case, because there are not only HTML DOMs, and Vuejs seems willing to support SVG. 

Here's an example: https://jsfiddle.net/voecgwp1/

The left side one does not work in Google Chrome 51.0.2704.106 on Archlinux. The v-bind causes the failure, and text binding leaves an error.

**Comment by simonmysun** [comment]
@yyx990803 shall i open a new issue for this?

**Comment by yyx990803** [comment]
@simonmysun yes please open a new one.

**Comment by simonmysun** [comment]
Ok~
https://github.com/vuejs/vue/issues/3263
