### ISSUE TITLE
Use a real extend helper

### ISSUE THREAD

**Issue by JosephSilber** [yyx990803/vue#1002]
While trying to use `Vue.util.extend`, I realized it is a very basic implementation; it doesn't support deep extending and it doesn't support extending from multiple sources.

Can we please move the [resource's `extend` helper](https://github.com/vuejs/vue-resource/blob/master/src/util.js#L38-L68) into the vue core?

**Comment by yyx990803** [comment]
It's not in core because core doesn't need it. Vue core's util is by design internal, and is exposed only because advanced users and plugin authors may find some of it useful. If you need a specific helper, you should either bring your own or use an actual general-purpose util library like lodash.
