### ISSUE TITLE
Allow register of asset with array rather than object

### ISSUE THREAD

**Issue by fergaldoyle** [yyx990803/vue#1003]
Instead of registering global assets (components, directives, etc) I prefer the pattern of registering private assets as it explicitly states what assets are available to a component.

Currently if I want to register a private asset I need to use a hash, e.g. 

```javascript
{
    components: {
        'componentId' : {
            ...
        }
    },
    directives: {
        'directiveId' : {
            ...
        }
    }
}
```
But this means that I have to manually maintain the id / selector of the asset. I'd want the asset to have the same id / selector across all components in an app for consistancy.

Consider something like this:
```javascript
import { paginComponent } from 'components/pagin/pagin';
import { actionMenuComponent } from 'components/action-menu/action-menu';
import { inputDirective } from 'directives/input';

export var pageManager = {
    template: require('./page-manager.html'),
    components: [paginComponent, actionMenuComponent],
    directives: [inputDirective],
    ...
};
```
`paginComponent` `actionMenuComponent` and `inputDirective` would all self define thier default id / selector, e.g:
```javascript
export var paginComponent = {
    selector: 'pagin',
    props: ['item-count', 'page-size', 'current-page', 'page-change'],
    template: require('./pagin.html'),
    ...
}
```
When an asset is registered with an array opposed to an object hash, the id / selector is pulled from the `selector` property (might be better to use `id` property for consistency with all asset types)

Currently to achieve this, i have a small utility function to register assets which creates a hash out of an array of assets, using the `selector` property of each asset create a hash as Vue expects:
```javascript
{
    ...
    components: reg(paginComponent, actionMenuComponent, subComponent),
    directives: reg(inputDirective),
    ...
}

function reg() {
    var out = {};
    for (var i = 0; i < arguments.length; i++) {
        out[arguments[i].selector] = arguments[i];
    }
    return out;
}
```

Allowing the use of array vs object when registering assets would be a non breaking change and allows for the above syntax which I think is nice.

**Comment by fergaldoyle** [comment]
Also along these lines, if it was possible to have a "strict mode", where instead of private assets that will be available to a Vue instance and its children (and descendants), they are only available to the Vue instance and NOT it's children / descendants.

Forcing the children to state their asset dependencies rather than getting them from the parent seems to me to equal better decoupling.

**Comment by cheapsteak** [comment]
+1 on both
The array syntax would also make obsolete #1029
Current project has 24 components declared in the root app because people keep sticking everything there out of convenience. Strict mode would be lovely.

**Comment by yyx990803** [comment]
Both supported now via 5fb37fb12cb6245914c3f0ec99aa4822835f6d5c and 17e4b33b7a71f0c9d5c358854f45998ca9f8b78a . Note all assets use the same `id` field, and strict mode defaults to false.

**Comment by fergaldoyle** [comment]
Great stuff

**Comment by cheapsteak** [comment]
How do you specify the selector of a component registered in an array?  
It wasn't mentioned in the [0.12.8 release notes](https://github.com/yyx990803/vue/releases/tag/0.12.8)

**Comment by yyx990803** [comment]
@cheapsteak use an `id` field. I've added it to the release note.

**Comment by cheapsteak** [comment]
Thanks!
