### ISSUE TITLE
`ready` method is not called on child component

### ISSUE THREAD

**Issue by FWeinb** [yyx990803/vue#1005]
While trying this framework using `vue-loader` and `webpack` I noticed that the `ready` method on a child component isn't called. At first I though that it must be some problem with `vue-loader` after but building a reduced test cased I think this is a problem with `vue@0.12.5`.

You can find the test case [here](http://jsbin.com/cucowa/2/edit?js,output).

**Comment by crswll** [comment]
If you don't use `Vue.extend()` it calls the ready hook. Unless there's a reason for that I'm not aware of, which is very likely, I think that's the problem.

**Comment by FWeinb** [comment]
I am using `Vue.extend()` in the test case.

**Comment by FWeinb** [comment]
@yyx990803 
Awesome!  :+1: That was very fast!
