### ISSUE TITLE
Unable to add classes/styles to own component

### ISSUE THREAD

**Issue by FWeinb** [yyx990803/vue#1007]
It is currently not possible to add styles/classes to your own components, because the the custom element isn't rendered to the DOM. It is quite unintuitive that the component isn't rendered to the DOM.

I made a little [demo](http://jsbin.com/nukeba/3/edit?html,js,output) to show the problem. In my opinion the `style` attribute should be taken into account be the whole `<my-component>` element. This is how normal html components work and it is very strange to just remove the `class` attribute completely.  Another issue it that you can't attach event handlers to `<my-component>` because the element in that component don't have a common parent.

There is a workaround to this though, you could wrap your component in a `<div>` and apply all `props` (like style, class etc.) to that. But that feels very annoying and wouldn't play that well with the Web Components Spec.

**Comment by fergaldoyle** [comment]
Set the `replace` option to `false` if you want to keep the wrapping component tag. Also you'd probably want to set the custom tag to `display: block` because all custom html tags will by default be `display: inline`.

http://jsbin.com/pukozisezo/edit?html,js,console,output

**Comment by FWeinb** [comment]
Awesome! Didn't catch that in the [documentation](http://vuejs.org/api/options.html#replace). Why isn't this the default? Is there a way to make all elements behave like that?

**Comment by yyx990803** [comment]
The replace:true behavior is more intuitive when you think in terms of components, especially when you are using [single file components](http://vuejs.org/guide/application.html#Single_File_Components). Both the root element and all the related styles are contained in the component itself. What you write in the template is what gets rendered.

You can set `Vue.options.replace = false` to change the default.

**Comment by FWeinb** [comment]
I was using the single file component but maybe I am a bit biased towards `replace = false` because I worked a lot with real web components. But you are right with `replace = false` there isn't really a way to style the whole element from within the single file component because one would need the something like the `:host` css rule like [poylmer is doing it](https://www.polymer-project.org/0.5/articles/styling-elements.html#element-defined-styles)
