### ISSUE TITLE
Incorrect scope in transcluded repeater

### ISSUE THREAD

**Issue by JosephSilber** [yyx990803/vue#1010]
Using a repeater in trascluded content seems to set the scope to the current component, instead of the parent - as it is outside of the repeater:

http://jsfiddle.net/43LbnLpj/

**Comment by OEvgeny** [comment]
See [12.5 release notes](https://github.com/yyx990803/vue/releases/tag/0.12.5) - now trascluded component is the child of its host component. So, this will work:  http://jsfiddle.net/43LbnLpj/1/

**Comment by JosephSilber** [comment]
@OEvgeny I've actually read the release notes, but that didn't help me much.

> Note that `{{msg}}`, together with any directives on the transcluded components, will still be compiled in the **host's parent scope**.

The **host's** parent scope, not the **host** parent scope.

Unless I'm misunderstanding it, the `tab` content is compiled the the scope of `tabs`' parent.

In my example, `v-repeat`'s content should be compiled in the root scope, which is `inner`'s parent.

**Comment by OEvgeny** [comment]
Ah, yes. Got it.
