### ISSUE TITLE
jQuery plugins and v-model not working together

### ISSUE THREAD

**Issue by Chalkin** [yyx990803/vue#1011]
I'm trying to use the typeahead jquery plugin https://github.com/bassjobsen/Bootstrap-3-Typeahead inside vuejs. I have tried around quite a bit and i get the plugin working. But i don't get it working in combination with the v-model which is on my input field.

How can i update the value on my v-model when using the plugin to enter a value. I have the same problem on any other type of plugin like timepicker or anything else.

Currently I'm trying to get it working with a vuejs component:

``` js
Vue.component('typeahead', {
    template: document.querySelector('#typeahead-template'),
    props: ['onLoad'],
    ready: function () {

        var self = this;

        console.log('ready');
        console.log(this.$el);

        $('.typeahead', this.$el).typeahead({
            source: [{id: "someId1", name: "Display name 1"}]
        });

        //self.newTimetracking.project = 'neues projekt xx';
    },

    data: function() {
        return {
            //project: 'projekt name'
        }
    }
});
```

that's my input field on the component:
``` html
<script id="typeahead-template" type="x-template">
        <div class="form-group">
            <input type="text" v-model="newTimetracking.project" class="typeahead">
        </div>
 </script>
<typeahead></typeahead>
```

And this is my input without the component: 
``` html
<div class="input-group date" id="startdatetime">
                <input type="text" v-model="newTimetracking.start" class="form-control typeahead">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
```

``` js
$('.typeahead').typeahead({
            source: [{id: "someId1", name: "Display name 1"}]
        });
````

So how can i update the v-model value when the input value is entered by a jquery plugin?

**Comment by Shiak1** [comment]
I have the same issue using [jQuery selec2](http://select2.github.io/), here's a [sample](http://jsfiddle.net/Shiala/7n0c26vw/) where the new value doesn't get alerted after change, however when I add the [lazy option](http://jsfiddle.net/Shiala/7n0c26vw/1/) it does get alerted. This probable happens cause the jQuery plugin only triggers a change event and not an input event.

**Comment by Shiak1** [comment]
[Jefferey Way - Using Typeahead with Vue](https://laracasts.com/series/search-as-a-service/episodes/3)

**Comment by yyx990803** [comment]
@Chalkin questions like this should be posted to [vuejs/Discussion](https://github.com/vuejs/Discussion/issues). Also, please make sure to provide a debuggable example using jsfiddle, codepen or jsbin.
