### ISSUE TITLE
Consecutive changing display and opacity properties through a Vue method won't trigger opacity transition animation

### ISSUE THREAD

**Issue by germansokolov13** [yyx990803/vue#1013]
Here is the example:
http://jsfiddle.net/wy2qf6yx/228/

The `show()` method should change the display property first and then change the opacity only after that.  So that when opacity is changing the display is already block; If they are changed simultaneously at the same time then the transition animation is not triggered.

Why does it happen that way and how can I work it around? I need to both change display property and animate opacity. Using `v-if` is not an options as I should not remove the tags completely from the DOM.

**Comment by germansokolov13** [comment]
Hmm, it seems it actually happens even without using Vue even with consecutive javascript command because of the asynchronousness. So the issue is unrelated to to the Vue.js.

**Comment by Nirazul** [comment]
What you want is most probably this [Directive: `v-show`](http://vuejs.org/api/directives.html#v-show).
