### ISSUE TITLE
How to reach the object data inside the component? [question]

### ISSUE THREAD

**Issue by PavelPolyakov** [yyx990803/vue#1016]
Hi,

As gitter chat looks not very active, I would ask the question here. If there is some other proper place to ask such questions, please, point me there.

I started to use vue.js and met one issue.

I have the vue instance, which has an array under it's $data. It's possible to put another value to the data, by clicking the button.
![image](https://cloud.githubusercontent.com/assets/839290/8533391/ffb759a0-2434-11e5-8e8c-b56828cfeedc.png)

Based on this array, using the v-repeat directive, I print another component ```response```.
![image](https://cloud.githubusercontent.com/assets/839290/8533395/08ff2254-2435-11e5-8928-e11f92dac8e9.png)

My question is, assuming that I put an object to the data ```{uuid:xxx}```, how can I reach this object value in the component? In particular in the data function?
This approach doesn't work:
![image](https://cloud.githubusercontent.com/assets/839290/8533432/58625410-2435-11e5-9063-349eb719ccec.png)

![image](https://cloud.githubusercontent.com/assets/839290/8533410/28902280-2435-11e5-9bcc-de6e9866b09f.png)

I even am able to see the uuid, when printing ```this```
![image](https://cloud.githubusercontent.com/assets/839290/8535173/96ffff3e-2443-11e5-903b-a945ef4dcb18.png)

But can't reach it in any way. I only able to reach it from the template, while want to have the access to it from the code.

Here is the full code:
https://jsfiddle.net/4pqu1t8w/5/

Any advice is appreciated.

Regards,

**Comment by yyx990803** [comment]
Questions should be posted to [vuejs/Discussion](https://github.com/vuejs/Discussion/issues).

The `data` function is used to create the initial/default state for your component; it is called before merging with the external data. Use other lifecycle hooks such as `created` or `compiled` to access fully resolved data.
