### ISSUE TITLE
HTTP response arrived after instance been destroyed

### ISSUE THREAD

**Issue by fenivana** [yyx990803/vue#1017]
Minimal example:
```js
    var foo = new Vue({
      el: '.foo',

      data: {
        bar: 1
      },

      ready: function() {
        var me = this;
        this.$destroy();
        setTimeout(function() {
          console.log(me); // "me" is still a valid object
          me.bar = 2;
        }, 1000);
      }
    });
```

Throws:
```
Uncaught TypeError: Cannot set property 'bar' of null
```

It often occurs if switching between components too quickly.

Wrapping the code with a try/catch block is not a good idea, because it will eat other errors, and add complexity.

**Comment by mark-hahn** [comment]
You are assigning to a component after it is destroyed.  How do you expect

**Comment by fenivana** [comment]
I expect the error should be suppressed inside the Vue internal, at least in production environment ( Vue.config.debug = false ).

**Comment by Nirazul** [comment]
This is basically a javascript error, so I don't believe that vue should suppress it. I think it would be best to just check after every HTTP response, if the component is still alive.

**Comment by fenivana** [comment]
Even if the instance has been destroyed, it is still a valid object. You can assign `me.quz` and whatever else other than the bound props. This is a side-effect of Object.defineProperty(). As Evan said "99.9% of the time you don’t even need to think about it", then this is the 0.01% that I must always take care of in EVERY ajax and other async callbacks.

**Comment by yyx990803** [comment]
Throwing an error by simply accessing a property on a destroyed instance seems to obtrusive, so I've preserved the data reference on destroyed instances. However, do note that when you mutate the data of an already destroyed instance, it's possible to cause side effects on other instances that happen to observe the same object. So it is still recommended to check if the instance is still alive inside async callbacks.

**Comment by fenivana** [comment]
So quickly, thanks : )

I think the newly introduced side effect is a mixed blessing, it is sometimes expected.

**Comment by zjlovezj** [comment]
Forgive me commenting on such an old issue, but it seems the only relevant issue I could find.

This kind of error happens again (vue@^2.6.10).
My understanding is that we should check instance liveness inside async callbacks.
My question is: what's the formal way to check component instance liveness?
