### ISSUE TITLE
Problem when remove item of list (array) with other list (array) inside

### ISSUE THREAD

**Issue by silasrm** [yyx990803/vue#1018]
I have this struture with 2 components (1 to control 'datas' list and other to control 'horas' list of each 'datas' list item):

    'datas': [
        {
            'data': 'XXXX',
            'horas': [
                {'hora': 'YYYY1'},
                {'hora': 'YYYY2'},
                {'hora': 'YYYY3'}
            ]
        },
        {
            'data': 'XXXX2',
            'horas': [
                {'hora': 'YYYY2.1'},
                {'hora': 'YYYY2.2'}
            ]
        },
    ]

### Problem
When I add N 'datas' itens and add N 'horas' itens, on whatever 'datas' list item, and try remove whatever 'datas' list item, this erro occurs:

```Uncaught TypeError: Cannot read property 'nextSibling' of null```

**Comment by yyx990803** [comment]
Please provide a debuggable reproduction using jsfiddle or a similar service.

**Comment by silasrm** [comment]
@yyx990803 sorry with delay https://jsfiddle.net/silasrm/xufn6t6z/1/

**Comment by yyx990803** [comment]
Looks like you are using a quite out-of-date version of Vue - please consider upgrade to the latest version.

**Comment by silasrm** [comment]
If I upgrade vue.js version, v-events crash. Why?
In doc's I'm not find v-events.

**Comment by silasrm** [comment]
Last and functional version, with changes because v-events crash: https://jsfiddle.net/silasrm/xufn6t6z/2/

Munch more clean! :D

**Comment by yyx990803** [comment]
:+1:

**Comment by silasrm** [comment]
Thank's for help :D
