### ISSUE TITLE
Something cause a raw mustache flickering

### ISSUE THREAD

**Issue by TeroBlaZe** [yyx990803/vue#1021]
Mostly it happens in chrome when you switch the page back/forward and almost never when your cache disabled оr the page was reloaded and the scripts loaded with status 302.
Almost the same situation with IE but even if you refresh the page.
But I notice that with Firefox everything smooth

So that it can be concluded that is an issue with Google's V8 and IE's Chakra, not a bug with VueJS, isn't it? Are there is no better solution than http://stackoverflow.com/questions/30810691/websocket-vuejs-screen-flickering-visible-mustache-code ???

**Comment by yyx990803** [comment]
Use v-cloak: http://vuejs.org/api/directives.html#v-cloak
