### ISSUE TITLE
Directives in v-repeat are resolved into the component child scope with 0.12.5+

### ISSUE THREAD

**Issue by noirbizarre** [yyx990803/vue#1022]
With Vue.js 0.12.5+, directives on transcluded content are compiled into the child scope if nested into a v-repeat directive.

Here a sample demonstrating the bug with Vue.js 0.12.6: http://jsfiddle.net/noirbizarre/6yy4zy2s/3/

**Comment by yyx990803** [comment]
This is a known issue and has been fixed in dev branch: #1010

**Comment by noirbizarre** [comment]
Ok Thanks and sorry I didn't find it.
