### ISSUE TITLE
Specify component dependencies using camelCase

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#1029]
One of my devs is getting tripped up that we're using camelCase for props, dash case for components

Could you bring over the camelCase to dash-case conversion for component dependency names as well?

```js
new Vue({
    el: 'body',
    replace: false,
    data: {
    },
    methods: {
    },
    template: '<my-component></my-component>',
    components: {
        'myComponent': {
            template: 'blah'
        }
    }
})
```
http://jsfiddle.net/gk2vozpu/

Thanks

**Comment by young-steveo** [comment]
I created a PR that should address this for components/directives/etc. https://github.com/yyx990803/vue/pull/1030

**Comment by yyx990803** [comment]
This is different from props though, because props are primarily used inside JavaScript and expressions where dash case is awkward. On the other hand, the only use of component ids are as tag selectors - I don't see the benefits of using camelCase here.

**Comment by cheapsteak** [comment]
While that is a valid reason, the line of deduction might require a better grasp of how the framework is used than a junior dev would have.

I would like to be able to tell them to either "always camelCase in javascript", and "always dash-case in HTML", or "always camelCase in javascript, except when interfacing with HTML" but the new props naming convention kind of throws that off.

I got a PR today where the fella had given up and started naming everythinglikethis to get around having to remember what's camel and what's dash :see_no_evil:

**Comment by yyx990803** [comment]
Directives, elementDirectives and Components are the only ones that demand dash-case, because they appear in HTML as tag names or as attributes, but never appear in methods or expressions. Props is the only thing that appear in both places, hence both syntax are allowed.

I don't like the idea of creating alternative syntax just for the sake of being easier to remember, especially when the confusion came from not understanding how the framework works.

**Comment by cheapsteak** [comment]
"For the sake of consistency" is how I would put it; it does have the side effect of making it easier to remember, but it's mainly so people who aren't yet familiar with the framework wouldn't see this as a reason to be apprehensive (I'm sure you know how unreasonably critical developers can be :smile: ). The reasoning for the inconsistency is solid, but requires one to reason through it, and perhaps a bit of familiarity/experience using it as well (else how could they know for sure which things never appear in methods or expressions).

I think it might be worth it if the change would lessen the confusion for those who don't yet well understand how the framework works, but I understand that it would be undesirable to bog down codebase and API

**Comment by yyx990803** [comment]
I've been rethinking this suggestion and it starts to make more sense.

In addition, I remember in the past someone raised the same suggestion out of another reason - ES6 object shorthands:

``` js
import componentA from './components/a'
import componentB from './components/b'

export default {
  components: {
    componentA,
    componentB
  }
}
```

**Comment by mark-hahn** [comment]
It would be *really* nice if camelCase could be used everywhere in code and
hyphens used only in html and templates.  It could even be enforced.

**Comment by young-steveo** [comment]
@yyx990803 cool. Is my PR now relevant, or should I update it?

**Comment by yyx990803** [comment]
@young-steveo yeah I would merge it if we decide to make the change. It'd be nice to rebase against latest `dev` though.

**Comment by young-steveo** [comment]
@yyx990803 Rebased.

Note: the e2e tests are currently broken in the latest dev, but my new unit test is still passing.

**Comment by cjsaylor** [comment]
:+1:
