### ISSUE TITLE
Directives on generated HTML

### ISSUE THREAD

**Issue by PhillippOhlandt** [yyx990803/vue#1031]
Hello,

I have a div with the v-html directive that call my renderXYZHtml function.
```
<div v-html="renderXYZHtml()">
```

That function return html like 
```
<div v-on="click: myFunction"></div>
```

But when I click on the div, the myFunction function doesn't get called.

**Comment by yyx990803** [comment]
It's not recommended to compose Vue templates using dynamic HTML strings, therefore `v-html` and triple curlies both treat their content as static HTML (they don't compile them).

Use [partials](http://vuejs.org/api/elements.html#partial) instead.
