### ISSUE TITLE
Using classes in scope

### ISSUE THREAD

**Issue by cseufert** [yyx990803/vue#1033]
if i create a new Vue, with a list (array) of class objects, once vue has put getter/setters on these, i seem to loose all the method functions. What is the best way to avoid this, currently i am coping all the properties to a new object before inserting into scope, and to save back to server using class methods, i am copying the scope data back to the original class using something like objs[1].prop1 = $.extend(true,{},data.obj1].prop1) where these properties are objects.

**Comment by yyx990803** [comment]
Please make a fiddle to better explain your problem. Best practice is you should always be using plain Objects as Vue data. Data is just data; it should not have behavior, behavior belongs in the ViewModel.

**Comment by yyx990803** [comment]
Closing (inactivity)
