### ISSUE TITLE
The solution for props name start with "data-" when hyphenated prop names been deprecated

### ISSUE THREAD

**Issue by butsalt** [yyx990803/vue#1034]
I'm commonly using props start with `data-`. `data-*` is recommended to exchange proprietary information. Through this way, I don't need to worry about the attribute that I use to exchange data will cause any impact on dom.
```JavaScript
props: {
    "data-checked": {
        type: Boolean
    }
}
```
If hyphenated prop names have been deprecated, I wish I can use props start with 'data-' like this in future:
```HTML
<my-component data-checked></my-component>
```
```JavaScript
props: {
    "checked": Boolean
}
this.checked //true
```
And
```HTML
<my-component data-my-msg="something"></my-component>
```
```JavaScript
props: {
    "myMsg": String
}
this.myMsg //"something"
```
If not find properer attribute, then
```HTML
<my-component my-msg="something"></my-component>
```
```JavaScript
props: {
    "myMsg": String
}
this.myMsg //"something"
```

**Comment by young-steveo** [comment]
:+1:   This would be awesome if configurable via a global `Vue.config` option, like `parseDataProps`. 

```html
<my-component data-my-msg="something"></my-component>
```

```js
props: {

    // with parseDataProps : false
    dataMyMsg : String,

    // with parseDataProps : true
    myMsg : String
}
```

**Comment by yyx990803** [comment]
@young-steveo I'm not sure if the config is necessary here - it seems very unlikely to conflict with 3rd party libs, and even if it does you can use the non-data-prefixed syntax to avoid it.
