### ISSUE TITLE
用vue.js的v-repeat数据更新问题

### ISSUE THREAD

**Issue by nolouch** [yyx990803/vue#1035]
我通过api初始化data
```
$(function() {
    getJSON('/api/weibos', {
        page: {{page_index}}
    }, function (err, results) {
        if (err) {
            return fatal(err);
        }
        console.log(results);
        $('#loading').hide();
        initVM(results);
    });
});
```
然后通过v-repeat生成样式，以及条目。
但是当我点击表单post的时候，数据更新了，vm怎样才能在页面不刷新的情况下让v-repeat重新生成样式。查了下实例对象没有刷新的方法，只有destroy。

**Comment by yyx990803** [comment]
你的 initVm 是怎么写的为什么不放上来...
更新数据就是靠赋值啊，vm.weibos = results
建议仔细看过文档后再开 issue，另外问题类的请发到 [vuejs/Discussion](https://github.com/vuejs/Discussion)

**Comment by nolouch** [comment]
好的，谢谢
