### ISSUE TITLE
checkboxes with array model

### ISSUE THREAD

**Issue by robertleeplummerjr** [yyx990803/vue#1037]
How do I get something like this to work?:
```html
<script>
new Vue({
  data: {
    languages: ['english', 'japanese', 'chinese']
    myLanguages: ['english', 'chinese']
  }
});
</script>
<span v-repeat='language : languages'>
  <input
    type='checkbox'
    value='{{ language }}'
    v-model='myLanguages'>
</span>
```

**Comment by rmp135** [comment]
What exactly are you wanting to happen? 
If it's a list of checkboxes and their checked state, you could hold the languages as an object rather than a string.

````html
<script>
new Vue({
  data: {
    languages: [
        {name: 'english', checked:true},
        {name: 'japanese', checked:false},
        {name: 'chinese', checked:true}
    ]
  }
});
</script>
<span v-repeat='language : languages'>
  <input
    type='checkbox'
    value='{{ language.name }}'
    v-model='language.checked'>
</span>
````
You can then use a filter/map to retrieve the names of the selected languages.

Here's a jsfiddle demonstrating it. http://jsfiddle.net/rmp135/v9vx9qyd/

**Comment by robertleeplummerjr** [comment]
I guess the use case is to use the check boxes in a similar manner that
your use a select with the ability to select multiple selections.  Sort of
a "check all that apply" scenario, where the checkables come from an array
of possibilities.

**Comment by yyx990803** [comment]
Old example here: http://jsfiddle.net/yyx990803/1onz2ho7/1/

Please open questions like this at vuejs/Discussion instead of the core repo.
