### ISSUE TITLE
vue-repeat new row every 3 item

### ISSUE THREAD

**Issue by ThomasRalee** [yyx990803/vue#1038]
Hi,

Is it possible to create a new row every 3 element?

For example...
````php
<div class="row">
	<article v-repeat="connectors" track-by="id" style="text-align:center" class="col-md-4">
		<img v-repeat="images | filterBy '1' in 'profile'" src="img/connector/@{{imagePath}}"/ >
		<p style="font-size:1.5em">@{{model}}</p>
	</article>
</div>
````
This will repeat nicely...
But what i was hoping was to create a new ````<div class="row">```` every 3 "connectors".

Sorry that i didn't mirror the example in fiddle, i am using Laravel so i am kind of lost on the fiddle..

Thanks in advance.

Cheers
Thomas

**Comment by azamat-sharapov** [comment]
*This repo is not for questions. There is vuejs/Discussion repo for that*.

In your example `<div class="row">` is outside `v-repeat`, so it's not being `v-repeat`ed, you need to move that into `<article v-repeat="connectors">`. 
Not sure about wrapping elements with `div` on every 3rd step of iteration, but you can `v-if` any element like so:

```
    <article v-repeat="connectors" track-by="id" style="text-align:center" class="col-md-4">
        <img v-repeat="images | filterBy '1' in 'profile'" src="img/connector/@{{imagePath}}"/ >
        <p style="font-size:1.5em">@{{model}}</p>
       
       <!-- this will be inserted every 3rd time -->
       <br v-if="($index % 3 === 0) && $index !== 0">
    </article>
```

**Comment by yyx990803** [comment]
As suggested, please don't post questions in this repo.
