### ISSUE TITLE
Unexpected v-transition behavior when using v-repeat with mutation methods

### ISSUE THREAD

**Issue by young-steveo** [yyx990803/vue#1039]
Here's [a fiddle](http://jsfiddle.net/r2a5deep/) that uses all of the [mutation methods](http://vuejs.org/guide/list.html#Mutation_Methods) on an array that this being used by v-repeat with a javascript v-transition.

Things I noticed:

* `push` and `pop` behave as expected.
* When using `shift` and `unshift`, the new array element is added to the front of the list, but the last item in the list animated in/out.
* `sort` and `reverse` work, but there are no transitions applied.
* `splice` kinda works; the data is updated correctly, but then only one new element is transitioned, even though I removed one element from the middle of the list and added two new elements.

**Comment by young-steveo** [comment]
A simpler version of the fiddle without the component or opacity fade: http://jsfiddle.net/r2a5deep/1/

**Comment by yyx990803** [comment]
When the repeated array contains primitive values, `v-repeat` is automatically in `track-by="$index"` mode because it's impossible to accurately track the position duplicate primitives that have the same value. If you want accurate-position transitions, always use Objects in your repeat array.

**Comment by young-steveo** [comment]
@yyx990803 Thanks Evan.  That makes sense.  So, I updated the fiddle: http://jsfiddle.net/r2a5deep/2/

Now `shift`, `unshift`, and `splice` behave as I expected, but the `sort` and `reverse` methods still do not animate.

**Comment by yyx990803** [comment]
`sort` and `reverse` do not animate because the items are the same, so no element entered/left the DOM. If you want smooth moves for reorders, it's better to absolute-position the items and animate CSS-transform based on `$index`.

**Comment by young-steveo** [comment]
That makes sense from a technical perspective, but it seems counterintuitive from the point of view of the user.

Thanks for the explanation; I should be able to develop a decent workaround.

BTW, I love the library as a whole. :+1:
