### ISSUE TITLE
bug, vm.$compile 编译中 v-repeat 指令失效

### ISSUE THREAD

**Issue by niluanxy** [yyx990803/vue#1041]
我写了一个自定义的组件，其中是手动给子项目添加 v-repeat 属性，然后调用 父vm 的 $compile 方法编译对象，但是测试后出现item内部不能使用 {{属性}} 输出值，代码片段如下：

模板文件代码：
```HTML
<mg-select data="payType" class="list-embed">
    <item class="icon-left icon-right">
        <i class="icon ion-plugs"></i>
        {{text}}
        <i class="icon-right ion-checkbox"></i>
    </item>
</mg-select>
```

数据文件代码：
<pre>
module.exports = {
    template: require("./template.html"),

    data : {
        payType: {
            val: null,
            items: [
                {text: "中国", val: "cn" },
                {text: "美国", val: "usa" },
                {text: "英国", val: "en" }
            ],
            key: "val",
            select: null
        }
    }
}
</pre>

组件代码：
<pre>
module.exports = (function() {
    Vue.component("mg-select", {
        template: "<content></content>",
        inherit: true,
        ready: function() {
            var $el = $(this.$el), parent, data;

            parent = this.$parent;
            data = $el.attr("data");

            // 如果有 data 数据，则通过 data 中的 items 生成子项目
            if (data && parent[data] && parent[data].items) {
                var $item = $el.find("item");

                if ($item.length) {
                    $item.addClass("item")
                         .attr("v-repeat", data+".items");

                    parent.$compile($item[0])
                }
            }
        }
    });
})();
</pre>

**Comment by yyx990803** [comment]
因为传进来的时候 `{{text}}` 已经被编译过了啊

**Comment by niluanxy** [comment]
那有没有方法阻止，在我需要的时候编译


在2015年07月14日 06:11，Evan You 写道:

因为传进来的时候 {{text}} 已经被编译过了啊

**Comment by niluanxy** [comment]
还有，你有没有计划和ng一样加入指令优先级的概念，因为现在没法控制，所有的指令都会优先组件component编译，这在一些复杂的组件中会很麻烦和无法控制
在2015年07月14日 06:11，Evan You 写道:

因为传进来的时候 {{text}} 已经被编译过了啊

**Comment by yyx990803** [comment]
指令是有优先级的（看源码，没有 priority 的默认为 0），但是组件，if 和 repeat 永远优先。

**Comment by yyx990803** [comment]
你这里思路很奇怪，为什么要手动编译？

``` html
<mg-select class="list-embed">
    <item class="icon-left icon-right" v-repeat="payType">
        <i class="icon ion-plugs"></i>
        {{text}}
        <i class="icon-right ion-checkbox"></i>
    </item>
</mg-select>
```

如果你想要完全对用户隐藏 Vue 的存在那我也没办法了...

**Comment by yyx990803** [comment]
关了，不是 bug，是用法问题

**Comment by niluanxy** [comment]
因为我是需要对模板进行二次处理，目的让使用的人用起来最简单


在2015年07月14日 21:27，Evan You 写道:

Closed #1041.
