### ISSUE TITLE
Suggestion for v-repeat directive, to provide computed variables/values

### ISSUE THREAD

**Issue by steffans** [yyx990803/vue#1042]
Using the v-repeat directive it sometimes happens that a related object is needed depending on the current value. Example: When iterating an array of items, the getType() method is used to get a related type object if it exists.

```html
<ul>
    <li v-repeat="items">
        {{ name }} <span v-if="getType($value)">{{ getType($value).name }}</span>
    </li>
</ul>
```
But it would be nice to create other computed variables for the v-repeat, like this:

```html
<ul>
    <li v-repeat="items" var="type: getType($value)">
        {{ name }} <span v-if="type">{{ type.name }}</span>
    </li>
</ul>
```
Since the type depends on the item object, the $value can be omitted and automatically passed to the getType($value) method.

```html
<ul>
    <li v-repeat="items" var="type: getType">
        {{ name }} <span v-if="type">{{ type.name }}</span>
    </li>
</ul>
```
For now i created my own directive doing this, but i seems like a useful addition for the v-repeat directive.

**Comment by azamat-sharapov** [comment]
This brings "relational database models" feeling, stealing your idea! :smile: 
Supporting additional arguments like `getType(someKey)` would make it more flexible, instead of `$value` only.

But I don't get that `var` thing.. why not just prop with method like this: 
`<li v-repeat="items" type="getType($value)">` ?

**Comment by steffans** [comment]
@azamat-sharapov `var` is just a property for the defining the variables/values. It's is basically like the old `v-with` which passed values to a component. The property could be named differently, `with` or `data` could also work as a property name. Even multiple assignments can work like this:

```html
<li v-repeat="items" with="type: getType, other: getOther(someKey)">
```
Also the `$value` would be the default argument, if you don't set any argument. Sure if you put an argument like `getType(someKey)` will also work.

**Comment by mark-hahn** [comment]
> But it would be nice to create other computed variables

Can't you do this in a method?

**Comment by yyx990803** [comment]
I'm not sure if we should add directives just for syntax sugar like this... there are different ways to deal with this, for example a computed array, use components, or a custom directive that does what you described. My opinion is that it's fine to leave it as a user-land thing.
