### ISSUE TITLE
newVal === oldVal when $watch on array

### ISSUE THREAD

**Issue by azamat-sharapov** [yyx990803/vue#1043]
Not fully sure it's bug or I'm misunderstanding something, but couldn't find anything in docs explaining this weird behavior: http://jsfiddle.net/5qg4wso7/

*Also on $watch API docs, there is `sync` option, about which I can't find any info in docs and in source code.*

**Comment by yyx990803** [comment]
The array only **mutated**, but its reference did not change.

`sync` option is internal, not meant for public use. Maybe I should underscore it.

**Comment by azamat-sharapov** [comment]
I see. I only need to track length of array at the moment, so using expression worked: http://jsfiddle.net/5qg4wso7/1/

Thanks!

**Comment by dalanmiller** [comment]
Ahhh, having this same problem in #1805. In this case, how would I detect objects which have had a property change?

**Comment by shaqueoneal** [comment]
> how would I detect objects which have had a property change?

how?
