### ISSUE TITLE
不需要双向邦定时怎么处理

### ISSUE THREAD

**Issue by bjtqti** [yyx990803/vue#1046]
我只是想用vue创建一个列表，不需要dom监听后续的变化，要怎么办？

**Comment by yyx990803** [comment]
1. 这不叫双向绑定
2. 不需要监听数据变化为啥要用 Vue
3. 提问请到 [vuejs/Discussion](https://github.com/vuejs/Discussion)，这里只接受 bug report 和 feature request.
