### ISSUE TITLE
How to replace a Vue object on a DOM? Is there an "unmount" method?

### ISSUE THREAD

**Issue by drxcheng** [yyx990803/vue#1047]
I have a Vue object mounted to a form. I want to replace the object with another Vue object.

When I just do `this.$mount('form')` in the new object, the old Vue object is still catching the events (`v-on`). When I do `this.$destroy()` in the old one and same mount in the new one, events are not caught.

What's the correct way to do this? Thank you!

**Comment by yyx990803** [comment]
You can't. Once a piece of DOM is compiled you can't compile it again.
The proper way to do this is to make a component and include the form in its template, create it and append to the DOM. When you need a new one, destroy the old one with `vm.$destroy(true)` (the `true` is needed here to remove it at the same time), then start over and create a new instance.

**Comment by yyx990803** [comment]
Oh and please post questions to [vuejs/Discussion](https://github.com/vuejs/Discussion/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) instead of this repo.

**Comment by drxcheng** [comment]
Thanks for replying!

**Comment by FWeinb** [comment]
Maybe you can use [dynamic components](http://vuejs.org/guide/components.html#Dynamic_Components) to switch depending on your state.

**Comment by trusktr** [comment]
Some people might like to remove a Vue from DOM then render a React component inside the same target element. Well, Vue destroys the target element ( 😢 ) so it's not as simple as you might think.

Read this thread on how to do it: https://forum.vuejs.org/t/add-component-to-dom-programatically/7308/13
