### ISSUE TITLE
Global event 

### ISSUE THREAD

**Issue by thelinuxlich** [yyx990803/vue#1048]
It would be useful if $dispatch(or a new method) could trigger a event for every vm, independently of the hierarchy

**Comment by yyx990803** [comment]
You could just use an external event bus for that.

**Comment by azamat-sharapov** [comment]
Speaking about external event buses, what do you recommend Evan? haven't ever used one, advice appreciated.

**Comment by yyx990803** [comment]
@azamat-sharapov Node's built-in EventEmitter is probably the easiest one. Both webpack and browserify mock it for you I believe. Or you can also use https://www.npmjs.com/package/component-emitter or https://github.com/mroderick/PubSubJS

**Comment by azamat-sharapov** [comment]
Thank you

**Comment by MAAARKIN** [comment]
@yyx990803 i'm using vuejs and i'm try to emit a event global like u recommend, i trying to do something like this:

...
eventEmitter.emit('my-event', 'my-message');

and in my other component ComponentB.vue

i do like this:

events: {
			'my-event': function (msg) {
				console.log(msg)
			}
		}

can i use events: {} from the componentB to get my event?

**Comment by LinusBorg** [comment]
@MAAARKIN No. you will have to register a listener on the same bus.

Also, this issue is closed and Github issues are reserved for feature proposals and bug reports.

Please consider opening a thread on our community forums at forum.vuejs.org
