### ISSUE TITLE
suggestion: user custom assets

### ISSUE THREAD

**Issue by kazupon** [yyx990803/vue#1049]
Developing the custom directive, custom filter and plugin it sometimes happens that custom assets is needed.

If have any API that the user register custom asset, and using it, I think that it's very useful.

The following validation example:

```html
<form>
  <input type="text" name="threshold" value="5" v-validate="min: 1, max: 10">
</form>
```

```js
// register `min` validator to custom assets
Vue.customAssets('validator', 'min', function (val) {
  // something ...
})


Vue.directive('validate', {
  bind: function () {
    var el = this.el
    var validatorName = this.arg
    
    // retrieve validator from custom assets
    this.validator = Vue.customAssets('validator', validatorName)
    
    // something ...
  },
  update: function (val, old) {
    var vm = this.vm
    var el = this.el
    var validatorName = this.arg
    var validator = this.validator
    var validatorArg = this.expression
    var model = el.getAttribute('name')
    var value = el.getAttribute('value')
    var keypath = ['validation', model, validatorName].join('.')

    // validate !!
    var ret = validator.call(this, value, validatorArg)
    
    // set validation result
    vm.$set(keypath, ret)
    
    // something ...
  }
})

```

**Comment by yyx990803** [comment]
Why does this need to be on Vue? Couldn't it just be an internal module of the plugin?

**Comment by kazupon** [comment]
Yes :wink:, We can be an internal module of plugin.

But by providing user custom assets API to us, not only the plugin developer but the plugin user as well, I think that we gets the advantage of consistency.

**Comment by yyx990803** [comment]
I don't think should be part of Vue core, because Vue is a singleton and this could potentially lead to namespace clashes. It feels more natural to me to expose this type of assets on the plugin module itself. Maybe we can add some conventions for this in the plugin authoring guide.

**Comment by kazupon** [comment]
Okay. :smiley:
I'll try custom assets management in plugin-side.

Well, Come to think of it, You're right.

**Comment by yyx990803** [comment]
You can expose assets on your plugin similar to how Vue does it (just an idea):

``` js
var vv = require('vue-validator')
var min = vv.validator('min')

// users can register custom validators:
vv.validator('my-validator', function (value) {
  // ...
})
```
