### ISSUE TITLE
'replace' option default value changed to true in v0.12.7? 

### ISSUE THREAD

**Issue by panteng** [yyx990803/vue#1051]
Hello,
In vue api doc, I see you say the default value of 'replace' option is false. But I find the default value is true in v0.12.7. I have to set the value to false manually. Is this an intentional change or just a mistake?

**Comment by OEvgeny** [comment]
According to [releases](https://github.com/yyx990803/vue/releases) it is ``true`` since 12.2. I think this change was missing in doc. You can post issues related to documentation in [this repo](https://github.com/vuejs/vuejs.org).

**Comment by panteng** [comment]
Got it. Thanks for your reply.
