### ISSUE TITLE
0.12.7给组件显式传参没效果

### ISSUE THREAD

**Issue by PeakTai** [yyx990803/vue#1052]
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>component</title>
    <script src="bower_components/vue/dist/vue.js"></script>
</head>
<body>
<my-component v-with="name:name"></my-component>
<script>
    window.onload = function () {
        Vue.component("my-component", {
            template: "Hello {{name}}"
        });
        new Vue({
            el: "body",
            data: {
                name: "Peak"
            }
        });
    }
</script>
</body>
</html>
```
打开网页，只显示一个Hello，就不截图了。

**Comment by bjtqti** [comment]
需要显示的增加inherit

Vue.component("my-component", {
           inherit: true,
            template: "Hello {{name}}"
        });

**Comment by butsalt** [comment]
`v-with`在0.12.0的时代就已经被废除了，建议你在[英文版的官网](http://vuejs.org/)查阅相关文档，你所关心的问题在[这里](http://vuejs.org/guide/components.html#Passing_Data_with_Props)，中文版的文档相对已经比较旧了。所以，在0.12.7@Vue下的正确的写法应该是[这样](http://jsfiddle.net/5sH6A/124/)，为了避免`name`属性对dom的影响，个人推荐写法是[在传参属性名之前加上`data-`前缀](http://jsfiddle.net/5sH6A/125/)。对了，有关Vue的使用问题或讨论应该在[讨论版](https://github.com/vuejs/Discussion/issues)进行，这里主要是用来提出bug或者建议的。

**Comment by yyx990803** [comment]
@butsalt 多谢详细的回答 :)
