### ISSUE TITLE
v-if not working inside v-repeat

### ISSUE THREAD

**Issue by rleger** [yyx990803/vue#1053]
Hi,

I can't get v-if to work properly inside a v-repeat

in a component, this is my template

The idea is to show a list id when debug is on (turned on with a checkbox).

```
<select v-model='itemId' number>
    <option value="@">All</option>
    <option v-repeat="itemList" value="{{ id }}">
        <span v-if="debug">{{ id }} - </span>{{ name | capitalize }}
    </option>
</select>
```

This is the component :

```
module.exports = {
    template: require('./component.template.html'),

    props: ['itemId', 'ItemList', 'debug'],

    data: function() {
        return {
            itemList: [],
            itemId: '',
            debug: false,
        };
    }
};

```

If I display {{debug}} in the template it gets updated properly to true or false.

It works fine outside of v-repeat. Am I missing something ??

Thanks !

(thanks so much for vue-js it turned my developer life around !)

**Comment by OEvgeny** [comment]
It's recommended to use [``option``](http://vuejs.org/guide/forms.html#Dynamic_Select_Options) parameter for ``select`` element. You can use computed properties to achieve desired behaviour.

**Comment by rleger** [comment]
I think it's not really what I'm looking for..

I don't want to use an optgroup, I want to prepend an item with its identifier when I'm in debug mode to help troubleshoot.

I'm not looking to group items together.

Not in debug mode : 
```
<select>
  <option value="a">A</option>
  <option value="b">B</option>
</select>
```

in debug mode : 
```
<select>
  <option value="a">1 - A</option>
  <option value="b">2 - B</option>
</select>
```

**Comment by OEvgeny** [comment]
Doc says:
> When you need to dynamically render a list of options for a ``<select>`` element, it’s recommended to use an ``options`` attribute together with v-model:

You need to specify `options` attribute:
```
<select v-model='itemId' number options="opt">...
```
And than specify array for options list in your `data`:
```
opt: [
  { text: 'A', value: 'a' },
  { text: 'B', value: 'b' }
]
```
It will render:
```
<select>
  <option value="a">A</option>
  <option value="b">B</option>
</select>
```

Now you can make `opt` computed property to react to `debug` value. 
You can use it to work around this issue. Hope it helps :)

**Comment by rleger** [comment]
right, it works as a workaround thanks. Seems like a bit of an overkill for what I wan't to accomplish.
Still, I wonder why v-if or v-show don't work inside a v-repeat.

Thanks for your help

**Comment by yyx990803** [comment]
It's probably because spans are not allowed inside option elements?

**Comment by yyx990803** [comment]
Confirmed - when you put other elements inside `<option>`, they all get crunched into plain text.

**Comment by rleger** [comment]
Oups didn't thought of that :(, thanks
