### ISSUE TITLE
百度地图对象赋值给组件Data报错

### ISSUE THREAD

**Issue by liyunfang** [yyx990803/vue#1055]
data: function () {
    return {
        zoom  : 11,
        center : null,
        class : null,
        bmap: null
    }
  },

map是实例化后的百度地图对象
this.bmap = map;
错误：Uncaught TypeError: Cannot redefine property

赋其他值不报错。

**Comment by yyx990803** [comment]
http://vuejs.org/guide/faq.html

1. 不要把复杂对象当 data。data 应当是可以无缝转化为 JSON 的对象。
2. 不需要对其进行数据绑定的东西不要放在 data 里面。

**Comment by butsalt** [comment]
Vue会通过`defineProperty`对传入Vue实例的数据的每个属性重新进行定义(如果这个属性的类型为Object，还会对这个属性对应的值的每个属性继续重新进行定义)，从而实现对属性的监听效果。你遇到的问题我觉得应该是map对象内部有无法进行再定义的属性(或子属性)。就像[这个例子](http://jsfiddle.net/5sH6A/128/)中显示的那样。如果这个map实例只是本组件内部使用的话，可以使用`$`,`_`作为属性前缀，那么Vue在进行重新定义时会跳过这些属性。但需要注意的是当你需要使用这个属性的时候你不能再使用类似`this.bmap`的方式进行获取，而应该改用`this.$data._map`的方式进行获取。并且这个属性的值发生变化时，Vue也不会对其进行监听。[这是一个范例](http://jsfiddle.net/5sH6A/129/)。或许最好的方式是Vue在对属性进行重新定义时，使用`Object.getOwnPropertyDescriptor`.实际上我现在有想过用Vue+Openlayers3做一个数据绑定的地图组件。我会在父组件中创建一个Map实例，并把这个实例采用`props`的方式传递给子组件。子组件会在创建时创建一层Layer用来展示它所关心的数据，并把这个Layer装入到Map中。子组件会在销毁时，将自己的Layer从Map中移除。

**Comment by liyunfang** [comment]
那我想搞一个百度地图组件，需要把这个map给公开出来？应该怎么做 求指教？英文水平有限，不好意思。

**Comment by liyunfang** [comment]
呵呵，我已经实现这个功能了。我是这样做的，你看可以吗？
在组件里 把百度地图实例化好后  可以动态把这个添加到父级的data里
this.$parent.$add('_bmap',map);
然后父级就可以这样调用百度api了    
vm.$data._bmap.centerAndZoom(new BMap.Point(116.417854,39.921988),15);

**Comment by liyunfang** [comment]
只不过这样调用的话 每次都会返回一个 undefined

**Comment by ppq1991** [comment]
不要把复杂对象放进 data，你这个 map 不需要放进 Vue 实例里。
类似的讨论请移步： https://github.com/vuejs/Discussion/issues

**Comment by liyunfang** [comment]
@ppq1991  谢谢你的回答。 
但是我是要做一个百度地图的组件component
要在组件里实例化百度地图，不保存到data里怎么做呢？外部要调用。

我现在这样做了：
在组件里 this.$add('_bmap',map);  加下划线是为了不重写这个对象

外部调用的时候 在组件上加个 v-ref="bdmap"
vm.$.bdmap.$data._bmap.centerAndZoom(new BMap.Point(116.417854,39.921988),15);
