### ISSUE TITLE
vm.$log数组时报错

### ISSUE THREAD

**Issue by chaoren1641** [yyx990803/vue#1059]
`vm.$log([1,2])`

时会提示错误:

```Uncaught TypeError: t.charCodeAt is not a function```

**Comment by butsalt** [comment]
vm.$log的作用是用来输出vm下的data中的部分/全部数据的。如果只是单纯要对数组在控制台输出为什么不用console.log呢？
正确的用法应该是[这样的](http://jsfiddle.net/5sH6A/130/)  。
这是官方的[api](http://vuejs.org/api/instance-methods.html#vm-\$log\(_\[keypath\]_\))，你可以看一下。

**Comment by chaoren1641** [comment]
是这样的，我在data里有一个对象数组，我现在想consle.log某一个对象，使用vm.$log(items[3])，打出来确是vue里的整个data。使用console.log(items[3])，能看到items[3]的get set后的对象。 所以我尝试着直接vm.$log(items),会报错。

**Comment by yyx990803** [comment]
你应该用 `vm.$log('items[3]')`

**Comment by chaoren1641** [comment]
嗯，已经知道啦，多谢
