### ISSUE TITLE
0.11之后版本v-with没起作用的问题

### ISSUE THREAD

**Issue by Alexorz** [yyx990803/vue#1060]
Hello，刚遇到个问题，0.11.0后的版本，下面这种场景下，`v-with`并没有让`scope`变成`user`对象。

````html
<div id="demo-1">
  <p v-component="user-profile" v-with="user">
      {{name}}<br>{{email}}
  </p>
</div>
````

````javascript
Vue.component('user-profile', {})

var parent = new Vue({
  el: '#demo-1',
  data: {
    user: {
      name: 'Foo Bar',
      email: 'foo@bar.com'
    }
  }
})
````

运行结果符合预期的Demo，0.11.0-rc3：http://jsfiddle.net/Alexorz/ytphnqg9/2/
运行结果不符合预期的Demo，0.12.7：http://jsfiddle.net/Alexorz/kmskcf47/3/

是否是bug？

**Comment by butsalt** [comment]
0.12.7下的`v-with`已经被废除了，我在#1052 回答过，你可以看一下。

**Comment by Alexorz** [comment]
所以遇到这种使用场景，只有把template挂到js里一种办法吗？
无论如何，希望文档能更新，有段时间没用vue了，遇到这个点废了我一下午。。

**Comment by yyx990803** [comment]
中文文档在翻译中，因为改动比较大，而且都是志愿参与，所以进度比较缓慢。如果你有兴趣可以到 https://github.com/Jinjiang/vuejs.org/tree/0.12-zh 参与翻译工作。

如果用最新版本，文档请以英文版为准。0.12 改动还是比较多的。

**Comment by yyx990803** [comment]
关于你里面的用例，需要在 `user-profile` 组件里暴露一个 user prop，然后用 `<user-profile user="{{user}}">` 这样的形式传进去。

**Comment by butsalt** [comment]
@Alexorz template用字符串还是直接用html都可以啊，主要是组件之间的数据传递现在只允许用`props`来进行了。  也就是说，作为父组件你不能再对子组件做整个data的传递了。  
[试试这个Fiddle](http://jsfiddle.net/5sH6A/131/)

**Comment by butsalt** [comment]
版本变更所导致的不兼容以及新功能实际上在[Release](https://github.com/yyx990803/vue/releases)已经表述的比较清楚了。建议在对项目做升级时先仔细阅读一下:)

**Comment by Alexorz** [comment]
感谢两位的耐心说明，确实有段时间没关注Vue了，我先看看文档 : )
