### ISSUE TITLE
Dynamic Select Options is impractical

### ISSUE THREAD

**Issue by baank** [yyx990803/vue#1061]
It really is ridiculous to have to convert data to the text/value JSON object format in order to correctly render select options dynamically.

Ideally we would have something along these lines:

```html
<select v-model="selectedItem" v-options="array" v-text="item.firstName" v-value="item.id">
</select>
```

**Comment by yyx990803** [comment]
Just want to point out that indicating the current design is "ridiculous" is not a polite way to open a feature request.

**Comment by Shiak1** [comment]
I was thinking something like this:

    <select v-model="selectedItem" v-options="array" text="firstName" value="id"></select>
where value is optional and if not specified the model will contain the whole object, we talked about it in [discussion](https://github.com/vuejs/Discussion/issues/235)

**Comment by crswll** [comment]
That filter approach is awesome. I've been using computed properties but this is way more useful.

**Comment by yyx990803** [comment]
As suggested in the discussion thread, you can write a reusable custom filter to transform the array:

``` html
<select v-model="selectedItem" options="array | extractOptions 'firstName' 'id'"></select>
```

The reason there are not dedicated attributes for this conversion is because there are many possible cases the attribute syntax won't suffice: e.g. the source data could be an Object, the select needs optgroups, the text/value need to be formatted, etc. A custom filter gives you the full capability to do any sort of transform you want, while the attribute syntax is just extra syntax for one particular use case.

**Comment by boussou** [comment]
... ;-) 
+1 @yyx990803 (about "ridiculous")

People often forget that they get this for free while you spent numerous hours on it.
Thank you for bringing us a lightweight & smart alternative to angular.

**Comment by OEvgeny** [comment]
+1 for filter approach. :+1:

**Comment by baank** [comment]
Sorry it was just born out of frustration. There wasn't any malice behind this and I definitely appreciate how fantastic VueJS is.

It would be great if this filter approach could be added into the documentation.

**Comment by yyx990803** [comment]
No worries, added to todos in docs: https://github.com/vuejs/vuejs.org/issues/86

**Comment by eliasjpr** [comment]
I think computed properties is a better approach. Cleaner templates easier to understand. Having inline filter is like having inline stylesheets in html.

**Comment by merianos** [comment]
And what about if we need additional attributes for the options ? like data-*="", selected=""

**Comment by crswll** [comment]
You can use a `v-for` now.  I guess you couldn't do that in the past or it acted funky? Can't remember. But yeah: http://vuejs.org/guide/forms.html#Select-Options

**Comment by rpkilby** [comment]
This is detailed in the "Component Scoping" section of #1200. Basically, the iterated `item` in the `v-repeat` loop would be undefined in the parent scope, making this error:

```html
<option v-repeat="item in list" value="{{ item.value }}">{{ item.text }}</option> 
```

I think...
