### ISSUE TITLE
Vue.js 0.12.7 ignores Vue.config.replace = false in repeated components

### ISSUE THREAD

**Issue by fullfs** [yyx990803/vue#1064]
Hello!
http://jsfiddle.net/b4g7p2w1/2/

**Comment by yyx990803** [comment]
This could be a bit confusing, but `replace` is not a global config, but an option. To change an option's default you set it on `Vue.options`, not `Vue.config`: http://jsfiddle.net/yyx990803/b4g7p2w1/3/
