### ISSUE TITLE
Variable in component outer element class deactivate the outside v-class

### ISSUE THREAD

**Issue by noirbizarre** [yyx990803/vue#1065]
Hi!

I just noticed that it's possible to call a component et use v-class from outside and it will be properly merged with existing class but when you introduce a variable into the component class attribute, the outside v-class is ignored

Here's a fiddle illustrating the bug: http://jsfiddle.net/noirbizarre/xcres8hr/3/

**Comment by nouveller** [comment]
I'm not sure if this is related, but when I set up some `props` for a component and some `data` the default values for `props` don't work. Unless I'm understanding it incorrectly.

http://jsfiddle.net/gthk4jm6/2/

**Comment by yyx990803** [comment]
@nouveller that is a separate issue, also fixed: https://github.com/yyx990803/vue/issues/1072

**Comment by nouveller** [comment]
@yyx990803 Ah, brilliant. I've been using a work around for the time being but look forward to the fix in a new release. Thanks!

**Comment by noirbizarre** [comment]
@yyx990803 Thanks !
