### ISSUE TITLE
The data generated by props  will be replaced by the default data in whole!

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#1066]
If I have a component will props and a default data function, the props with default value but with null raw value won't be set into data. Here is the [example](http://jsfiddle.net/TerenceZ/e1qxvhhe/3/).

**Comment by yyx990803** [comment]
Thanks, this is a known issue and has been fixed in `dev`: https://github.com/yyx990803/vue/commit/145fed71f92bebab6b14b6c5bbe584c6aecaca25
