### ISSUE TITLE
v-repeat and v-if on same element not working

### ISSUE THREAD

**Issue by HendrikThePendric** [yyx990803/vue#1074]
I have a `<tr>` I need to repeat and conditionally show. I found that using a `v-repeat` and `v-show` on the same element does not work, so previously I have been using a `<template>` for repeating and then a `v-if` on the actual repeating element. However in Internet Explorer 10+ this is causing issues, because it does not allow a `<tr>` to live inside of a `<template>`.

I am still on version 0.11.8. Will upgrading solve the issues, i.e. allow me to combine `v-repeat` with `v-show`?

Or is there another way to work around this?

FYI, this current markup is not working, it does repeat but the conditionality is not working as expected:

```html
<tr v-repeat="row: table.rows" v-if="row.display">
    ....
</tr>
```

**Comment by Nirazul** [comment]
Could you try using `filterBy` instead of `v-if`?

```
<tr v-repeat="row: table.rows | filterBy true in 'display'">
    ....
</tr>
```

**Comment by HendrikThePendric** [comment]
Excellent, I got this working now. Using this syntax throughout now. Many thanks for the fast reply!
