### ISSUE TITLE
Vue 0.12.8 assumes `process.env.NODE_ENV` is defined.

### ISSUE THREAD

**Issue by TeffenEllis** [yyx990803/vue#1075]
Given Vue 0.12.8 is required using an AMD loader such as Webpack or Browserify, the browser throws an error at every occurrence of `process.env.NODE_ENV`. 

I believe the regression has something to do with this commit.
https://github.com/yyx990803/vue/commit/0d3b26455d37d09112fc33d05d9e0aa354984f15 

Thank you.

**Comment by yyx990803** [comment]
Although it's present in the source code, it is automatically converted into plain strings by build tools. The distributed file doesn't contain it. Are you running into the error somewhere?

**Comment by uipoet** [comment]
Yes, after building an application with Webpack, such as here: https://github.com/vuejs/vue-webpack-example

**Comment by yyx990803** [comment]
@uipoet webpack auto shims `process` when it detects it, which should just work without special setup. I'm running the webpack example with 0.12.8 just fine. If you are experiencing errors, can you provide a repro?

**Comment by TeffenEllis** [comment]
After testing with your repo I've determined that the issue is our configuration of Webpack's `node` polyfills.

Thank you for your time!
