### ISSUE TITLE
Submit directive

### ISSUE THREAD

**Issue by nekufa** [yyx990803/vue#1076]
Now for any form we use "on" directive and manually prevent default action:

```html
<form id="as-is" v-on="submit: addTask">
  <input type='submit'/>
</form>

<script type="text/javascript">
  new Vue({
    el: "#as-is",
    methods: {
      addTask: function(e) {
        e.preventDefault();
        // do the work
      }
    }
  });
</script>
```

My idea is to made this approach more simpler, like this:

```html
<form id="to-be" v-submit="addTask">
  <input type='submit'/>
</form>

<script type="text/javascript">
  new Vue({
    el: "#to-be",
    methods: {
      addTask: function() {
        // do the work
      }
    }
  });
</script>
```

**Comment by mark-hahn** [comment]
You would have to do this for every event.  And there could be events that
vue doesn't even know about.

What is wrong with the current method?

**Comment by nekufa** [comment]
I can't add labels for issues - looks like only repository owner can do this.
Please, note that it is an enhancement.

Current method is ok, but it does not match DRY principle.

In my opinion, form processing is big part of most web applications.
But, i'm not sure that feature should be included in the core.
I've register the issue to discuss this behaviour.

**Comment by yyx990803** [comment]
Sounds like an overkill to add a core directive just for this simple task, I think this should be a userland concern (aka make your custom directive). Feel free to open a new issue to discuss at vuejs/Discussion.
