### ISSUE TITLE
Can't set properties under certain circumstances

### ISSUE THREAD

**Issue by Padarom** [yyx990803/vue#1078]
I've been trying to get into Vue.js recently and am building something a little more complex than I would usually do with this library. However I have stumbled across a really odd behaviour, which doesn't allow me to set properties.

What I'm building is sort of a step-based assembly interpreter (similar to [TIS-100](http://www.zachtronics.com/tis-100/)), where you have multiple nodes, each with their own set of instructions, that get executed in parallel. The execution of the next line takes place, whenever I click a button on the page. It usually calls a method on the Vue instances called `startExecution()`.

The relevant code of this method:
```js
startExecution: function() {
  var instruction = this.currentInstruction; // currentInstruction is a computed property
  var canContinue = false;

  var nextInstruction = this.instructionPointer;

  // Do whatever the instruction wants you to do.
  // This could change canContinue to true.
      
  if (canContinue) {
    nextInstruction = this.instructionPointer + 1; 
    // Or go back to 0, if the nextInstruction is higher than the number of instructions.
  }

  this.$set("instructionPointer", nextInstruction);
}
```
This part already works. Whenever a instruction says "I'm okay, you can go on with the next one", it will increase the instruction pointer by one, or go back to the first one.

There are however conditional (as well as unconditional) jumps, which change the `instructionPointer` themselves and let `canContinue` stay on false. These actions all happen in separate methods, such as `action_JMP` (unconditional jump), `action_JGZ` (jump if greater than zero), ...

What these do, in their body is pretty much the following:
```js
action_JMP: function() {
  var newInstruction = this.instructionPointer;
  // Do stuff

  this.$set("instructionPointer", newInstruction);
}
```
Here it starts to become weird. When I log the value of `this.instructionPointer` after it has been changed in the action, it is correct and appears to have changed. Logging it in `startExecution`, when I next hit the button however shows, that it hasn't, in fact, changed. It remained the same for some reason.

This also reflects in the template, where I just echo out the `instructionPointer`. It never updates when I'm inside one of the `action_...`-methods, even though the console.log in there suggests so.

What is the reason for this? Is this a Vue.js issue or is it just me being stupid? (The latter would mean that it should belong in `vuejs/Discussion` I think)

**Comment by yyx990803** [comment]
I can't tell what's wrong based on your description - it'd be helpful if you can provide some sort of reproduction of the issue.

**Comment by yyx990803** [comment]
Closing (inactivity)
