### ISSUE TITLE
`withLock` strategy will make some two-way binding not sync.

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#1082]
For example, the `v-model`, when its value changes, it will update the binding value, if the binding value's watcher modify the value, it won't propagate to the `v-model`'s value because the `withLock` in directive.

**Comment by yyx990803** [comment]
This had to do with two problems:

1. modifying the value as the user types would often result in weird UX. If you specifically need that functionality, two-way binding is not the best way to achieve it.
2. When using `v-model` with write filters, we often actually **want** the display to be out of sync with the underlying model: http://jsfiddle.net/yyx990803/daju2xfw/

**Comment by TerenceZ** [comment]
In my case, I create a `radio` component (can be used without the `radio-group`). On the purpose to get the default behavior of the system input, I put a transparent input on the component's template and bind a `v-model` for the `checked` value.

On the other hand, I create a `radio-group` component. In the `radio-group`, I want to make at least one `radio` selected, so I watch the `radio`'s `checked` state when the `radio` attached and update the group's state when it's changed. However, when tap on the selected `radio`, the `radio` will be deselected, so in the `radio-group` I re-select the `radio`, but this `re-selection` won't propagate to the model `checked` of the `radio`'s input:(

I have no any other ideas to achieve this purpose...

**Comment by yyx990803** [comment]
You can just reselect in the nextTick (it's unlocked by then).
