### ISSUE TITLE
Not quite right behavior when a component is right inside another one

### ISSUE THREAD

**Issue by fullfs** [yyx990803/vue#1084]
http://jsfiddle.net/wvbqbyLp/16/ - error (check out console)
http://jsfiddle.net/wvbqbyLp/17/ - ok

I can see it's happening because of replace mechanism and VMs are overlapping but I think the warning is not quite an exact one :)

**Comment by azamat-sharapov** [comment]
I think `v-component` was deprecated and allowed only with `<table>` elements. Weird that it's actually working in your second jiddle.

**Comment by azamat-sharapov** [comment]
[This](http://jsfiddle.net/wvbqbyLp/18/) should be right way to do it in 0.12.
