### ISSUE TITLE
suggestion: passing function result in inline statements

### ISSUE THREAD

**Issue by kazupon** [yyx990803/vue#1090]
https://github.com/yyx990803/vue/blob/fd69bccc6a66fbadf75d7767defb8e1d0cc99bef/src/directive.js#L148

Why `fn` does not return ? Security reasons ?

The following example, sometimes we want to need value that the function return dynamic condition.

```html
<form id="demo">
  <h1>select</h1>
  <p>
      <input type="radio" name="widget" value="title" v-model="widget">
      <input type="radio" name="widget" value="description" v-model="widget">
  </p>

  <h2>input</h2>
  <p v-if="toggleWidget">
    <input v-model="title" v-validate="maxLength: dynamicConstraint('title', 'condition1')">
  </p>
  <p v-if="toggleWidget">
    <input v-model="description" v-validate="maxLength: dynamicConstraint('description', 'condition2')">
  </p>
</form>
```

```javascript
Vue.use(require('vue-validator'))

new Vue({
  data: {
    widget: 'title',
    title: '',
    description: ''
  },
  compueted: {
    toggleWidget: function () {
      return this.widget === 'title'
    }
  }
  methods: {
    dynamicConstraint: function (name, condition) {
      var ret = 100
      if (name === 'title') {
        if (condition === 'foo') {
          // somehting todo ...
        } else {
          // somehting todo ...
        }
      } else if (name === 'description') {
        // somehting todo ...
      }
      return ret
    }
  }
}).$mount('#demo')
```

It can be implemented using `data` option properties and computed properties, but the function is flexibility better than these properties.

If Vue.js could pass the function result in inline statements, I think that it's very useful.

**Comment by yyx990803** [comment]
Are you using `acceptStatement` in `v-validate`?

Note in your use case, you don't need `acceptStatement`.
`dynamicConstraint('a', 'b')` is an expression, so it works without `acceptStatement`.

In comparison, a statement is something like `a++`, which has side effects. For example in `v-on="click: a++"`, if we don't detect a statement, the directive will get the result of `vm.a++` in its `update` handler, which is not a function.

**Comment by kazupon** [comment]
Thank you for your comment.

>dynamicConstraint('a', 'b') is an expression

That’s right !!
It worked without `acceptStatement`.

**Comment by pags** [comment]
I'd still love to know why the line referenced above:

https://github.com/vuejs/vue/blob/fd69bccc6a66fbadf75d7767defb8e1d0cc99bef/src/directive.js#L148

Doesn't pass through the return value of `fn.call(vm, vm)` ?  This value would be immediately useful for at least one use case.
