### ISSUE TITLE
Value from 'default' param of 'props' gets replaced by component's data

### ISSUE THREAD

**Issue by fullfs** [yyx990803/vue#1092]
Hello! Am I missing something?

http://jsfiddle.net/wvbqbyLp/20/ - ok
http://jsfiddle.net/wvbqbyLp/21/ - default value is not present

**Comment by yyx990803** [comment]
Yeah, this has been fixed in 0.12.8: http://jsfiddle.net/yyx990803/wvbqbyLp/22/
