### ISSUE TITLE
cannot resolve component in `v-repeat` when `config.strict` is true

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#1096]
When I set the `config.strict` to true, the repeat directive cannot resolve the proper component. For example followed. The demo is [here](http://jsfiddle.net/TerenceZ/eujehgq4/2/) (See the console).

```html
<outer>
    <template v-repeat="5">
       <inner>$index</inner>
    </template>
</outer>
```

**Comment by yyx990803** [comment]
duplicate: https://github.com/yyx990803/vue/issues/1080
