### ISSUE TITLE
Data binding updates aren't reflected inside textareas

### ISSUE THREAD

**Issue by jackmcdade** [yyx990803/vue#1109]
If i put the same tag inside `<pre>` and `<textarea>` tags, the former will stay in sync with 2-way data bindings but the latter doesn't budge. Fiddle: <https://jsfiddle.net/df4fxhqy/11/>

**Comment by cheapsteak** [comment]
FWIW, it does work if you bind to the text area's "value" property instead, i.e. 

```html
<textarea v-attr="value: $eval('rows | json')>
```

https://jsfiddle.net/xd6dms73/
