### ISSUE TITLE
Support object values in `v-model` for <select>

### ISSUE THREAD

**Issue by jackmcdade** [yyx990803/vue#1115]
When using the `{text:'', value:''}` format for dynamic `<select>` options it becomes complex to get the `text` back out again for display since the `v-model` binds the `value`. One must then run a computed property and filter the `options` again and... you get the point.

Would it be possible to to support a syntax like this?

```
options: [
  {this: 'This One'},
  {that: 'That One'}
]
```

Which would then let us get that value back out like `this.options[this.selected]`. Just an idea. Feel free to say nay.

**Comment by jackmcdade** [comment]
Yeah that would definitely work too.

**Comment by Rastishka** [comment]
This would be cool!

**Comment by JosephSilber** [comment]
@yyx990803 we can do that in my proposed `optionify` filter:

```js
Vue.filter('optionify', function(items, text, value) {
    if (arguments.length > 1) {
        return items.map(function(item) {
            if (value === undefined) return item[text];

            return {
                text: item[text],
                value: item[value],
            };
        });    
    }

    return Object.keys(items).map(function(key) {
        return {
            text: items[key],
            value: key,
        }; 
    });
});
```

**Comment by J-F-Liu** [comment]
Installed latest code in dev branch, but it still doesn't work.
As I debug the code, I find that inside `function buildOptions` of select.js
After execute line 144 ` el.value = op.value`, `el.value` is "[object Object]", a string value.

**Comment by yyx990803** [comment]
@J-F-Liu of course `el.value` will be serialized. The object value only works when syncing back to model.

**Comment by J-F-Liu** [comment]
The example code in #1183 still doesn't work, can you have a try?

**Comment by simplesmiler** [comment]
@J-F-Liu did you build?
> The dist folder contains the standalone build for Vue.js, however files here are only checked-in when a release happens. If you are on the dev branch, files here are NOT up to date.

**Comment by J-F-Liu** [comment]
@simplesmiler Yes, I installed with `bower install yyx990803/vue#dev`, after clone the repo and run build task the code works now, thanks.

**Comment by app-sparkler** [comment]
``` jade
select(@change="statusSelected")
  option(v-for="orderStatus in orderStatusList", :value="    JSON.stringify(orderStatus)") {{ orderStatus.status }}
```

**Comment by doublemarked** [comment]
@app-sparkler afaik serialization like that is not necessary. In the docs they show the following example:

```
<select v-model="selected">
  <!-- inline object literal -->
  <option v-bind:value="{ number: 123 }">123</option>
</select>
```

From here: https://vuejs.org/v2/guide/forms.html#Select-Options

**Comment by ndabAP** [comment]
It seems like the support for objects as values is dropped again.

**Comment by appsparkler** [comment]
@ndabAP 

It does work...


```html
<template id="my-temp">
	<div>
		<h1>{{myProps.foo}}</h1>
	</div>
</template>
```

```javascript
Vue.component('myComp', {
	template:'#my-temp',
	props: ['myProps'],
})

```html
<my-temp my-props="{foo: 'bar'}" ></my-temp>
```

gives the output of :

```html
<h1>bar</h1>
```

screenshot:

![image](https://user-images.githubusercontent.com/12084821/32404927-f821da58-c180-11e7-8e9d-0516c9a53c7e.png)


Good Luck...

**Comment by appsparkler** [comment]
@ndabAP 

It does work...


```html
<template id="my-temp">
	<div>
		<h1>{{myProps.foo}}</h1>
	</div>
</template>
```
## +
```javascript
Vue.component('myComp', {
	template:'#my-temp',
	props: ['myProps'],
})
```
## +
```html
<my-temp my-props="{foo: 'bar'}" ></my-temp>
```

## gives the output of :

```html
<h1>bar</h1>
```

## screenshot:

![image](https://user-images.githubusercontent.com/12084821/32404927-f821da58-c180-11e7-8e9d-0516c9a53c7e.png)


Good Luck...

**Comment by zealotrahl** [comment]
So, still no sollution to this?

**Comment by appsparkler** [comment]
@zealotrahl please see my answer above your question.

**Comment by djom202** [comment]
Hi, Any work around this? I'm still facing this issue with the `v-model` and `Objects`
