### ISSUE TITLE
多个select component时提示Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by dalphyx** [yyx990803/vue#1120]
在写一个简单的省级级联component时发现，提供个demo：http://jsfiddle.net/4oa8anz4/

demo提供的是市在省之前时的正确表现，但只要把level2的市级元素移到level1的省级元素之后，就会报Cannot read property 'childNodes' of undefined

**Comment by tcdona** [comment]
看到根本没有 level = 1 的属性配置
```
if (this.level !== '2') { 
```
是不是比
```
if (this.level === 1) { 
```
好些 ？而且没报错了
