### ISSUE TITLE
Vue loosing bindings even using $set method when using keypath props values

### ISSUE THREAD

**Issue by sl-codenine** [yyx990803/vue#1122]
I have some strange behavior after upgrading to vue-0.12.9.

I'm not sure what's going on, can't explain really. I've created simplified fiddle to demonstrate it http://jsfiddle.net/plunntic/ydjzhkn8/

Not sure if it's me doing something wrong, but it looks more like vue having problems with bindings?

**Comment by sl-codenine** [comment]
I've updated the fiddle with some more examples, it looks like vue is loosing the bindings even when using `$set` method, when using keypath value for a prop, like `my-prop="{{ my_model.my_array }}"`.

**Comment by yyx990803** [comment]
You shouldn't be initializing `some_model` in the created hook. You should be returning it inside the `data` option, which is specifically for initializing observed properties:

``` js
data: function () {
  return {
    some_model: { ... }
  }
}
```
