### ISSUE TITLE
请问如何使用异步组件

### ISSUE THREAD

**Issue by tcdona** [yyx990803/vue#1123]
http://jsfiddle.net/yolio2003/vrzcxp42/8/
看起来我还是不会用下面的代码：
```
Vue.component('async-example', function (resolve, reject) {
  setTimeout(function () {
    resolve({
      template: '<div>I am async!</div>'
    })
  }, 1000)
})
```

**Comment by yyx990803** [comment]
`<component>` 上面用 `is` 不是 `id`: http://jsfiddle.net/yyx990803/vrzcxp42/10/

**Comment by tcdona** [comment]
啊，sorry 这个问题上，错了好多次。。。 总是把 is 写成了 id，我太粗心了

**Comment by cocody** [comment]
在webpack+vue-loader 时候都是.vue的组件文件，怎样用异步组件？

**Comment by yyx990803** [comment]
http://cn.vuejs.org/guide/components.html#异步组件

**Comment by breezefeng** [comment]
vue2.0里面使用异步组件watch无效是怎么回事
