### ISSUE TITLE
content select is not expected if the contents aren't mutual exclusive.

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#1125]
As the description followed. For an online demo, check [here](http://jsfiddle.net/TerenceZ/3wsk4kmx/).

```html
<!-- Before Compile -->
<comp>
  <div a></div>
  <div a b></div>
</comp>

<!-- After Initialisation -->
<div class="comp">
    <div a b></div>
    <div a></div>
    <div a b></div>
</div>

<!-- Expectation -->
<div class="comp">
    <div a b></div>
    <div a></div>
</div>

<template id="comp-tmpl">
<div class="comp">
  <content select="[b]"></content>
  <content select="[a]"></content>
</div>
</template>
```

**Comment by yyx990803** [comment]
This is actually intended. Each content outlet will get **all** content elements that match its selector, regardless of its appearance order. This allows the same block of content to be reused multiple times in the component, which is sometimes very useful. I also think it's better than having the rendered result depend on how the outlets are ordered.

You can use a more specific selector in your example: `<content select="[a]:not([b])">`.
