### ISSUE TITLE
$index on v-repeat with orderBy

### ISSUE THREAD

**Issue by timavo** [yyx990803/vue#1126]
I got a list of `users` which are displayed with `v-repeat`.

HTML:
```
<ul id="vue">
    <li v-repeat="users | orderBy 'name'" v-on="click: onClick($index)">@{{ name }} | @{{ phone }}</li>
</ul>
```

JavaScript:
```
new Vue({
    el: '#vue',

    data: {
        users: [
            { name: 'Berta', phone: '555-123-4567' },
            { name: 'Delta', phone: '999-123-4567' },
            { name: 'Anton', phone: '888-123-4567' },
            { name: 'Echo', phone: '333-123-4567' },
            { name: 'Charlie', phone: '444-123-4567' }
        ]
    },

    methods: {
        onClick: function(index) {
            this.users.$remove(index);
        }
    }
});
```
If I just use `v-repeat="users"`, I can access the original user with `this.users[$index]`. However, if I manipulate the list by ordering and/or filtering (e.g. `v-repeat="users | orderBy 'name'"`), `$index` points to the element in the ordered list.

What I'd like to do is removing an element from the original users array. As stated above `this.users.$remove($index)` only works on the original `v-repeat`, not on filtered or ordered lists.

**Comment by timavo** [comment]
Ok, I was able to remove the user with the following changes:

HTML
```
<li v-repeat="user in users | orderBy 'name'" v-on="click: onClick(user)">@{{ user.name }} | @{{ user.phone }}</li>
```

JavaScript
```
methods: {
    onClick: function(user) {
        this.users.splice(this.users.indexOf(user),1);
    }
}
```

**Comment by yyx990803** [comment]
Just remove the item directly with `this.users.$remove(user)`.

**Comment by timavo** [comment]
Thanks a lot for that fast answer! :-) :+1:
