### ISSUE TITLE
v-show allowing multiple boolean args

### ISSUE THREAD

**Issue by afischer** [yyx990803/vue#1127]
Having the ability to have comma separated booleans or even multiple booleans with minimal logic (and/or) in a single v-show would be great. 

Thanks for the awesome tool.

**Comment by yyx990803** [comment]
You can use inline expressions like `(a && b) || c`, if you need something more complex, consider using a [computed property](http://vuejs.org/guide/computed.html).

**Comment by afischer** [comment]
Ah, thanks! I'll put a PR in the documentation noting this.
