### ISSUE TITLE
Is Laravue a good practice?

### ISSUE THREAD

**Issue by levelel** [yyx990803/vue#1130]
I've found this repository called "Laravue". 
https://medium.com/laravel-news/advanced-front-end-setup-with-vue-js-laravel-e9fbd7e89fe2 
which uses Laravel as backend and Vue as frontend engine.
My question is that, although it looks convenient, is the way this author constructs the app against the patterns Vue uses? For example, it references the whole "app" in each components, so that it allows (and encourages) direct access of function and variables in every components across the app. Would that potentially cause any problems?

**Comment by yyx990803** [comment]
This should be moved to [vuejs/Discussion](/vuejs/Discussion).

I personally don't like the style shown in the post, but people can do whatever they like. In most cases you want your components to be well encapsulated and rely on simple props rather than the entire app state.
