### ISSUE TITLE
$index not available on element that v-repeat is on

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#1138]
fiddle:  
http://jsfiddle.net/x912s7tn/1/

According to the docs for [displaying a list](http://vuejs.org/guide/list.html), this should work:

```vue
<item v-repeat="10" index="{{$index}}"></item>
```
```js
var Item = Vue.extend({
    id: 'item',
    props: {
        index: { type: Number }
    },
    data: function() {
        return { index: 0 }
    },
    template: '{{index}}'
})

new Vue({
    el: 'body',
    components: [Item]
})

```
But I'm getting :

```
[Vue warn]: Invalid prop: type check failed for index="{{$index}}". Expected Number, got Undefined.
```

**Comment by azamat-sharapov** [comment]
When `v-repeat`ing component, you get limited abilities of `v-repeat`, so you can't access `$index/$value/$data` in that case. I think Evan has mentioned that somewhere in issues. You can wrap it with `<template>` tag.

**Comment by yyx990803** [comment]
For repeated components, `$index` is automatically available, but only inside the component's own template. Because they are components so they get the same limitation of component scope rules: http://vuejs.org/guide/best-practices.html#Component_Scope
