### ISSUE TITLE
Should not try to read optional props from a document fragment

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#1139]
fiddle: http://jsfiddle.net/o65b85e1/1/

```js
var Foo = Vue.extend({
    props: {
        optionalProp: {
            type: Number,
            required: false
        }
    }
})

new Foo({
    el: document.createDocumentFragment()
})
```

results in:

```
Uncaught TypeError: el.getAttribute is not a function
```

**Comment by yyx990803** [comment]
Hmm, looks like all props should be just skipped in this case. But under what situation would a fragment be passed to the instance?

**Comment by cheapsteak** [comment]
Probably not useful for practical usage, but I was trying to get Vue working again in the framework benchmark :)

http://jsfiddle.net/garnwraly/nfd216t3/1/

**Comment by yyx990803** [comment]
Hah, that seems to be a lot faster than the old version...

**Comment by cheapsteak** [comment]
Yeah :D
A friend at work is saying Vue's a lot slower than React for style-attribute based animations, I was thinking that can't be right, and even if it is slower it can't be by much
Found the benchmarks from a couple months ago, looks like Vue's more than twice as fast as React
http://jsfiddle.net/garnwraly/jkbqk8xo/5/

**Comment by yyx990803** [comment]
Well, the bottleneck for style-attribute-based animations is almost never the framework, but the properties you are animating ;)
