### ISSUE TITLE
未知报错，还是不稳定

### ISSUE THREAD

**Issue by niluanxy** [yyx990803/vue#1143]
代码在同事Win7 X64 Chrome下报错，其他地方正常。
![2](https://cloud.githubusercontent.com/assets/7076522/9189820/d00e30d6-4020-11e5-881f-00b275443c77.png)
![1](https://cloud.githubusercontent.com/assets/7076522/9189822/d4b17d28-4020-11e5-8e8d-85fd65a20457.png)

**Comment by yyx990803** [comment]
看起来你的数据结构里面有对 window 的引用，这种你不给我能跑的代码我也没办法啊。

**Comment by niluanxy** [comment]
行，我把代码发给你，往不要外传，公司项目，发你邮箱就可以吗？


在2015年08月11日 12:36，Evan You 写道:

看起来你的数据结构里面有对 window 的引用，这种你不给我能跑的代码我也没办法啊。

**Comment by niluanxy** [comment]
已经确定vue的问题，只要切换到0.12.6以下版本就能正常，以上全部有问题

**Comment by yyx990803** [comment]
把代码和详细的重现步骤发给我

**Comment by niluanxy** [comment]
代码已经发给你了，用完记得删除哦

**Comment by yyx990803** [comment]
代码跑起来以后登陆不了。我建议你：1. 不要用压缩版本的 Vue；2. 在抛错的地方打上断点看看，你貌似在一个组件的 `ready` 钩子里面干了什么事情，比如 `$set` 了一个对象，然后这个对象里面有对 `window` 的引用。

**Comment by yyx990803** [comment]
下个版本的数据观测会自动跳过非简单对象。
