### ISSUE TITLE
v-model and v-on="click" with checkbox, different priority chrome and firefox

### ISSUE THREAD

**Issue by z358z358** [yyx990803/vue#1146]
I want to use v-model and v-on with checkbox

like this : `<input type="checkbox" v-model="test" v-on="click: foo"> `

jsfiddle: http://jsfiddle.net/c686xbrn/

but chrome and firefox alert different result

how can I get same? thx

**Comment by yyx990803** [comment]
Don't use `v-on`, use `watch`: http://jsfiddle.net/yyx990803/c686xbrn/1/

**Comment by z358z358** [comment]
ok thx  

but I try to use v-repeat together  http://jsfiddle.net/7hk7rz10/

how to I watch them? thx

**Comment by yyx990803** [comment]
Use components: http://jsfiddle.net/yyx990803/7hk7rz10/2/

**Comment by ian-patel** [comment]
@yyx990803  How about `v-model` and  `v-on:paste="work_shorten"` with input textbox? 
I would like to have new data when `paste` event fired. 
 https://jsfiddle.net/ianpatel/1c1mqcfh/

**Comment by sakopqiu** [comment]
There is another(but not so that elegant) workaround, wrap you onclick logic with Vue.nextTick

```
onClickFunc(){
   Vue.nextTick(()=>{
    //here goes your onclick logic
  }); 
}

```

**Comment by maoxiaoke** [comment]
#293

**Comment by kushal555** [comment]
> Don't use `v-on`, use `watch`: http://jsfiddle.net/yyx990803/c686xbrn/1/

Can you please replace your `vue.js` CDN URL.

**Comment by LinusBorg** [comment]
@kushal555  this is a 3 year old issue, applies to Vue 0.11 or something.
