### ISSUE TITLE
auto transform property to number even if its property assert type is string.

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#1148]
For example as followed, after initialisation, a warn "Expected string, got number" will be raised up.

```html
<comp a="10"></comp>
<script>
Vue.component({
    name: "comp",
    props: {
        a: { type: String }
    }
});
</script>
```

**Comment by yyx990803** [comment]
This is auto casted because in most cases people do want a Number when they pass a number. If you want a literal string of numbers you'd have to do `<comp a="{{'10'}}"></comp>`.
