### ISSUE TITLE
Dynamic Select clarification request

### ISSUE THREAD

**Issue by maiorfi** [yyx990803/vue#1149]
Hi.

I just got that as for V 0.12.9+ adding select options tag through v-repeat is deprecated.

I already started refactoring my code, but how could I specify attributes for "inflated" repeated options other than text and value? What for example about "disabled" or "style" or "class" attributes?

Thanks!

**Comment by yyx990803** [comment]
You can use object format in the form of

``` js
{
  text: '123',
  value: 123,
  disabled: true
}
```

Style and classes for dynamic options are currently not supported. I'd suggest using a selector like `.select-input option` to style these options.

**Comment by maiorfi** [comment]
Ok, thanks.

Is there any other property I can use for "option" object?

**Comment by maiorfi** [comment]
Maybe making v-repeat for options obsolete could be reconsidered: whenever I extend base html select with plugins such as select2 (through a custom directive) weird things happen :(

**Comment by yyx990803** [comment]
For select2, checkout the official example: http://vuejs.org/examples/select2.html

**Comment by maiorfi** [comment]
It seems that updating backing options array "later" (with respect to viewmodel initialization) doesn't work. Since I usually fill my select (actually select2) in ajax return callbacks it is a hard issue to work around :(

Please take a look to https://jsfiddle.net/yyx990803/zuc27nw9/

Thanks!

**Comment by yyx990803** [comment]
The example assumes the options are static. What you can do is instead of `$eval`ing once, use `vm.$watch()` inside `bind()` to update the options of select.

**Comment by yyx990803** [comment]
Closing this, but I will think about if there's anyway to improve the current select syntax.
