### ISSUE TITLE
keep-alive and wait-for do not work together

### ISSUE THREAD

**Issue by nkovacs** [yyx990803/vue#1150]
http://jsfiddle.net/nkovacs/L94uaxrf/

Click "Page 1", click "Page 2", then click "Page 1" again.

Since the page1 component is cached, its compiled function is not called again, and it never emits the event.

**Comment by yyx990803** [comment]
Yeah. I saw the post in Discussion - currently the idea is that we probably need a new hook (instead of `compiled`) that is called right before the first insertion. This hook will provide a callback and also accepts returning a Promise.

**Comment by nkovacs** [comment]
This is not really related to that, I just discovered it accidentally while looking at the code.
For the intended usage of wait-for, this could be fixed by not waiting for the event if the component is reloaded from cache. The component should have all the data it needs (though it might be stale), so there's no need to wait.
