### ISSUE TITLE
Allow a checkbox in a td to be clickable anywhere in the td

### ISSUE THREAD

**Issue by Ben52** [yyx990803/vue#1154]
My problem is a pretty simple one, there must be a simple solution. I have a table, and a checkbox on each row.
```
<tr v-repeat="claim: claims">
    <td  v-on="click: claim.selected = !claim.selected">
        <input  v-model="claim.selected" type="checkbox">
    </td>
</tr>
```
The problem is, it works when clicking around the input, within the td, but when I click on the input directly, it automatically gets unselected because of the on click of the surrounding td. Does anyone have a solution?

**Comment by Mat-Moo** [comment]
What is the purpose of the checkbox? why not just show a selected/not selected class state on the td based on claim.selected? (If you need it then add a hidden input?)

**Comment by yyx990803** [comment]
Although dirty, you can add a `v-on` listener on the input and stop the event propagation. In future versions you can also directly do `<input type="checkbox" checked="{{claim.selected}}">`. Please post this type of questions to vuejs/Discussion later.
