### ISSUE TITLE
Select defaults not recognized if it's an empty string

### ISSUE THREAD

**Issue by miljan-aleksic** [yyx990803/vue#1155]
Hi,

if there is a list of options and of them has value as '' (empty string) and the model is set as empty string as well, it will not get synced being the default option empty. Easier to see than to say... check jsfiddle [here](http://jsfiddle.net/miljan/8ran25s9/1/).

I know about the new default option feature in 0.12.10 but the options are dynamic in this situation and there could be or not an empty string option.

**Comment by amine014** [comment]
There's a big problem with selecting options, http://jsfiddle.net/504L15f5/4/ for example

**Comment by yyx990803** [comment]
@amine014 the fiddle works properly with latest `dev` branch, so wait for the next release please.

**Comment by miljan-aleksic** [comment]
Thanks Evan :)
