### ISSUE TITLE
$add is not considering the keypath

### ISSUE THREAD

**Issue by miljan-aleksic** [yyx990803/vue#1156]
When using $set the keypath go deep creating all the nested levels required, but that doesn't happen when using $add. Maybe is a limitation of $add and should be combined with $set but the documentation states keypath for $add as well, and I'm assuming it should work the same way. Let me know if wrong.

Example [here](http://jsfiddle.net/miljan/zxh4oe4n/1).

**Comment by yyx990803** [comment]
Yeah, that's an error in the doc. Only `vm.$get` and `vm.$set` support paths. In fact, since `$set` does everything `$add` does, `$add` should just be deprecated.

**Comment by miljan-aleksic** [comment]
So its correct to use $set even if the object you are setting does not exists in the root?

**Comment by yyx990803** [comment]
yeah, `$set` calls `$add` internally. Note there's the difference between `vm.$set` vs `vm.object.$set`: the former accepts paths, because it's a vm instance method; the latter only accept keys, because it's a data object enhancement method.

**Comment by miljan-aleksic** [comment]
That make sense, I would suggest updating the docs to avoid further confusions and deprecating $add seems correct then. Thanks Evan.
