### ISSUE TITLE
suggestion($add, $set): silent mode

### ISSUE THREAD

**Issue by miljan-aleksic** [yyx990803/vue#1157]
I'm not sure if possible, but in some situations I need to alter the $data object on the fly (before the dome is compiled) without firing any watch event. My suggestion would be adding the Silent option for both, Ex: this.$set('foo', true) being the result the same but without triggering any watchers events.

**Comment by yyx990803** [comment]
This is not really recommended, because it breaks down the reactivity guarantee. You can, however, call `$watch` after you call `$set`.

**Comment by miljan-aleksic** [comment]
Yes, of course, is just the app is quite big and complex and makes it difficult to do so, but I understand. Thanks for considering, anyway.

**Comment by yyx990803** [comment]
Well, that's why I usually advice against adding new data properties on the fly. Prefer a deterministic data model, it helps you reason about your app once it gets big.

**Comment by miljan-aleksic** [comment]
Yes, you are totally right, already started moving towards that approach ;)
