### ISSUE TITLE
Selected option tag in list issue

### ISSUE THREAD

**Issue by amine014** [yyx990803/vue#1158]
<option v-repeat="trainings"  @{{state}}  >
               @{{ name }} - @{{ category }}€</option>
</select>

@{{state}} is not getting compiled

Any help please?

**Comment by amine014** [comment]
<option v-repeat="trainings"  selected="@{{state}}"  > not working too

**Comment by amine014** [comment]
The following are valid, equivalent and true:

<option selected />
<option selected="" />
<option selected="selected" />
<option selected="SeLeCtEd" />
The following are invalid:

<option selected="0" />
<option selected="1" />
<option selected="false" />
<option selected="true" />

**Comment by yyx990803** [comment]
If you are also using `v-model` on the select element, you should use [dynamic options](http://vuejs.org/guide/forms.html#Dynamic_Select_Options).

**Comment by amine014** [comment]
$.ajax({
                        method: "POST",
                        url: "../modalUserInfo"+ '?_token=' + document.querySelector('#token').getAttribute('value'),
                        data: this.userInfo,
                        success: function(trainingList) {  //todo-me create a function for that repetitive lines
                            that.nextWizard(tabIndex)
                            that.trainings = trainingList
                            var training_page = $("#training").text();
                            $.each( that.trainings, function( key, trng ) {
                                alert(training_page + '+++' + trng.name)

                                if (trng.name == training_page) {
                                    alert('in' + trng.name)
                                    $.extend(trng, {"state":"selected"});
                                    //$('#trainingsList option[value=training.page]').attr("selected", "selected");
                                }
                            });
                        },

**Comment by amine014** [comment]
$.ajax({
                        method: "POST",
                        url: "../modalUserInfo"+ '?_token=' +        document.querySelector('#token').getAttribute('value'),
                        data: this.userInfo,
                        success: function(trainingList) {  //todo-me create a function for that repetitive lines
                            that.nextWizard(tabIndex)
                            that.trainings = trainingList
                            var training_page = $("#training").text();
                            $.each( that.trainings, function( key, trng ) {
                                alert(training_page + '+++' + trng.name)

                                if (trng.name == training_page) {
                                    alert('in' + trng.name)
                                    $.extend(trng, {"state":"selected"});
                                    //$('#trainingsList option[value=training.page]').attr("selected", "selected");
                                }
                            });
                        },

**Comment by amine014** [comment]
So my only problem is to get @{{ state }} compiled <option  v-attr=" {{ state }}">

**Comment by yyx990803** [comment]
`selected="{{state}}"` should work if you are not using `v-model`. http://jsfiddle.net/504L15f5/

**Comment by amine014** [comment]
no sorry it's not working the browser select the last in the list as selected is in all the options

**Comment by yyx990803** [comment]
Please look at the example carefully. If you are looking for multiple select you need to add the multiple attribute. http://jsfiddle.net/504L15f5/1/
