### ISSUE TITLE
change value of the button

### ISSUE THREAD

**Issue by lithstud** [yyx990803/vue#1160]
Hi,

This is not actually an issue with the framework, but rather a question for help. 
I have a button, which opens a dropdown (bootstrap). Once I click the li from the dropdown, it should change the span text which is inside that button. Basically it simulates select tag. In jquery, I have this function which works perfectly. 

    function changeCategory() {
        $dropdown = $('ul.dropdown-menu li');
        $dropdown.click(function() {
            var category = $(this).find('a').text();
            $category_button = $('.category span.text');
            $category_button.text(category);
        })
     }

I'm trying to migrate most of the code to Vue.js and I'm just struggling with this. How would I do the same thing in it? I'm sure it's a simple thing but I'm just missing something. 
Thanks.

**Comment by yyx990803** [comment]
Please post questions to [vuejs/Discussion](vuejs/Discussion) instead of the main repo.
