### ISSUE TITLE
Value in mustache not dynamically updated in custom directives?

### ISSUE THREAD

**Issue by Voyga** [yyx990803/vue#1164]
```html
<div v-repeat="value in array" v-press="{{$index}}"></div>
```

```javascript
press: {
    isLiteral: true,
    update: function() {
        this._isDynamicLiteral = true;
        App.index = this.expression
    }
}
```
At first I can get the right $index value. But if I delete a value in the array, the `update` function is executed, but `this.expression` still passes the original $index value before changes. How can I get the right $index if something changes in the array?

**Comment by yyx990803** [comment]
Why are you using a literal directive here? Why not just `v-press="$index"` and then

``` js
press: {
  update: function (index) {
    console.log(index)
  }
}
```

Also, `this._isDynamicLiteral` is an internal flag, you don't need to set it yourself. If you provide `update` to a literal directive then it is automatically a dynamic literal.

So if you **really** want a literal directive, it should be

``` html
<div v-repeat="value in array" v-press="{{$index}}"></div>
```

``` js
press: {
  isLiteral: true,
  // same update function
  update: function (index) {
    console.log(index)
  }
}
```

**Comment by Voyga** [comment]
Thanks. I misunderstood the doc.

**Comment by mark-hahn** [comment]
> . I misunderstood the doc.

I have written 2 apps in vue (which is great btw) but I still get confused
as to when the mustache is needed.  Not needing them in some situations
even when replacement is happening is confusing.

It would be cool if they were allowed in all places where things were
evaluated.  The evaluation parser could strip them out.
