### ISSUE TITLE
Deprecate `wait-for` component param

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#1169]
ref: [Discussion#334](https://github.com/vuejs/Discussion/issues/334)

### Problem

`wait-for` is originally designed to control the transition timing of dynamic components, but it has proven confusing and cumbersome to use.

1. It has to be declared in the parent template, and them implemented by **all** child components that can potentially be switched into.

2. You have to pick a event name that doesn't conflict with anything else. There's the chance that a child component could dispatch an event with the same name.

### Proposal

Deprecate `wait-for` and introduce a new lifecycle hook (tentative name: `activate`) that is called before component insertion. The component will not be inserted until the user calls the passed-in callback, or return a promise.

### Example

``` js
Vue.component('example', {
  activate: function (insert) {
    doSomethingAsync.then(function () {
      // set data or something
      insert() // done
    })
  }
})
```

The activate hook will be called when a component is about to be inserted into the DOM, either as a static component (in the form of a custom element) or as a dynamic component (with `<component bind-is="view">`). Note it is **not** called when you imperatively manipulate the instance with instance API methods like `$before`.

Also, a component with `keep-alive` will not invoke `activate` if it was already activated and kept alive.

**Comment by AlexandreBonaventure** [comment]
Is the activate hook called when using `$addChild` ?

**Comment by yyx990803** [comment]
@AlexandreBonaventure No. It is only used in dynamic component switching.

**Comment by AlexandreBonaventure** [comment]
So, I guess the way to do it right will be to call `$addChild` when I resolve a promise for instance (loading remote data) ?
Also, I was wondering if there is any way to reference a child (in vm.$refs) when using `$addChild`

**Comment by yyx990803** [comment]
@AlexandreBonaventure yes, since you are using the lower-level imperative API, you are responsible for managing the timing yourself.

As fo refs, if you are using the latest alpha/beta, you can pass in a private `_ref` option when creating the child:

``` js
vm.$addChild({
  _ref: 'child'
})
```

**Comment by AlexandreBonaventure** [comment]
Thanks. I asking these questions because we are using Vue with a WISIWYG software called Hype ( http://tumult.com/hype/ ). So we need to mount some child components in separate wrappers. And `$addChild` is the only way we found to do it.  

Maybe it will be helpful for you to know this usage for further development.

**Comment by yyx990803** [comment]
@AlexandreBonaventure cool! That looks really interesting.

**Comment by AlexandreBonaventure** [comment]
Thanks for your interest. Here's a link of our latest project using Vue / Hype.
https://www.robertveutlire.com

This workflow gives us the ability to prototype the design quickly while keeping a stable structure for logic and javascript with Vue.
