### ISSUE TITLE
Make strict mode the default

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#1170]
### Problem

Currently, when a asset is passed into a component as an option, it becomes available not only to that component, but also **all descendants** of that component in the view hierarchy. Although convenient in some cases, this encourages a child component to implicitly rely on its ancestor providing an asset it needs. When looking at the child component alone, it becomes unclear where the dependency comes from and makes it hard to locate the source of that dependency. This can impact the maintainability of large codebases with many nested components.

### Proposal

Make strict mode the default in 1.0. Potentially remove the strict config option altogether.

**Comment by fergaldoyle** [comment]
+1. Currently building a large application with strict turned on, and it's really beneficial.

**Comment by TerenceZ** [comment]
+1.

**Comment by simplesmiler** [comment]
Considering this, how would one pass assets from parent to child?
Imagine a slider component which lets consumer to specify custom transition for slides.
Would this be possible only by extending component and overriding assets?

Currently this is possible by containing such component in an "asset provider" component. Hacky, but gets job done.

**Comment by yyx990803** [comment]
@simplesmiler I'd imagine such a component would come with a set of pre-defined transitions and let the user pick one... although theoretically you can pass it in like `prop-custom-transition="$options.transitions.myTrans"`... but that looks hacky too.

**Comment by swannknani** [comment]
+1

**Comment by davidkhess** [comment]
+1 - never used that pattern and wouldn't want to rely on it.

**Comment by yyx990803** [comment]
Confirmed. Deprecation warning implemented in alpha and the option will be removed in beta.

**Comment by indus** [comment]
How do I now implement a component hierarchy where two components have the same asset-component?

**Comment by yyx990803** [comment]
@indus you explicitly depend on that asset-component in both components.

**Comment by jasonvarga** [comment]
Sorry to revive an old thread.

I have a couple of helper filters: `pre`, for example lets me do `{{{ var | pre }}}` which is shorthand for `<pre><code>{{ var | json }}</code></pre>`. I found it very handy to just drop it anywhere for debugging.

Does this mean I will now have to register these as filters on every component I wish to use them on?

Is there an alternative?

**Comment by yyx990803** [comment]
@jasonvarga just register it globally

**Comment by jasonvarga** [comment]
How? On the root Vue instance? That gives me deprecation warnings when I use it inside a component.

>
[Vue warn]: {DEPRECATION} Falling through to parent when resolving filters with id "pre". Strict mode will be the default in 1.0.0. See https://github.com/yyx990803/vue/issues/1170 for details.

**Comment by yyx990803** [comment]
Vue.filter('pre', ...)

**Comment by jasonvarga** [comment]
Oh, right - wonderful, thanks!
