### ISSUE TITLE
Deprecate $add()

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#1171]
### Problem

`$add()` currently has the somewhat confusing behavior of doing nothing if a key already exists, even if you pass the second argument which is supposed to be the value. On the other hand, its functionality can be replaced by `$set()` in almost all cases. It just seems unnecessary.

### Proposal

Deprecate `$add()`. Use `$set()` instead.

**Comment by kazupon** [comment]
:+1: I agree.

**Comment by vitorarjol** [comment]
:+1:

**Comment by abishekrsrikaanth** [comment]
:+1:

**Comment by holic** [comment]
:+1:

**Comment by davidkhess** [comment]
+1

**Comment by gapipro** [comment]
:+1:

**Comment by yyx990803** [comment]
Implemented in alpha branch. Just need removal in beta.

**Comment by Joeper214** [comment]
```javascript
Vue.component("insert-cf-params", {
    template: '#insert-cf-params-template',
    data: function () {return {
      params: {},
      result: {},
      loading: false,
    };},
    methods: {
      submit: function () {
      },

      back: function () { app.show_tabpane('add_modify'); },
    },
    created: function () {
      var self = this;
      console.log(self);
      var cft = new CFTemplate(current_infra);
      cft.insert_cf_params(this.$parent.current_infra.add_modify).done(function (data) {
        self.params = data;
        _.each(data, function (val, key) {
          self.result.$set(key, val.Default);
        });
        app.loading = false;
      }).fail(alert_danger(function () {
        self.back();
      }));
    },
  });
```



I was using  `self.result.$add(key, val.Default)` and it works fine on Vue 0.12.0

but the problem is when I changed to Vue 1.0.0. and changed it to this:

`self.result.$set(key, val.Default)`. is having an error.

console says it's not a function. Any workaround on this?

I am now using Vue 1.0.0.

**Comment by OEvgeny** [comment]
@Joeper214 please read docs carefully. `$set` on objects is deprecated. Since 1.0 there are `Vue.set` and `vm.$set` methods.

**Comment by Joeper214** [comment]
Thanks man. @OEvgeny

**Comment by matthewcanty** [comment]
Docs still mentions $set here:

http://vuejs.org/guide/list.html#Caveats

**Comment by azamat-sharapov** [comment]
@matthewcanty that right, because `array.$set()` is not depreciated.
