### ISSUE TITLE
[建议]指令和组件添加优先级属性

### ISSUE THREAD

**Issue by niluanxy** [yyx990803/vue#1172]
希望能加入优先级的设计，和NG一样，比如有两个组件或者指令，一个 v-repeat ，一个 v-tap，比如 v-repeat 的优先级为900，v-tap 优先级为 800，则 v-repeat 一定会保证在 v-tap 之前执行和渲染。有了这个东西就能做一些复杂的设计和组件了。还有希望能设置指令的名字，现在所有指令的前缀都是 v-，这样指令编写的时候就可能出现覆盖的问题。能自定义的话，自己写的指令都用同样的前缀，就能避免这个问题了。

**Comment by yyx990803** [comment]
现在就有 priority 选项的，看下源码...
指令覆盖的问题，不要弄成全局的就不会覆盖了啊

**Comment by niluanxy** [comment]
现在加进去了吗？没看源码，所以不太清楚，因为你的源码结构我看的有一丢丢晕。还有指令覆盖，我刚好就是弄成全局了。。。所以，比较希望前缀能自定义。priority这个属性，是不是数字越大，优先级越高，编译越在前面？

**Comment by yyx990803** [comment]
https://github.com/yyx990803/vue/blob/dev/src/directives/attr.js#L12

**Comment by yyx990803** [comment]
自定义前缀暂时不考虑，我希望通过统一的前缀和其他所有 attribute 区分开来。你可以用 `v-my-xxx` 的形式。
