### ISSUE TITLE
是否有引用外部模板的内置方法呢?

### ISSUE THREAD

**Issue by galenyuan** [yyx990803/vue#1174]
Hi
Vue中有没有类似AngularJS的TemplateCache方法能够引用外部模板来做header,footer一类的东西呢？
Thanks

**Comment by yyx990803** [comment]
Vue 有 [partial 机制](http://cn.vuejs.org/api/elements.html#partial)，但不支持针对模板的异步加载。推荐的做法是在开发时直接模块化打包。运行时能够异步加载的最小单位是组件。
