### ISSUE TITLE
v-el not working

### ISSUE THREAD

**Issue by itangog** [yyx990803/vue#1176]
https://jsfiddle.net/6at4L307/ Double click on a todo to edit it , it will not focus.  I tried the Vue.nextTick function but still not working .

**Comment by simplesmiler** [comment]
@itangog `v-el` doesn't work when wrapped in a `v-repeat`.

**Comment by yyx990803** [comment]
`v-el` inside a `v-repeat` won't register on the top vm because there could be many of them conflicting with each other.

See how to handle this in the official todomvc example: https://github.com/yyx990803/vue/blob/dev/examples/todomvc/js/app.js#L110-L123
