### ISSUE TITLE
Pass Objects/Arrays as props for custom component?

### ISSUE THREAD

**Issue by gmhenderson** [yyx990803/vue#1177]
Is there some way to make this work?

```javascript
Vue.component('my-select', {
    template: '<select options="options"></select>',
    props: ['options']
})
```
Then on my page use:
```html
<my-select options="[{text: 'Cats', value: 'cats'}]"></my-select>
```

More generally, is there some way to pass object/arrays to a custom component directly from the view?

**Comment by yyx990803** [comment]
try `options="{{ [{text: 'Cats', value: 'cats'}] }}"`

**Comment by gmhenderson** [comment]
Perfect, thank you.

**Comment by mattbit** [comment]
I ran into the same problem and the `{{ }}` trick doesn't solve when using version 1.0.0. I managed to get it working with `:options="[{text: 'Cats'}]"`.
Is this the right way to do it?

**Comment by animabear** [comment]
The same as @mattbit when use vue1.0.8

**Comment by simplesmiler** [comment]
@mattbit @animabear curly braces are not supported for props since 1.0.0.
Thus `:options="[{text: 'Cats'}]"` is the idiomatic way to do this.

**Comment by animabear** [comment]
@simplesmiler  I see, thanks

change log:  [https://github.com/vuejs/vue/releases](https://github.com/vuejs/vue/releases)

**Comment by vedmant** [comment]
You can also use single quotes for attribute, :items='[{text: "Cats"}]' if you generate json on backend, it uses double quotes by default.

**Comment by HelgeSverre** [comment]
In case anyone finds this issue from google searching for the same thing in Vue 2.0 and figures out that interpolation in props has been removed like I did, here is the proper way to do this is to simply do ```<custom-element v-bind:whatever="['test','test2']"></custom-element>``` or ```<custom-element :whatever="['test','test2']"></custom-element>```.

**Comment by jm398964** [comment]
During case a person discover this question commencing Google probing meant for the similar obsession in Vue 2.0 as well as information away to [Pay someone to do my assignment - Customassignment.com](http://www.customassignment.com/do-my-assignment.html) exclamation in support have be detached reminiscent of achieve.

**Comment by Roeefl** [comment]
@HelgeSverre Thanks! <3

**Comment by sangzhenlin** [comment]
{{ }}what is the meaning?

**Comment by yhhwpp** [comment]
what if `options` is complex Object

**Comment by nd9600** [comment]
If you try to bind an array as variable, you might need to do
```vue
<custom-element v-bind:whatever="[...array]"></custom-element> or <custom-element :whatever="[...array]"></custom-element>
```
which uses [ES2015's spread syntax](http://babeljs.io/docs/en/learn/#default-rest-spread).

**Comment by danawesome** [comment]
Thank you @nd9600. This was just what I needed to get my errors to go away. The funny thing was, it was still handing the array into the vars without data problems, just the warning.

**Comment by MatheusRamos90** [comment]
I had the same problem... removed our friends {{ }} and baang! It worked.
