### ISSUE TITLE
route

### ISSUE THREAD

**Issue by wormen** [yyx990803/vue#1179]
hello
tell me where you can read about configuring routed  (html5history)  need a client-side implementation, rather than the server

**Comment by Mat-Moo** [comment]
http://html5doctor.com/history-api/

**Comment by wormen** [comment]
This is understandable, but I was interested in another time ... as an example
https://www.npmjs.com/package/vue-route

**Comment by Mat-Moo** [comment]
@wormen I'll assume English is not a native language for you as I'm not understanding the question correctly, sorry :(

**Comment by wormen** [comment]
@Mat-Moo in what place it is not clear?

**Comment by wormen** [comment]
that's a decision that I needed to
http://michaeljcalkins.com/2015/07/getting-started-with-vuejs-creating-routes-with-vue-router/
http://vuejs.github.io/vue-router/installation.html

**Comment by simplesmiler** [comment]
@wormen

There are people in the community who speak russian, so don't be afraid to duplicate your messages in russian. Although you should probably ask questions in [vuejs/Discussion](https://github.com/vuejs/Discussion/issues) or [vue gitter](https://gitter.im/yyx990803/vue).

---

В комьюнити есть люди, разговаривающие по-русски, там что не стесняйтесь дублировать сообщения на русском. Тем не менее, вопросы лучше размещать в [vuejs/Discussion](https://github.com/vuejs/Discussion/issues) или [vue gitter](https://gitter.im/yyx990803/vue).

**Comment by yyx990803** [comment]
@simplesmiler :+1:  thanks :)
