### ISSUE TITLE
Local scope Vue inside component?

### ISSUE THREAD

**Issue by brycehanscomb** [yyx990803/vue#1180]
If I have a Component that transcludes inner content (using `<content></content>`), how can I hook that inner content up to a Vue instance?

In [this example fiddle](http://jsfiddle.net/4uv19djo/6/), I would expect the prop `testModalVue.$data.a` to be visible to the HTML, but it appears not to show.

Note that if you then type into the `<input>` which is bound to `a`, it then updates the VM, but I get the feeling that it's not bound to `testModalVue`, but `containerVue`.

How can I make this work?

**Comment by yyx990803** [comment]
Inserted content follow [component scope rules](http://vuejs.org/guide/best-practices.html#Component_Scope).

It seems you are looking for [`inline-template`](http://vuejs.org/guide/components.html#Inline_Template).

**Comment by brycehanscomb** [comment]
Hi Evan, I've looked into this and I'm still getting some weird behaviour:

[Fiddle #1](http://jsfiddle.net/fcL11akr/2/) shows what looks like `{{ a }}` being correctly compiled in child's scope without needing to use `inline-template`. Note however that the binding doesn't update if you type into the `<input>` box.

[Fiddle #2](http://jsfiddle.net/hwy8qLcc/1/) shows what happens when I put `inline-template` on the `<modal-window>` component--it no longer compiles the component, and the binding still doesn't update if you type into the `<input>` box.

I'm not sure what to make of this.

**Comment by yyx990803** [comment]
Ah, sorry, I didn't look at your original fiddle careful enough - `inline-template` is not related here. Rather, you should not be manually mounting a Vue instance inside another. Just use one top-level instance: http://jsfiddle.net/yyx990803/fcL11akr/3/

**Comment by brycehanscomb** [comment]
Ok, thanks for your help!
