### ISSUE TITLE
v-repeat 对自定义组件无效

### ISSUE THREAD

**Issue by xingrz** [yyx990803/vue#1184]
有这么一段代码：

```xml
<row-item v-repeat="row : rows" source="{{row}}" />
```

在 `row-item` 里并不能得到 `source` 属性。

然而改成这样之后就可以：

```xml
<template v-repeat="row : rows">
  <row-item source="{{row}}" />
</template>
```

**Comment by yyx990803** [comment]
直接 `<row-item v-repeat="source in rows">` 就可以。

**Comment by xingrz** [comment]
好，多谢

**Comment by xingrz** [comment]
@yyx990803 另外想请教一个问题，如何绑定比如说 textarea 的 selectionStart / selecitonEnd 这种 property（而不是 attribute）呢？

**Comment by yyx990803** [comment]
可以自己写一个 `v-prop` 指令，很简单的

**Comment by xingrz** [comment]
好，我尝试下，谢谢
