### ISSUE TITLE
VUE and managing check box values

### ISSUE THREAD

**Issue by dmarko484** [yyx990803/vue#1188]
Checkbox status is  nterpreted by VUE in model using true / false values. But this usualy doesnt reflect the model values from real database storage. Typical HTML tag definition looks like this: 
<input type='checkbox' value='1' />

'On' value is '1' and 'Off' value is ''.  VUE should have the way how to reflect this for model value. True / false values as used now are not easy to fit with database. Following my tag example above I would expect that clicking check box sets model value to '1' and unsetting value sets model to ''. This should also follow situation when we have several checkboxes bound to one model for multivalue selection.

**Comment by yyx990803** [comment]
This is already implemented and will be shipped in next release.

**Comment by dmarko484** [comment]
Just checked 0.12.11 release but can't see any change in this area there. How it is meant to work now?

**Comment by yyx990803** [comment]
@dmarko484 my bad, I overlooked the PR when writing the release note...

**Comment by dmarko484** [comment]
Do you suppose to add this to release notes for 0.12.11?

**Comment by yyx990803** [comment]
@dmarko484 there's actually some minor issues regarding this feature, so I'll officially include it in a patch release..

**Comment by dmarko484** [comment]
Thanks for your GREAT effort! And greetings from Czech republlic ...

2015-08-26 10:39 GMT+02:00 Evan You <notifications@github.com>:

**Comment by yyx990803** [comment]
Shipped in 0.12.12.

**Comment by dmarko484** [comment]
I how it is supposed to work? I thought that when I have e.g. 
<input type'checkbox' v-model='finished' value='1'> 
so clicking on this checkbox willl sets 'finished' model to '1' instead of true ...

**Comment by yyx990803** [comment]
https://github.com/yyx990803/vue/releases/tag/0.12.12
