### ISSUE TITLE
数组超过1000很卡，是我用法不对吗

### ISSUE THREAD

**Issue by 5dao** [yyx990803/vue#1190]
更换数组

listVue.$data.items=newArray

newArray,有1000一个，浏览器卡下，

**Comment by pandada8** [comment]
如果新旧内容有部分重复的话可以考虑加上 $index

**Comment by 5dao** [comment]
没有旧内容，空的  []
新数据异步获取的，

**Comment by yyx990803** [comment]
有多卡，你是什么用例需要一次这么多数据？

**Comment by 5dao** [comment]
你好，firefox，就是一个表格，ajax获取的json数组，1000行不到，然后更新listVue.$data.items=newArray，，，很卡的，有那么一阵浏览器都不能动，

**Comment by zzz6519003** [comment]
xiaoyou上次podcast里说的animation的钩子什么的  是指的是啥哇

**Comment by 5dao** [comment]
@zzz6519003 什么？

**Comment by yyx990803** [comment]
你的表格是不是还有很多列？行 * 列总共有多少？

现在 `v-repeat` 对于超大表格的初始渲染确实会比较慢，你可以考虑:

1. 对用户来说显示全部 1000 行是否有必要？可以用过滤器做分页。
2. 表格如果不需要交互，只是单纯的显示，可以写一个自定义指令做手动渲染，效率完全由自己控制。

将来的版本会针对 `v-repeat` 做特别的优化。
