### ISSUE TITLE
how to pass params in dynamic component?

### ISSUE THREAD

**Issue by arccode** [yyx990803/vue#1193]
I hava a dynamic component, for example,  
var mainWrapper = new Vue({
          el: '#main_wrapper',
          components: {
            dashboard: Dashboard,
            wheels: Wheels,
            wheel: Wheel
          }

how to  pass param to dashboard or others?

**Comment by yyx990803** [comment]
1. Please post questions to https://github.com/vuejs/Discussion/issues, not here;
2. Please read the docs before opening questions.
