### ISSUE TITLE
bug templating

### ISSUE THREAD

**Issue by wormen** [yyx990803/vue#1195]
there is a code, which clones the array element

```
var self = this, item, arr = [];
for(var i in self.items){
    arr.push(self.items[i]);
    if( i == idx){
        item = arr.slice(idx, idx+1);
        arr.push( item.name ? item : item[0] );
    }
}
self.items = arr;
```

the code works correctly, but the template glues source element and copied

**Comment by yyx990803** [comment]
Please provide a reproduction. You code doesn't show the problem.

**Comment by wormen** [comment]
@yyx990803 screenshot submission along with an array enough?

**Comment by wormen** [comment]
correctly  https://yadi.sk/i/9cvQRuhvichtG
bag https://yadi.sk/i/7FRywEfsichta

**Comment by yyx990803** [comment]
No, not enough. What I need is **actual code that reproduces the bug**, like [this](https://github.com/yyx990803/vue/issues/1117)

I can't fix bugs just by looking at screenshots.

**Comment by wormen** [comment]
@yyx990803 I write a personal message to the gitter

**Comment by wormen** [comment]
@yyx990803 update the information in gitter

**Comment by wormen** [comment]
@yyx990803 http://jsfiddle.net/nkovacs/k2n2vpkL/

**Comment by wormen** [comment]
sorry, I did not save
http://jsfiddle.net/k2n2vpkL/1/

**Comment by yyx990803** [comment]
You should not have duplicate objects in your array. Push a "clone" of it instead. Your code is also quite messy.

Fixed: http://jsfiddle.net/yyx990803/k2n2vpkL/3/
