### ISSUE TITLE
Can't use options without v-model

### ISSUE THREAD

**Issue by JosephSilber** [yyx990803/vue#1196]
Sometimes, I'm not actually interested in two-way binding on a `select`, and all I care about is listening to the `change` event. However, without `v-model`, `options` doesn't work.

So what I have to do instead is use `v-model` and set up a watcher, which works, but is more than I should need<sup>1</sup>.

I'm not sure this can even be "fixed", since `options` is a directive argument of `v-model`.

---

<sup>1</sup> I could also manually create the `option`s with `v-repeat`, but that's being discouraged by the framework.

**Comment by yyx990803** [comment]
Actually, if you are not using `v-model`, it's fine to use `v-repeat` for options. The warning heuristics is a bit aggressive, but you can ignore it.

I'm also considering improving the `options` param in 1.0, since it's not really intuitive.

**Comment by dgerber** [comment]
Also, it's somewhat annoying that the warnings appear even when repeating `option` in a `datalist`.

**Comment by yyx990803** [comment]
@dgerber that's gonna be gone :) It should only warn if it's used inside select with `v-model`.

**Comment by yyx990803** [comment]
Ok, in 1.0 with `v-for`, `options` is no longer necessary! You can just do this:

``` html
<select v-model="selected">
  <option v-for="obj in list" bind-value="obj">{{obj.text}}</option>
</select>
```

Here `bind-value` will allow you to bind `selected` to `obj` even if it's an object.

**Comment by yyx990803** [comment]
See https://github.com/yyx990803/vue/issues/1229
