### ISSUE TITLE
If object is missing a child object Vue throws error in the console in component.

### ISSUE THREAD

**Issue by kzima** [yyx990803/vue#1197]
I have two issues in a common scenario, where data is comming from the server in ajax call:
1. if I refer to an array element in the template I get this error in console
[Vue warn]: Error when evaluating expression "todo.columns[0].display". 
2. if object is missing a child element (not predefined), then vuejs also throws an error:
Cannot read property 'display' of undefined at Vue.eval (eval at <anonymous> 

JS fiddle demo: 
https://jsfiddle.net/kzima/20yw13kq/5/

What is the best aproach for this scenario?

Thanks,
Kris

**Comment by yyx990803** [comment]
Predefine the things you need? http://vuejs.org/guide/best-practices.html#Data_Initialization
Also, you can put things that depend on certain data inside a `v-if` block.

**Comment by kzima** [comment]
Hi Evan,

Thanks for quick reply. I followed your advise but I still get errors in the console. 
I have changed to <code>v-if</code> and I push items to the <code>todo.columns</code> array using <code>$set</code> method, but it makes no difference. Am I missing something?

updated js fiddle:
https://jsfiddle.net/kzima/Lw01eg1p/

Thanks,
Kris

**Comment by yyx990803** [comment]
This is what I meant: https://jsfiddle.net/yyx990803/Lw01eg1p/1/

**Comment by kzima** [comment]
That worked great, thanks.

However, I am getting a really weird behaviour when I rename "todo" to "todoTable". I am then getting errors in the console. Funny enough if I remove the span with <code>v-repeat="column: todo.columns"</code> from the template, the error is gone.

https://jsfiddle.net/kzima/Lw01eg1p/2/
