### ISSUE TITLE
Additional planned changes

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#1198]
- `$data` can no longer be used as a prop. Replacing the component's default data is not a good pattern.

- Deprecate `inherit: true`. This option was originally used for internal mechanisms, but in 1.0 this is no longer needed internally. As an API, when over-used it can lead to subtle bugs and make the state of components harder to understand.

- ~~Deprecate `v-el`. Prefer using querySelector. In 1.0.0 there may be a new method for querying the DOM, because 1. sugar 2. standard interface for normal and fragment instances.~~ `v-el` will be renamed to `el`.

**Comment by azamat-sharapov** [comment]
Looking forward for `v-for`!
:+1: for other breaking changes.

**Comment by davidkhess** [comment]
I like them all except worried about killing off `inherit: true`. I agree it is not be a good pattern in general but sometimes it is useful and the easiest way to handle complex interactions/data passing in tightly coupled components.

**Comment by yyx990803** [comment]
@davidkhess I've yet to come across a situation where `inherit: true` is absolutely needed to make it work. Sure it can make some things "easy", but not necessarily in a good way.

**Comment by davidkhess** [comment]
I see it like the convenience of the JavaScript closure. It has visibility to everything in every parent scope when you create it but you typically only capture a couple of vars in practice. 

Overuse of closures would be bad style. But they certainly come in handy in some patterns where code is tightly coupled.

**Comment by yyx990803** [comment]
@davidkhess I know it's like lexical scoping, however the difference is that in JavaScript all your functions need to be written together to get lexical scoping, so it's fairly clear to understand when you look at the file. But components are by definition a unit of isolation, and often separated in different files; how they are used together is defined in the template of the parent component. When you look at a child component with `inherit:true`, you can't easily reason about the context it is being used in. To make  `inherit: true` components maintainable, we have to rely on self discipline - i.e. only use it when you need to - but that's exactly what I want to move away from in 1.0. I want the system to be maintainable-by-default.

**Comment by davidkhess** [comment]
When I use `inherit: true` (which is rarely), I only do it when I have components declared within another component in the same `.js` file. That way, I can visually see the nesting and the implications of it – much like you can with a javascript closure.

I'm mainly playing devil's advocate – I could live without it. It is just that over the years, I've been burned a couple of times by decisions to overly restrict a system behavior and to be later forced to go back and open it back up.

I'm personally comfortable with your position as I've not got enough Vue-years under my belt yet to take a strong stance against it.

**Comment by Mat-Moo** [comment]
I have a base component (widget) that I'm extending with multiple variations of it (text widget, image widget etc) and use component is to select the correct widget. How do I pass props for all the different widgets that would need different props? This is currently the only place I use extend, and worries me.

**Comment by davidkhess** [comment]
I've found that using Vue.extend and mixins are usually a better way to do "subclassing" rather than nested components.

**Comment by TerenceZ** [comment]
Would removing `v-el` and using `querySelector` lead to get a wrong element? For example, would the query result is `.a.b`? Because I am using many `v-el` in my components' mixins to apply some behaviors...

```html
<template id="comp">
<content></content>
<div class="a"></div>
</template>

<comp><div class="a b"></div></comp>
```

**Comment by yyx990803** [comment]
@TerenceZ I'm not sure if I understood your original usage. And how would the query API solve that for you?

**Comment by TerenceZ** [comment]
@yyx990803 I'm sorry I haven't describe the issue clearly. The problem is how to select the element declared in the template, not including the transcluded elements. For example,

```html
<template id="comp">
<content></content>
<div class="a"></div>
</template>

<comp><div class="a b"></div></comp>
```

Here I want to select the element `.a`, not the element `.a.b`. Using `v-el` I can be easy the locate the `.a`, but if using `querySelector`, it will get the result `.a.b`. 

The reason for ignoring that comment is that I assume this problem can be resolved the new query API provided by `vue` .
