### ISSUE TITLE
Deprecate `v-repeat` in favor of `v-for`

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#1200]
I am working on a new version of `v-repeat`, which is significantly more performant than the current version, but introduces a few breaking differences in terms of scoping. In order to keep backwards compatibility in the 1.0 migration, this new version will be introduced as `v-for` so that the original `v-repeat` can be left intact.

Current status: all tests passed. You can test `v-for` in the current 1.0.0-alpha branch.

#### Required alias

Alias is required when using `v-for`, and the `item in items` syntax is preferred. It reads more naturally:

``` html
<li v-for="item in items"></li>
```

This also means the `$value` meta property will no longer be used. `$index` and `$key` are still available. You can also still refer to the parent scope index in nested loops as `$parent.$index`.

#### No more anonymous child VMs

Previously, `v-repeat` creates an actual child VM instance with `inherit: true` for every repeated block. This is no longer the case with `v-for`: each repeated block in `v-for` is now a real partially compiled fragment, with a lightweight intermediate "scope". This greatly reduces the overhead and as a result you should see significant performance improvement for both initial rendering (up to 100% for non-component loops)  and re-rendering with `track-by` (up to 50%, as tested in dbmonster).

This also means:

1. Using an extra `<template>` repeat no longer creates the overhead of a child instance.
2. `v-ref` would not work on `v-for` if the repeated block is not a component, because there are no longer anonymous child instances created in that case.

#### Component Scoping

Now this is the part that is the most different. Previously when you use a component with `v-repeat`, you get somewhat weird scoping:

``` html
<!-- can't use $index here -->
<comp v-repeat="item in list"></comp>
```

In the above example, `item` and `$index` are automatically available inside the component, but not in the parent template. If you do want to use `$index` in the parent template, you have to create a `<template>` to wrap the repeat. In addition, this requires the component implementation to be aware that it is `v-repeat` specific, because the external data is not received via the standard `props` interface.

With `v-for`, you get the expected scoping:

``` html
<comp v-for="item in list" id="{{$index}}" data="{{item}}"></comp>
```

And you need to explicitly pass external data into the component as `props`. This makes your component implementation no longer `v-repeat` specific and less magical.

**Comment by sdebacker** [comment]
Nice ! How can we install this version via npm ?

**Comment by dominiquedutra** [comment]
@sdebacker This is a proposal for 1.0.
@yyx990803 is proposing some changes and people will provide feedback.

**Comment by sdebacker** [comment]
Yes but these proposed changes are already pushed to 1.0.0-alpha branch.

**Comment by yyx990803** [comment]
@sdebacker You can install a branch as `npm install yyx990803/vue#1.0.0-alpha`. Note the branch is unstable, so use at your own risk.

**Comment by sdebacker** [comment]
Thanks but it returns no matches found: yyx990803/vue#1.0.0-alpha

**Comment by yyx990803** [comment]
@sdebacker what version of npm are you using?

**Comment by sdebacker** [comment]
I just upgrade npm to 2.12.1 via homebrew, perhaps I need 2.14 ?

**Comment by yyx990803** [comment]
weird... I just tried it and it works... maybe a typo? ;)

**Comment by thelinuxlich** [comment]
+1 great proposal

**Comment by kazupon** [comment]
+1

**Comment by davidkhess** [comment]
+1

**Comment by Pandahisham** [comment]
+1

**Comment by pespantelis** [comment]
:+1:

**Comment by OEvgeny** [comment]
:+1:

**Comment by kayyyy** [comment]
+1

**Comment by azamat-sharapov** [comment]
> Component Scoping

So, this: `<comp v-for="item in list" id="{{$index}}" data="{{item}}"></comp>` is still compiled on parent's scope, except `$index`, `$key` and `item` being on `v-for`'s scope?

**Comment by yyx990803** [comment]
Implemented in alpha branch.

**Comment by sdebacker** [comment]
@yyx990803 I switched from zsh to bash and I can now run ```npm install yyx990803/vue#1.0.0-alpha```

**Comment by mattymil** [comment]
So if I am interpreting this correctly, deprecation of v-repeat in lieu of the v-for will create true partials as opposed to vms. Within the standard use case, will we experience any loss of functionality when passing this object back to event handlers?

**Comment by yyx990803** [comment]
@mattymil I've yet to see a use case where the anonymous child vm is necessary. In most cases you pass the `item` of `item in items` into an event handler, which is the data object from the repeated Array.

**Comment by adampatarino** [comment]
So in practice, with dynamic components, when passing data to children we currently do something like this:

```HTML
<component 
    is="{{currentView}}"
    child-prop="{{parentData}}"
    >
</component>
```

And with this new spec it would more like this?

```HTML
<component 
    bind-is="currentView"
    bind-child-prop="parentData"
    >
</component>
```

**Comment by mattymil** [comment]
ok interesting. Thanks

**Comment by jonathanpmartins** [comment]
+1
Testing alpha 6 now! Lot of work on my views...

**Comment by jonathanpmartins** [comment]
+1

**Comment by furybean** [comment]
So by the doc in rc.vuejs.org, this syntax is not support in 1.0.0?
```HTML
<li v-for="items"></li>
```

**Comment by simplesmiler** [comment]
@furybean it's not supported, you have to use `v-for="item in items"`.

**Comment by furybean** [comment]
@simplesmiler Thanks.

**Comment by blocka** [comment]
A little late to the party but...
Not sure if this was a "feature" of `v-repeat` but using the alias syntax allowed you to store data on the VM, such as application (component) state. For example, if you wanted to turn on editing mode for an item in your list you could do: `$data.$('editing',true)` and you wouldn't have to dilute your object.

Since `v-for` is no longer using a VM, I'm assuming this is no longer possible. Is there a clean workaround? Or maybe I'm not understanding the change (I have actually not moved over to v1.x yet, so I haven't had a chance to experiment, but I am looking at a current code base and trying to evaluate the pain involved).

**Comment by caoliangsong** [comment]
+1
