### ISSUE TITLE
Possible to update template?

### ISSUE THREAD

**Issue by elliotlings** [yyx990803/vue#1202]
Is it possible to update the template after super has been called?

I need to do some logic to work out the template, but I can't use `this` before super has been called in ES6.

Won't work:
```js
export default class BaseWidget extends Vue {
    constructor(options) {

        // Work out template but need to use 'this'

        super(options);
```

Ideal:
```js
export default class BaseWidget extends Vue {
    constructor(options) {
        super(options);

        this.template = this.getTemplate();
```

**Comment by yyx990803** [comment]
You can't directly use ES6 class to subclass Vue - you should use `Vue.extend`.
If you really want ES6 classes, take a look at this: https://github.com/vuejs/vue-class-component

**Comment by elliotlings** [comment]
I think I will just have to do something like this for now:

```js
import BaseWidget from "./BaseWidget";

export default class GridItem extends BaseWidget {
    constructor(options) {
        options.template = $('#template-widget-GridItem').html();
        super(options);
    }
}
```
