### ISSUE TITLE
发现一个稳定复现的报错

### ISSUE THREAD

**Issue by whwnow** [yyx990803/vue#1205]
在使用v-repeat和track-by的时候发现个问题

报错内容为：
Uncaught TypeError: Cannot read property '__v_trans' of null

http://jsfiddle.net/whwnow/ta48pj08/2/

复现步骤为点击两次pageDown后，点击一次pageInit

顺便搭车，repeat使用了item in items语法，组件代码里能不能不用 this.item.xxx，同步成this.xxx~

**Comment by yyx990803** [comment]
你自己的代码有问题。

``` js
this.items = this.items.concat(this.items, data2);
```

这里你等于把 `this.items` 跟自己和 data2 都拼接了，所以 `this.items` 里的内容会重复。`v-repeat` 不允许出现重复对象（这个我会加个警告进去）。

改成这个就好了：

``` js
this.items = data1.concat(data2)
```

**Comment by whwnow** [comment]
明白了，原来是这个原因。多谢解答！

**Comment by whwnow** [comment]
不好意思，太蠢了。。。居然没发现链接了两个items的值。消消气……又让你感叹世人的愚蠢了……

**Comment by tminglei** [comment]
@whwnow  ^_^

**Comment by yyx990803** [comment]
没事，哈哈
