### ISSUE TITLE
partial template

### ISSUE THREAD

**Issue by wormen** [yyx990803/vue#1207]
tell me how to connect to the partial template?
eg

```
Vue.partial('layer-transition-settings', '#layer-transition-settings');
```

```
<script type="text/x-template" id="layer-transition-settings">
    layer-transition-settings block
</script>
```

I have not found a description of how the act is done correctly

**Comment by azamat-sharapov** [comment]
тут вопросы не задают. Вам в [сюда](https://github.com/vuejs-ru/Discussion) или vuejs/Discussion.

**Comment by wormen** [comment]
@azamat-sharapov а мне кажется я этот момент описал там где нужно ... так как в доках по этому поводу ничего нету

**Comment by azamat-sharapov** [comment]
@wormen во первых у вас плохо получается с английским. Во вторых у вас вопрос - не bug report и не feature request, читайте [правила - что куда писать](https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines), тем более во время создания issue гитхаб вам показывает ссылку на эти правила, выделяя её: 
![image](https://cloud.githubusercontent.com/assets/3023661/9462283/f05ec37c-4b3e-11e5-8ff2-4e6c4d86e606.png)

Кроме того, проект открытыми исходниками, даже доки: https://github.com/vuejs/vuejs.org
Так что если вы уверены, что в доках чего то не хватает или какая то ошибка, вы можете это сами исправить или issue там открыть.

**Comment by azamat-sharapov** [comment]
А насчет вашего вопроса, если вы **доки** внимательнее смотрели, то там не говориться ничего о селекторах (selector), `Vue.partial` берет только `string` как второй аргумент: http://vuejs.org/api/global-api.html#Vue-partial\(_id\,_\[partial\]_\)

**Comment by wormen** [comment]
это я видел, в том и печаль
