### ISSUE TITLE
macbook esc key can't fire dom event in chrome

### ISSUE THREAD

**Issue by ke-pan** [yyx990803/vue#1208]
My env is Yosemite, Chrome Version 44.0.2403.130, and MacBook Pro.
I am not sure that's Vue's problem. I try in Safari, it is ok. I try with other keyboard, it is good also.

**Comment by yyx990803** [comment]
Please provide a reproduction. I have exactly the same environment but it's working for me.

**Comment by ke-pan** [comment]
It's my fault. A chrome extension block the esc event. I spent a whole afternoon to 'debug' it:( Sorry for wasting your time.
