### ISSUE TITLE
Pluralize bug

### ISSUE THREAD

**Issue by natocTo** [yyx990803/vue#1209]
Hello, 

 I am not sure if I am doing something wrong but I have bug when use pluralize filter.

[https://jsfiddle.net/qex8fxpt/1/](https://jsfiddle.net/qex8fxpt/1/)

**Comment by yyx990803** [comment]
The pluralize filter follows simple rules and cannot handle irregular special cases (11th, 12th & 13th). You can write a custom filter for this type of formatting.
