### ISSUE TITLE
Checkbox not checked on page load after updating to 0.12.11

### ISSUE THREAD

**Issue by Ben52** [yyx990803/vue#1210]
I have a row of checkboxes bound to filters. When a checkbox is checked, it sets that attribute to true in the url's hash, and makes an ajax call which retrieved data with the filter applied. As well on page load, the hash is checked for filters and the data is fetched accordingly. The checkboxes are bound with v-model and if set to true in the url, their value is set to true. This worked until I updated to 0.12.11, now the filters work, but the checkboxes are not remaining checked.

**Comment by Ben52** [comment]
I figured it out. When it was grabbing the value from the url hash, the hash had a value of true, and that didn't get cast to a boolean, so the checkbox did not get checked. After casting it to a boolean it works as it should. I'm not sure why this only broke in 0.12.11.

**Comment by yyx990803** [comment]
确实是个 bug，0.12.12 已经修正。
