### ISSUE TITLE
使用svg时导致的内存泄露问题

### ISSUE THREAD

**Issue by zuibunan** [yyx990803/vue#1216]
一个实时数据监控的界面，table布局，列出一些人的数据，某些属性是用svg展示出来的
使用chrome的开发者工具每隔一段时间截取快照，发现内存递增，其中string对象数量在不断增加
这些strings基本都是svg字符串

当我使用整体替换字符串的方式更新界面时，内存占用一直比较稳定，使用vue的话内存占用就会不断增加

**Comment by yyx990803** [comment]
请给重现。

**Comment by zuibunan** [comment]
和svg的构造有关，这个demo里的svg会造成内存递增，用一个更简单的svg就没问题了
http://jsbin.com/bobovefiqi/edit?html,js,output

**Comment by yyx990803** [comment]
不要用 svg 字符串赋值啊... Vue 可以直接绑定 svg 的...

**Comment by zuibunan** [comment]
直接绑定怎么搞？

这样吗？
http://jsfiddle.net/yyx990803/bbt0f3nz/light/

我现在是在一个filter里用d3.js把传入的数据转换成svg字符串的，如果像上例那样，就需要自己构造svg了，有些麻烦

**Comment by yyx990803** [comment]
你可以写一个自定义指令在 Vue 里面直接用 D3。你这样生成字符串再替换效率有点低...

**Comment by zuibunan** [comment]
已改成自定义指令，无内存递增的问题了，多谢！

不过，直接用svg字符串替换时内存递增，这个是我代码的问题还是vue的bug...
http://jsbin.com/bobovefiqi/edit?html,js,output

**Comment by yyx990803** [comment]
可能是 `v-html` 指令的问题。我有空看下。
