### ISSUE TITLE
vue v0.12.12

### ISSUE THREAD

**Issue by wormen** [yyx990803/vue#1217]
https://yadi.sk/i/CQ8bXcHIifrKs

**Comment by yyx990803** [comment]
Please be more specific - did this happen after you upgrade? What version were you using previously? What does your code look like? You can't expect people to help you just by posting a screenshot.

**Comment by wormen** [comment]
@yyx990803 previous version was 0.12.10, just updated, and there was an error

**Comment by yyx990803** [comment]
All the vue-router tests are working properly for 0.12.12, so I need a real demo to see what's wrong.

**Comment by wormen** [comment]
very strange here it works perfectly
http://jsfiddle.net/xyu276sa/10/

except for messages in the console

```
[vue-router] already installed.
[vue-router] v-link can only be used inside a router-enabled app.
[vue-router] <router-view> can only be used inside a router-enabled app.
```

but in the project, I have an error at this point
```
var $indexCtrl = new Vue
```

**Comment by wormen** [comment]
he looked a little bit, because of what a mistake ... as it turned out, it is certainly not because it can not find the element ID

error gave the router, causing all falls

**Comment by wormen** [comment]
error occurs after the announcement
`Vue.use(VueRouter);`

**Comment by wormen** [comment]
after I unplugged the router, the error is still there when the announcement
`new Vue`

**Comment by wormen** [comment]
Could this be due to the fact that I used nodejs?
because in php it had no such problems

**Comment by yyx990803** [comment]
If you are using the router you should start the app with the router. Closing until you can provide a repro with the actual error.

**Comment by wormen** [comment]
@yyx990803 I cited the example above, at the moment there is only the code that is provided in the example

**Comment by wormen** [comment]
it turns out there are two errors, one of **vue**, and the second from **vue-router**
and two identical error

**Comment by yyx990803** [comment]
You example isn't even using the router correctly, nor does it show the error you originally described.

**Comment by wormen** [comment]
@yyx990803 router code was taken from your example ... minor changes to it

**Comment by yyx990803** [comment]
You are mounting two Vue instances onto the same element `#app`. Your `$indexControl` should just be `App`.

**Comment by wormen** [comment]
even if I hook after the other selectors, or disable `$indexControl` the error still persists

**Comment by yyx990803** [comment]
Then it means the example is irrelevant to your error - and you need to provide one that actually shows the error.

**Comment by wormen** [comment]
the above link, I showed the code that there are now in fact used

**Comment by yyx990803** [comment]
But it's not showing the error in your screenshot. How many times do I have to explain this? I can't help you if the error only happens for you, because it means there's something wrong with your setup which is not shown.
