### ISSUE TITLE
feature request: debugging reactions

### ISSUE THREAD

**Issue by mark-hahn** [yyx990803/vue#1218]
I am in the middle of my second website and I love Vue.  It has made me much more productive and organized.

However, I spend a significant amount of my time debugging inside of Vue code.  When I have a variable not working (because of my problem) it shows up as an exception in the Vue code.  I set breakpoints in the Vue code that I find as I step through it but even then it is hard to tell what is going on because of the getter-setters.  

I would like to propose some debugging tools for Vue.  I will implement them after the end of my current project.   I would need help though since I am not an expert in Vue code.  Suggesting what to hook in the code would be a good example of the help.

The debugging aids would fall into two categories.  ...

- Observing the usage of Vue reactivity.  I think of Vue's operation much like RxFs, i.e. observables and subscribers.  The data and props are observables and anywhere the data/props are used, declaratives, instance methods etc., are the subscribers.  These reactions are automatic in Vue which makes for ease-of-use but the *magic* makes debugging harder.
  - Traces could dump reactions to either the console log or a log file.  There would be one line per automatic variable reaction (observation).
  - Breakpoints could be set for when a reaction happens.  A reaction could have some kind of identifier.  The id could come from reading the log.  Or a data key-path could be watched for usage.

Does anyone have any thoughts on this?  Would anyone other than me find it useful?

**Comment by yyx990803** [comment]
I do have something like this in mind but haven't got time, and it'd be great if someone wants to work on it. But as you said, it relies on a lot of Vue internals. Maybe the first step is to start with the UX of the tool - i.e. how do we present the reactivity to the users? How about the component hierarchy? What would the UI be like? At this stage, I think it'd be wise to start with things that are not implementation-bound.

**Comment by mark-hahn** [comment]
I forgot to document the second category.

- Showing observable values instead of getter/setters.  The chrome extension is very useful but it only works when looking at the DOM.  This means it can only observe declaratives.  I want a method of looking at any observable with all values resolved.  This needs to work even when stepping through code, or at least when a breakpoint is hit.  This could be something that runs in the console.

**Comment by mark-hahn** [comment]
> What would the UI be like? 

Yes, once we have this the implementation would be much easier.

Here is a beginning suggestion for the UI design:  The UI could run in a second web page.  Being browser based would also mean it could run in the Atom editor and Facebook's nuclide.  Later it could even be source-based linking with the Vue user's source code like a real IDE.  This last part would obviously be long terms.

**Comment by yyx990803** [comment]
@mark-hahn but then it needs some sort of communication bridge injected into the app page? How about just injecting the UI itself into the current page?

**Comment by mark-hahn** [comment]
Note:  I am having a lot of ideas flowing at the moment and many are bad ideas.  This is a good way to start designing.

> it needs some sort of communication bridge injected into the app page?

Idea: Node has a bridge (debug API) for developers to hook up debuggers.  So does chromium.  The APIs are very low level.  For vue it could be at least querying key-paths to find observables and then acting on them. 

In the beginning a simple gdb-like command-line repl interface could be used to talk to the debug API.  So the API would be hard to do but the first UI would be very easy since it would just map user interaction to api calls.

Later higher-level UIs like the one you are probably thinking of could be implemented on the API.  So there would be only one pull-request to Vue for this API and then everything else could be decoupled and not affect the Vue core.

> How about just injecting the UI itself into the current page?

Yes that could be done, even with the API idea.  The API could be called from anywhere, even from injected code in the current page.

If the API looks hard then I'll drop the idea quickly.  But I really feel that an API is a proven method for using debuggers.

Of course if you disagree on the API idea I will drop it.  You have final say on any ideas.  I wouldn't do any work unless you 100% agree with it.

**Comment by yyx990803** [comment]
Let's close this for now and move it to vuejs/Discussion when we have time to work on it.

The Node/Chromium debug API seems a bit too lower level for what I had in mind. Note that you can do `vm.$log()`, which gives you clean state instead of getter/setters, even when paused at a break point.

What I think would be more generally useful is something along the lines of Ember Inspector: https://chrome.google.com/webstore/detail/ember-inspector/bmdblncegkenkacieihfhpjfppoconhi?hl=en

**Comment by mark-hahn** [comment]
That amber example looks quite nice.
