### ISSUE TITLE
Loose element attributes when directive binds

### ISSUE THREAD

**Issue by elliotlings** [yyx990803/vue#1220]
I may be overlooking something here.

```js
Vue.directive('editable', {
    bind: function() {

        var self    = this,
            el      = self.el;

        this.model = el.getAttribute(Vue.config.prefix + 'model');

        console.log(this.model);

        // Make the content editable
        $(el).attr('contenteditable', true);
    },
});
```

```html
<div v-model="test" v-editable>This content should be editable!</div>
```

While this adds the attribute contenteditable="true" to the element, ```this.model``` is null. Having looked through other directives out there (which do the same thing), it should pick up v-model?

Thanks

**Comment by yyx990803** [comment]
Directives have compilation priorities. `v-mode` has 800: https://github.com/yyx990803/vue/blob/dev/src/directives/model/index.js#L12

Default priority is 0, so your custom directive is bound after `v-model`, which already removed itself. To be able to get v-model value, use a priority higher than 800.

**Comment by elliotlings** [comment]
Thanks, that sorted it :)
