### ISSUE TITLE
should cache of computed prop be default to false or configurable?

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#1222]
I find that the default of cache for computed prop is true, however, in my case, most of computed props are simple enough are in most of time they are not changed. So it means caching them is wasting memory. Should its default configurable in `config` or default to false?

**Comment by yyx990803** [comment]
That makes sense, although the difference in terms of memory usage is pretty small. 10k computed properties results in less than 2MB of memory, so in most cases you probably don't need to worry about it...

**Comment by young-steveo** [comment]
I agree with setting the default to `false`, especially since most computed properties are simple.  This would allow the developer to fine-tune an application by applying caching where it is needed rather than removing caching everywhere that it is not.

**Comment by yyx990803** [comment]
I personally debated a bit when introducing the change, and yeah it seems "trade memory for performance only when you really have to" is the better default here. Cache will default to false in 1.0.

**Comment by young-steveo** [comment]
For reference: https://github.com/yyx990803/vue/issues/1232#issuecomment-136755427

**Comment by simplesmiler** [comment]
Would this be overridable globally and/or per component? Or only per computed property?

**Comment by yyx990803** [comment]
@simplesmiler probably per property only. Global override doesn't seem like a good idea to me. In most cases, the only time you'd disable caching is when you know you want to access it as a getter AND it contains non-reactive dependencies (e.g. Date.now(), DOM sizes).
