### ISSUE TITLE
IE 11 {{ mustache }} bug

### ISSUE THREAD

**Issue by panteng** [yyx990803/vue#1223]
I had a variable name 'typeName', and I wanted to display it in the page, so I used mustache style in my html:
    ```<div> {{typeName}} </div>```

It worked fine in Chrome, but in IE 11, it didn't show the value of 'typeName', but the mustache expression itself:
![1440742281567](https://cloud.githubusercontent.com/assets/8369690/9541404/665639c2-4d9a-11e5-8489-c41b6aae6b9c.png)

I opened the console of the developer tool in IE 11. No errors. But when I looked into the dom, I found this:
![qq 20150828152259](https://cloud.githubusercontent.com/assets/8369690/9541366/060e8a74-4d9a-11e5-92cd-3786f6c04172.png)
The mustache expression is divided into two lines.
I don't know whether it is the reason that causes this issue.
Waiting for help. Thanks for reading.

ps: For now, I have to use v-text instead of mustache expression. And v-text works fine in both Chrome and IE 11.

**Comment by yyx990803** [comment]
Does this happen for every mustache tag? Can you provide a reproduction?

**Comment by panteng** [comment]
This doesn't happen for all of the mustache tags in my project in IE 11. Only a few of them work fine, while others don't. For now I cannot provide a reproduction because this is a large project and I don't know which part goes wrong. I think if I can reproduct it, I will know the reason. I just want you to know this issue and it may give you some points to take care of in the future developing of Vue.js.

I think maybe I use too many 3rd party libs in my project and some of them may conflict with vue.js. Or maybe the ftl tags? I don't know. 

Once I find the reason, I will come back to this issue.

**Comment by IntellectProductions** [comment]
I'm actually having this same problem. I'm sorry. I didn't see that there was already this issue opened!

https://github.com/yyx990803/vue/issues/1255

**Comment by yyx990803** [comment]
Closing until repro is available.

**Comment by KennyWho** [comment]
I have the same problem in IE,but not every mustache tag has this problem,I'm not sure how to provide a reproduction.I ues v-text instead of the mustache expression,but I think it's not the best way.
My vue version is 0.12.
![qq 20151026141721](https://cloud.githubusercontent.com/assets/7511329/10722624/18402122-7bed-11e5-94c3-446bffde469b.png)

**Comment by luckymore** [comment]
@KennyWho 
it‘s to be a non-standard use. :laughing:

**Comment by panteng** [comment]
@KennyWho 
Do you use Browserify to bundle all vue-related files into one file too?

**Comment by ram-reddy** [comment]
for The sake of IE 

change the <template id=xx> tag to  <script type="text/html-template" id="xx">

**Comment by soledad2410** [comment]
Thank alot @ram-reddy :D
