### ISSUE TITLE
2-way filters on 0.12.11  - filter gets applied but model doesn't get updated

### ISSUE THREAD

**Issue by aristidesfl** [yyx990803/vue#1224]
![example gif](http://zippy.gfycat.com/ShadyEarnestCassowary.gif)
http://jsfiddle.net/yyx990803/0h70puer/

**Comment by yyx990803** [comment]
The read filter only affects the input. If you want to limit the model value to two decimals, you need to still do it in the write filter: http://jsfiddle.net/yyx990803/0h70puer/1/

**Comment by JosephSilber** [comment]
The filter in that fiddle only removes non-numeric characters. It doesn't round the value.

If you want to round the value of model, do it in the filter.
