### ISSUE TITLE
The _initData extremely slow since upgrade to Vue 0.12.11 from 0.12.10

### ISSUE THREAD

**Issue by nadirabid** [yyx990803/vue#1226]
Here're some quick screen shots of the results from the Dev Tools profiling utility:

Vue 0.12.10:

<img width="1079" alt="screen shot 2015-08-29 at 4 53 47 pm" src="https://cloud.githubusercontent.com/assets/667656/9565078/3a56ca46-4e6f-11e5-8b55-053f3f2a5295.png">

Vue 0.12.11

<img width="1081" alt="screen shot 2015-08-29 at 4 54 20 pm" src="https://cloud.githubusercontent.com/assets/667656/9565079/43a80268-4e6f-11e5-8df6-719ceb259a20.png">

If I dig deeper it it seems to be while merging the data instance but I couldn't figure out what the reason for the slow down was. 

Wondering if you have any idea what might be the reason or where to start looking. I'll try to see if I can isolate the problem to try and reproduce it in a jsfiddle or something.

**Comment by yyx990803** [comment]
Are you using a component like `<comp v-repeat="items">` without an alias?

**Comment by yyx990803** [comment]
Oh, this might be because the vm is now observing `_` and `$` prefixed properties. Does your data contain a lot of these properties?

**Comment by nadirabid** [comment]
Vast majority of properties defined on `$data` or using `$add` aren't prefixed. I'm using a few properties, prefixed with `$`, that I define directly on the VM like so:

```js
this.$unwatchX = this.watch('x', this.handleX.bind(this));
```

I am however using `v-repeat` without aliases. Using an alias does have a significant performance increase.

*Vue 0.12.12 __without__ aliasing*:

<img width="1075" alt="screen shot 2015-08-29 at 5 51 09 pm" src="https://cloud.githubusercontent.com/assets/667656/9565249/9e3ba60e-4e78-11e5-9b93-e58fb30880cd.png">

*Vue 0.12.12 __with__ aliasing*:

<img width="1079" alt="screen shot 2015-08-29 at 5 50 49 pm" src="https://cloud.githubusercontent.com/assets/667656/9565250/bb9ef048-4e78-11e5-9ca3-a3de89fe1091.png">

However, this is still quite a lot slower than *Vue 0.12.10 __with__ aliasing*:

<img width="1076" alt="screen shot 2015-08-29 at 6 11 03 pm" src="https://cloud.githubusercontent.com/assets/667656/9565265/c05f1314-4e79-11e5-9b28-a59e396e499b.png">

I'll try to narrow down on what specifically could be causing the slow down.

**Comment by yyx990803** [comment]
Can you briefly describe what the `v-repeat` in question look like? Are you using a lot of `$add`?

**Comment by yyx990803** [comment]
The only commit in 0.12.11 I can imagine being related to this is https://github.com/yyx990803/vue/commit/794214a3ffca378a8cdefe3f08acea46c7f33b98

Can you try commenting out the `sync: true` lines in your local files and see if it makes a difference?

**Comment by nadirabid** [comment]
I commented out the `sync: true` lines, and its practically restored to 0.12.10 performance numbers.

*Vue 0.12.12*:

<img width="1066" alt="screen shot 2015-08-30 at 8 44 58 am" src="https://cloud.githubusercontent.com/assets/667656/9568043/7945598c-4ef3-11e5-99df-1ef01110f15f.png">

*Vue 0.12.12 __without__ https://github.com/yyx990803/vue/commit/794214a3ffca378a8cdefe3f08acea46c7f33b98*:

<img width="1065" alt="screen shot 2015-08-30 at 8 43 43 am" src="https://cloud.githubusercontent.com/assets/667656/9568039/506109ee-4ef3-11e5-98d1-072d2170f1b2.png">

Looking at the code, is this something I can toggle through config options?

In answer to your previous questions. I'm using `$add` only a handful of times. Here's a copy paste of the `v-repeat` I'm using: 

```js
<x-node
    v-repeat="nodes"
    track-by="id"
    is-view-optimized="{{ isViewOptimized }}"
    graph-width="{{ width }}"
    graph-height="{{ height }}"
    center-view-to="{{ centerViewTo }}"
    data-state="{{@ dataSyncState }}"
    node-state="{{@ nodeState }}">
</x-node>
```

**Comment by yyx990803** [comment]
Ok, are you using `Vue.config.async = false`?

**Comment by yyx990803** [comment]
So this seems to be caused by sync mode + merging a lot of props into a repeated object, which on every merge, `$add` is being called and thus forcing the entire list to be re-evaluated.

Tested in 1.0.0-alpha, and this would no longer happen with `v-for`.

**Comment by nadirabid** [comment]
Thanks!
