### ISSUE TITLE
Deprecate "options" param for <select v-model>

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#1229]
### Problem

The `options` param has been a common gotcha when dealing with `v-model` on `<select>` elements. It  often requires additional formatting of the source data with a custom filter, and has limited capabilities in customizing the rendered options.

### Proposal

The reason `options` existed was due to some internal implementation issues - there is really no reason for it to be that way from the UX perspective. Therefore in 1.0, with some internal refactoring, we will deprecate the `options` param - instead, just use a normal `v-for`:

``` html
<select v-model="selected">
  <option v-for="option in list">{{option}}</option>
</select>
```

If you have an Array of objects, you can also bind the underlying `v-model` value directly to the object using the `bind-value` syntax on the options:

``` html
<select v-model="selected">
  <option v-for="obj in objList" bind-value="obj">{{obj.description}}</option>
</select>
```

**Comment by J-F-Liu** [comment]
Great, when I first see options I think it should be v-options.

**Comment by jonathanpmartins** [comment]
+1

**Comment by thelinuxlich** [comment]
Can I use it like this:

```
<select v-model="selected">
  <option v-for="obj in objList" :value="obj">{{obj.description}}</option>
</select>
```

**Comment by jonathanpmartins** [comment]
@yyx990803 What happened with the $index variable of the v-for (deprecated v-repeat) loop?

**Comment by ije** [comment]
the `bind-value` syntax can't visit the property of  'obj' of 'objList'?

at the following example, the options' value is equal it's node text, but I wish the options' value is equal the obj.value!
```
<select v-model="selected">
  <option v-for="obj in objList" bind-value="obj.value">{{obj.description}}</option>
</select>
```

**Comment by yyx990803** [comment]
@ije this issue was a bit out of data, the syntax should be `v-bind:value` instead of `bind-value`.

**Comment by Haixing-Hu** [comment]
@yyx990803  I need to write a customized select component which accepts a property `options` which specifies either the options or the option groups (that is, acts exactly the same as the `options` property in the v0.x.x version of Vue.js). How can I do that?  Thanks in advance.

**Comment by yyx990803** [comment]
@Haixing-Hu http://vuejs.org/guide/custom-directive.html#params

**Comment by sagaio** [comment]
@yyx990803 FYI, I think http://vuejs.org/examples/select2.html is still using the old param.

**Comment by bajras** [comment]
Quick question:

I’m creating dynamic selects depending on the data and would like to set it in a way where the first option is always selected and is passed in to the v-model. Since i'm setting formData to empty object on initial load and v-model is bind to that it doesnt get assigned to the v-model. How can I get it to work where I would like to add the selected option to be in the v-model.

```html
<select v-model="formData[word.name]" :name="word.name">
 <option v-for="(option, index) in word.fieldProps.opts" :key="index" :value="option.value" :selected="index === 0 ? 'selected' : ''">{{ option.value }}</option>
</select>
```

```javascript
data() {
      return {
        formData: {}
};
```
