### ISSUE TITLE
Transitions during instance initialisation.

### ISSUE THREAD

**Issue by karevn** [yyx990803/vue#1230]
Currently, transitions are only available when using `v-repeat` or `v-if`. It would be very useful to make transitions available for components without these directives, and (most importantly) for a root Vue instance. 

Use case examples: 
1. A lightbox or a popup. Its whole content should fade in on creation in most cases.
2. Toolbar panels (visual-studio like) may slide from outside of the window.

**Comment by yyx990803** [comment]
Isn't that the use case for `v-if / v-show` + transition? You want the state of these components to be state-driven, not managed imperatively.

**Comment by karevn** [comment]
It's like `v-if / v-show` except that it's repeating over and over again the same code:
````vue
<template>
<div v-show="initialized" v-transition="some-transition">bla-bla-bla</div>
</template>
<script>
module.exports = {
  data: function () {
    return {
      initialized: false
    };
  },
  ready: function () {
   this.initialized = true
  }
}
</script>
````

It would be much more handy to write something like this at the parent template:

````vue
<template>
<my-component transition="some-transition"></my-component>
</template>
````

**Comment by yyx990803** [comment]
The `v-if`/`v-show` is meant to be used from the parent component though.

Consider the use case you mentioned: a popup, lightbox or sidebar, they are all part of your app, and whether it is displayed should be managed by a piece of state in your app, e.g. `isSidebarOpen`. So you should have in your app template something like this:

``` html
<sidebar v-show="isSidebarOpen" v-transition="some-transition"></sidebar>
```

And if the component also needs to be able to control its own show/hide state, you pass that parent state into the component as a two-way prop:

``` html
<sidebar show="{{@isSidebarOpen}}" v-transition="some-transition"></sidebar>
```

Then inside sidebar you can close itself by setting `this.show = false`. But in either case, I don't see the need for initialization transitions.

**Comment by yyx990803** [comment]
Closing (inactivity)
