### ISSUE TITLE
Atom and safe eval

### ISSUE THREAD

**Issue by quintanar401** [yyx990803/vue#1231]
Hi,

I've tried to use Vue in an Atom plugin and it works really great. But there is one issue - Atom does not allow eval. Though it is possible to overcome this with loophole package when I create a new Vue object, I've found out that when 'data' object is not initially fully initialized (for example contains empty [] array) and this array is used to generate a list then Vue doesn't compile the list related directives until the first element is added to the list. And then it does this with a delay, so it is not possible to use loophole to provide the safe eval. And I get an exception.
I've resolved the issue by adding a fake element to the array before 'new Vue' call and then deleting it afterwards but this is obviously just a hack.
I wonder is there a way to insert loophole call somewhere to prevent the eval-exception or maybe it is possible to add a property that could be used to provide a wrapper for eval unsafe calls?

**Comment by yyx990803** [comment]
There's a CSP branch for this purpose: https://github.com/yyx990803/vue/tree/csp

**Comment by mark-hahn** [comment]
Support for atom should somehow be in the normal release.  I'm trying to
get Atom to use Vue and this would be a problem.  Could there be an option
to use strict or not?

**Comment by yyx990803** [comment]
@mark-hahn CSP support involves shipping an entire JavaScript parser/interpreter, so the file size becomes twice as large, that's why there are two versions in the first place.

**Comment by mark-hahn** [comment]
I understand now.  I'll pester the atom team about why they are using
strict.

**Comment by yyx990803** [comment]
@mark-hahn that's probably due to the restrictions of the Chromium Embedded Framework. Atom is running as a privileged app that has access to your file system, so allowing eval opens up potential security loopholes. This is also why Chrome OS / Firefox OS apps also enforce CSP. Although in those environments file size doesn't matter anyway.

**Comment by mark-hahn** [comment]
The size doesn't matter in Atom either.  It is already gigantic and they
use one copy of an npm module for all packages.

Can you make the CSP version available in npm?

**Comment by yyx990803** [comment]
@mark-hahn it already is: http://vuejs.org/guide/installation.html#CSP-compliant_build

**Comment by mark-hahn** [comment]
What is the npm name?

**Comment by yyx990803** [comment]
It's a tag. `npm install vue@csp`

**Comment by quintanar401** [comment]
Yes,
"vue" : "csp"
works ok.

**Comment by mark-hahn** [comment]
Thanks, I've never seen syntax like that.  I thought "@" was only for
versions.

**Comment by quintanar401** [comment]
hmm, seems "vue" : "csp" doesn't work with apm publish
Not sure what to do. Probably the only way is to include .js file as is.

**Comment by mark-hahn** [comment]
> hmm, seems "vue" : "csp" doesn't work with apm publish

Please post an issue on atom/apm
