### ISSUE TITLE
Vue 1.0.0-alpha.1 slower than 0.12.12 ?

### ISSUE THREAD

**Issue by sdebacker** [yyx990803/vue#1232]
I just switched to 1.0.0 alpha but my app is now very slow, even after I rewrote things to remove all warnings.
Is it a known issue ?

**Comment by azamat-sharapov** [comment]
You should probably track down what exactly is slow, [like people do](https://github.com/yyx990803/vue/issues/1226), otherwise it may be hard to help.

**Comment by sdebacker** [comment]
Here is some more info:

![capture d ecran 2015-09-01 a 16 04 21](https://cloud.githubusercontent.com/assets/134503/9606350/39265b54-50c3-11e5-8b90-150988b0c4c1.png)

app.js:647 refers to 

```js
function nextTickHandler () {
    pending = false
    var copies = callbacks.slice(0)
    callbacks = []
    for (var i = 0; i < copies.length; i++) {
        copies[i]()
    }
}
```

CPU Profile with 0.12.12

![capture d ecran 2015-09-01 a 16 18 29](https://cloud.githubusercontent.com/assets/134503/9606700/4764c91a-50c5-11e5-9b12-ec97f149be43.png)

CPU Profile with 1.0.0-alpha.1

![capture d ecran 2015-09-01 a 16 17 05](https://cloud.githubusercontent.com/assets/134503/9606707/54feb842-50c5-11e5-8e89-6d97f2ff893a.png)

**Comment by yyx990803** [comment]
Some questions:

1. Do you have a lot of complex computed properties?
2. Have you tried building using [production settings](http://vuejs.org/guide/application.html#Deploying_for_Production)?

**Comment by sdebacker** [comment]
2. I didn’t tried building using production settings for now.
1. Here is my computed object:

```js
computed: {
  today: function() {
    return Date.now() / 1000 | 0;
  },
  timelineWidth: function() {
    return ((this.maxDate - this.minDate) / this.zoomFactor) + this.marginLeft + 15 | 0;
  },
  maxZoom: function() {
    return (this.maxDate - this.minDate) / (window.innerWidth - (this.marginLeft + 15)) | 0;
  },
  zoomFactor: function() {
    return this.maxZoom + this.minZoom - this.zoom;
  },
  years: function() {
    var minDate = this.minDate,
        minYear = new Date(this.minDate * 1000).getFullYear() + 1,
        maxYear = new Date(this.maxDate * 1000).getFullYear() + 1,
        years = [],
        year;
    for (year = minYear; year < maxYear; year++) {
      years.push(new Date(year, 0, 1).getTime() / 1000 - minDate);
    }
    return years;
  },
  minDate: function() {
    var min, i, p;
    for (i = 0; i < this.projects.length; i++) {
      for (p = 0; p < this.projects[i].periods.length; p++) {
        if (typeof min == 'undefined' || min > this.projects[i].periods[p].start_date) {
          min = this.projects[i].periods[p].start_date;
        }
      }
    }
    return min;
  },
  maxDate: function() {
    var max = 0, i, p;
    for (i = 0; i < this.projects.length; i++) {
      for (p = 0; p < this.projects[i].periods.length; p++) {
        if (max < this.projects[i].periods[p].end_date) {
          max = this.projects[i].periods[p].end_date;
        }
      }
    }
    return max;
  }
},
```

**Comment by yyx990803** [comment]
I see, I understand why now, this is because I turned off default caching for computed properties in 1.0.0-alpha.1. It seems it should be cached by default because we don't want to manually set cache: false for every computed properties like these.

**Comment by yyx990803** [comment]
For now, if you add `cache: true` to all your computed properties the perf issue should go away. In alpha 2 it will be on by default.

**Comment by sdebacker** [comment]
Yes, it works, thanks for the very good work !

**Comment by young-steveo** [comment]
@yyx990803 So I guess we're going back to `cache: true` by default?

**Comment by yyx990803** [comment]
@young-steveo yep, the memory cost seems trivial compared to situations like this.

**Comment by young-steveo** [comment]
@yyx990803 :+1:

**Comment by sdebacker** [comment]
I refactored my code by removing the two complex minDate and maxDate and set it as a single method ```setMinAndMaxDates()``` that do a ```this.$set('minDate', minDate);``` and ```this.$set('maxDate', maxDate);```. This method is then manually called when needed (after ajax calls).
It's less magic but more performant even with cache set to true.
