### ISSUE TITLE
Extract some functionality into separate NPM modules?

### ISSUE THREAD

**Issue by alessioalex** [yyx990803/vue#1233]
Hey there,

I think it would be beneficial to extract some parts of Vue into their own repos, such as: [observable](https://github.com/yyx990803/vue/tree/dev/src/observer), [nextTick](https://github.com/yyx990803/vue/blob/dev/src/util/env.js#L49-L85), [cache](https://github.com/yyx990803/vue/blob/dev/src/cache.js) and perhaps others too.

These could live inside their own Github repos in the vuejs organization.

Would you be open to something like this?

Edit: in case you like the idea but don't have time for this, I would be glad to help out.

**Comment by alessioalex** [comment]
Btw, by beneficial I mean they would have their own documentation, tests, issue tracker. They can be used by other people without having to require Vue directly. It would also make the Vue source code a bit easier to read (since there will be fewer files).

**Comment by azamat-sharapov** [comment]
See [this comment](https://github.com/vuejs/Discussion/issues/158#issuecomment-105237656) and Evan's reply to it.

**Comment by alessioalex** [comment]
Thanks @azamat-sharapov missed that thread. I guess I'll close this one and extract these myself.

**Comment by yyx990803** [comment]
@azamat-sharapov thanks, I was about to point to the same thread ;)
