### ISSUE TITLE
Allow setter on instantiation for $ and _ data properties

### ISSUE THREAD

**Issue by swannknani** [yyx990803/vue#1235]
I'm often using Vue.js with 2D or 3D framework, and it's very handy to have kind of "private" properties like theses beginning with $ or _ :+1: 
Typical cases are when storing 2d canvas context. It's super useful to not have Vue adding some getter and setter to this properties.
However is can be like boring to always declare your property to ```null```inside the ```data```hook and to set it properly inside the ```created``` or ```ready``` hook afterwards.

So my question is :

Is is possible to allow setter on "private" properties beginning with $ or _ only when the component instantiate in order to setup your component properly ?

```
module.exports = {
    data() {
        _vector: null
    }
    ready() {
        this._vector = new THREE.Vector3(1., 1., 1.) 
    }
}
```

vs 

```
module.exports = {
    data() {
        _vector: new THREE.Vector3(1., 1., 1.) 
    }
    ready() {
        console.log(this._vector) // For the moment this will print undefined
    }
}
```

**Comment by yyx990803** [comment]
If you don't declare a property in `data()`, then it won't be observed. The two examples you listed are actually equivalent. So just setting `this._vector` in `ready()` should do what you want, unless I'm not fully understanding your use case.

Maybe there can be an option `statics` that simply attaches some non-observed properties to the instance...

**Comment by swannknani** [comment]
For the moment the first code block is how I'm actually dealing with the problem.
Event if I declare my property (starting with ```_``` or ```$``` in the ```data``` hook, it will be ```undefined``` in the ```ready``` hook.

> Maybe there can be an option statics that simply attaches some non-observed properties to the instance...

Do you mean ES6 statics keyword or a proposal to add this statics options to Vue ?

**Comment by swannknani** [comment]
@yyx990803 Ok thanks I understand now.

> Maybe there can be an option statics that simply attaches some non-observed properties to the instance...

So are you ok to implement something like that in order to deal with such cases ?

**Comment by yyx990803** [comment]
@swannknani I thought about it, but it's probably a bad idea because I may need to add new private properties to the Vue prototype in the future. It'd be weird if a `_` prefixed worked before and after an upgrade it starts to throw a warning.

For your original use case - are you using the vector for data binding? (or do you expect it to be reactive?) If not, there's no need to declare it in data at all. If yes, why prefix it with `_`?

**Comment by swannknani** [comment]
@yyx990803 
> For your original use case - are you using the vector for data binding? (or do you expect it to be reactive?) If not, there's no need to declare it in data at all. If yes, why prefix it with _?

No, i don't need this property to be reactive, so stop me if I'm wrong but if I declare it straight into my component, the only way to access it after is ```console.log(this.$options.myVector```

**Comment by yyx990803** [comment]
If you don't need it to be reactive, don't declare it in `data`, but you still **can** attach it as a plain property to the vm, e.g.

``` js
created: function () {
  this.vector = new THREE.Vector3(1., 1., 1.)
}
```
