### ISSUE TITLE
SVG and tree view examples don't work on Mac or Win8.1

### ISSUE THREAD

**Issue by nkev** [yyx990803/vue#1239]
The following examples don't work on my MBP Chrome or Safari and Windows 8.1 Chrome or IE11:

http://vuejs.org/examples/svg.html
http://vuejs.org/examples/tree-view.html

![2015-09-02_21-55-46](https://cloud.githubusercontent.com/assets/5410916/9630425/7cf26076-51bd-11e5-8659-92ac4d79481a.jpg)

**Comment by yyx990803** [comment]
This was most likely due to jsdelivr CDN errors during a version upgrade. They work fine now.
