### ISSUE TITLE
v-on enhancement

### ISSUE THREAD

**Issue by lepture** [yyx990803/vue#1240]
A proposal on `v-on` directive:

`v-on` should accept `$emit` event, for instance:

```html
// <child> component
// vm.$emit('hello')

<child v-on="hello: doSomething"></child>
```

**Comment by yyx990803** [comment]
`v-on` is specifically for DOM events. They are tied to the DOM, dispatched by user interactions, and therefore handled in the DOM. Vue events are often for app's internal logic and emitted in JavaScript, and they should be handled in JavaScript. Mixing the two would likely cause confusion.

If you want it's very simple to write a custom directive to listen to Vue events though.
