### ISSUE TITLE
triggering a transitionend event after enter transition is done in in-out mode causes error

### ISSUE THREAD

**Issue by nkovacs** [yyx990803/vue#1241]
It only happens with in-out mode. The css transition that triggers the transitionend event is entirely unrelated to the component transition, which in the example uses js callbacks, and has already finished by the time the transitionend event is called.

http://jsfiddle.net/nkovacs/h800dpx2/

Uncaught TypeError: Cannot read property 'parentNode' of null caused by child.$el being null [here](https://github.com/yyx990803/vue/blob/master/src/directives/component.js#L259)

**Comment by yyx990803** [comment]
Just add `css: false` to your transition: http://vuejs.org/guide/transitions.html#JavaScript_Only_Transitions
