### ISSUE TITLE
Support array of objects in `bind-style`

### ISSUE THREAD

**Issue by Mat-Moo** [yyx990803/vue#1242]
This used to work for me in 0.12 (cFont and cTextAlign are computed functions)
```<div v-style="cFont, cTextAlign">```
where cFont and cTextAlign return an object with multiple values, however in 1alpha (bind-style) only the last one is used, e.g. my text is aligned but not coloured/styled, and if I reverse them, it's coloured/styled but not aligned.

**Comment by yyx990803** [comment]
That's a multiple clause, which is no longer supported in 1.0.0. But we can make `bind-style` support an array of objects:

``` html
<div bind-style="[cFont, cTextAlign]">
```

**Comment by Mat-Moo** [comment]
Bind-style taking an array is good, will save lots of additional computed properties just to do that :)
