### ISSUE TITLE
FilterBy with components

### ISSUE THREAD

**Issue by silasrm** [yyx990803/vue#1243]
Hi,

I'm trying to using this https://jsfiddle.net/silasrm/8L61dt58/1/

But this error occurs:
Uncaught TypeError: Cannot read property 'push' of undefined

**Comment by yyx990803** [comment]
Please describe the steps to reproduce the error.

**Comment by silasrm** [comment]
Hi,

See this link https://jsfiddle.net/silasrm/8L61dt58/4/ with developer tools/firebug open.

Explain:
My app have a list with component working with v-repeat:
```
<div v-repeat="itens" v-component="item-data-component">
</div>
```

This is ok. But I need to add a search field to searching in list item:

```
<input type="text" v-model="search" placeholder="Search in name..." />
```

And change de v-repeat to:
```v-repeat="itens | filterBy search"```

When I add letter, this filtering list, but when I remove letter to clear search term, occurs this error: 
```Uncaught TypeError: Cannot read property 'push' of undefined```

Thank's.

**Comment by yyx990803** [comment]
This is a vue-validator bug, please open the issue at the vue-validator repo instead.

**Comment by silasrm** [comment]
Hi,

Sorry for my mistake, thk's!
