### ISSUE TITLE
Leave transition hook is called twice if css:false in in-out mode

### ISSUE THREAD

**Issue by nkovacs** [yyx990803/vue#1244]
Ran into this after trying your suggestion from #1241:

http://jsfiddle.net/nkovacs/a29fk09w/

**Comment by nkovacs** [comment]
Why did you close this?

**Comment by yyx990803** [comment]
Thought this was related to https://github.com/yyx990803/vue/pull/1246 ?

**Comment by nkovacs** [comment]
No, that didn't fix it unfortunately.
