### ISSUE TITLE
Snake case props support.

### ISSUE THREAD

**Issue by sl-codenine** [yyx990803/vue#1247]
Somewhat related to #1000 

I think there should be - probably in global Vue config - an option to replace camel case with snake case. Working with Vue props in coffee script isn't consistent with it's variable naming convention.

Making it a global option shouldn't add any visible performance overhead and would be a great thing to make Vue coffee compatible again, as it was before introducing props concept.

**Comment by yyx990803** [comment]
You can still use snake-case when declaring props. But in templates you have to use camelCase to refer to them because `{{a-b}}` will be parsed as a minus operation.

**Comment by sl-codenine** [comment]
Actually i meant something like that, in fact:

```coffee
SomeComponent = Vue.extend {

  props: ['some_value']

  # or

  props: {
    some_value: {
      type: String
    }
  }

}
```

And then in html:

```html
<some-component some-value="Just an example." inline-template>

  {{ some_value }}

</some-component>
```

Here the underscore `snake_case` is perfectly aligned with coffeescript conventions, and declaring props in html mark-up using `snake-case="value"` is totally acceptable.

The only difference here is that Vue would have to parse `some-value="value"` html attribute to `some_value` variable instead of `someValue`, based on some optional config option.

**Comment by yyx990803** [comment]
Can't you use `some_value="value"` in HTML?

**Comment by sl-codenine** [comment]
Right, somehow didn't thought about that. Looks like quite nice work-around for my issue. Anyway that's on the other hand isn't aligned with html conventions, at least it's a bit uncommon.

So i still think it would be a nice feature to have in Vue, but your solution makes me happy :smile:

Thanks a lot.

**Comment by yinrong** [comment]
I would like to reopen this. We are working both in web and server, so we demand snake_case coding convention which is not supported by Vue props. @yyx990803 could I propose a global config to do this?

**Comment by yinrong** [comment]
@yyx990803 what's your opinion on this?

**Comment by bradlis7** [comment]
This would be in line with ruby/rails conventions as well. A global config would be a plus.

**Comment by nickmessing** [comment]
@bradlis7, I don't think we are interested in "being in line" with any back-end technology. I personally see no benefit in adding support for even more casing, existing camelCase & kebab-case is more than enough for most use cases. Adding another one "because I like it" is not a valid reason.

**Comment by bradlis7** [comment]
Well, how about coffeescript then? It's not really "because I like it". It's the ruby/rails/coffeescript coding standard.

It probably wouldn't be too hard for Vue to look at the props available, and determine if the prop is defined `variableName` or `variable_name`, and assigning it as it finds it.

**Comment by nickmessing** [comment]
@bradlis7, I am sorry if that sounded rude, I didn't mean it to, it's just that we are following HTML and JavaScipt coding standards because that's waht Vue is all about and we don't follow any other coding standards since we are not affiliated to them.

**Comment by scott-fryxell** [comment]
What about people with reading difficulties. I prefer snake_case because It makes a difference in my ability to visually parse the page. 

what about supporting snake case as an accessibility feature?

**Comment by jim90272** [comment]
I have often wondered why I couldn't just do away with camelCase and kebab-case, and just use snake_case for everything - both for JS and HTML.  It seems pretty confusing for Vue to be converting back and forth between camelCase and kebab-case.  As far as I can tell, the only advantage of camelCase is that it provides a way to distinguish between class definitions and ordinary functions.  Class definitions use something like MyClass, which is camelCase, but with the first word capitalized.  I don't plan to ever use classes in my web pages, so I can get away with using snake_case everywhere.  But people who come from the world of Angular are used to making everything a class, so doing away with classes would probably be uncomfortable for them.
