### ISSUE TITLE
Performance degradation since 0.12.8

### ISSUE THREAD

**Issue by duebbert** [yyx990803/vue#1248]
I'm displaying a large list (c. 5000 rows) with vuejs and have only noticed now that since 0.12.8 the performance has degraded extremely. Up until 0.12.7 it was nice and fast.

Here is a very simple fiddle with 0.12.7: http://jsfiddle.net/acsLo9zf/2/
And here is the exact same with 0.12.8: http://jsfiddle.net/acsLo9zf/1/

If you press the "Next 20" and "Previous 20" you'll see how excruciatingly slow the filter function has become since 0.12.8. I've also tested this with the latest 1.0.0-alpha2 and the issue persists.

EDIT: Wrongly wrote 0.11.7 and 0.11.8 when I meant 0.12.7 and 0.12.8

**Comment by simplesmiler** [comment]
I guess you meant 0.12.7 and 0.12.8. Indeed 0.12.7 performs superior to 0.12.8 in your fiddle.

**Comment by duebbert** [comment]
Yes, you're right. Thanks for the correction. I've updated the issue now with the correct versions.

**Comment by duebbert** [comment]
Actually the situation seems more complicated. The fix in 3333598 did indeed improve the performance but there is still a major performance regression when using a sufficiently complex large array (4,000 items) and filtering and slicing the items.It's fine in 0.11.x but nearly unusable in 0.12.x.

Unfortunately I don't have time at the moment to dig into this deeper and set up a new fiddle that demonstrates it. The filtering works fine when setting the value in JS but is terribly slow when inputting values in an v-model input form.

We have reverted back to 0.11.8 for now.

**Comment by arrilot** [comment]
I also had a situaton where `filterBy` from user input was extremely slow in 0.12.7
Ended up implementing a custom filter for my case.

**Comment by yyx990803** [comment]
@duebbert are you filtering it in a computed property, or using the `filterBy` array? Did you specify a specific key to filter by like `filterBy search in 'key'`?

**Comment by yyx990803** [comment]
Regression when filtering large arrays should be fixed with 2a41b3a0bdc45bbac912c6f6206541d76ed34665 - @duebbert would appreciate if you can try it out

**Comment by duebbert** [comment]
Will do but can only do that earliest on Monday.

**Comment by duebbert** [comment]
Just tested it and it seems to have fixed it. Excellent work. Many thanks!
