### ISSUE TITLE
v1.0.0-alpha.2: Uncaught TypeError: Cannot read property '__vfrag__' of null

### ISSUE THREAD

**Issue by weislanes** [yyx990803/vue#1249]
Update: [Reproduction here](http://jsfiddle.net/mikeemisme/64scphgn/)

Occurring when dragging a list item from one unordered list to another - in this case when using RubaXa/Sortable to manage lists.

Appears to be caused by the location of the comment node after items are moved, according to comments under #437 - typeError 'Cannot read property '__vue__' of null'. That similar issue was closed as could not be reproduced. 

Billiam later provided [more details as well as a jsfiddle example](https://github.com/yyx990803/vue/issues/437#issuecomment-66904584). 

Now that v1.0.0 uses 'v-for' instead of 'v-repeat' it generates the error: Cannot read property '__vfrag__' of null.

**Comment by yyx990803** [comment]
Can you provide a repro using 1.0.0-alpha.2?

**Comment by weislanes** [comment]
Sure thing. (Repro created here)[http://jsfiddle.net/mikeemisme/64scphgn/]

**Comment by weislanes** [comment]
Spent more time on this and don't think it's due to the comment issue that affected #437. Looks like comment nodes are not output in the DOM in Vue 1.0.0 when using v-for, as far as I can tell. 

So issue is caused by something else that I can't seem to resolve.

**Comment by yyx990803** [comment]
Ok, so in 0.12, the anchor nodes for `v-repeat` will be an empty textNode in normal mode, and comment node in debug mode. So the code that hacks around comment nodes should also check for empty textNodes: http://jsfiddle.net/64scphgn/5/

**Comment by weislanes** [comment]
Thanks for that info but this doesn't resolve the issue. If you walk through the reproduction steps in your updated Fiddle the 'Cannot read property '__vfrag__' of null' error still appears. 

Note that this only happens after dragging between two lists, dragging within a list appears to be OK. Any ideas?
