### ISSUE TITLE
Pass global javascript variable to component

### ISSUE THREAD

**Issue by PhillippOhlandt** [yyx990803/vue#1254]
Hello,

When I define a global javascript variable like so:

```
<script>
    var related_books = {{ related_books|json_encode()|raw }};
</script>
```

(Note: I use twig as template engine)

How can I pass that variable over a property to my component?

Tried the following but it doesn't work:

```
<booksrelationselect books="{{ '{{related_books}}' }}"/>
```

**Comment by yyx990803** [comment]
You need to connect to that global in your vm's `data` option so that it becomes available for data binding.

``` js
new Vue({
  data: {
    related_books: related_books
  }
})
```

**Comment by trusktr** [comment]
@yyx990803  what if that variable changes? How do we use it in `computed` and have it update when it is changed?

**Comment by posva** [comment]
@trusktr please, use the forums or discord for questions, if the variable changes, you will need to reassign. You can even set it in the created hook: `this.globalvariable = 'something` and it won't be observed.
PS: Do not answer back, please 😛
