### ISSUE TITLE
IE doesn't register {{ data }} in the style attribute

### ISSUE THREAD

**Issue by IntellectProductions** [yyx990803/vue#1255]
I have IE grabbing the data that's NOT inside a style attribute, but the style attribute won't display the variables. For instance, my component has this template:

```html
<div class="thumb {{ className }}" style="height:{{ height }}px" slide-index="{{ $index }}" v-on="click: handleClick">
	<img src="{{ image }}" alt="{{ alt }}" style="height:{{ height }}px" />
	<div class="caption" v-if="caption">
		{{ caption }}
	</div>
</div>
```

It registers className, $index, image, alt, and caption.. but it's not registering ANY of the data inside the style attributes. Is there a better way to go about this? Chrome registers it just fine, but I IE won't. My thumb component looks like this:

```js
var SliderThumb = Vue.component('sliderthumb', {
	template: require('./templates/thumb.html'),

	replace: true,

	data: function() {
		return {
			height: 200,
			image: '',
			alt: '',
			caption: '',
			className: ''
		}
	},

	props: ['slideIndex', 'sendIndex', 'imageSrc', 'imageAlt', 'caption'],

	ready: function() {
		this.image = this.imageSrc;
		this.alt = this.imageAlt;
		this.caption = this.caption;

		// Make first thumb active on load
		if( this.$index == 0 )
			this.className = 'active';
	},

	methods: {
		handleClick: function(e) {
			this.sendIndex( this.$index );
			this.className = 'active';
		}
	}
});
```

It has a default height so I would think it would show that value, but it's not. It's doing this in all my other components. I was developing in Chrome and it was working great, but forget to check IE here and there so now all my components are somewhat broken.

Thanks for any advice. Is there a different way to go about setting the height/width/color/etc of elements that would go in the style tag instead of using a data variable? I'm so use to developing jQuery plugins and they just use the `.height( $value )`, but it seems weird to do that in Vue.. might just be me though.

**Comment by simplesmiler** [comment]
`v-style`?

**Comment by IntellectProductions** [comment]
NICEE!! I didn't know of this! I looked at the directives, but obviously not close enough. I'm sorry for posting such a silly question!

**Comment by simplesmiler** [comment]
Yes you can do it like this. I usually make `styles` computed property though.

**Comment by IntellectProductions** [comment]
Aren't computed properties typically for concatenation or some sort of heavy logic, not just replacing the value of a key though?

**Comment by IntellectProductions** [comment]
Plus when I move this into computed properties, my tag can't read it now.

```js
computed: function() {
	return {
		styles: {
			width: function() {
				return this.style.width + 'px'
			},
			height: function() {
				return this.style.height + 'px'
			},
			marginLeft: function() {
				return this.style.marginLeft + 'px'
			}
		}
	}
},
```

I can't access it by doing this.styles through my component AND my v-style="styles" won't work anymore. It will only read it if it's from the data method, not computed.
I would like to use computed so I can automatically add this.style.height + 'px' as the getter instead of typing + 'px' everywhere...

**Comment by yyx990803** [comment]
IE throwing away mustache tags inside `style` attributes is a long-known issue, that's why using v-style is preferred for compatibility.

Re last comment: you're using wrong syntax for computed:

``` js
computed: {
  styles: function () {
    return {
      width: ...,
      height: ...
    }
  }
}
```

**Comment by simplesmiler** [comment]
I see computed properties as "things that can be inferred from existing data". Styles fall under this description.

What I would do is:
```js
data: function() {
  return {
    height: 200,
  };
},
computed: {
  styles: function() {
    return {
      height: this.height + 'px',
    };
  },
},
```

**Comment by IntellectProductions** [comment]
Oh thank you!
