### ISSUE TITLE
Can components keep the tag wrapping them?

### ISSUE THREAD

**Issue by fnlctrl** [yyx990803/vue#1258]
Currently, component tags will be replaced by it's template:
```javascript
Vue.component('my-component', {
    template: '<p>A custom component!</p>'
})
```
and
```html
<my-component></my-component>
```

gets rendered to:

```html
<p>A custom component!</p>
```

However, is there any way to let it be rendered like this, keeping the tag around template?
```html
<my-component>
     <p>A custom component!</p>
</my-component>
```

If i do
```javascript
Vue.component('my-component', {
    template: '<my-component><p>A custom component!</p></my-component>'
})
```
It will result in infinite recursion.

An option to keep the wrapping tags will be very useful,
say if i want to implement a component for tags like that in [Angular Material](https://material.angularjs.org/latest/#/demo/material.components.tabs)
and I want to write something like this in html:

```html
<tabs>
    <tab title="foo">baz</tab>
    <tab title="bar">whatever</tab>
</tabs>
```

which it gets rendered to:

```html
<tabs>
    <tabs-wrapper>
        <tab-item>foo</tab-item>
        <tab-item>bar</tab-item>
    </tabs-wrapper>
    <tabs-content-wrapper>
        <tab-content>baz</tab-content>
        <tab-content>whatever</tab-content>
    </tabs-content-wrapper>
</tabs>
```

so it's obviously reasonable to keep the `<tabs>` tag.

otherwise, I will have to do something like: 

```javascript
Vue.component('tabs', {
        props: ['label'],
        template: '<tabs-avoid-recursion><content></content><tabs-avoid-recursion>',
});
```

which is verbose.

**Comment by simplesmiler** [comment]
There is an options for that.

```js
Vue.component('my-component', {
    replace: false,
    template: '<p>A custom component!</p>'
})
```

**Comment by fnlctrl** [comment]
Thanks! problem solved.

**Comment by simplesmiler** [comment]
The `replace` option used to be `false` by default, but was changed to `true` is [0.12.2](https://github.com/yyx990803/vue/releases/tag/0.12.2). I guess guide is slightly out of date and needs updating.

**Comment by yyx990803** [comment]
Guide has been updated.

**Comment by trevorhreed** [comment]
This thread is old, I know. Did the `replace` option get removed?

**Comment by sirlancelot** [comment]
Yes

**Comment by trevorhreed** [comment]
:( Out of curiosity, would you mind sharing the reasoning for this?

**Comment by JCH77** [comment]
What a pity to remove replace option. It can be useful to keep custom tags in rendered HTML.
