### ISSUE TITLE
Handle methods differently if user is on mobile

### ISSUE THREAD

**Issue by IntellectProductions** [yyx990803/vue#1259]
I'm having trouble setting up my Vue components to handle their methods differently if the user is on mobile. For instance a navigation drop down, if a user clicks on a link, I want to prevent them from going to that location, but instead drop down the drop down. Whereas on desktop, I want them to go to it if they click on it and only drop down on hover. I'll need this for so many other aspects of my project.

I have a main Vue instance:

```js
var Main = new Vue({
	el: 'body',

	data: {
		mobile: true
	},

	ready: function() {
		if( document.clientWidth >= 992 )
		{
			this.mobile = false;
		}
	}
});

export default Main;
```

Then for my components, I'm doing something like this:

```js
import Main from './../Main';

var NavLink = Vue.component('navlink', {
	template: '#nav-link-template',

	replace: true,

	data: function() {
		return {
		}
	},

	props: ['text', 'url'],

	ready: function() {
	},

	methods: {
		handleClick: function(e) {
			e.preventDefault();
			console.log(Main.mobile);

			if( Main.mobile )
			{
				if( this.$children.length )
				{
					// Has dropdown
					this.$children[0].dropDown();
				}
				else
				{
					// No dropdown so redirect user
					window.location = this.url;
				}
			}
			else
			{
				// Not mobile so let user go
				window.location = this.url;
			}
		}
	}
});
```

Not only does `Main.mobile` return the default value no matter what resolution because their ready methods seem to run BEFORE the Main ready method.. but this also feels like the wrong setup.

Thanks for any insight.

**Comment by simplesmiler** [comment]
I think you need to listen for a 'resize' event on the window, and update
the 'mobile' field in the handler.

**Comment by IntellectProductions** [comment]
So I have to do that in every single component? That seems repetitive. That's what I'm trying to avoid. I already know I could get it working like that.. but I hate having to do that in every single one. And when I do it in my Main vue instance, the other components fire before the Main vue instance does so it's always the default value..

**Comment by yyx990803** [comment]
Why do you have to store it? Just check screenwidth in the method. It's not that expensive. Or use a [mixin](http://vuejs.org/guide/extending.html#Extend_with_Mixins).

BTW, this type of questions should be posted to [vuejs/Discussion](/vuejs/Disucssion/issues) instead.

**Comment by PrimozRome** [comment]
@IntellectProductions did you find a good solution how to handle this?
