### ISSUE TITLE
how to write code better?

### ISSUE THREAD

**Issue by tcdona** [yyx990803/vue#1260]
想要做到切换 classname 的目的，怎么做比较好目前代码：

http://jsfiddle.net/yolio2003/otqcz1fm/4/

感觉不好。

**Comment by yyx990803** [comment]
直接用表达式来做：https://github.com/yyx990803/vue/blob/dev/examples/todomvc/index.html#L44-L46

**Comment by tcdona** [comment]
hi，小右，多谢回复，已经很简洁的搞定了：
http://jsfiddle.net/yolio2003/otqcz1fm/11/

但是衍生了一个问题：
http://jsfiddle.net/yolio2003/otqcz1fm/22/

数组内部，我要想单独操作 project 的数据怎么办？ 只能 parentlist.$set ?

**Comment by tcdona** [comment]
@yyx990803 https://github.com/vuejs/Discussion/issues/375
额 貌似这里要写英文？

**Comment by sinoon** [comment]
我觉得可以这样，多一个数据字段，叫select，然后绑定v-on="mouseup: select = $index"，在v-class="
select === $index"，不需要写方法就可以实现，而且select这个数据字段也可以直接用来得出当前第几个被点击或者激活状态

http://jsfiddle.net/otqcz1fm/23/

在 2015年9月6日 上午11:24，tcdona <notifications@github.com>写道：

**Comment by sinoon** [comment]
@tcdona 另外有两个地方不明白是为何这样写，一个是为啥用`mouseup`?
另外一个是data里面不是通常都直接放对象就好了么？为何用function + return数据的方式？

**Comment by tcdona** [comment]
@sinoon hi 我其实已经这么做了，看这里
http://jsfiddle.net/yolio2003/otqcz1fm/11/
function + return 、mouseup 和业务有关先忽略，
现在主要是想单独操作 project 该怎么办呢？ 只能 vm.projectlist.$set 重写所有的数据的方式觉得很不优雅, 看这里：
http://jsfiddle.net/yolio2003/otqcz1fm/22/

以上我都整理到 vuejs/discussion 中，但是没人理我。。。https://github.com/vuejs/Discussion/issues/375

**Comment by tcdona** [comment]
@yyx990803 @sinoon  我终于尝试成功了，http://jsfiddle.net/yolio2003/otqcz1fm/35/

因为想要单独修改数组内部的单个数据：

```
item.isCur = true // not working，不明白为啥不可以？
this.projectlist[i].isCur = true // not working, 不推荐的错误用法
this.projectlist.$set(i, {
 'isCur': true,
   'path': 'pathrewrite', 
}) // working but must rewrite all key value 
this.projectlist.$set('['+ i +'].isCur', false) // not working ，数组 $set 不支持 path 参数?
// best solution :
this.$set('projectlist['+ i +'].isCur', true)
```

希望上面的尝试能在文档中有相关例子，我真的没找到才来麻烦大家的。

**Comment by yyx990803** [comment]
1. `isCur = true` 不行是因为你的初始数据对象里面没有 `isCur` 这个属性，所以 Vue 没有办法侦测到。推荐的做法是确保要侦测的属性被正确的初始化：http://jsfiddle.net/otqcz1fm/36/

2. 对象也可以直接 `item.$set('isCur', true)` 来强行添加一个可侦测属性。但是更推荐的做法是像 1 里面那样预先声明。

3. 数组的 `$set` 不接受 path，只接受 index。

**Comment by tcdona** [comment]
哈哈，原来是我思路还没转换过来，优先设计更好的扁平数据结构，其次牢记初始化数据属性！
多谢多谢，终于解了一大悬念，正在团队内推广 vue 呢！
