### ISSUE TITLE
Prop validation occurring before a v-if

### ISSUE THREAD

**Issue by rmp135** [yyx990803/vue#1262]
If a component is set up such that it requires a prop of type Object, yet it also has a v-if on the same property, the prop validation fails when the value is set to null. 

I don't feel this should be the case as the v-if should have caught the falsey value and not rendered/removed the component (thus no validation should take place).

Here's a [JSBin](https://jsbin.com/kukokul/edit?html,js,console,output) demonstrating what I mean.

**Comment by Mat-Moo** [comment]
Answers my question as well https://github.com/vuejs/Discussion/issues/373 !

**Comment by Mouvedia** [comment]
@yyx990803 is this fixed for the [`component`](https://vuejs.org/v2/api/#component) tag as well ?
