### ISSUE TITLE
filters changing arrays to objects break v-repeat

### ISSUE THREAD

**Issue by vprimachenko** [yyx990803/vue#1265]
Filters which process arrays and return a hash, eg a grafting operation like `groupBy`, lead to `v-repeat` not being evaluated as expected. An workaround is to use a method but is semantically not correct. cf [this fiddle](http://jsfiddle.net/vvqLatqw/1/)

**Comment by yyx990803** [comment]
In order to make array filters like `filterBy` and `orderBy` work for both array and object repeats, `v-repeat` pre-converts all values into arrays before piping them through filters. Thus you should avoid returning non-Array values inside `v-repeat` filters.

In this case, it's better to convert the array into another array, rather than an object (or use the method workaround).

Future versions will raise a warning when you return non-Array values in a `v-repeat` filter.

**Comment by vprimachenko** [comment]
The `preProcess`ing facilities are only used by `v-for` and `v-repeat` and can be simplified away once `v-repeat` is gone (`^1.0.0`). This issue can then be properly solved using
```diff
diff --git a/src/directive.js b/src/directive.js
index 1b6fadf..d3628d8 100644
--- a/src/directive.js
+++ b/src/directive.js
@@ -118,3 +117,0 @@ Directive.prototype._bind = function () {
-    var preProcess = this._preProcess
-      ? _.bind(this._preProcess, this)
-      : null
@@ -129 +125,0 @@ Directive.prototype._bind = function () {
-        preProcess: preProcess,
diff --git a/src/directives/for.js b/src/directives/for.js
index 31d789c..e3103a0 100644
--- a/src/directives/for.js
+++ b/src/directives/for.js
@@ -73,7 +73 @@ module.exports = {
-    if (process.env.NODE_ENV !== 'production' && !_.isArray(data)) {
-      _.warn(
-        'v-for pre-converts Objects into Arrays, and ' +
-        'v-for filters should always return Arrays.'
-      )
-    }
-    this.diff(data)
+    this.diff(this.process(data))
@@ -479 +473 @@ module.exports = {
-  _preProcess: function (value) {
+  process: function (value) {
diff --git a/src/watcher.js b/src/watcher.js
index c5136ba..4952465 100644
--- a/src/watcher.js
+++ b/src/watcher.js
@@ -23 +22,0 @@ var uid = 0
- *                 - {Function} [preProcess]
@@ -107,3 +105,0 @@ Watcher.prototype.get = function () {
-  if (this.preProcess) {
-    value = this.preProcess(value)
-  }
```
This change also makes using filter in `v-for`more logical as filters do receive the value referenced in the directive and the user does not have to return a specifically formatted values from filter, what promotes filter reuse.

**Comment by yyx990803** [comment]
This is actually a bit more complicated because it involves compatibility with `filterBy` and `orderBy`, but yes it will work as you proposed in official 1.0.
