### ISSUE TITLE
Initialize a Vue object after dynamic DOM creation

### ISSUE THREAD

**Issue by omarfouad** [yyx990803/vue#1266]
Hi Guys,

I have a very simple Vue object in a page (input and div) and a link that opens up a modal window. The modal window takes its contents from an element on the page. In this case, when the modal fires up, it takes a copy of the HTML containing the Vue object and places it in the modal's body:

```html
<section class="#content">
	<div id="vueApp">
		<div>{{title}}</div>
		<input type="text" v-model="title">
	</div>
</section>

<a href="#" data-modal data-modal-localElement="#content">Open</a>
```

```js
var v = new Vue({
	el: "#vueApp",
	data: {
		title: "The title"
	}
})
```

The modal, once pops up will contain the following: 

```html
<div id="vueApp">
	<div>{{title}}</div>
	<input type="text" v-model="title">
</div>
```

In the modal, the vue modal gets disconnected, so updating the input doesn't change the contents in the div (title). Is there anyway to rebind those together? 

Thanks in advance.

**Comment by yyx990803** [comment]
Please post questions to [vuejs/Discussion](/vuejs/Discussion/issues).
