### ISSUE TITLE
Vue.js and vue-router two way data-binding

### ISSUE THREAD

**Issue by externuz** [yyx990803/vue#1267]
Hi, Evan! I am trying to use your framework now, and I have one question: how can I use vue-router for two-way binding data from component to parent and from parent to components? Simple example: we have three pages. One page - 'users', second - 'cards', and third - 'main'. Scheme is very simple: 'main' should know all about 'cards' and 'users'. 'Users' should know all 'cards' and 'cards' should know nothing about 'users' and 'main'. Hope, you understand me. It's administration page, you could already understand.

Please, help me! It's very important. Thanks!

**Comment by yyx990803** [comment]
Questions should be posted to [vuejs/Discussion](/vuejs/Discussion/issues) instead of the main repo.
