### ISSUE TITLE
Improvement: Consistent filter behavior for custom components

### ISSUE THREAD

**Issue by karevn** [yyx990803/vue#1269]
The next code works fine:
```vue
<template>
  <input type="text" value="{{@property | filter}}">
 <!-- where filter is two-way filter -->
</template>
```
but this one does not:
```vue
<template>
  <custom-input value="{{@property | filter}}">
  <!-- where filter is two-way filter -->
</template>
```
It fails with `Cannot bind two-way prop with non-settable parent path: ...` message, because `compileProps` function does not recognise complex binding expressions with filters for custom components. This can be worked around, but is not intuitive and requires lots of a boilerplate code (especially taking in account, that it does work for standard html elements).

**Comment by azamat-sharapov** [comment]
Probably related: https://github.com/yyx990803/vue/issues/1237#issuecomment-137105064

**Comment by yyx990803** [comment]
This will be supported in 1.0.0. Current 1.0.0-alpha.3 already support read filters, but not two-way filters.
