### ISSUE TITLE
So many warning with `Unobservable object found in data: [object Date]`

### ISSUE THREAD

**Issue by FTAndy** [yyx990803/vue#1270]
```
[Vue warn]: Unobservable object found in data: [object Date]
```

With 0.12.13 version updated, this warning shows up, but I cannot trace the call stack to find where the error comes from.

@yyx990803 , any help?

**Comment by azamat-sharapov** [comment]
> but I cannot trace the call stack

Have you tried to switch debug mode on?

**Comment by yyx990803** [comment]
I'll remove that warning in the next version.

**Comment by FTAndy** [comment]
@azamat-sharapov , they do not impact any thing, just some warnings to warn you to trace some data.

**Comment by azamat-sharapov** [comment]
yeah I didn't notice that he was getting warning, though error and he wants to see trace.
