### ISSUE TITLE
Suggestion: Using component options for passing plugin configuration

### ISSUE THREAD

**Issue by steffans** [yyx990803/vue#1271]
It would be nice to be able to pass a plugin configuration using the component options. Therefore the plugin needs a way to register a event/callback which will be called when the component instance is created (or on other lifecycle events). This would allow the plugin to apply configuration values and for example create instance properties accordingly. Which is basically what the native options like `data`, `filters` and `methods`do already.

It would be great to offer this flexibility for plugins as well.

**Comment by karevn** [comment]
+1

**Comment by yyx990803** [comment]
Yeah, this is currently possible, but very ad-hoc. It's a good to standardize an API for it.

**Comment by yyx990803** [comment]
It looks what we want here is actually a way to inject a global mixin. For now you can achieve it like this:

``` js
Vue.options = Vue.util.mergeOptions(Vue.options, {
  created: function () {
    if (this.$options.myOption) {
      // initialize stuff based on myOption...
    }
  }
})
```

What this does is extend the default `options` for all Vue instances so the behavior is applied to every single Vue instance created. This is however undocumented at the moment. We could make it something like this:

``` js
// apply a global mixin
Vue.mixin({
  created: function () {
    if (this.$options.myCustomOption) {
      console.log(this.$options.myCustomOption)
    }
  }
})

new Vue({
  myCustomOption: 123
})
// -> 123
```

**Comment by steffans** [comment]
Sounds good to me, with the mixin a plugin can hook into every event. Merge strategies make also sense, since they might  differ depending on the plugin option.

**Comment by kazupon** [comment]
This issue had been occured in vue-validator.
https://github.com/vuejs/vue-validator/issues/55
https://github.com/vuejs/vue-validator/issues/57

Maybe I could resolve this issue.
I'll try to fix this issue at vue-validator.

Thanks !!
