### ISSUE TITLE
Unobservable objects in data in "I know what I am doing" mode.

### ISSUE THREAD

**Issue by karevn** [yyx990803/vue#1273]
Disallowing unobservable objects in data makes sense, but... Sometimes, you really need to pass them. For example, for different kinds of Drag-n-drop implementations. Of course, it can be avoided with Flux-like architecture, but as all we know - there is nothing like, say Lux.js for Vue now.
So, I offer to add an option to allow unobservable objects for certain props explicitly, like this:
```javascript
var component = Vue.extend({
  props: {
    property: {
       unobservable: true
    }
  }
})
```
So, these objects should not be observed, but should be passed at least, to allow an access to the data without hacks.

**Comment by yyx990803** [comment]
Hmm, I think the warning may have been too aggressive. I'll consider just remove the unobservable object warning.

**Comment by karevn** [comment]
I have a feeling it's not just a warning, but unobservable objects are fully ignored. Can try to put together some example.

**Comment by yyx990803** [comment]
Vue will not convert the keys on non-native objects, but replacing them will still be reactive. e.g. you can do `this.date = new Date()`, but can't expect `this.date.xxx` to be reactive.

**Comment by karevn** [comment]
Sure thing. But I have a feeling (not confirmed with formal tests), that they are completely ignored when passed as props:
```
<custom-component some-prop="{{@unobservableObject}}"></custom-component>
```
`customComponentInstance.$log()` gives me no `someProp` field at all.

**Comment by yyx990803** [comment]
Nah, it works as expected.

**Comment by karevn** [comment]
Hmm. It makes sense, but is a bit confusing when you don't know about JSON-stringifiable, don't you think? Some placeholder just to indicate "an object is here" would be great.

**Comment by yyx990803** [comment]
Yeah, `vm.$log` could use some improvement in the future, but not a priority at the moment.

**Comment by cheapsteak** [comment]
I'm trying to pass the result of a service call (that contains an array of dates) to a route's data hook and this is throwing 783 warnings.   
Had to turn of debug mode to be able to see useful logs (it was spamming the console)

**Comment by yyx990803** [comment]
@cheapsteak this warning is going to be removed in the next release.
