### ISSUE TITLE
Two-way filter writes on blur

### ISSUE THREAD

**Issue by fergaldoyle** [yyx990803/vue#1274]
Two-way filter writes on blur, even if the input value hasn't changed. Is this expected behavior? I suppose the value has technically changed from what it originally was before the filter was applied.

e.g. I added some console logs to the currency example:
https://jsfiddle.net/0h70puer/2/

If you focus and blur on input several times you'll see the `write` method is called each time.

**Comment by yyx990803** [comment]
Writing on blur is necessary to ensure correct two-way filter behavior, and the write function must be called in order to determine wether the model value has changed. It won't do anything if the value remains the same with the current model value.
