### ISSUE TITLE
v-on支持条件过滤吗？

### ISSUE THREAD

**Issue by rendongsc** [yyx990803/vue#1275]
看API文档，目前只支持key的过滤，除了Key过滤外，支持表达式的过滤吗，业务需要根据简单业务条件确定是否允许相应click等事件，比如：enableClick等对象属性来设置是否允许click等。
谢谢！

**Comment by yyx990803** [comment]
可以用自定义 filter 实现，具体见源码里面 key filter 的实现。或者直接在方法里面做检查也可以。

**Comment by rendongsc** [comment]
谢谢！
