### ISSUE TITLE
v-repeat is inverse on safari

### ISSUE THREAD

**Issue by armands2ar** [yyx990803/vue#1276]
JSFiddle here:
http://jsfiddle.net/douso81p/

Expected output:
```
ONE
TWO
THREE
```

Output on Mac safari (and Windows safari):
```
THREE
TWO
ONE
```

**Comment by yyx990803** [comment]
Object repeat does not guarantee the order (same as `for ... in` in JavaScript, which is not specified in the spec and thus engine-dependent.)

**Comment by hbrls** [comment]
Is the upcoming `v-for` the same?

**Comment by yyx990803** [comment]
@hbrls yes.
