### ISSUE TITLE
New attr binding syntax problem

### ISSUE THREAD

**Issue by karevn** [yyx990803/vue#1277]
New attr binding syntax does not work with filters:

```
<div style="{top: prop1 + 2, left: prop2 | filter"></div>
```
produces Vue warning: `Invalid expression. Generated function body: {top:scope.prop1+2, left:prop2`
Please note, that missing curly brace is not a typo - it's missing from the warning message.

**Comment by yyx990803** [comment]
The new syntax is a JavaScript object literal, you can't mix filters in it. You can only pipe the whole object through a filter. In most cases you probably want to bind the style to a computed property - inlining filters for multiple properties is messy.

**Comment by karevn** [comment]
Makes sense. But... I think there should be a more readable warning for compatibility reasons.
