### ISSUE TITLE
Deprecate `v-component` in favor of `is`.

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#1278]
### Problem

Previously, `v-component` was necessary to deal with table element components:

``` html
<table>
  <!-- can't use custom elements here -->
  <tr v-component="my-comp"></tr>
</table>
```

This works, but `v-component` is a literal directive which doesn't go well with the new binding syntax, where all `v-` directives expect to be bound to expressions. We could use the new literal syntax:

``` html
<tr v-component.="my-comp"></tr>
```

Which is a bit verbose.

### Proposal

Since we are already using the `is` attribute for dynamic components, why can't we use:

``` html
<tr is="my-comp"></tr>
```

This is in fact the same as the real custom element syntax. The only possible issue is if the page also happens to reigster a real custom element with the same name - which is very unlikely, because real custom elements must be namespaced with a hyphen, and so should your vue components if you expect external real custom elements on the page.

**Comment by young-steveo** [comment]
@yyx990803 copy-paste typo: examples are opening a different tag than they are closing: `<tr></td>`

**Comment by yyx990803** [comment]
@young-steveo oops, fixed

**Comment by young-steveo** [comment]
@yyx990803 Would this mean that `is` would work on any HTML element?  Or, is it still only for the `tr` workaround?

**Comment by yyx990803** [comment]
@young-steveo it would work on anything.

**Comment by nervgh** [comment]
I think what mixing of syntax of vue-components with syntax of Web Components is bad idea.

**Comment by yjeroen** [comment]
Question: To stay similar to #1308, would `is="abc"` become `v-is="abc"`, or can it stay as `is`?

**Comment by yyx990803** [comment]
@nervgh Vue components are modeled after web components. It already uses custom elements and the slot API.

@yjeroen it will stay as `is`. It's part of the component special vocabulary.

**Comment by zzz6519003** [comment]
it's best if we can see the corresponding implementation code 🍺
