### ISSUE TITLE
disable recursive component lookup

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#1279]
In 1.0.0, I find that if the component's name is defined, it will set itself into its `options.components` in implicit. So if I have a component name `nav` and its template is `<nav></nav>`, it will lead to max call size exceeded and there is no way to disable this behavior expect rename component's name `nav` to others.

**Comment by yyx990803** [comment]
Nav is a native element. You shouldn't be using it as a component in the
first place...

**Comment by azamat-sharapov** [comment]
I think I have in source once, where Vue checked if tag name is native HTML, before registering component.. I must be mistaking though.

**Comment by yyx990803** [comment]
@azamat-sharapov it does, but I missed the new HTML5 ones...

**Comment by yyx990803** [comment]
Closing because I think renaming is the obvious thing to do here: it's a good idea to avoid the ambiguity between "native element" vs "recursive calls".
