### ISSUE TITLE
v-for does not push items into the child vue component scope

### ISSUE THREAD

**Issue by karevn** [yyx990803/vue#1280]
Please refer to this:
https://jsfiddle.net/5gunktaj/

expected output: 
`Item text: bar`

**Comment by yyx990803** [comment]
Did you read the scoping difference between `v-for` and `v-repeat` here? https://github.com/yyx990803/vue/issues/1200

**Comment by karevn** [comment]
No, I did not. :) Btw, you probably need to update it, as mustache-type props bindings were replaced with `bind-attr` syntax.

If anyone faced the same problem, here is how it should be done now: https://jsfiddle.net/g9maj8po/
