### ISSUE TITLE
should not remove slot attribute

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#1281]
Removing the slot attribute makes it hard to apply css rules on it...

**Comment by yyx990803** [comment]
Good point!

**Comment by mikeevstropov** [comment]
@yyx990803 Hi! Slot attribute is removing now. Should it?

**Comment by mikeevstropov** [comment]
@yyx990803 Oh... I see... Im sad... https://vuejs.org/v2/guide/migration.html#slot-Attribute-Styling-removed
