### ISSUE TITLE
repeated component with alias set property to late

### ISSUE THREAD

**Issue by noirbizarre** [yyx990803/vue#1283]
When looping on a component with v-repeat, the property on the child component is set too late and:
- it trigger a lot of warnings in the console if the property is required
- it break every computed properties depending on it

This JsFiddle illustrate if (look into the debugger):
http://jsfiddle.net/noirbizarre/7u2e5yvb/1/

**Comment by yyx990803** [comment]
This has to do with the scoping issue of `v-repeat`. In 1.0.0 `v-for` will require explicitly passing in the props, and the type checks will work as expected.
