### ISSUE TITLE
Use the property specification for auto-casting in literal properties

### ISSUE THREAD

**Issue by nkovacs** [yyx990803/vue#1284]
Instead of always auto-casting, which leads to confusing behavior like #1148, you could use the property specification's type to determine what, if any, auto-casting should occur. For example:

```js
Vue.component('example', {
  props: {
    propString: {
      type: String
    },
    propStringOrNumber: {
      type: [String, Number]
    },
    propAllThree: {
      type: [Boolean, Number, String]
    },
  }
})
```

(I hope it's not impossible to extend type like that)
`propAllThree` would work like the current auto-casting, `propStringOrNumber` would be auto-casted to number, but not boolean, and `propString` would never be auto-casted.

If type is not specified, it could default to either `[Boolean, Number, String]` or just `[String]` *for the purposes of auto-casting only*. I'm not sure which one would be better, but in any case, you can explicitly specify the type to avoid auto-casting.

**Comment by nkovacs** [comment]
I've started working on this, I'll send a PR soon.

**Comment by ppq1991** [comment]
that's great

**Comment by yyx990803** [comment]
I'll close this for now, let's continue the discussion in the PR thread.
