### ISSUE TITLE
自定义指令如何通过js代码render到指定el？

### ISSUE THREAD

**Issue by rendongsc** [yyx990803/vue#1287]
刚从backbone转过来，对于vue的理解还在摸索中。
我们希望通过vue开发各种各样的指令，如表单中的日期、下拉选择等，怎么通过js代码，创建自定义指令并render到指定的容器中？
谢谢！

**Comment by yyx990803** [comment]
问题请不要发到这里，这里只接受 bug report 和 feature request.
提问可以到 [vuejs/Discussion](/vuejs/Discussion/issues)。

另外，这个问题太笼统，建议仔细看过文档里面关于组件的部分以后再提更具体的问题。

**Comment by rendongsc** [comment]
已找到实现方式，谢谢！
