### ISSUE TITLE
In IE10,IE11 

### ISSUE THREAD

**Issue by hbshun** [yyx990803/vue#1288]
![demo](https://cloud.githubusercontent.com/assets/9050905/9782182/ac341c88-57cd-11e5-92f2-bb219887a78b.png)
你好，如图代码所示，在IE10和IE11中无法渲染出来，我用了webpack打包工具，求解，谢谢！

**Comment by yyx990803** [comment]
IE 不支持原生 template tag, 所以 template 会被看作未知元素，不能出现在 table 内部。直接在 tr 上 v-repeat 即可

**Comment by hbshun** [comment]
是的，不过IE9上可以，好奇怪

**Comment by hbshun** [comment]
已经关闭的，我回复你还能看到吗？

**Comment by yyx990803** [comment]
可以...

**Comment by hbshun** [comment]
回复这么快，美国应该是晚上了吧\(^o^)/~
麻烦再问一下，如果是表格中的某几行用v-repeat重复，怎么写

**Comment by hbshun** [comment]
不好意思，我有点犯傻，您早点休息~
