### ISSUE TITLE
Checkboxes are not being checked

### ISSUE THREAD

**Issue by buzdykg** [yyx990803/vue#1289]
I'm trying to implement a 'check all' checkbox. It's working as expected until any of the checkboxes to be checked is changed separately.
Here's the fiddle demonstrating the issue - http://jsfiddle.net/74m7L6go/ .
Reproduce steps:
1. Check and uncheck a checkbox in the `th`;
2. Check David;
3. Check and uncheck a checkbox in the `th` - nothing happens.

Just in case, OS X Google Chrome Version 45.0.2454.85 (64-bit).

Any workarounds, suggenstions?

**Comment by simplesmiler** [comment]
This fiddle uses 0.11.0. Are you sure that's what you want?
Ran against 0.12.13, and it's working just fine.

**Comment by buzdykg** [comment]
@simplesmiler Oh, thank you for the swift response, closing the issue.
