### ISSUE TITLE
`v-el` and `v-ref` usage change after binding syntax update

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#1292]
This was originally raised in https://github.com/yyx990803/vue/issues/1173#issuecomment-139092569 

### Problem

`v-ref` and `v-el` are some special built-in feature that allow you to register a child component or a DOM node on the parent component. They are not really directives, but were presented as "literal directives" in previous versions. In 1.0.0, we are making literal directives more explicit, which also makes writing them a little more verbose (example: `v-ref.literal="xxx"`).

In addition, the user needs to consult the doc to remember that `v-el` registers under `vm.$$`, and `v-ref` registers under `vm.$`. The `$` and `$$` are not very explicit and does not map well with the directive names.

### Proposal

Rename to more explicit properties:

- `vm.$` -> `vm.$refs`
- `vm.$$` -> `vm.$els`

Use the arguments in the [new binding syntax](ttps://github.com/yyx990803/vue/issues/1325) to mark the ref id:

``` html
<!-- child component ref, registers vm.$refs.child -->
<comp v-ref:child></comp>
<!-- elsewhere... -->
{{$refs.child.msg}}

<!-- element ref, registers vm.$els.node -->
<div v-el:node></div>
```

### Caveats

camelCase names are converted to all lowercase when the HTML is parsed:

``` html
<comp v-ref:someThing></comp>
```

Gets rendered as:

``` html
<comp v-ref:something></comp>
```

Thus, it is necessary to use the dash-case <-> camelCase mapping for refs too (similar to props):

``` html
<comp v-ref:some-thing></comp>
{{ $refs.someThing.msg }}
```

**Comment by azamat-sharapov** [comment]
:+1:

**Comment by Codebryo** [comment]
:+1:

**Comment by thelinuxlich** [comment]
totally agree

**Comment by kazupon** [comment]
:+1:

**Comment by TerenceZ** [comment]
I've tried this syntax and I find that the browser will transform the camelcase into lowercase, it means if I write $.someComp, it will transform to $.somecomp, it destroys the benefits 1 and not easy to discover this...

**Comment by yyx990803** [comment]
@TerenceZ thanks for pointing that out - I think that can be solved by adding a warning that suggests using dash-case (which auto converts to camelCase, like props do)?

**Comment by yyx990803** [comment]
Oh, actually, because it gets converted during browser parsing, there's not really a way to detect it...

**Comment by yyx990803** [comment]
Alternatively:

``` html
<comp $="someThing"></comp>
<div $$="node"></div>
```

**Comment by tianhai82** [comment]
actually $="someThing" and $$="node" is not very intuitive, esp for new users. we have no clues to guess wat does $ and $$ stands for. Even for experienced users, they will also make mistake using it.

**Comment by TerenceZ** [comment]
@yyx990803 @tianhai82 ya, I also think the alternative notation is not intuitive but confused, esp for new users. Because it uses dot notation `$.someThing` in js and equation `$='someThing'` in template. The later seems to assign `someThing` to `$`.

IMO, although the old notation will let user have to remember the transform from `ref | el` to `$ | $$`, but it is only non-intuitive, not confused.

**Comment by Nirazul** [comment]
I disagree with the argument that the $ notation is not intuitive. Even in Chrome devtools (and other browser devtools) we have the $('selector') syntax. It's not quite the same but together with the ubiquitous jQuery syntax, for many developers it is clear that $ means 'select' or 'store' in a variable.

**Comment by nervgh** [comment]
@tianhai82
@TerenceZ 
@Nirazul
+1

I am not agree.

**Comment by zhongxingdou** [comment]
还是v-ref v-el简单，建议继续保留

**Comment by zhongxingdou** [comment]
现有的已经足够简洁好用了，希望1.0语法不要这么大改动。

**Comment by nervgh** [comment]
@zhongxingdou on english, please

**Comment by thelinuxlich** [comment]
Some people are complaining about $ being not intuitive, we could change the instance properties instead:

```
<!-- registers vm.$ref.child -->
<comp :ref.child></comp>
<!-- registers vm.$dom.node -->
<div :dom.node></div>
<!-- caveat: must use dash-case instead of camelCase, similar to props -->
<!-- registers vm.$ref.someComp -->
<comp :ref.some-comp></comp>
```

**Comment by young-steveo** [comment]
@thelinuxlich :+1: :+1: :+1:

**Comment by yyx990803** [comment]
@thelinuxlich hmm, it looks like a prop on a component though (prop ref with a `.child` modifier).

I'd say something like this:

``` html
<comp v-ref:child></comp>
<div v-el:node></div>
```

Then let's rename `this.$` to `this.$refs`, and `this.$$` to `this.$els`.

**Comment by OEvgeny** [comment]
@yyx990803 :+1:

**Comment by thelinuxlich** [comment]
Agreed

**Comment by te1** [comment]
:+1:

**Comment by Nirazul** [comment]
Ok, but please add some aliases like that: 

```html
<!-- registers vm.$.child -->
<comp $:child></comp>
<!-- registers vm.$$.node -->
<div $$:node></div>
```

```js
this.$.child
this.$$.node
```

**Comment by yyx990803** [comment]
@Nirazul is it necessary to have a shorthand for something as short as `v-ref:id` and `this.$refs`? I don't think so...

**Comment by Nirazul** [comment]
@yyx990803 It seems necessary for v-bind and v-on. I don't get the difference. 
It's not about shorness, for me it's about ease of use.

**Comment by yyx990803** [comment]
@Nirazul what makes `$` easier than `$refs` except for you being used to the old syntax? `v-ref` and `vm.$refs` is more explicit and easier to remember for new users.

**Comment by Nirazul** [comment]
I totally agree with you that `v-ref` should be the main syntax. It's the same reason I like your decision to drop `#=` and so on. I'm just really accustomed to the dollar syntax. I name my dom references with a leading `$` since.. forever. 
So the syntax appealed to me and I didn't want to see it go without me at least trying to convince you ;)
But nevermind, all in all, the changes look promsing!

**Comment by jhaesus** [comment]
Causes problems with templating engines. Forcing the use of plain html. Possible to keep old v-el="item" syntax as a backup?

**Comment by yyx990803** [comment]
@jhaesus what template engine is it?

**Comment by jhaesus** [comment]
Slim.

Found something that works like this:
```slim
div(v-el:item='')
```

but can no longer use the regular syntax
```slim
div v-el:item
```
because that will render
```html
<div>v-el:item</div>
```

Suppose it'll have to do.
