### ISSUE TITLE
Transition in a partial causes an error

### ISSUE THREAD

**Issue by Mat-Moo** [yyx990803/vue#1295]
I've a component that displays text based on a number of factor.This uses partials to help with the expected output. However if I try and use a transition in a partial I get an error :( if I take the partial and have it directly as my template component it works as expected. 1alpha

**Comment by yyx990803** [comment]
Please provide a reproduction.

**Comment by Mat-Moo** [comment]
http://jsbin.com/lemobe/edit?js,console,output
