### ISSUE TITLE
v-model with write filters

### ISSUE THREAD

**Issue by SeoFood** [yyx990803/vue#1300]
Hi

v-models with a write filter only write the value when input is changed and not like in older version on every input event.

Here are the 2 Examples:

Working Version (0.12.10): http://codepen.io/SeoFood/pen/JYYpaO
Not Working Version (0.12.11): http://codepen.io/SeoFood/pen/eppVjd

The Inputs only allow numbers.

**Comment by yyx990803** [comment]
This is an intended change in 0.12.11. The old behavior (formatting the value as the user type) results in awkward UX in most scenarios. We've found it to be much more natural and useful to let the user type whatever they want and format later. This was what two-way filters were originally designed for.

If you do want to limit what can be typed into the input, you can add a listener and update the input's value yourself.

**Comment by fullfs** [comment]
Oh no no no no no. Damn it.
@yyx990803 You've removed a very-very-very-very useful feature, you know. 
But for what? It was already possible to do almost the same thing with ```lazy``` option. 
All my project's forms are leaning on the removed behavior. I just can't move to 0.12.11 or further now

**Comment by fullfs** [comment]
It's like "go use jquery" now, honestly

**Comment by yyx990803** [comment]
@fullfs it's really simple to revert, just remove these: https://github.com/yyx990803/vue/blob/dev/src/directives/public/model/text.js#L46-L54

**Comment by fullfs** [comment]
@yyx990803 Wow, thanks! Providently as always :)
Would like to have the option for ```v-model``` if possible
