### ISSUE TITLE
Call watch callback even when value is set to current value

### ISSUE THREAD

**Issue by kaptajnen** [yyx990803/vue#1302]
I noticed that the callback for the watch function is not called if the value is set to the current value. It would be nice to have an option to have the callback called even though the value is the same.

Here's a fiddle demonstrating the behavior: http://jsfiddle.net/do7fo4zr/
If you open the console you can see the callback is not called when the value is set to the same value twice in a row.

**Comment by mark-hahn** [comment]
What is your use case for this?

**Comment by yyx990803** [comment]
That's the point of the API: `watch` only triggers when the value has actually changed. Vue also buffers multiple changes in the same event loop so the callback only trigger once with the latest value. Making it trigger on every set defeats its purpose, and I'm sure there's a better way to achieve what you want.

Closing, but feel free to continue the discussion. (Maybe start a new thread with what you are trying to do at vuejs/Discussion instead)

**Comment by kaptajnen** [comment]
In my case I plot the new value in a graph every time it changes. By not updating when the value is changed, the graph represents the wrong image of the change over time.

**Comment by yyx990803** [comment]
Why would you need to update the graph when the value has **not** changed?

**Comment by kaptajnen** [comment]
To trend the change over time. You can imagine if the value changed 5 times, but the value only changed 2 times, the graph should be a flat line followed by a small increment. By only updating when the value changes, the graph turns into a continuously rising line instead.

Obviously I can just make my own event to fire when I get new data, and trigger the graph update there so it may not be that big of an issue after all.

**Comment by yyx990803** [comment]
You should just always re-render in a setInterval rather than doing it inside a watch callback.

**Comment by kaptajnen** [comment]
That is an ever better idea, thanks!

**Comment by simplesmiler** [comment]
Another thing you can do is to store not the latest value, but a list of n latest values, where n is the number of points that should be drawn.
And yet another one is to store `t` alongside actual value, and increment `t` in callback, and in watch callback for `t` draw your graph.
