### ISSUE TITLE
Even a destroyed VM can not be mounted again

### ISSUE THREAD

**Issue by zhongqf** [yyx990803/vue#1305]
After destroyed by `app.$destroy(true)`, the vm can not be mounted `app.$mount("#app")` again.
Is it desired or a bug?
If it is a desired action, how should we clean up and re-mount it?

**Comment by yyx990803** [comment]
This is intended. A destroyed vm cannot be used again.

If you want to reuse a component:

``` js
var App = Vue.extend({
  template: '...',
  // ...
})

// mount on empty div and append to #app, instead of mounting on it
var app = new App().$mount().$appendTo('#app')
// destroy old one
app.$destroy(true)
// create a new instance and mount again
app = new new App().$mount().$appendTo('#app')
```

However, this sounds like a rare use case to me. Why do you want to destroy and remount instead of just resetting the state of the app?

**Comment by zhongqf** [comment]
Thanks. I will use it in this way. 
Yes, as you think, it is an abnormal usage. :smile: 
I am trying to reuse a vue-component within Meteor Blaze template.
