### ISSUE TITLE
transition-mode="out-in" causing issue with directive.

### ISSUE THREAD

**Issue by crswll** [yyx990803/vue#1306]
I set up a demo of the issue. Not sure if it has to do with `vue-router` or not so I posted it here.

http://jsbin.com/nugojawine/1/edit?html,js,output

Basically, if I use "out-in" the directive doesn't seem to wait to apply the same way it does with other transition modes. Not sure if this is an issue with my approach or the directives are being applied too early. Either way it seems inconsistent. Any light on the issue or my technique would be awesome.

**Comment by yyx990803** [comment]
This is because Masonry relies on the element to be already inserted so that it can read its width and height. What you can do is to wait until the vm is attached in the masonry directive:

``` js
Vue.directive('masonry', {
  update: function (items) {
    var self = this;
    this.vm.$once('hook:attached', function () {
      var masonry = new Masonry(self.el, {
        percentPosition: true
      });
    })
  },
  unbind: function () {
    // ...
  }
});
```

**Comment by crswll** [comment]
Thanks a lot for that. 

I was triggering a window resize my actual component on attached to get around this issue but this feels better. 

This also helps with how to keep the unbind on the directive from happening too quickly and getting weird right before the transition to the other component comes in.
