### ISSUE TITLE
Insert el before target - Uncaught TypeError: Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by weislanes** [yyx990803/vue#1307]
**Issue:**
 I've a component repeated seven times, outputing a list for each day of the week. I'm using a drag and drop library so users can drag from one list to the next. It mostly works. When users rearrange the list, I use underscore to update the order of the data object so that problems solved.

However when a list that had items on it is cleared (completed or deleted tasks) and a new item is added/dragged to that list I see this error: 

**Uncaught TypeError: Cannot read property 'parentNode' of null**

And the console points me to this:

	 * Insert el before target
	 *
	 * @param {Element} el
	 * @param {Element} target

	exports.before = function (el, target) {
	  target.parentNode.insertBefore(el, target)

target is null. 

**Vue version:** 1.0.0-alpha
Am working on a repo however any idea what may be the cause given the above info?

**Comment by yyx990803** [comment]
This really depends on the drag and drop lib you are using, because `v-repeat/for`'s render mechanism my be in conflict with what the 3rd party lib is trying to do.

**Comment by yyx990803** [comment]
Closing (no repro)
