### ISSUE TITLE
Form value initialisation leads to blank value on blur

### ISSUE THREAD

**Issue by arbarrett** [yyx990803/vue#1310]
When I enter or update a text field form value, the value is reverted upon blur.
This issue seems to begin in v12.11.
The following simple fiddlejs shows the behaviour.
https://jsfiddle.net/5sH6A/155/
If I uncomment 'dog: null,' or 'this.cat.name = 'ginger';', then the issue disappears.
However uncommenting 'this.cat = 'cat';' alone, doesn't fix it.
Uncommenting both 'this.cat = 'cat';' and 'this.cat.name = 'ginger';' causes the issue to persist.
This all seems odd to me. (btw, I am very thankful for vuejs!)

**Comment by Mat-Moo** [comment]
Fiddle is blank?

**Comment by arbarrett** [comment]
Sorry, I have now updated the link above.

**Comment by yyx990803** [comment]
1. A property is only observed when you declare it in `data`;

2. If you set a non-declared property in `created`, it becomes a non-observed property. `v-model` will not convert it to an observable property for you. However, if you do not set it in `created`, `v-model` will notice that the property doesn't exist, and therefore create it as a observable property.

The best practice is to **always** declare what you want observed in `data`.

**Comment by arbarrett** [comment]
Thanks Evan. I was mostly confused as to why "this.cat.name = 'ginger'" fixes the issue, but "this.cat = 'cat'" doesn't. Why would setting "this.cat.name" in the "created" method mean that "this.dog" becomes observed? And why setting "this.cat = 'cat'" prevents "this.dog" from being observed?

**Comment by yyx990803** [comment]
`this.cat.name` simply causes an error so the vm didn't even finish the initialization.

**Comment by arbarrett** [comment]
Ah yes, I see. Thanks. Sorry for the bother.
