### ISSUE TITLE
Is there legal way how I can get repeater $index inside of my component?

### ISSUE THREAD

**Issue by nervgh** [yyx990803/vue#1313]
Hi

```html
<vue-map :size="size" :elements="elements" :on-click-element*="onClick">
    <vue-map-hint v-for="hint in hints">
        {{$index}} <!-- IT NEED FOR ME -->
    </vue-map-hint>
</vue-map>
```
```js
Vue.component('vue-map-hint', {
    replace: false,
    inherit: true,
    attached() {
        console.log(this.$index); // I NEED REPEATER $index HERE
    }
});
```
I say `inherit: true` and I see https://yadi.sk/i/A6bVwZtHj5hkp.
1. It's good, but the `$index` does not exists there :disappointed:
2. If I will be expanding the `_scope` I see it https://yadi.sk/i/ByyqqVnYj5iFg

Consequently, I could write `this._scope.$index`, but `_scope` is private.

Thanks!

**Comment by yyx990803** [comment]
pass it in as a prop:

``` html
<vue-map-hint v-for="hint in hints" index="$index">
</vue-map-hint>
```

``` js
Vue.component('vue-map-hint', {
    replace: false,
    props: {
      index: Number
    },
    attached() {
        console.log(this.index); // I NEED REPEATER $index HERE
    }
});
```

**Comment by nervgh** [comment]
wow, thanks, very fast :zap:

I still have one question: _Why `$index` does not pass in my component, when I write `inherit: true`? It is correct behaviour?_

**Comment by yyx990803** [comment]
`inherit: true` doesn't work with `v-for` scopes since it's going to be deprecated in 1.0.

**Comment by nervgh** [comment]
Ok. We will miss you, `inherit: true` :smile:
