### ISSUE TITLE
Issue when changing the component template on created event

### ISSUE THREAD

**Issue by miljan-aleksic** [yyx990803/vue#1314]
Hi!

seems there is an issue with dynamically changing the component template. On [this](http://jsfiddle.net/5sH6A/160/) fiddle you can see a Fields component which has a Field child component with different layouts depending of the field type (input, checkbox).

In line 13 of the JS the template change is happening and as you can see it doesn't work, but if you change that line for this one, it starts working.

```
this.$options.template = this.$options.templates['text'];
```

Seems being limited to accept only one template during the iteration. Let me know if more details are required.

**Comment by yyx990803** [comment]
The short answer is: you're not supposed to do this - because template compilations are cached, and modifying it at runtime makes optimizations impossible.

You can use dynamic partials for this.

**Comment by miljan-aleksic** [comment]
You know you are right :)
