### ISSUE TITLE
Allow v-on to also work on custom events when used on child component

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#1315]
#### Problem

Currently the common practice for parent-child communication is passing down a method as a callback:

``` html
<comp :on-something="handleSomething">
</comp
```

But this requires the child to declare a function prop, and calling a method on itself to communicate to the parent is not so intuitive:

``` js
// we need to either make "onSomething" a required prop,
// or check its existence before calling it.
if (this.onSomething) {
  this.onSomething()
}
```

A lot of times, it's nicer to have the loose coupling of real events:

``` js
// just this would be nice
this.$emit('something')
```

Previously we had the `v-events` directive, which serves this exact purpose; I removed it in favor of the callback-prop pattern, partly because I felt the event system was problematic due to the issues outlined in #1175. But now the problem is somewhat mitigated with the solution proposed in #1175 (stop propagation by default), we can now reconsider the event pattern. If we bring back `v-events` with the new directive syntax, it would look like this:

``` html
<comp
  v-events:update="handleUpdate"
  v-events:ready="onChildReady">
</comp>
```

Which is not bad; but since we are already using `v-bind:` for both native attributes and props, why not just use `v-on` for both native and custom events?

#### Proposal

Allow `v-on` to listen for Vue custom events when used on a child component. In particular, **props** and **events** should constitute the public API of a component:

- props for passing data down
- events for handling actions up

A typical component would look like this:

``` html
<comp
  v-bind:prop-a="parentA"
  v-bind:prop-b="parentB"
  v-on:ready="onChildReady"
  v-on:update="onChildUpdate">
</comp>
```

With shorthand:

``` html
<comp
  :prop-a="parentA"
  :prop-b="parentB"
  @ready="onChildReady"
  @update="onChildUpdate">
</comp>
```

**Comment by karevn** [comment]
:+1:

**Comment by thelinuxlich** [comment]
nice!

**Comment by kazupon** [comment]
:+1:

**Comment by azamat-sharapov** [comment]
This will be great.

**Comment by Pandahisham** [comment]
finally ! :+1:

**Comment by simplesmiler** [comment]
I like the clear separation of up and down dataflow :+1:

---

Warning: madness ahead.

We currently have two types of directives: first accept expressions (similar to `:` props)  and second accept statements (similar to `@` props). Quite a parallel between props and directives.

So what if directives are actually some kind of "unbound" props? They are injected into the component instance and modify instance behavior a bit. They are like ad-hoc mixins, applied not by the component itself, but by the component consumer.

``` html
<my-button @click="ddShown = true">Show the dropdown</my-button>
<my-dropdown :if="ddShown" @click-away="ddShown = false">
  Hi, I am dropdown!
</my-dropdown>
```

Look closely, are these props or directives?

**Comment by yyx990803** [comment]
@simplesmiler this is what I had in mind when I mentioned "dropping v- altogether and make everything custom attributes"; but you saw what happened ;)

**Comment by simplesmiler** [comment]
I guess the issue is that names start to clash. I wonder how this is solved in unified call syntax proposal of C++. Went googling.

**Comment by thelucre** [comment]
How would you emit a custom event from the child, assuming you bind to the parent with this syntax?

For instance:
```javascript
@imagesLoaded="parentChildImagesLoaded"
```

**Comment by yyx990803** [comment]
@thelucre http://vuejs.org/api/instance-methods.html#Events

**Comment by sai-prasanna** [comment]
@yyx990803  what about something like props validation for events?
