### ISSUE TITLE
<input> value not reactive [1.0.0-alpha]

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#1317]
http://jsfiddle.net/cwgv3vtn/2/

```HTML
<input $$.input type="text" value="qwerty" >
this doesn't update: {{$$.input.value}}
```

**Comment by Mat-Moo** [comment]
http://vuejs.org/guide/forms.html
You're not using a model to link the input to any data...

**Comment by cheapsteak** [comment]
Was hoping I wouldn't have to add a property in my data object for this, all the logic's contained in the template  

Usage is kind of like:  
```html
<div>
    One place to add a thing: <input $$.input-a type="text" on-keyup-enter="addItem($$.inputA.value)">
    <button on-click="addItem($$.inputA.value)" bind-disabled="$$.inputA.value">submit (disabled if textbox value empty)</button>
</div>
...
<div>
    Another place to add a thing to the same array: <input $$.input-b type="text" on-keyup-enter="addItem($$.inputB.value)">
</div>
```

http://jsfiddle.net/r34ac4p2/

And that works (didn't used to be able to do this before v-el and v-ref became reactive), except for binding the button's disabled property to the input element's value  

Having to use a v-model and add a property to the data object to make the value reactive would seem to add just a little bit of cruft, and also sync the value of two separate input boxes (which I don't want)

**Comment by Mat-Moo** [comment]
Well if there is nothing for Vue to observe, how can it react? To me that should be a simple input component using your callback. Maybe I'm wrong, wait for the master to turn up :)

**Comment by yyx990803** [comment]
This won't work because Vue's reactivity requires the source of truth to be in JavaScript, not the DOM. Vue does not observe any change to `$$.input.value` because it's a DOM element property. The simple rule of thumb is if you need reactivity, it needs to be in `data`.
