### ISSUE TITLE
Question: trying to understand `/src/observer`

### ISSUE THREAD

**Issue by alessioalex** [yyx990803/vue#1320]
So I've looked at the Observer code and tests and was trying to use it outside of Vue, just to try to figure out how it works.

From what I've looked at the object properties get converted to setters and getters, that should trigger a notify function on the dependency.

However when I try to update a property on an observed object, it doesn't call the notify function:

```js
var Observer = window.observer;
var obj = { a: 1 };
var ob = Observer.create(obj);
var dep = ob.dep;
dep.notify = function() { alert('object updated'); }.bind(dep);

// shouldn't the notify function be called?
obj.a = 45;
```

Live example here (observer is bundled via browserify): http://jsfiddle.net/y6jcah6w/

I'm also having some trouble understanding this lines of the update property test: https://github.com/yyx990803/vue/blob/dev/test/unit/specs/observer/observer_spec.js#L54-L69 (more specifically what does `Dep.target = watcher` do).

Would appreciate some help @yyx990803 thanks a bunch!

**Comment by azamat-sharapov** [comment]
https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines
