### ISSUE TITLE
在v-repeat的元素自己身上加v-if无效

### ISSUE THREAD

**Issue by chairuosen** [yyx990803/vue#1326]
version: 0.12.1 of mine  or edge on jsfiddle
demo: http://jsfiddle.net/rx8xsy3c/

**Comment by posva** [comment]
As a quickfix, use `v-show`

**Comment by chairuosen** [comment]
@posva Yeah, you are right.
 just a bug report.

**Comment by yyx990803** [comment]
Did you see the warning in console? It's telling you don't use `v-if` together with `v-repeat`.
In 1.0 `v-for` will be ok with `v-if`, but it's still recommended to use `v-show` instead.
