### ISSUE TITLE
lazy惰性更新的中文支持

### ISSUE THREAD

**Issue by heibanke** [yyx990803/vue#1327]
您好，非常喜欢您的vue.js，

使用中发现，如果加上lazy，input在输入中文时会更新两次，第一次先更新成输入的字母，然后立即更新为中文。这在表单验证时会出现些问题，比如不必要的验证了输入的字母。

想问一下是否在这种情况下不应该使用lazy，或者说lazy的使用有何限制？谢谢

**Comment by songofhawk** [comment]
这是不是还是由于同时绑定了 v-model 和 value引起的啊? https://github.com/vuejs/vue/issues/1790
