### ISSUE TITLE
What happened to access to this.$index inside a component?

### ISSUE THREAD

**Issue by jackmcdade** [yyx990803/vue#1329]
I want to call a method from inside a component and not have to explicitly pass the `$index` and `$event`, but access it with `this.$index`. I know this works, I've done it, but now I don't know what's going on. This literally works in some of my components but not others, even though they're built exactly the same.

Here's a fiddle, clicking the buttons should log the `$index` but remains undefined. 

<http://jsfiddle.net/jackmcdade/wzuhn2yb/10/>

**Comment by yyx990803** [comment]
Note a method's `this` context is **always** bound to the instance that declared it, no matter where it is called. In both examples, the `check` method is called on the parent instance, not the repeat instance.

It's better to pass the `$index` into the method instead.
