### ISSUE TITLE
Observe more bindings inside directive

### ISSUE THREAD

**Issue by thelinuxlich** [yyx990803/vue#1333]
The select2 example from VueJS doesn't work if the options are dynamically set after loading:

http://jsfiddle.net/yyx990803/zuc27nw9/light/

So how can I observe the options array to avoid this?

**Comment by yyx990803** [comment]
Use `this.vm.$watch(optionsExpression, cb)` to handle the update.

**Comment by thelinuxlich** [comment]
When the options array is replaced it doesn't work:

http://jsfiddle.net/zuc27nw9/16/

**Comment by yyx990803** [comment]
I have no idea why, it seems like select2's problem.

**Comment by thelinuxlich** [comment]
Got it working with a ugly hack, you should consider doing something similar on the example: http://jsfiddle.net/zuc27nw9/21/
