### ISSUE TITLE
Directives defined within component is not resolved.

### ISSUE THREAD

**Issue by fnlctrl** [yyx990803/vue#1335]
As described in the [guide](http://vuejs.org/guide/components.html#Private_Assets) and specified in the [docs](http://vuejs.org/api/options.html#directives), components can have private assets, but this won't work:
```javascript
components: {
    foo: {
        directives: {
             bar: {
                bind: function(){....}
             }
        }
    }
}
```
see this fiddle please.
http://jsfiddle.net/fnlCtrl/hbLrdeus/

**Comment by yyx990803** [comment]
Read this section on component scope: http://vuejs.org/guide/best-practices.html#Component_Scope

It only works when you are using it inside the child component's **own** template.

**Comment by fnlctrl** [comment]
for the record, use 'inline-template' on component to get the directive working.

**Comment by fnlctrl** [comment]
I've read through [Component Scope](http://vuejs.org/guide/best-practices.html#Component_Scope) and [Communication Between Instances](http://vuejs.org/guide/best-practices.html#Communication_Between_Instances), but I still couldn't figure out a clean way to do this:

I'm currently implementing a 'tabs' component, which i imaged to look like:
```html
<tabs>
    <foo v-tab-label="foo"></bar>
    <bar v-tab-label="bar"></bar>
</tabs>
```
and gets rendered as:
```html
<tabs>
    <tabs-pagination>
        <span>foo</span>
        <span>bar</span>
    <tabs-pagination>
    <foo></bar>
    <bar></bar>
</tabs>
```

The `tab-label` directive was intended to $dispatch an event to `tabs` component, registering current element as a content of a tab, (which is an `angular` approach).
But this will not work because `tab-label` is not used inside it's own template.

Then I tried 
```html
<tabs inline-template>
    <foo v-tab-label="foo"></bar>
    <bar v-tab-label="bar"></bar>
</tabs>
```

but it still won't work because in the `tab-label` directive's `bind` function, `this.vm` points to `tabs` instead of `foo` and `bar` (which I later understood the reason is that, `tab-label` is compiled at `tab`'s scope), so I can't pass `this.vm` by $dispatch.


What i actually need is something that:
1. can be added as an attribute(or directive, prop, whatever) to any child element/component (of `tabs`), that will $dispatch an event, passing itself as argument,
2. without the need to be manually defined in the child component's own definition.

Would you kindly give me some advice on that?

**Comment by fnlctrl** [comment]
After deeper thoughts I think I need this:

A directive that uses the scope of the component it is attached to, without being defined in the component's `directives` option, like angular.js

**Comment by fnlctrl** [comment]
Ok, I found the solution.
Inside the directive's bind function, use 'this.el.__vue__' to access the scope of the component it is attached to.

@yyx990803  Maybe provide a public property for that? Using `__`-prefixed private properties doesn't look quite a right thing to do.
