### ISSUE TITLE
Suggestions about 'inline-template' directive

### ISSUE THREAD

**Issue by fnlctrl** [yyx990803/vue#1336]
1. if `inline-template` directive and `template` option are both present, use the html content to replace `<content></content>` insertion point, instead of replacing the whole template.
Or at least provide an option for this behavior.

2. Add `inlineTemplate` to component options, so we don't have to use `inline-template` every time we use a component.

**Comment by fnlctrl** [comment]
The use case is as follows:

I have a `tabs` component for switching tabs, which looks like
```html
<tabs inline-template>
    <foo v-tab-label="foo"></bar>
    <bar v-tab-label="bar"></bar>
    <div>Some random content that will not be registered as a tab</div>
</tabs>
```

and gets rendered as:
```html
<tabs>
    <tabs-pagination>
        <span>foo</span>
        <span>bar</span>
    <tabs-pagination>
    <foo></bar>
    <bar></bar>
    <div>Some random content that will not be registered as a tab</div>
</tabs>
```

The `tabs` component:
```javascript
module.exports = {
    template:
    '<tabs-pagination>' +
        '<div v-repeat="tab in tabs"></div>' +
    '</tabs-pagination>' +
    '<content></content>',
    replace: false, // to keep the 'tabs' tag
    inherit: true,
    create: function() {
        this.$on('tab-created',registerTab);
        function registerTab (){}
    },
    directives: {
        'tab-label': {
            bind: function() {
                this.el.__vue__.$dispatch('tab-created',this);
            }
        }
    }
};
```


The problem is:
1. Without `inline-template`, the `tab-label` directive won't work because
> It only works when you are using it inside the child component's own template. #1335 
2. With `inline-template`, the `<tab-pagination></tab-pagination>` will be ignored.
3.If I decide to live with `inline-template` to solve problem 1, I will have to add it every time I use `tabs`, which is of course annoying.

**Comment by yyx990803** [comment]
Here's a more sensible API without the need for `inline-template` or using a directive:

``` html
<tabs>
  <tab label="foo">
    <foo></foo>
  </tab>
  <tab label="bar">
    <bar></bar>
  </tab>
</tabs>
```

Each `tab` component, when created, dispatches an event so that the parent `tabs` can register it.

**Comment by fnlctrl** [comment]
@yyx990803 
It won't work if I define `tab` within `tabs`, even with `inline-template`.

see this fiddle:
http://jsfiddle.net/fnlCtrl/sob1g5nn

**Comment by fnlctrl** [comment]
@yyx990803 

Still needs `inline-template` to work.
fiddle: http://jsfiddle.net/fnlCtrl/8pvgu8pk/

**Comment by yyx990803** [comment]
Don't think of `tab` as a private component of `tabs`... import them together in the parent component.

**Comment by fnlctrl** [comment]
But conceptually, `tab` should really be a private component of `tabs` because:
1. `tab` is a `dependency` of `tabs`, not `peer dependency`.
2. `tab` will never be used elsewhere, outside of `tabs`, nothing will capture it's $dispatched events.
3. For other developers, importing `tabs` *should* suffice it's usage (which is intuitive), otherwise it needs to be documented (and for *every* other ui component that has a *peer dependency*).

**Comment by yyx990803** [comment]
If the developer needs to be aware of it then it's not private...

**Comment by fnlctrl** [comment]
Ok, so it's not private.
Then, would it be better that this relationship of dependency can be explicitly specified, something like a `dependency` option that will be injected into parent vm(in this case `body`)'s components/directives.

Otherwise using a component means looking up the docs, finding all other possible dependencies, and including all of them on the parent vm if they exist....

**Comment by yyx990803** [comment]
I don't think that's really that bad. It's more like composition rather
than dependency.

**Comment by fnlctrl** [comment]
Ok... guess I'll just live with that ;)
Thanks!
