### ISSUE TITLE
什么情况下会使双向绑定失效?

### ISSUE THREAD

**Issue by galenyuan** [yyx990803/vue#1337]
如题，local版本没问题，各项操作均能正常使用，与真实服务器连接后有一个section双向绑定失效，数据正常赋值，但看起来并没有被实例成vue的model
![image](https://cloud.githubusercontent.com/assets/10335062/9979136/b82ce33c-5f8c-11e5-8d50-0dbd4f75ce80.png)
这是console出来的数据，只是单纯的数据，每个属性都没有get和set属性。
这部分数据是异步回调的，由于服务器性能限制，需要大概两秒才能取得结果，跟这有关系么? 是不是要在实例化vue之前完成所有的数据处理呢？

**Comment by fnlctrl** [comment]
你是给$data对象建了一个新属性，把这个数组赋过去吗？如果是这样的话必须用Object.$set()来建属性
读一下这里的警告部分：http://cn.vuejs.org/guide/list.html#遍历对象

**Comment by posva** [comment]
It really is annoying to see all that issues in chinese. The traduction isn't always reliable. Why some of you aren't making the effort? Is it because @yyx990803 is the only one that can handle the question?

PS: English isn't my native language either.

**Comment by galenyuan** [comment]
@fnlctrl 试过$set()了 也不行

**Comment by galenyuan** [comment]
@posva Sorry boss, just because Chinese is @yyx990803 and mine native language, and it will easy to known it I use Chinese to raise a issue.

EN Version:
Question: When will mustache bindings(Model - View) disabled?
Detail: App runs well in my local server with mock data, but when I run it in real server with real data, one of sections' view can not update by model, data is get from server by async, and sever response in about 2s, data has been updated but view keep on, image which attached is data I consoled, looks set and get function are missed in it.
- if I need to finish all data operate before Vue instantiation?
- I try $set() function, but it also make no effort.

Thanks

**Comment by yyx990803** [comment]
1. It's not "disabled", actually, it's probably never set up.
2. Read this section: http://cn.vuejs.org/guide/best-practices.html#数据初始化
3. Make sure to provide a reproduction (重现). Only describing the issue almost never helps.

**Comment by azamat-sharapov** [comment]
I recommend posting in 2 different language (english and chinese), if you find very hard to express yourself. 

@posva look at positive side: You have learned new word today:

重现 = reproduction

:smile:

**Comment by posva** [comment]
@azamat-sharapov you use the same word for sexual reproduction and for a reproductionL (I'm saying it aftrer looking at the single meaning of each character)

**Comment by fnlctrl** [comment]
@posva '重现' literally means recurrence in Chinese. '重' for 're-', '现' for appearance.

**Comment by posva** [comment]
It is indeed so offtopic, but kinda fun :smile:

**Comment by azamat-sharapov** [comment]
@posva I have no idea what you are saying :) but @fnlctrl has made it clear I think. Anyways, let's see 重现 for the issue!

**Comment by galenyuan** [comment]
Thanks for all of you, issue has been fixed by init data before Vue instantiation(实例化) :)
