### ISSUE TITLE
可否对unsafeEval做下兼容处理

### ISSUE THREAD

**Issue by gebilaoxiong** [yyx990803/vue#1338]
你好；
我最近在开发一款chrome插件
在devtool面板中使用了您的VUE

但是遇到一点问题
由于chrome插件环境的安全策略，在代码中无法使用new Function。
而您的代码中许多关键位置使用了new Function。
导致代码不能运行。
可否考虑做下兼容处理。
感谢

**Comment by yanxyz** [comment]
用 CSP 兼容版本测试了吗？另外可以考虑放宽扩展的 CSP 限制。

**Comment by gebilaoxiong** [comment]
无法放宽。。。这部分是限制死了的，在AngularJS中 针对CSP做了兼容处理的

**Comment by yyx990803** [comment]
http://cn.vuejs.org/guide/installation.html#CSP_兼容版本

**Comment by gebilaoxiong** [comment]
感谢作者 esprima涨姿势了

**Comment by udbmnm** [comment]
同开发插件遇到该问题，感谢你们
