### ISSUE TITLE
Proper way to let parent bind children's data?

### ISSUE THREAD

**Issue by fnlctrl** [yyx990803/vue#1339]
Consider this example:
```html
<tabs>
  <tab label="Followers" some-magic-prop-or-directive="{{ number }}">
    <followers></followers>
  </tab>
  <tab label="Messages"  some-magic-prop-or-directive="{{ number }}">
    <messages></messages>
  </tab>
</tabs>
```

that gets rendered as

```html
<tabs>
  <tabs-pagination>
      <span>Followers 123</span>   <!-- Note the numbers here -->
      <span>Messages 456</span>
  <tabs-pagination>
  <tab label="Followers">
    <followers></followers>
  </tab>
  <tab label="Messages">
    <messages></messages>
  </tab>
</tabs>
```

Now, as the `tabs` need child component's data to display the numbers, and the numbers are fetched from api (so the data should be two-way binded),
what is the proper way to get it?

Using props + callbacks needs to define a prop inside each child component,
Using directives won't get the data binded...

The only way I can think of now, is setting up watches inside each child component, that $dispatchs the new value upwards..

**Comment by OEvgeny** [comment]
According to [contribution guide](https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md) questions should be in [vuejs/Discussion](https://github.com/vuejs/Discussion/issues)

**Comment by fnlctrl** [comment]
Sorry about that.
moved [there](https://github.com/vuejs/Discussion/issues/412).
