### ISSUE TITLE
[FEATURE] Animate element on event trigger (eg: v-animate-on="data-loaded")

### ISSUE THREAD

**Issue by AlexandreBonaventure** [yyx990803/vue#1340]
Hi, 
We're already using 0.12 in production, and I have to say we're really happy with it. 

One feature which would really help us is the ability to trigger and control transition system via the event system. Right now, we're are using some hacky tricks to achieve some animations by adding and removing elements to the DOM (v-if). I was trying to implement this feature with a custom directive but I wanted to use the built-in transition system. Sadly, there's no exposed API for it (am I wrong ?). 

I would be glad to contribute with a pull request or so. Please, tell me if there is some ways to implement this, that would be really useful. 

Thank you.

**Comment by azamat-sharapov** [comment]
Can I ask you for some use case, if you don't mind? I mean usage in general. Transitions would work if element changes state.. I might be misunderstanding, but how would you trigger transition without changing element's state?

**Comment by AlexandreBonaventure** [comment]
Yes, of course. Here's a jfiddle where I'm trying to show how it can be painful to "animate" some element. Because transition system has been thought to handle leaving or entering the dom. 

http://jsfiddle.net/5sH6A/167/

Here, I'm just trying to trigger a animation in place without removing the element. Just like this page : https://daneden.github.io/animate.css/

It could be useful also for plenty of stuff like trigger a shake when form validation fail, etc...

Is it more clear now ? Thanks

**Comment by yyx990803** [comment]
The internal transition system is provided because it handles the tricky parts around inserting/removing elements together with CSS transitions. If you are not inserting/removing stuff, you should not need the internal transition system - you can trigger a CSS transition by setting the CSS style, toggling CSS classes or use an external animation library, anything you want.

Example: http://jsfiddle.net/yyx990803/5sH6A/168/

**Comment by mystrdat** [comment]
Triggering a specific animation on demand should be a feature, just like it is in `velocity-react` or similar.

**Comment by raffomania** [comment]
Maybe this could be provided with something other than `<transition>`, like a directive?
