### ISSUE TITLE
this.$$.dateinput.focus() does not trigger the native date picker on Android

### ISSUE THREAD

**Issue by hbrls** [yyx990803/vue#1341]
I think the input is focused because the focus css styles applys. But the native date picker does not show up. Click again the focused date input using finger will trigger the native date picker.

I'm not sure it's a Vue issue or not.

I will try to make a simple demo later.

**Comment by yyx990803** [comment]
As far as I know, mobile OS disallows programmatically triggering input behaviors (e.g. raise keyboard, trigger date picker...) - it only works if **the user triggered the input**. There's nothing Vue can do about this.

**Comment by young-steveo** [comment]
@yyx990803 That's true on iOS, but not Android.
