### ISSUE TITLE
feature request: provide `add_space` attribute to `content` tag 

### ISSUE THREAD

**Issue by Centaur** [yyx990803/vue#1342]
Just a minor problem: when `content` selects multiple child tag in a component, the result html does not contain whitespace between these child tag. This is fine in most cases but not for buttons. If there is no whitespace between 2 button tags, there will be no space between the buttons on the page. We can add an extra attribute to `content` tag to solve this:

```html
<content selector=".buttons" add_space="true"/>
```

**Comment by OEvgeny** [comment]
Why can't you use styles to do it? http://jsfiddle.net/drL8tz05/

**Comment by yyx990803** [comment]
It's not good practice to rely on the default whitespace. Use CSS instead.
