### ISSUE TITLE
在 v-style 中使用 background-image 产生的 404 问题 

### ISSUE THREAD

**Issue by banrikun** [yyx990803/vue#1343]
可能是我使用姿势不正确，求指点，谢谢。

HTML:
``
<a class="wxm-i-avt" v-style="background-image: 'url(' + userAvatar + ')'"></a>
``

如果后端输出空数据，则 `userAvatar` 为 `undefined`，控制台会出现：
``
http://127.0.0.1:666/undefined 404 (Not Found)
``

在插入 `<img>` 标签时，可以使用 `v-attr` 解决，但是在插入背景图片时，请问有什么方法可以避免这个问题呢？

**Comment by yyx990803** [comment]
如果你知道 `userAvatar` 可能为空，那你需要自己做这个检查：

``` html
<a v-style="backgroundImage: userAvatar ? 'url(' + userAvatar + ')' : ''"></a>
```
