### ISSUE TITLE
联动的select选项更新失效

### ISSUE THREAD

**Issue by xor3** [yyx990803/vue#1344]
以下场景：
```
<select v-model="provinceId" options="optionsProvinces"></select>
<p>{{provinceId}}</p>
 <select v-model="cityId" options="optionsCities  "></select>
```
两个联动的select选项省和市，市的选项optionsCites根据选中的provinceId获取（在watch中), 先选择省再选择城市是OK的，但是当选择了市以后重新更改省，“省”更改了选项，但<p>{{provinceId}}未更新，猜测是异步更新的问题，但不理解的这应该是基本的DOM绑定不应该出问题的，故在此提出。

**Comment by xor3** [comment]
突然想到设置　Vue.config.async = false，结果 {{provinceId}}更新了。
感觉异步模式 下的select 还是有问题，继续研究。

**Comment by yyx990803** [comment]
请用 jsfiddle 给个重现.

**Comment by allanfreitas** [comment]
@yyx990803 can you put a rule for english only here on github?

**Comment by yyx990803** [comment]
@allanfreitas it's recommended to use English here, but I wouldn't make it required. Some Chinese users don't feel comfortable or simply can't accurately describe the issue in English.

**Comment by yyx990803** [comment]
Closing (inactivity)

**Comment by wangxuesong29** [comment]
@allanfreitas This is quite arrogant and ignorant to say "put a rule of English only". Non-English speakers should be able to question too.

**Comment by posva** [comment]
hey @wangxuesong29 this issue was closed almost 4 years ago, there is no need to call out someone in that situation, they may have also changed their mind in the meantime and this could create a discussion on an inactive and closed issue. Thanks!
