### ISSUE TITLE
type check should not fail for String prop just because it looks like a number 

### ISSUE THREAD

**Issue by Centaur** [yyx990803/vue#1345]
http://jsfiddle.net/pxkdo9td/

Set value `.00` as a String prop should success, current behavior is a throwing a warning and prop gets `undefined` value:

```
[Vue warn]: Invalid prop: type check failed for strProp=".00". Expected String, got Number.
```

**Comment by yyx990803** [comment]
Yeah, this is a known issue with auto-casting of the current prop syntax, but it will no longer be the case in 1.0 when using the new prop syntax.
