### ISSUE TITLE
关于计算属性缓存生效

### ISSUE THREAD

**Issue by byr-gdp** [yyx990803/vue#1348]
在vue教程[计算属性部分](http://cn.vuejs.org/guide/computed.html)，我试着尝试了**计算属性缓存**，但结果是无论`cache`取值如何，`{{example}}`都只会在`msg`改变时才更新。不会因为`Date.now()`变化而变化。
是我对文档的理解有偏差吗？

**Comment by ppq1991** [comment]
是这样的，注意文档中:

> 然而，要注意这只发生在 JavaScript 程序内部访问的时候，数据绑定还是依赖驱动的。当你在模板中绑定一个 {{example}} 的计算属性时，DOM 只会在反应式依赖改变时才会更新。
