### ISSUE TITLE
关于绑定表达式作用及表现

### ISSUE THREAD

**Issue by byr-gdp** [yyx990803/vue#1351]
重现地址：https://jsfiddle.net/p7vjf4ak/

[教程](http://cn.vuejs.org/guide/forms.html)中关于绑定表达式部分的讲述没有让我理解其作用是什么。

尝试了下加入`true-exp` `false-exp`以及`exp`，但我不知道这些值如何才能正确输出，通过`{{...}}`形式还是其他方式呢？

同时，在加入`true-exp` `false-exp`以及`exp`后，与未加入相比，甚至连正常的`{{...}}`会没有输出。

可能表述不是那么清楚，重现地址多点击几次也许可以发现。

:)

**Comment by yyx990803** [comment]
https://jsfiddle.net/p7vjf4ak/1/

另外，请不要在这里发问题，这里的 issue 只处理 bug 和 feature request。问题请发到[论坛](forum.vuejs.org)去。尽量用英文，如果实在不想用英文，发到中文子版块。

**Comment by byr-gdp** [comment]
Thanks anyway.
I will share my problem in the right place later while  using English to the best of my ability.

By the way, the forum url you mentioned above is not correct, <http://forum.vuejs.org/> may be right.

Thanks for solving my problem... :)
