### ISSUE TITLE
Select2 - Updating list of options

### ISSUE THREAD

**Issue by SERVANT14** [yyx990803/vue#1352]
I love that you have an example directive that helps with integration between Select2 and Vue. I have a set of four dropdowns that are dependent on each other.

So, each time one dropdown changes, the list of available options in the succeeding dropdowns are affected. With this implementation, the options in the dropdown can never change.

http://jsfiddle.net/zuc27nw9/23/

Is this possible with Select2 and Vue?

**Comment by yyx990803** [comment]
Please move questions to the forum: https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines

**Comment by SERVANT14** [comment]
Sorry. I'm new.

**Comment by thelinuxlich** [comment]
See a workaround http://jsfiddle.net/zuc27nw9/21/

**Comment by SERVANT14** [comment]
Thanks so much @thelinuxlich. I went with this. Not sure if it's a proper approach, but it works so far:

```javascript
this.vm.$watch(optionsExpression, function (newValue) {
                $(self.el).empty();
                $(self.el).select2({
                    data: newValue
                })
            });
```

**Comment by thelinuxlich** [comment]
glad it worked :)

**Comment by SERVANT14** [comment]
Doesn't work with filters, however :(

http://jsfiddle.net/zuc27nw9/26/

**Comment by thelinuxlich** [comment]
Yeah, I suggest you use a computed property

**Comment by SERVANT14** [comment]
Thanks! Works great!
