### ISSUE TITLE
check for current value in object

### ISSUE THREAD

**Issue by foxdust** [yyx990803/vue#1353]
I have an object and I would like to trigger a function depending the status of each person. How can I get the value 'status' of each?

new Vue({
      el: '#foo',
      data: {
        foo: {
          person1: {
            name: 'Jane',
            status: true
          },
          person2: {
            name: 'John',
            status: false
          }
        }
      }
  });

**Comment by yyx990803** [comment]
https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines
