### ISSUE TITLE
Keep inherit: true in component options?

### ISSUE THREAD

**Issue by fnlctrl** [yyx990803/vue#1354]
[The inherit option has been deprecated. Alway pass data to child components via props.](https://github.com/yyx990803/vue/releases/tag/1.0.0-beta.1)

consider this use case:
```html
<tabs>
  <tab label="foo">
    {{ someParentData }}
    <foo></foo>
  </tab>
  <tab label="bar">
    {{ someParentData }}
    <bar></bar>
  </tab>
</tabs>
```
Since it's impossible to know in advance what data will be used in `tabs` and `tab`, nothing can be pre-defined in `props`, so `inherit: true` seems the only solution.

**Comment by yyx990803** [comment]
Where do you expect `someParentData` to be? In your use case `{{ someParentData }}` will be evaluated in the top-most scope and it should just work.

**Comment by fnlctrl** [comment]
Yes, I have misunderstood the scoping rules.
Everything is working fine now without `inherit: true`.
Thanks!
