### ISSUE TITLE
"factory is not a function" while registering component inline via options.components with browserify

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [yyx990803/vue#1361]
I have tried to compile the browserify example with the current 1.0 beta and it was unable to register components inline.

That was a quick fix:
vuejs/vue-browserify-example#2 

But I assume this is not wanted behaviour.

**Comment by yyx990803** [comment]
Thanks for noting, these examples will be updated accordingly before 1.0 is out of beta.
