### ISSUE TITLE
migrate from `v-repeat` to `v-for` while using partial inside the loop

### ISSUE THREAD

**Issue by vprimachenko** [yyx990803/vue#1363]
I have trouble migrating following code to `Vue 1.0`. I use `1.0.0-alpha.6` as a migration path.
```html
<label v-repeat="param in params">
	{{$key}} : <partial :name="'editor-'+param.type"></partial>
</label>
```
Vue setup
```javascript
new Vue({
	el: 'body',
	data: {
		params: {
			paramA : {
				type: 'number',
				value: 42
			}
		},
	},
	partials: {
		'editor-number': '<input v-model="param.value" type="number">'
	}
})
```
as the [`v-for` version](http://jsfiddle.net/jj3rgvh3/) throws warnings and an error i believe this to be a bug

**Comment by vprimachenko** [comment]
sorry to necro, but it seems the issue is deeper. c.f.:
```html
<div v-repeat="collection in document">editor for {{$key}}<br>
	<template v-for="input_type in schema[collection.type]">
		<partial :name="'editor-'+input_type"></partial>
	</template>
</div>
<div v-for="collection in document">editor for {{$key}}<br>
	<template v-for="input_type in schema[collection.type]">
		<partial :name="'editor-'+input_type"></partial>
	</template>
</div>
```
```javascript
window.demo = new Vue({
	el: 'body',
	data: {
		document: {
			'collection#1': {
				"type": 'test_collection',
			}
		},
		schema : {
			test_collection: {
				"foo":"number",
			}
		}
	},
	partials: {
		'editor-number': '<input v-model="collection[$key].value" type="number"> {{collection | json}}'
	}
})
```
when outer loop is changed to `v-for` the inputs lose their value on blur

**Comment by yyx990803** [comment]
That's actually a separate issue, opening a new one in #1370.

**Comment by chenjie-cnooc** [comment]
can i use ionic components in vuejs? such as collection-repeat and mobile ui

**Comment by simplesmiler** [comment]
@chenjie-cnooc I don't see how this is related to the topic, but no. Ionic depends on angular, and angular component directives are not compatible with vue and will require almost complete rewrite. The only thing you can reuse from ionic is CSS.
