### ISSUE TITLE
v-repeat underscore

### ISSUE THREAD

**Issue by midan888** [yyx990803/vue#1365]
Hi. I got on this issue today, I don't know if this is a bug or not, check this out.
I am fetching data from mongodb, the data object has this list of resources
each resource item is mongo document.
When I use this way of showing data `v-repeat="resources"`,  "_id" doesn't work, its just undefined.
But when I use `v-repeat="resource : resources"` and then `resource._id` it works.
I think its some kind of connected to underscore.
```
    <div v-repeat="resources" class="list-group-item row">
        <div class="col-md-10">
            <span>{{_id}}</span>
			<span class="label label-primary">{{method}}</span>
			<span class="label label-info">{{url}}</span>
		</div>
		<div class="col-md-2">
			<button v-on="click: removeResource(_id)" class="btn btn-xs btn-danger pull-right" aria-hidden="true">Remove</button>
		</div>
	</div>
```

**Comment by yyx990803** [comment]
Properties that start with underscore are not proxied on the vm instance because they may conflict with Vue's internal private properties. You can access it in the template as `$data._id`.

**Comment by midan888** [comment]
Got it. Thanks for reply. 
Good luck with the v.1.0.0 release
