### ISSUE TITLE
Vue+Webpack, how to reference global Vue in a component

### ISSUE THREAD

**Issue by Honghe** [yyx990803/vue#1366]
Enviroment:
* Project is cloning from https://github.com/vuejs/vue-webpack-example

Just as `index.js` in module `b` https://github.com/vuejs/vue-webpack-example/blob/master/src/views/a/index.js 
How to refrence global `Vue` object in this module
Thanks!
```
module.exports = {
  template: require('./template.html'),
  replace: true,
  data: function () {
    return {
      msg: 'This is page A.',
      leftName: 'Bruce Lee',
      rightName: 'Chuck Norris'
    }
  },
  components: {
    'app-header': require('../../components/header'),
    'app-pane': require('../../components/pane')
  }
}
```

**Comment by finico** [comment]
```js
var Vue = require('vue');
```

**Comment by Honghe** [comment]
@finico `var Vue = require('vue');` has been required in main.js (https://github.com/vuejs/vue-webpack-example/blob/master/src/main.js ).
Doing this several time, is it ok?
Some package such as `Echarts` can only be init once.

**Comment by simplesmiler** [comment]
@Honghe It's totally ok. Webpack does not inline `require` calls, so you can `require` module anywhere you need it, it will only be instantiated once.

**Comment by Honghe** [comment]
@simplesmiler Thank you!
But one more question, `webpack` use `__webpack_require__` to replace `require` when packs our code, but I can't find the definition of `__webpack_require__`, where is it?

**Comment by simplesmiler** [comment]
@Honghe I don't think I can answer that, it really depends on how this is implemented by webpack.
