### ISSUE TITLE
filterBy is not working with v-for

### ISSUE THREAD

**Issue by gjuchault** [yyx990803/vue#1367]
Hi.

I'm upgrading to the newest vuejs version which introduces `v-for`. I'm switching from this markup http://pastebin.com/0dZc7SiQ to this markup http://pastebin.com/xu44nsn4

I have the following error : http://imgur.com/CiXHyFV
Data looks like this : http://pastebin.com/BpiuzJig

Fact is; if I remove `filterBy` and `trackBy`, every thing is working (but not filtered).
`parsePath` is called once with `"categories[$index]"` and once with `undefined` which triggers the error. What's the mistake here ?

Thanks

**Comment by yyx990803** [comment]
Could you please put everything in a single reproduction next time? Use http://jsfiddle.net/
That would make it much easier for me to debug it.

**Comment by yyx990803** [comment]
You original usage with `v-repeat` was wrong:

``` html
<template v-for="category in categories">
    <div id="tab-{{ $index }}">
        <template v-for="article in articles | filterBy category in 'category.name'" track-by="id">
            ... {{ article.id }} ...
        </template>
    </div>
  </template>
```

Note the quotes around `category.name`: that makes it a path to search in (aka searching in `article.category.name`. Your original code is evaluating `category.name` as an expression which results in `undefined`.

Also you can just filter by `category` instead of `categories[$index]`.

**Comment by Sameerkashmirbox** [comment]
<li v-for="employee in Employees | filterBy search in'name'" class="list-group-items">

**Comment by Sameerkashmirbox** [comment]
<li v-for="employee in Employees | filterBy search in'name'" class="list-group-items">
