### ISSUE TITLE
How to pass partials/components now that strict mode is the default?

### ISSUE THREAD

**Issue by JoshZA** [yyx990803/vue#1371]
I have a generic grid that I pass partials/components to, for rendering custom column content/markup

In the past I could just reference the component located in the parent by name, but with strict mode I can't anymore

Parent:

```
        data: function () {
            return {
                gridColumns: [ // grid column definitions 
                    {
                        name: 'Name',
                        part: this.$options.partials.test,
                    }
            }
        },
        partials: {
            'test': 'partial here!'
        },



<grid :columns="gridColumns">
```

In the child grid:

```
        <td v-for="col in columns">
                <partial v-if="col.part" :name="col.part"></partial>
```

Sadly this fails, any idea how I can dynamically pass in components/partials?

VueJs 1.0.0-alpha.6

I could probably call vm.$interpolate for the 'partials' but that will likely be quite slow

**Comment by yyx990803** [comment]
Use content insertion?

**Comment by yyx990803** [comment]
BTW, please submit questions to the [forum](http://forum.vuejs.org). The issues here are for bugs only.

**Comment by simplesmiler** [comment]
I was asking something related when non-strict mode was deprecated: https://github.com/yyx990803/vue/issues/1170#issuecomment-133065007

I guess the right way to do this now is to generate the component if it is first party, or extend and override its assets if it is third party.

``` js
var Grid = require('grid'); // @NOTE: third party component

// @NOTE: first party component
function gridFactory(partials) {
  return {
    template: ...,
    partials: {
      cell: partials.cell
    },
  },
}

var cell = '...'; // @NOTE: partial

new Vue({
  el: ...,
  components: {
    GridOne: gridFactory({ 
      cell: cell,
    }),
    GridTwo: Grid.extend({
      partials: {
        cell: cell,
      },
    }),
  },
});
```

I think it worth discussing on the forum.

**Comment by JoshZA** [comment]
I just tried implementing this with content insertion, sadly being unable to access local scope is a deal breaker.

I'll try your way now @simplesmiler thanks =)
