### ISSUE TITLE
How to get clean Data form vue

### ISSUE THREAD

**Issue by GloriaCHL** [yyx990803/vue#1373]
I get data from server and put it into a vm, The data will get some get/set methods inset. I want to get a clean data, how can I do? I use Vue.filter('json')(****) but it get an error.

**Comment by yyx990803** [comment]
Please post questions to the [forum](http://forum.vuejs.org).

Just do `JSON.parse(JSON.stringify(...))`.

**Comment by furey** [comment]
@yyx990803 

Any plans on adding a utility method or something similar to access said "clean data"?

E.g.

vm.data(); // or...
vm.$data.data(); // or...
vm.nested.object.data(); // etc

Or maybe add a note to the http://vuejs.org/api/#data section of the API documentaion? 

Just spent an hour trying to source how to do so before stumbling across this issue (was trying to lodash _.pluck specific values of a nested vm data object to post via AJAX).

**Comment by yyx990803** [comment]
@furey I think `JSON.parse(JSON.stringify())` is simple enough, no need for an extra API method. Feel free to send a PR to the docs!

**Comment by furey** [comment]
@yyx990803 

Not sure on the prose/terminology, but... done!

https://github.com/vuejs/vuejs.org/pull/171

**Comment by finico** [comment]
keep in mind that in this case the date turns into a string
```JSON.parse(JSON.stringify(new Date())) 
> Date String in the UTC
```
in such cases it would be better to use deep cloning
