### ISSUE TITLE
component does not access to it's methods when I use content insertion

### ISSUE THREAD

**Issue by alioygur** [yyx990803/vue#1375]
there is my component.

index.js

```
module.exports = {
  inherit: true,
  template: require('./template.html'),
  data: function(){
    return {};
  },
  methods:{
    choseImage: function() {
      console.log("chose image");
    },
    readImage: function() {
      console.log("read image");
    }
  }
};
```
template.html
```
<input type="file" name="file" style="position:absolute; left: -9999px;" v-on="change: readImage">
<content></content>
```

I am using it like this.

```
<file-upload-c>
  <a class="image-box m-center" v-on="click:choseImage">
    <p>
      <i class="material-icons">add</i>
    </p>
    <p>
      Add Photo
    </p>
  </a>
</file-upload-c>
```

I am getting this error.

    [Vue warn]: Directive v-on="click: choseImage" expects a function value, got undefined

is this a bug ?

**Comment by karevn** [comment]
It's by design. The template passed via `<content></content>` is evaluated in a different context (parent Vue instance's context) and does not see `chooseImage`.

**Comment by dennisver** [comment]
What if you try chooseImage() instead of chooseImage?
`<a class="image-box m-center" v-on="click:choseImage()">`

**Comment by yyx990803** [comment]
This is by design. See http://vuejs.org/guide/best-practices.html#Component_Scope

**Comment by alioygur** [comment]
@yyx990803 can I pass parameters to slot from parent ?

**Comment by yyx990803** [comment]
@alioygur what do you mean? Can you give an example?
