### ISSUE TITLE
Vue 1.0beta2: events $emitted should get listeners from events property 

### ISSUE THREAD

**Issue by thelinuxlich** [yyx990803/vue#1376]
When $emitting, listeners don't work if they are declared inside events property of component.

**Comment by yyx990803** [comment]
Repro? Note that `$emit` only triggers event listeners on the instance itself.

**Comment by AlexandreBonaventure** [comment]
I stumble upon the same problem. It happens when you have a sub-child.
Here is a repro with the 1.0.alpha-7 :
the bug -->   http://jsfiddle.net/hdpgrxp4/1/
when you return true in all instances it works ! -->   http://jsfiddle.net/hdpgrxp4/3/

**Comment by thelinuxlich** [comment]
What should we use to trigger events to siblings?

**Comment by posva** [comment]
@thelinuxlich I thougt that should be done with a mutual parent that handle the event and a prop on the sibling.
I am interested on any other ways of doing this

**Comment by thelinuxlich** [comment]
So a sibling $dispatches, parent gets the message and $broadcasts another message so another sibling gets it? Too much ping-pong, don't you think?

**Comment by posva** [comment]
@thelinuxlich I wasn't thinking about another message but more about a prop on the sibling

I thought props were for communicating down while events were made to communicate up. @yyx990803 can you please confirm that?

**Comment by rpkilby** [comment]
@posva - it seems to be a recommendation. From section 6 in the wiki's 1.0.0 binding syntax [reference](https://github.com/yyx990803/vue/wiki/1.0.0-binding-syntax-reference#v-on-on-child-component):

> v-on will also listen to custom Vue events (emitted via vm.$emit) when it is used on a child component.  The idea is that props and events should constitute the public API of a component:
> - props for passing data down;
> - events for handling actions up.

**Comment by posva** [comment]
yeah, that's what I read :smile:

**Comment by yyx990803** [comment]
Turns out this was fixed in beta and I forgot to backport it in alpha. Fixed: b8b87f7
