### ISSUE TITLE
Refreshing the page doesn't call dispatch

### ISSUE THREAD

**Issue by bkintanar** [yyx990803/vue#1379]
When refreshing a page in the browser, I'm not sure which doesn't fire, the `this.$dispatch` in the child or the `this.$on()` in the parent.

**Comment by yyx990803** [comment]
Please provide a reproduction.

**Comment by bkintanar** [comment]
Sorry. I'm new to fiddle. Here it is.

http://jsfiddle.net/368yjxsk/

Maybe I'm doing it wrong. If so, I'm so sorry.

**Comment by dennisver** [comment]
You can listen to the event in the created hook, instead of the ready hook.

**Comment by bkintanar** [comment]
created hook doesn't catch it either.

**Comment by dennisver** [comment]
http://jsfiddle.net/dennisver/368yjxsk/3/

**Comment by bkintanar** [comment]
@dennisver this fixes the issue.. thank you!
