### ISSUE TITLE
Suggestion: automatically bind props default value functions to current vm

### ISSUE THREAD

**Issue by OEvgeny** [yyx990803/vue#1382]
Sometimes we need to set objects/arrays as default values of property in ``props``. In these cases we need to specify a function that will return default value ([docs link](http://vuejs.org/guide/components.html#Prop_Specification)). 

My suggestion is to automatically bind this kind of functions to current vm. So we can get access to vm context.

Now there are in global context:
```js
props: {
  myProp: {
    type: Object,
    default: function () {
      console.log(this) // Window
      return {}
    }
  }
}
```

**Comment by yyx990803** [comment]
This is easy to implement, although I'm curious what particular use case do you have for it?

**Comment by OEvgeny** [comment]
I came across this trying to migrate to 1.0. Since ``props`` are separated from ``data`` now. I can't implement  logic that was in ``data`` function before. So, seems ``props`` default values are not so flexible as ``data`` for now.

In my case components can get some default values from local cache. Cache service is available in vm.

**Comment by yyx990803** [comment]
I see, thanks for the explanation!

**Comment by OEvgeny** [comment]
Thanks a lot, Evan!
