### ISSUE TITLE
Object.prototype.$set breaking meteor

### ISSUE THREAD

**Issue by tim-smart** [yyx990803/vue#1385]
Just a heads up, by setting `$set` as an Object prototype method we are breaking usage with meteor.

Meteor uses `$set` as a Mongo DB update property and sometimes checks for existence like so:

```js
if (modifier.$set) ...
```

Which will always be true with vue.js loaded, as it is set on the prototype.

**Comment by yyx990803** [comment]
Yeah, I'm aware of this. When 1.0.0 is out Vue will no longer modify `Object.prototype`.
