### ISSUE TITLE
$addChild + inline-template, works only once

### ISSUE THREAD

**Issue by PavelPolyakov** [yyx990803/vue#1386]
Hi,

As I think this is not an expected behaviour, I have decided to fire a bug.

**Description:**
1. Placing the new html into the DOM
2. Creating the new component instance using $addChild, on the fly. The component template is inline-one.
3. Component is rendered correctly only the first time
4. **important** if the component template is not "inline", everything is ok: http://jsbin.com/pojiwepite/edit?html,js,console,output

**Reproduction:**
http://jsbin.com/guhogufaqe/1/edit?html,js,console,output

(clicking any button will place a proper component, but only once. all the following attempts would lead to the unexpected behaviour)

Regards,

**Comment by yyx990803** [comment]
Why are you doing it like this anyway?... it is much more straightforward to use a `v-repeat` or `v-for` and push items into an array. You should try to make your interface data-driven whenever possible and avoid relying on imperative, ad-hoc manipulations.

**Comment by PavelPolyakov** [comment]
I do it, because I use Vue with Google Maps API.
There is an infowindow concept, the window which appears when you click the marker on the map:
https://developers.google.com/maps/documentation/javascript/3.exp/reference#InfoWindow

These windows are dynamically added to the dom, Google Maps API informs us that window is there with the help of *domready* event. I want, then to attach the Vue component to the newly appeared window.
Why I should use inline template? Because the other way, if template is provided inside the component, I would meet the glitch - https://monosnap.com/file/33PTab9UJVRfDvRYyPeKzd8SMyc0fl .

I have tried the other variants to get rid of the glitch ( http://forum.vuejs.org/topic/31/attaching-vue-js-to-infowindow-content-google-maps-api/13 ), but inline template was the solution.

I don't see any option to put ```v-repeat``` and ```v-for``` here.

**Comment by yyx990803** [comment]
There's no need for the `inline-template` at all. It could be much simpler:
http://jsbin.com/babotifowu/2/edit?html,js,console,output

**Comment by PavelPolyakov** [comment]
@yyx990803 

Please, do not close the issue. I respect your work much, but this is a bug, not a feature.
Your solution does not cover the topic. I was aware before, that without inline templates it works perfectly.

As I said - I need to use inline template, because otherwise I have a glitch during rendering https://monosnap.com/file/33PTab9UJVRfDvRYyPeKzd8SMyc0fl (video). Google Maps API dictates the rules, not my will.  It places the html to the DOM, if I apply the template afterwards, I will see the text falling out from the infowindow during rendering.

I use methods of the framework from the documentation, they don't work, I want to help to create framework better, tried several variants, narrowed down an issue and came up with the reproduction of it. Why the issue is simply closed? 

I completely understand, that I can't require anything, as framework is opensource, but I can expect that the real issue would be investigated, when you have free time. Please, reopen the issue.

**Comment by yyx990803** [comment]
Your reproduction is misusing the `el` option. You cannot return a selector in the `el` option - you must return a real element. When returning a selector, it always selects the first `<info-window>` element, which is already compiled. That's not a bug in the framework.

**Comment by PavelPolyakov** [comment]
@yyx990803 

Thanks, that makes more sense for my case. 

Last question, can we somehow pass a variable to the object, which would be visible inside the ```el``` method? I have tried to do that through ```props``` but they are not yet available during the call of ```el```. Can we somehow put some dynamic inside the ```el``` function?

It would allow me to do something like this:
```javascript
el: function(i) {
    return '#object-'+i;
}
```

Why I don't do:
```javascript
self.$addChild({el: function() { return `#object-info-${object.id}`;}}, Vue.extend(require('./object-info.vue')))
```

Because, when I do that, the rendering works fine, but, for some reason, any change of the objects which is done inside the newly created objects does not affect the other application. I haven't managed to reproduce it in short.

Regards,

**Comment by BigBlueHat** [comment]
@PavelPolyakov did you ever sort this out--the issue with an $addChild generated component sharing data with an earlier created $addChild?

I'm trying to add modal's via $addChild ('cause I can't figure out how to do it with markup...), and I'm experiencing the same thing.

Certainly there's a more appropriate way to do this...I just can't seem to find it. :frowning:

**Comment by BigBlueHat** [comment]
Ah...looks like you did sort it out...
http://forum.vuejs.org/topic/31/attaching-vue-js-to-infowindow-content-google-maps-api/15

Not quite my issue, though, it seems.

/me keeps hunting. :telescope:

**Comment by BigBlueHat** [comment]
Found it!!:exclamation: :stuck_out_tongue_winking_eye: 

Seems I was passing the construction options in as the only parameter...vs. `this.$addChild({}, Vue.extend({data: function() {...}}))` etc.

Magically, it all works...

/me left this here for posterity.
:tophat:

**Comment by PavelPolyakov** [comment]
@BigBlueHat 

Can you, please, paste a rich code part? Haven't understood your solution from the comment above. Would be interesting to check it.

Regards,

**Comment by BigBlueHat** [comment]
@PavelPolyakov, I think we were dealing with different issues. However, here's the basic difference:

```js
var component_def = {
  template: '<input v-model="name" />',
  data: function() {
    return {
      name: ''
    };
  }
};

var app = Vue({
  methods: {
    addComponent: function() {
      // I was doing this...
      this.$addChild(component_def);

     // now I'm doing this...
     this.$addChild({data: {name: "BigBlueHat"}}), component_def);
    }
  }
});
```

What seemed to be happening then is that I was only ever adding the same, fully formed child component--rather than an extended component based on the first `options` parameter.

Since `options` and a non-function-based component definition look identical to Vue, it didn't know or care that I was (mis)using `$addChild`...but now I do, so I fixed it. :smile:
