### ISSUE TITLE
v-repeat over an array of strings should not reuse child component for changed value

### ISSUE THREAD

**Issue by taras-puchko** [yyx990803/vue#1387]
Please see http://jsfiddle.net/5sH6A/174/ and press "Click me"

**Comment by posva** [comment]
Can you be more specific about the issue, please ? I don't understand what you're expecting

**Comment by taras-puchko** [comment]
I expect that once a component has been created for a specific ID that ID does not change in the data model for that component.
If I iterate over objects having ID property I can achieve that using track-by="id", and even without track-by components are never reused for new objects in a collection. But iterating over string array is different, which looks like a bug.

**Comment by yyx990803** [comment]
`v-repeat` over primitive values always reuse the instances - it's like `track-by="$index"` by default. You should **always use objects** if you expect position-tracking or full re-rendering.

**Comment by taras-puchko** [comment]
But why? If it makes sense to keep an object and component bound with track-by="id" or use full re-rendering for objects, it is also reasonable to keep my ID bound to a component too or use full re-rendering.
My use case is the following. I iterate over IDs of objects and want to load the object from DB in "created". Instead now I'm forced to "watch" over ID and reinitialize my component whenever ID changes. If my initialization logic contain multiple steps the component might appear in some unexpected intermediate states.

**Comment by yyx990803** [comment]
Because primitive values do not have unique identities. If an array contains two duplicate primitive values there is no reliable way to know which component should correspond to which.

Also, iterating over IDs and then load the object inside components sounds very inefficient, because you'd have 1 HTTP request for every single item. A better way to approach this is fetch all objects first, then iterate over the actual data.

**Comment by taras-puchko** [comment]
I haven't thought about duplicates before, but an array of objects can also have the same object at several positions so it's not fundamentally different from primitives, you already handle it in some way. Duplicate primitives may occur more often than duplicate objects in some scenarios but it's not my case. So I understand the defaults, but what about a flag like track-by-identity?

I can iterate over objects, but efficiency is also not an issue here since I have a cache. And because I have to load related objects in every component I wonder why not put all loading logic into component initialization including loading of "root" object.

**Comment by yyx990803** [comment]
It would actually warn you if a `v-repeat` array contains duplicate objects. But I agree that using default behavior based on value types can be confusing. In 1.0 `v-for` will use the same caching mechanism, and raise a warning prompting for `track-by="$index"` if duplicate values are found.

If you are stuck with 0.12, you still have to `watch` the id for proper data reload.
