### ISSUE TITLE
Time tag considered as custom element

### ISSUE THREAD

**Issue by kamui545** [yyx990803/vue#1389]
Hello,

It seems the ```<time>``` tag is considered as a custom element by VueJS.

I keep getting the following warning on 1.0.0 alpha and beta:

```
[Vue warn]: Unknown custom element: <time> - did you register the component correctly? 
```

**Comment by yyx990803** [comment]
Vue is using `element.toString()` to check if the browser returns `[object HTMLUnknownElement]`. Looks like this is a bug in Chrome where valid HTML5 elements `<time>`, `<data>`, `<rb>` and `<rtc>` return unknown instead of `[object HTMLElement]`.

I have filed a bug for Chrome, you can ignore this warning for now. Also the warning will not show up if you use the production build.

**Comment by yyx990803** [comment]
So chrome team considers it a WontFix at the moment: https://code.google.com/p/chromium/issues/detail?id=540526

I've added an extra rule to exclude the affected elements from the check: 13e0335

**Comment by kamui545** [comment]
Oh, this is a Chrome issue, my bad.
Thanks for the patch and the heads-up about the production build, didn't notice it :+1:

**Comment by NoelDavies** [comment]
This very same thing happens with the details tag as of vue 1.0.24

**Comment by Gangwolf** [comment]
Same thing happening with `<details>` and `<summary>` tags on Firefox.

**Comment by yyx990803** [comment]
@Gangwolf should be addressed in 63dbc1ca10d1663cb379ca7bd255d0ae3e836673

**Comment by ibrahim-brumate** [comment]
tag h7 return same problem in firefox using versions 2.2.4

**Comment by john-cheesman** [comment]
Just got this in Chrome for `<navigation>`, is it still an issue?

**Comment by posva** [comment]
no, it shouldn't, if you still have the issue you should open an issue with a repro so we can take a look

**Comment by LinusBorg** [comment]
`<navigation>` is an HTML5 element?

**Comment by posva** [comment]
You're right @LinusBorg , I thought he was getting an error with `time` 😅

**Comment by john-cheesman** [comment]
Sorry, the HTML5 tag is <nav>. Clearly I've spent too much time writing JS and I'm now forgetting HTML. On 13 Jun 2017 15:27, Eduardo San Martin Morote <notifications@github.com> wrote:no, it shouldn't, if you still have the issue you should open an issue with a repro so we can take a look
