### ISSUE TITLE
Loading spinner before loading image

### ISSUE THREAD

**Issue by mocheaz** [yyx990803/vue#1390]
I have a sildeshow build with v-repeat

```
<div v-repeat="pic in pictures">
    <img src="/img/loading.gif">
</div>
```

I want to show spinner before the image is loaded in the browser memory and show the image afterwards.

Any ideas?

**Comment by arrilot** [comment]
You should ask on the forum
https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines
