### ISSUE TITLE
1.0 binding syntax issue update for partial element

### ISSUE THREAD

**Issue by wprater** [yyx990803/vue#1391]
https://github.com/yyx990803/vue/issues/1325

the `partial` directive element expects an attribute `name` not the special binding syntax.  not sure what you're expecting, but the issue states it incorrect.  a static partial check for the `name` with `var id = el.getAttribute('name')`.

**Comment by yyx990803** [comment]
It has to do with how attribute interpolation (mustaches inside attributes) works - in 1.0 it is only allowed inside native attributes. `name` on partial is a Vue-specific attribute, and it must use `v-bind` for reactive binding.

**Comment by wprater** [comment]
yeah, I understand that, but that issues has a section for `shorthands`, and it's not correct?

```
<!-- special attributes -->
<component :is="view"></component>
<partial :name="partialName"></partial>
```

**Comment by yyx990803** [comment]
What's wrong with the shorthands?

**Comment by wprater** [comment]
sorry, should have been more clear.  the shorthand syntax will not work with [getAttribute](https://github.com/yyx990803/vue/blob/1.0.0-beta/src/directives/element/partial.js#L14)

https://jsfiddle.net/wprater/qvn7582L/1/

**Comment by yyx990803** [comment]
It first checks for a static `name`, and if that doesn't exist it will then checks for the dynamic one: https://github.com/yyx990803/vue/blob/1.0.0-beta/src/directives/element/partial.js#L19

**Comment by yyx990803** [comment]
The dynamic one expects **an expression which evaluates to a partial id**. The static one expects a literal partial id.
