### ISSUE TITLE
1.0 update issue

### ISSUE THREAD

**Issue by ije** [yyx990803/vue#1392]
I am try to update  to vue 1.0, and an error throws.
According to the release note, I loaded the alpha.7 vue and I changed the template syntax of my project, but still thorw an error.. I don't know what happened.

<img width="512" alt="screen shot 2015-10-07 at 15 46 58" src="https://cloud.githubusercontent.com/assets/2883484/10331791/c0eb34b6-6d0a-11e5-8426-97df93fe73ce.png">

**Comment by OEvgeny** [comment]
I think you need to use development version for migration. Also you can turn on debug mode in Vue to show warnings:
```
Vue.config.debug = true
```

**Comment by ije** [comment]
@OEvgeny thanks, it's work~
