### ISSUE TITLE
No way to escape "{{ }}"?

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#1394]
http://jsfiddle.net/s6jnskcs/3/

```html
&#123;&#123; foo &#125;&#125;
```
^ this is the exact same as this:
```html
{{ foo }}
```

How do I actually print `{{something}}` in a page?

**Comment by crswll** [comment]
I think you're looking for  [`v-pre`](http://vuejs.org/api/directives.html#v-pre).

**Comment by cheapsteak** [comment]
Ah yes indeed, thank you

**Comment by crswll** [comment]
No problem!
