### ISSUE TITLE
Helper to make a object reactive

### ISSUE THREAD

**Issue by thelinuxlich** [yyx990803/vue#1396]
For simple centralized stores

**Comment by yyx990803** [comment]
This is not really necessary, because whenever an object is passed into a Vue instance as `data` or set into an already reactive object, it also becomes reactive.

**Comment by AStaroverov** [comment]
How i can create communication storage like:
```
let store = new Vue ({
  data: {
   path: {to: {some: {data: {its: true}}}}
  }
})

let view = new Vue({
  data: {
    its: store.path.to.some.data.its
  },
  watch: {
    'its' : function(){console.log('update')}
  }
})
```

or i must use for watch 'its' some code:
```
let view = new Vue({
  watch: {
    '$root.path.to.some.data.its' : function(){console.log('update')}
  }
})
```

I think first example see some pretty or its not really?

**Comment by yyx990803** [comment]
@AStaroverov 

please read this: http://rc.vuejs.org/guide/application.html#State_Management

and this: http://rc.vuejs.org/guide/reactivity.html

I don't think you understand how reactivity works in Vue.

**Comment by AStaroverov** [comment]
thx!  it helped me
