### ISSUE TITLE
auto timeout for css transition

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#1398]
It's common that one component `comp`'s `v-show` change from `false` to `true` but its parent `parent` is still hidden. It means that if there are transition hooks on the `comp`, they won't be triggered due to no transition events fired for `comp`, even if the `parent` becomes visible later. To make the `comp` work properly, the transition should be timeout if no `transitionend` events fired after the given time.

**Comment by yyx990803** [comment]
This could be fixed with a more reliable visibility check when determining CSS transitions (see commit above)
