### ISSUE TITLE
Vue 1.0.0-beta.3 Non-required two-way binding warns if omitted.

### ISSUE THREAD

**Issue by Morgul** [yyx990803/vue#1400]
On Vue v1.0.0-beta.3, when creating a component that has a two-way binding specified, but not required, a warning is still thrown.

For example:

```javascript
var component = Vue.component({
        props: {
            show: {
                type: Boolean,
                default: false,
                twoWay: true
            }
        }
});
```
This prints the warning: "[Vue warn]: Prop "show" expects a two-way binding type."

**Comment by mark-hahn** [comment]
If it doesn't mean it is required, then what does it mean?
