### ISSUE TITLE
Is there an option to change the interpolation delimiter?

### ISSUE THREAD

**Issue by DanGamble89** [yyx990803/vue#1406]
I'm looking to use this with Django but Django already uses `{{`. Is there an option to change it to something like `{@`?

**Comment by yyx990803** [comment]
Please post questions to the forums. And yes, you can change the delimiters: http://vuejs.org/api/global-api.html#Vue-config

**Comment by DanGamble89** [comment]
Sorry, thanks for your quick response and i looked through the documentation for the config options but wasn't able to find them. That was exactly what i was looking for. Thanks again.
