### ISSUE TITLE
crash when v-for child element is manually removed from the DOM

### ISSUE THREAD

**Issue by yegor-sytnyk** [yyx990803/vue#1407]
If manually delete v-for element from JQuery and then update v-for source VUE will crash trying to remove corresponding element

Following code works with VUE 0.12.x, but not working in the latest alpha 

http://jsfiddle.net/hdpgrxp4/15/

There is no sense in removing element manually, that was legacy code, which was in separate file. Anyway maybe it worth to handle this situation.

**Comment by yyx990803** [comment]
`v-repeat`/`v-for` was never designed to work in situations like this, so I'd say this is a wont-fix.
