### ISSUE TITLE
Examples in rc.vuejs.org is using v0.12.15 rather than v1.0.0-beta.4

### ISSUE THREAD

**Issue by snarexx** [yyx990803/vue#1408]
Examples in rc.vuejs.org is using v0.12.15 library rather than v1.0.0-beta.4 library

There may have been changes in the code-base ( HTML, JS ) as well. It may need to be revised.

As one who will  start learning vuejs with v1, examples are the most important pages of the website.

**Comment by yyx990803** [comment]
Thanks, the RC site is for previewing the docs only. Examples will be updated when it's moved officially to vuejs.org.
