### ISSUE TITLE
Regarding the template property and DOM nodes

### ISSUE THREAD

**Issue by ceymard** [yyx990803/vue#1409]
TL,DR; could the .template property support using already constructed and detached dom elements for templating ?

The documentation specifies that template is a String property.

Looking at the code, I can see that it actually accepts DOM elements.

However, it also looks if it is a `<template>` or some other stuff (I didn't exactly get what and why `extractContent` did what it does).

Could it be possible to directly pass a DOM node without alteration ? (ie, without extracting its children).

I generally use jsx with a custom function that just compiles it to DOM element (along with a `/** @jsx */` pragma in babel). I would like to write stuff like :

```jsx
var mycomponent = {
  // wow ! such clean !
  template: <h1 class='{{ prop }}'>My super duper title !</h1>,
  props: ['prop']
};
```

Right now, I have to enclose everything in some element (like `div`) for this approach to work. Also, I'm not sure that the way I'm doing things will still work in future releases. :)

What are your thoughts on that matter ?

**Comment by ceymard** [comment]
Another food for thought ; what would you think of allowing template to be a function that returns new DOM elements that don't need to be cloned ?

**Comment by yyx990803** [comment]
It seems the only benefits of this approach is inline syntax highlighting for JSX? Is it possible to compile your JSX into a string instead?

**Comment by ceymard** [comment]
I can use things like

```jsx
(<div></div>).outerHTML;
```

that return a string. Of course, I lose time by creating nodes, transform them into String, and then have them parsed back to DOM nodes.

I figured that since you take a string to create DOM nodes via some parsing functions, having nodes directly supplied to `template` would skip that step (and thus gain some time).

In short, if template gets assigned some nodes, the compiler would just have to clone them.

Am I missing something in the way the compiler is working ?

**Comment by yyx990803** [comment]
That's actually what the template parser does. If it gets a direct node it
simply clones its childNodes.

**Comment by ceymard** [comment]
Yes, which is why I enclosed everything so far. I supposed it is to have `<script>` or `<template>` nodes present in the DOM to get them by id. Would it be too much hassle to change the behaviour to

- If `<script>` or `<template>` (or has a 'text/vue-template' attribute -- I don't recall the mime you use, if any), clone its childNodes
- Otherwise, clone everything.

Is there a reason you limited the cloning to the childNodes ?

**Comment by yyx990803** [comment]
It's just keeping the behavior consistent, because for both `<script>` and `<template>` it uses the inner content, excluding the outer node.

I assume you are using a babel plugin for the transpiling? Would something like this work for you? https://github.com/OpenJSX/jsx-to-html

**Comment by ceymard** [comment]
Ah, this is actually quite nice.

I think you can close this issue, as anyway I realize my request/suggestion was probably out of vue's scope.

Thank you for your time :)
