### ISSUE TITLE
How could I implement something like templateUrl in Angular?

### ISSUE THREAD

**Issue by kxxoling** [yyx990803/vue#1410]
I know it is officially suggested to use webpack or browserify to maintain components, but I want to get the GitHub pages taking effect as I push the source to GitHub without any extra building process.

If it is not supported, how can I work around with it? Is there any plan about it?

**Comment by posva** [comment]
You just can create a script in js or shell that creates a branch and add the new compiled code then push it to some branch like gh-pages. Give a look at this: https://www.npmjs.com/package/gh-pages

**Comment by kxxoling** [comment]
@posva I know how to do with auto compile, but this is hard to automatically run when I rebase, revert, or something like it. And I don't think this is elegant to maintain one more branch.

The best approach is templateUrl:

```
var Home = Vue({
  templateUrl: '/partial/home.html'
})
```

Or:

```
var Home = Vue({
  templateUrl: function(){$.get('/partial/home.html')}
})
```

**Comment by posva** [comment]
If you only want to have one branch you can keep a `dist` folder with the release. But honestly having a branch with only the release and force pushing to it isn't an issue. Furthermore the branch follows a different path and you won't have to deal with those kind of issues

**Comment by kxxoling** [comment]
I think the ``dist`` dir is the same as another branch, I don't like it.
I'm trying something with ajax, this may works in some way.

**Comment by posva** [comment]
IMHO you're complicating things to make it messier :confused: 
Having a master branch and another gh-pages branch with the release hosted on github is not messy and there is a lot of people using this technique

**Comment by kxxoling** [comment]
Um... I believe dist should not be part of git repository, I'm really hard to accept this.

**Comment by posva** [comment]
I am talking about the gh-pages. If you want to host your page in Github you **have** to deploy the content somehow. The most common way is to have a separated gh-pages branch

**Comment by posva** [comment]
If you have two branches then you don't need to have the dist folder inside of the master branch

**Comment by yyx990803** [comment]
There is no plan to support this, but you can somewhat simulate it using async components:

``` js
Vue.component('example', function (resolve) {
  $.get('template.html', function (template) {
    resolve({
      // ...
      template: template
    })
  })
})
```

**Comment by kxxoling** [comment]
I know the two ways, but neither of them I like it.

**Comment by yyx990803** [comment]
Then I'm afraid you'll have to implement it yourself.

**Comment by kxxoling** [comment]
I got it, thanks! @yyx990803 @posva
