### ISSUE TITLE
registering components in the components attribute doesn't work

### ISSUE THREAD

**Issue by kfirba** [yyx990803/vue#1412]
Hello.

I'm developing a SPA with vue-router and when I try to register components through the `components` property on the Vue instance it just doesn't work. My root component is stored in `app.js`:

``` js
module.exports = {

    template: require('./app.html'),

    data: function () {
        return {
            user: null,
            token: null,
            authenticated: false,
            business: false,
            admin: false
        }
    },

     components: {
         'nav-component': require('./components/nav.js'),
         'footer-component': require('./components/footer.js')
    }
    
}
```

Now with the router I just load some views which include the `nav-component` and `footer-component`. This used to work in 0.12.16. When I try this same code with `1.0.0-beta.4` I get a warning that the components aren't defined. In order to make it work with `1.0.0-beta.4` I need to hack and do register the components globally in the `app.js` ready method:

``` js
module.exports = {

    template: require('./app.html'),

    data: function () {
        return {
            user: null,
            token: null,
            authenticated: false,
            business: false,
            admin: false
        }
    },

    ready: function () {
        Vue.component('nav-component', require('./components/nav.js'))
        Vue.component('footer-component', require('./components/footer.js'))
    },

    // components: {
    //     'nav-component': require('./components/nav.js'),
    //     'footer-component': require('./components/footer.js')
    // }
    
}
```

This just doesn't feel right. You can take a look at this thread for a bit more details: http://forum.vuejs.org/topic/108/using-vue-1-0-beta-with-npm

**Comment by yyx990803** [comment]
This is a compat issue between vue-router 0.6.2 and beta 4. Will be fixed in the next release for the router.

**Comment by kfirba** [comment]
@yyx990803 thanks for the reply. I will check it out today. 

Just out of curiosity, what happened? What made it break? From my testing it seemed like all of the route components were properly registered and the root `app` component was properly registered as-well. It's just super frustrating when some bug happens and you just have no clue as of what causes it :(

**Comment by yyx990803** [comment]
The core has been going through some internal API changes before the final 1.0 release - once 1.0 stable is out this type of breakage should no longer happen.

**Comment by kfirba** [comment]
@yyx990803 Hey. I just tested this out with the `0.7.0` version but the same issue is there. Any idea?

**Comment by yyx990803** [comment]
Are you trying to access these components from nested components? 1.0 beta
is in strict mode by default. You should use the 1.0 alpha releases when
upgrading to get deprecation warnings.

**Comment by kfirba** [comment]
@yyx990803 I'm not sure what you mean? I define the components in my root Vue instance which the router is called with this component. In my `routes.js` file I define some routes and components so they should have access to every component that their ancestors have defined, in this case, they should have access to the components that `app.js` defines. The bootstrap file code:

``` js
// Import requirements using browserify
window.Vue = require('vue')
window.VueRouter = require('vue-router')

// Insert vue-router and vue-resource into Vue
Vue.use(VueRouter)
Vue.use(require('vue-resource'))

// Import the actual routes, aliases, ...
import { configRouter } from './routes'

// Create our router object and set options on it
const router = new VueRouter()

// Inject the routes into the VueRouter object
configRouter(router)

// Bootstrap the app
const App = Vue.extend(require('./app.js'))
router.start(App, '#app')
```

app.js:

``` js
module.exports = {

    template: require('./app.html'),

    data: function () {
        return {
            user: null,
            token: null,
            authenticated: false,
            business: false,
            admin: false
        }
    },

    components: {
        'nav-component': require('./components/nav.js'),
        'footer-component': require('./components/footer.js')
    }
    
}
```

routes.js:

``` js
module.exports = {

    configRouter: function (router) {

        router.map({
            '/': {
                component: require('./pages/home.js')
            }
        })
    }

}

```

the `Home` component should have `nav-component` and `footer-component` defined and use them. The code above worked in 0.12.6 but fails in 1.0.0-beta.4 and returns an error that the components are not defined.

Btw, what do you mean that the beta release is in strict mode?

**Comment by yyx990803** [comment]
1.0 no longer allows child components to access ancestor assets. Either
register them globally or explicitly depend on them in child components.
