### ISSUE TITLE
About the new "modal component" sample

### ISSUE THREAD

**Issue by superlloyd** [yyx990803/vue#1415]
A simple comment from a newbie...
It might be easy to fix, but it would be nice if the modal component did replace the "default header" with "custom header" as originally intended...

Now I am left with that as an exercise... might be a good exercise! ^_^ but would be nice to show how to do it in the examples! ;)

**Comment by yyx990803** [comment]
Do you mean it's broken? It seems to be replacing the default header correctly.

**Comment by superlloyd** [comment]
My bad, must have been tired.. 
yes, it worked, I realized later!

as a side note, 2 unrelated comment:
1. haven't looked at Vue and/or web development in a while but today, for some reason, doing it at home and finding Vue so much simpler now! Awesome! :)
2. v-on can only be applied once! What If I want to handle 2 events? (such as click and lost focus on a button)

**Comment by yyx990803** [comment]
http://vuejs.org/guide/directives.html#Multiple_Clauses

Please post questions to forum.vuejs.org instead. Also note in 1.0 `v-on` syntax will be different.
