### ISSUE TITLE
v-for on child component only seems to pass data when using v-component syntax.

### ISSUE THREAD

**Issue by deefour** [yyx990803/vue#1417]
Vue 1.0.0-beta4

A component named `'spec'` scoped as a child of a Vue, marked up in the style below [does not seem to play nicely with the `data` passed to it](http://jsfiddle.net/qw5nybgf/)

```html
<spec v-for="spec in specs" inline-template>
  <!-- ... -->
</spec>
```

Compare this to the alternative directive-based syntax; it [works as expected](http://jsfiddle.net/dopgdvcc/)

```javascript
<div v-component="spec" v-for="spec in specs" inline-template>
  <!-- ... -->
</div>
```

Unless I'm doing something wrong (entirely possible), this seems inconsistent, or at least unexpected.

**Comment by yyx990803** [comment]
1. `v-for` has different scoping rules from `v-repeat`: https://github.com/yyx990803/vue/issues/1200

2. In 1.0 `v-component` has been deprecated: https://github.com/yyx990803/vue/issues/1200 (You should use the non-minified version in your fiddles to see warnings)
