### ISSUE TITLE
Prop validation prevent correct rendering of components in async situations

### ISSUE THREAD

**Issue by Kerruba** [yyx990803/vue#1419]
When I tried to restrict the component's props to a specific type but the data is not already set or correct (like undefined or different from the expected type), the component doesn't render properly **even if in the future the data is filled with proper values** (typically an async call to other resources).

Example of this situation in [this jsfiddle](https://jsfiddle.net/fgsw9ssu/29/)

**Comment by yyx990803** [comment]
This is working as intended as far as I can tell, because you are initially passing down items as `''`, which is a string and is indeed a wrong type.

Just give the parent `items` the initial value of an empty array and it works properly: https://jsfiddle.net/yyx990803/fgsw9ssu/30/
