### ISSUE TITLE
How to escape }} inside a property?

### ISSUE THREAD

**Issue by halaei** [yyx990803/vue#1420]
Sometimes I need to put some server side data (json) into prop of a component. But that data may have "}}" in it. Using v-pre is not an option. I can escape `}}` by printing `}\}` instead, but is it really ok that the following html breaks things? After all, `}}` is inside a nested string. Why should it be matched with a `{{` outside?
```html
<my-comp data='{{[1,"}}",3]}}' inline-template>
    <div v-repeat="d: data">
        <div>
            {{ d }}
        </div>
    </div>
</my-comp>
```

[fiddle](http://jsfiddle.net/tuxtxvhp/)

**Comment by yyx990803** [comment]
This is a limitation of the 0.12 prop syntax. In 1.0 it's no longer an issue because we no longer use mustaches to indicate expressions for props:

``` html
<my-comp :data="[1,'}}',3]">
```

Since you can escape it with a slash, this is going to be a wontfix for 0.12.

**Comment by halaei** [comment]
Good. Looking forward to it.
