### ISSUE TITLE
Component data is not send to child components (1.0.0-beta.4)

### ISSUE THREAD

**Issue by marcvdm** [yyx990803/vue#1421]
Components are not sending its data to the props requested by child components.

Or i'm missing something...

https://jsfiddle.net/x8k3v6rt/1/

**Comment by yyx990803** [comment]
Did you read the guide? http://rc.vuejs.org/guide/components.html#Props

You "send" props  in the template,

**Comment by marcvdm** [comment]
My apologies. 
I have been looking over that for the last half hour.

**Comment by tianhai82** [comment]
see working example.
https://jsfiddle.net/x8k3v6rt/2/
