### ISSUE TITLE
Multiple classes with the same name

### ISSUE THREAD

**Issue by bennyschudel** [yyx990803/vue#1423]
When I manually destroy and add a component, the same class is applied multiple times.

=> http://jsbin.com/saxerovuku/edit?html,js,console,output

Btw: I'm not sure if this is the right way to achieve a hard reload of a component ;)

Best wishes.
Benny

**Comment by yyx990803** [comment]
A piece of already "compiled" DOM cannot be mounted again. You need to reomove the old DOM and append the new one.
