### ISSUE TITLE
Using dynamic components with inline templates

### ISSUE THREAD

**Issue by reshadman** [yyx990803/vue#1424]
I am trying to use dynamic components with ```component``` directive, but I also need the inline templates.

```html
<component is="@{{ currentComponent }}">
	<category steps="@{{ steps  }}" current-step="@{{ currentStep  }}" inline-template>
		Category
	</category>

	<candidate steps="@{{ steps }}" current-step="@{{ currentStep }}" inline-template>
		Candidate
	</candidate>
</component>
``` 

But the inline templates are always instantiated and shown, is there any way to use inline templates and dynamic components?

**Comment by Mat-Moo** [comment]
May I suggest using the forums, as this is for bug reporting http://forum.vuejs.org
