### ISSUE TITLE
vm.$watch on a specific property of objects in an array

### ISSUE THREAD

**Issue by tianhai82** [yyx990803/vue#1426]
Feature request. 
It will be useful and efficient to watch on a specified property of objects in an array. For example,
...
data: {
  users: [{id:1, name:"peter", age:16},{id:2, name:"John", age:18}]
}
...
vm.$watch('users.name',function(newVal, oldVal){
  // newVal and oldVal should return the particular user which name changed
   },{deep:false}
);

**Comment by cyrilchapon** [comment]
wtf. Document ?
