### ISSUE TITLE
Binding and Filtering References

### ISSUE THREAD

**Issue by thiduzz** [yyx990803/vue#1427]
Hi,

First of all i would like to congratulate the devs (or the dev) for this framework. 
Anyway... let's get down to business:

1 - I would like to know how to copy one object and cut all the bindings references attached to this object. I tried using some one-way binding with a child component but everytime i change the object in the child component it does affect the parent component. (even with the {{* object }} notation).

2 - There is not much reference on the "JS-side" of the components, the documentation is too focused on templating. I would suggest to maybe create a Cheat Sheet or something like this.

3 - For anyone wondering how to do "built-in" filtering in JS, here is an example:

var country = this.$options.filters.filterBy(this.countries, this.profile.country.code, 'in',['code']);

**Comment by yyx990803** [comment]
Questions and general discussion are better posted on the [forums](forum.vuejs.org). The issue list is for bug and feature requests only.

As for cutting the references, just do a deep copy of the object. The simplest form can be `JSON.parse(JSON.stringify(object))`.
