### ISSUE TITLE
`<component :is>` fails to resolve components if using a variable passed in via a prop using the expression syntax (`:prop="variable"`) (1.0.0-alpha-8)

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#1428]
Hard coding the component name makes it resolvable again

This works: `<component :is="'item'">`
http://jsfiddle.net/3dgb30mr/1/

This doesnt: `<component :is="itemComponent">` (itemComponent is a variable with a value of 'item')
http://jsfiddle.net/3dgb30mr/

**Comment by marcvdm** [comment]
When you use ``:item-component="'item'"`` it tries to bind it to the variable given


```js
<list :item-component="myVar"></list>
//Its the same as
<list v-bind:item-component="myVar"></list>
```

If you want to send a hardcode string try using do it without the colon ":" like so
```js
<list item-component="A message here"></list>
```

**Comment by cheapsteak** [comment]
Thanks for the breakdown, but the correct value seems to be getting passed down - I get logs warning that it can't resolve the component "item"  
This isn't everything working as intended right?

**Comment by marcvdm** [comment]
Binding with ``<my-component v-bind:property='myVar'>`` or ``<my-component :property='myVar'>`` is for binding variables! It is not intended to send a literal string.

If you do a bind with a literal string using ``<my-component v-bind:property="'myLiteralString'">`` it will count the quotes as part of the string.

The you get is: ``[Vue warn]: Failed to resolve component: 'item'``
Notice the quotes?

Its like doing:
```js
var item = "'item'"
```

If you want to send a literal string you do it without the bind like so ``<my-component property='myLiteralString'>``

Hope this helps! And if i'm wrong please correct me

**Comment by cheapsteak** [comment]
Ah you're right, the "failure to resolve" warning indeed doesn't usually wrap quotes around the missing component  

I thought the v-bind syntax was for binding "expressions", not necessarily variables  
Since the moustache syntax is now deprecated, how else would you do something like

```html
<my-comp prop="{{foo}}-bar">
```
?

I'd imagine it'd be

```html
<my-comp :prop="foo + '-bar'">
```

And if that's supposed to work, then why not 

```html
<my-comp :prop="'-bar'">
```

**Comment by yyx990803** [comment]
It should strip the quotes. Seems to be only reproducible in 1.0.0-alpha.
