### ISSUE TITLE
Failed to resolve component:父组件-子组件-第三层组件

### ISSUE THREAD

**Issue by lazyhero** [yyx990803/vue#1430]
结构是这样的:
最顶层组件为app.vue
![parent-vm](http://7jpswm.com1.z0.glb.clouddn.com/vue-issueQQ20151015-0@2x.png)
像官网介绍的一样，可以正常工作
其中子组件my.vue是这样的
![child-vm](http://7jpswm.com1.z0.glb.clouddn.com/vue-issueQQ20151015-1@2x.png)

在其中的一个组件my中,有几个按钮，可以触发子页面,我就照葫芦画瓢在my.vue中加上了components并且其中一个按钮链接到mycents
![child-link](http://7jpswm.com1.z0.glb.clouddn.com/vue-issueQQ20151015-2@2x.png)

但是无法切换到my组件下的mycents组件
![child-wrong](http://7jpswm.com1.z0.glb.clouddn.com/vue-issueQQ20151015-3@2x.png)

我想肯定是用错了概念;多谢帮助!

**Comment by yyx990803** [comment]
信息量不太够，你对 `el` 选项的理解也有问题。组件是不应该指定 `el` 的。

另外，问题请发到 [论坛](forum.vuejs.org)，这里只用于 bug report 和 feature request。
