### ISSUE TITLE
warns when duplicated props from mixins

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#1431]
Sometimes we would abstract some behaviours into mixins, for example: `A`, `B` and `C`. If `A` is mixed in `B` and `C`, and if the `A` has a required prop named `a`, then when component `D` requires `B` and `C` in mixins, vue will warn the `a` is required even if a value passed to `a`. Because one of the prop check from `B` or `C` digests the value of `a`, leaving another one nothing.

By the way, are there any suggestions to use / compose mixins? Because of the features of mixins,   sometimes some implicit conflicts will raise up and not easy to find out. And in addition, the mixins require the component to obey some implicit interfaces, which lead to hard to maintain the codes.

**Comment by yyx990803** [comment]
Looks like this is because props are not properly de-duped when merged. However it seems a bad idea to have duplicate props in multiple mixins. I don't think this is the mixin mechanism's problem, but rather how you use mixins...

IMO when you use multiple mixins, they should each serve a distinct purpose. If you have two mixins that have overlapping responsibilities then you probably need to rethink the design.

**Comment by TerenceZ** [comment]
Thanks, having duplicated props is actually a bad idea, I think I should remove the dep on `A` for `B` and `C`, then require the mixins `[A,B,C]` in component `D`:)

**Comment by OEvgeny** [comment]
Just curious. Imagine I have a mixin with some prop, I need to redefine its prop default value in component. How can I do it?

**Comment by azamat-sharapov** [comment]
@OEvgeny it will probably work like described in docs, not sure about props thought: http://rc.vuejs.org/guide/mixins.html#Option_Merging

**Comment by yyx990803** [comment]
@OEvgeny that sounds like a bad idea to me. You don't want the sub fields of an option to be merged from multiple sources. It makes your code very hard to reason about.

**Comment by OEvgeny** [comment]
@yyx990803 @azamat-sharapov thank you. I think there is something wrong with my approach... :)
