### ISSUE TITLE
dynamic component with props passing issue

### ISSUE THREAD

**Issue by ije** [yyx990803/vue#1432]
I create some dynamic components with a sample router, but  when I change the currentView value to render the component, there are some warn message print like:
`Data field "xxx" is already defined as a prop. Use prop default value instead.`
obviously, I passed the parent data by `props`

with Vue.js 1.0.0-alpha.8

**Comment by karevn** [comment]
@ije having a code example would be helpful...

**Comment by ije** [comment]
```html
<component v-bind:is="currentPageEditView" v-bind:editing-page="editingPage" v-bind:editing-post="editingPost" v-bind:editing-content="editingContent"></component>
```

```javascript
data: function() {
  return {
}
},
components: (function() {
  var components = {};
  utils.each(config.postPageComponents, function(component) {
    // component 			
    components[component.id] = component;
  })
  return components;
})()
```

**Comment by ije** [comment]
sorry, there are so many lines in my project, i just can paste the keypart of the dynamic component:

template look like this:
```html
<component v-bind:is="currentPageEditView" v-bind:editing-page="editingPage" v-bind:editing-post="editingPost" v-bind:editing-content="editingContent"></component>
```

the parent vm config look like this:
```javascript
{
  template: 'blabla...',
  data: function() {
    return {
      // other fields..
      currentPageEditView: null,
      editingPage: null,
      editingPost: null,
      editingContent: null
    };
  },
  components: (function() {
    var components = {};
    utils.each(config.postPageComponents, function(component) {
      // component preprocess
      component.props = ['editingPage', 'editingPost', 'editingContent'];
      components[component.id] = component;
    })
    return components;
  })(),
  methods: {
    editPost: function(post) {
      this.editingPost = post;
    },
    editPage: function(page) {
      this.editingPage = page;
    },
    editContent: function(content) {
      this.editingContent = content;
    }
  }
}
```

and the `config.postPageComponents` look like this:
```javascript
var config = {
  postPageComponents: [
    {
      template: 'blabla...',
      id: 'component-id',
      name: 'Name',
      data: function(){},
      method: {},
      // blabla..
    },
    // more components define
  ]
};
```

**Comment by ije** [comment]
sorry, I forget note that the parent vm is also a dynamic component...

**Comment by ije** [comment]
@karevn thank you!

**Comment by ije** [comment]
there is a screen shot of console warn messages.
<img width="976" alt="screen shot 2015-10-17 at 15 16 48" src="https://cloud.githubusercontent.com/assets/2883484/10557665/9e77414c-74e7-11e5-898d-b633876bf5dd.png">

**Comment by karevn** [comment]
@ije, it's "by design" behavior in new versions. If you need to have some default values for your props, just pass them in your prop config.

**Comment by yyx990803** [comment]
Declaring props is enough. No need to duplicate them in `data`.
