### ISSUE TITLE
Hide Element Before Rendering

### ISSUE THREAD

**Issue by ghprod** [yyx990803/vue#1434]
How to avoid something like this?

![image](https://cloud.githubusercontent.com/assets/1922652/10542749/a9b7363c-7444-11e5-9619-d2b6508682d6.png)

So basically i want to hide these elements/data and show up after dom is ready

Thanks

**Comment by karevn** [comment]
I suppose you just display templates before Vue is initialised. Why not to put templates into `<script type="text/html">` tags? Or you can wrap them into an invisible div.

**Comment by ghprod** [comment]
@karevn ah thanks for idea .. :+1: 

if i choose to wrap them with invisible div, then which event i should listening to display them?

Yes, its not bug, just need some thought from fellows in here :+1:

**Comment by karevn** [comment]
@ghprod you don't need to display them at all. You just "mount" Vue instance to some visible element at the initialisation, while templates stay invisible.

**Comment by ghprod** [comment]
@karevn ah yappp ... Thanks a lot.. closed :+1:

**Comment by OEvgeny** [comment]
@ghprod why not to use [`v-cloak`](http://vuejs.org/api/directives.html#v-cloak) directive? Also please post questions to forum, this is only for issues.

**Comment by ghprod** [comment]
@OEvgeny Ah my bad, i didnt notice about forum, i'm sorry .. 

Thanks for your hint :+1:

**Comment by karevn** [comment]
@OEvgeny because @ghprod talks about the moment when Vue is not launched at all, so directives have no effect.

**Comment by ghprod** [comment]
@karevn yes, and with style display none then its works perfectly .. :+1:

**Comment by ghprod** [comment]
or with animated.css and add this `animated fadeIn` on `v-cloak` element ..

Thanks all .. :+1:

**Comment by OEvgeny** [comment]
@ghprod wow, good to know! :+1:

**Comment by azamat-sharapov** [comment]
> @OEvgeny because @ghprod talks about the moment when Vue is not launched at all, so directives have no effect.

for `[v-cloak] { display: none; }` you don't need Vue to be initialized at all. This is correct way to hide vue templates until compiled.
