### ISSUE TITLE
Binding syntax suggestion

### ISSUE THREAD

**Issue by AlexandreBonaventure** [yyx990803/vue#1436]
Is there a way to assign the same value for multiples modifiers for v-on directive ?

```
<!-- now -->
v-on:focus="resetErrorDisplay":input="resetErrorDisplay"

<!-- suggestion -->
v-on:focus:input="resetErrorDisplay"

```

Thanks

**Comment by mark-hahn** [comment]
I have wanted this also.

**Comment by arrilot** [comment]
Too much complexity for almost IMO

**Comment by marcvdm** [comment]
:-1: Like @arrilot said, it's to complex.

You could also use the shorthand:
```js
<input @input="resetErrorDisplay" @focus="resetErrorDisplay" />
```
This is way more readable imo

**Comment by karevn** [comment]
Agree to @arrilot. Same handler for different events is a pretty rare use case...

**Comment by marcvdm** [comment]
Even the use case in this issue is irrelevant. To be able to enter input you first need to focus on the input field.

And if you want to reset the error display it might be better to watch in the model to check if its valid and reset the errors there.

I cannot think of a scenario where this could be useful.

**Comment by karevn** [comment]
@marcvdm may be something with `mouseover` / `mousemove`, `keyup` / `keydown`, etc. But it's still, hmm... thin and definitely not useful enough to modify the syntax.

**Comment by marcvdm** [comment]
@karevn ``input`` for ``keyup / keydown`` combination and the mouseover is obsolete when you use ``mousemove``
http://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_event_mouseenter_mouseover

**Comment by mark-hahn** [comment]
> may be something with mouseover / mousemove, keyup / keydown,

I have needed this many times.  It is not uncommon since there is no
alternative.

**Comment by yyx990803** [comment]
Thanks for the suggestion. However, this is in my opinion not "useful" enough to warrant a syntax adjustment. We should only adjust the syntax when it enables something that cannot be easily achieved - but in this case it's just typing convenience. In addition, it doesn't play well with the shorthand:

``` html
<input @focus:input="xxx">
<input @focus@input="xxx">
```

None of the above look right. It's more explicit to have:

``` html
<input @focus="xxx" @input="xxx">
```
