### ISSUE TITLE
The problem of binding class with two arrays

### ISSUE THREAD

**Issue by ElvisKang** [yyx990803/vue#1438]
Version:1.0.0-rc1
Javascript:
```Javascript
new Vue({
    el:'#test',
    data:{
    	arr:['class-A','class-B']
	}
});
```
HTML1:
```HTML
<div id="test" v-bind:class="arr"></div>
```
Result:
```HTML
<div id="test" class="class-A class-B"></div>
```
HTML2(**change `arr` to `[arr]`**):
```HTML
<div id="test" v-bind:class="[arr]"></div>
```
Result(**the `class` become `class-A,class-B`,which has a comma**):
```HTML
<div id="test" class="class-A,class-B"></div>
```
**When I tried to bind class with two arrays**
Javascript:
```Javascript
new Vue({
    el:'#test',
    data:{
    	arr1:['class-A','class-B'],
        arr2:['class-C','class-D']
	}
});
```
HTML:
```HTML
<div id="test" v-bind:class="[arr1,arr2]"></div>
```
Result:
```HTML
<div id="test" class="class-A,class-B class-C,class-D"></div>
```

**Comment by ElvisKang** [comment]
只是看完教程之后进行实验发现的。现在想想Vue提供了修改Array的方法，觉得似乎没什么必要分拆成两个数组。

**Comment by yyx990803** [comment]
数组模式只支持字符串。两个数组可以这样：

``` html
<div id="test" v-bind:class="arr1.concat(arr2)"></div>
```

**Comment by rpkilby** [comment]
I'm running into a similar issue when needing to combine the array and object shorthands. The current solution is to do something like this, but...

```v-bind:class="arr.concat(cond1 ? ['a'] : [], cond2 ? ['b'] : [])"```

Would it make sense to allow multiple v-bind:class statements?

```v-bind:class="arr" v-bind:class="{ 'a': cond1, 'b': cond2 }"```

**Comment by yyx990803** [comment]
@rpkilby You can't have two attributes with the same name. Your use case is complex enough to use a computed property for it.

**Comment by adinugro88** [comment]
how to create array like this @yyx990803 
data:{
       a : {
        ab :[
            abc:{
                 abcd:[
                   {
                       datta:"qweqweqwe"
                    },
                       {
                       datta:"qweqweqwe"
                    },
                    {
                       datta:"qweqweqwe"
                    },
                  
                ]

           }


       ]            
     }
   }
