### ISSUE TITLE
After Render Event

### ISSUE THREAD

**Issue by alanjames1987** [yyx990803/vue#606]
I want to use jQuery a lot with data binded lists, however, some jQuery selectors don't work because Vue has not completed rendering the page. The `nextTick` also is not working for me.

Is there an event I can hook into that runs once the view has been completely rerendered?

BTW I have `v-repeat` inside of a `v-repeat`. The `nextTick` runs after the first `v-repeat` is rendered but not after the second. The DOM objects I care most about are in the second `v-repeat`.

**Comment by bravf** [comment]
我也遇到了这种需求，能不能允许用户给v-repeat指定一个回调？

**Comment by fwon** [comment]
Suggest to do DOM operation after **attached** lifecycle in Vue.
Using v-repeat, there is a classical question in stackoverflow. However it is for AngularJS. But i think it is similar.

**Comment by yyx990803** [comment]
Closing (inactivity)
