### ISSUE TITLE
Change `replace` default to `true`?

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#640]
Seems most of the components I write today need `replace: true`, want to get an idea of actual usage. +1 if you think this makes sense.

**Comment by normanzb** [comment]
@ayamflow oh, you meant you want to keep the content as is and use vue just for manipulating visual changes right? i find it no problem at all with edge version: http://jsfiddle.net/11hh7rkf/

**Comment by ayamflow** [comment]
Yes, but using Vue.component, not Vue/Vue.extend.

**Comment by normanzb** [comment]
@ayamflow although a bit of tricky, still achievable by using method mentioned above: http://jsfiddle.net/11hh7rkf/2/

you may want to start a separate thread so someone fixes it?

**Comment by ayamflow** [comment]
Yep, thanks. Will try that !

**Comment by VictorSigma** [comment]
+1

**Comment by abiaskosty** [comment]
@yyx990803 Is it still in plans for 0.12.0 release?

**Comment by yyx990803** [comment]
As of now I'm inclined to preserve the current behavior, because

1. the behavior of actual Custom Elements / Web Components is similar to `replace: false` (so are Angular 2 components).
2. Defaulting replace to true makes it a bit weird when manually mounting instances (the template will replace the node that is mounted on)
3. Less breakage/migrating work for existing apps.
