### ISSUE TITLE
`v-with` fails silently if component has `replace: true` and more than 1 root element

### ISSUE THREAD

**Issue by Cyancat** [yyx990803/vue#655]
See this: http://jsfiddle.net/qm2wqg8u/5/

If replace set to true, and a multi root template could cause the param can't pass into component. In this case, the comment block cause the problem.

**Comment by agonbina** [comment]
@Cyancat I'm not sure I understand what you're trying to do here, can you explain what a "multi root template" is exactly? I don't see any reason why you would want to set a data property on a view model and then use v-with to override that value when there is many other ways you can do that.

**Comment by Cyancat** [comment]
@agonbina 
Set the default data is not the issue, this issue is just about v-with, which not work properly in this case.
Here is a more simple one without the default data: http://jsfiddle.net/qm2wqg8u/6/

About "multi root template":
This is a single root template: `template: '<div></div>'`
This is a multi root template: `template: '<div></div><div></div>'`

Here have a complicated example which include all cases,  which you could see the different due to the structure of template.
http://jsfiddle.net/qm2wqg8u/4/

**Comment by yyx990803** [comment]
This is actually because: when the template contains more than one node, the component becomes a "block component", which means it doesn't have a root node (but rather a DocumentFragment). So directives that were attached to the placeholder like `v-with` are lost during the transclusion. Theoretically this can be fixed though.

**Comment by Craga89** [comment]
+1 for a fix on this, I've recently run into this myself. As a workaround, I've utilising `inherit: true` for the time being. Is this a priority?

**Comment by yyx990803** [comment]
Fixed!

**Comment by Cyancat** [comment]
@yyx990803 
Thanks a lot! Looking forward to formal release :)
