### ISSUE TITLE
InsertBefore breaking data binding, undefined parentNode

### ISSUE THREAD

**Issue by Billiam** [yyx990803/vue#657]
I'm trying to solve an odd problem, and thought  I could work around it by manually adding some items to a directive's element:
http://jsbin.com/quxusu/2/edit?html,js,output

Which causes this error in a replace method:
```
 Uncaught TypeError: Cannot read property 'parentNode' of undefined
```

Is this a bug, or expected behavior?

**Comment by mk-relax** [comment]
I still have this problem, but then with a directive that **reduces** the number of children.

I'm implementing a `v-ladda` directive for 'ladda' buttons (Buttons with built-in loading indicators, https://github.com/hakimel/Ladda). In `bind()`, it changes the DOM by wrapping all children of a `<button>` in one `<span>` (I copied their code). 

Wrapping one child works fine, but when wrapping multiple children (even text nodes resulting from newlines, which is annoying) Vue fails with the TypeError again. 

See:
http://jsbin.com/cesuwo/edit?html,js,output
