### ISSUE TITLE
[Feedback] Difficulty appending child VM

### ISSUE THREAD

**Issue by jordangarcia** [yyx990803/vue#659]
Not really an issue, rather feedback from the difficult time I had appending a child VM.  This was quite easy in 0.10.x

The simple use case is as follows:

```js
var a = new Vue({
  template: '<div> root </div>'
})

var Comp = Vue.extend({
  template: '<div> child </div>'
})

a.$mount(document.body)
a.$addChild({}, Comp).$appendTo(a.$el)
```

I tried this code for a quite a while until I figured out:

```js
a.$addChild({}, Comp).$mount().$appendTo(a.$el)
```

This is quite a bit more arduous than just passing the `parent` in the component configuration.  

It would be really nice if I could do something like: 

```js
var b = new Component()
a.$append(b)

// passing a component instance to $append or $appendTo would call $mount() and append to the a.$el
```

What are your thoughts on this workflow?

**Comment by yyx990803** [comment]
Yeah I agree this usage feels cumbersome. It would be fairly easy to just extend `Vue.prototype` with your proposed method if you don't need `inehrit: true`:

``` js
Vue.prototype.$append = function (vm) {
  vm.$parent = this
  vm.$root = this.$root
  if (!this._children) this._children = []
  this._children.push(vm)
  if (!vm.$el) vm.$mount()
  vm.$appendTo(this.$el)
}
```

Unfortunately this cannot deal with possible `inherit: true` situations (which is handled in `$addChild()`)
