### ISSUE TITLE
Frozen data models

### ISSUE THREAD

**Issue by tarh** [yyx990803/vue#662]
I suggest to allow frozen trees into a data model. Example:

	function makeSubModel(val) {
		return Object.freeze({
			key1: Object.freeze({
				key2: val
			})
		});
	}
	var data = {
		frozenSubModel: makeSubModel('init')
	}
	new Vue({
		// …,
		data: data
	});
	data.frozenSubModel = makeSubModel('changed');

The current version rejects the frozen model: `"Cannot define property:__ob__, object is not extensible."` But frozen objects don't need to be observed.

***

I have several instances of Vue that share the same template. Is there a means to compile the template once?

My current code:

	var myTpl = '<div>…</div>';
	var vm1 = new Vue({
		// …,
		template: myTpl
	});
	var vm2 = new Vue({
		// …,
		template: myTpl
	});

I would like to have:

	var compiledTpl = Vue.compile('<div>…</div>');
	var vm1 = new Vue({
		// …,
		template: compiledTpl
	});
	var vm2 = new Vue({
		// …,
		template: compiledTpl
	});

**Comment by TMiguelT** [comment]
+1 for both those suggestions. I'm going to hope that Vue.component already pre-compiles templates but I don't know for sure.

**Comment by yyx990803** [comment]
Template compilations are cached as long as they are the same string.

The frozen object usage seems interesting, I can take a look after my vacation :)

**Comment by tarh** [comment]
Thanks.
(Just an informal question) Do you plan to integrate [Format.js](http://formatjs.io/)? I am considering contributing for this feature.

**Comment by yyx990803** [comment]
@tarh I personally have no plan in doing it, feel free to contribute!
