### ISSUE TITLE
Invalid expression. Generated function body:  scope.prof[{{scope.cprof}}]

### ISSUE THREAD

**Issue by yotamN2** [yyx990803/vue#663]
I tried to use variable as the value inside [] and it's doesn't work:
`a(v-repeat='prof[{{cprof}}]' href='#/{{$key}}')`

What is the right syntax?
Edit: I tried `prof[\'{{cprof}}\']` and it's worked but it doesn't find the variable so the repeat doesn't happend

**Comment by builtap** [comment]
```v-repeat``` is a Vue tag attribute that requires an expression, that is, some valid JavaScript code.  This expression can be an Array, Object or Number. In your case, it could be ```v-reapt="prof['cprof']"```. On the other hand, ```href``` is a simple html attribute that requires a string, hence the use of mustache bindings for variable interpolation (see http://en.wikipedia.org/wiki/String_interpolation). 

Ref: http://vuejs.org/api/directives.html#v-repeat.
