### ISSUE TITLE
Filter.write is going to the model and back to the DOM 

### ISSUE THREAD

**Issue by aristidesfl** [yyx990803/vue#664]
I think this was being addressed in another issue ~~but I can't find it~~ #554.
Here is a case scenario problem: http://jsfiddle.net/tsx6hw7r/4/

--------------

EDIT: here another example of the problem: http://jsfiddle.net/92jv3svm/2/

**Comment by aristidesfl** [comment]
Yet another example: http://jsfiddle.net/z0a7u671/2/

**Comment by aristidesfl** [comment]
Currently write filters work better as a tool to condition the user interface.
For example, in this application a write filter is used to disable alpha keys, and disambiguate which character should be used to separate decimal places: http://jsfiddle.net/gdopraof/1/

Would be nice to keep this functionality somehow, maybe as a different kind of filter?

**Comment by yyx990803** [comment]
With b5ac185 , if now only write filters are present, it will no longer force the update back to the DOM.

**Comment by aristidesfl** [comment]
This is good improvement. Allows almost everything, except the 2 way currency example:
1. Storing only valid values: [yes] (http://jsfiddle.net/dyekbcbs/)
2. 2 way currency: [no] (http://jsfiddle.net/saoprh9z/)
3. Restricting user input: [yes] (http://jsfiddle.net/wvr0yx5h/)

From a Vue user point of view, ideally there would be a way to explicitly enable / disable forced update like for example:
```
filters: {
  currency: {
    read: ...
    write: ...
    forceSync: true/false
  }
}
```

However it would probably make more sense to be able to set this on the template because the difference e presentational and belongs to the element which is being modified. For example, double pipe to loosen the filter update cycle  `v-model: amount || currency`, or maybe a separate attribute?

**Comment by yyx990803** [comment]
The two-way currency problem can't be fixed by disabling sync alone, since it requires detailed control of where to place the cursor after updating the input's value in DOM. In particular cases like this, it's probably better to write a custom directive instead.

**Comment by aristidesfl** [comment]
But the point of disabling sync is not having to update the input's value in DOM, so no need to replace the cursor right?

**Comment by yyx990803** [comment]
But don't you want to format the `.00` in the currency example? The reason it's hard to interact with is because `v-model` doesn't know where to correctly restore the cursor position after a DOM update (which resets the cursor).

**Comment by aristidesfl** [comment]
I was thinking that the format would be disabled on the input which is being manipulated by the user, and let the user write anything.

**Comment by yyx990803** [comment]
Oh, do you mean delay the formatting until the user blurs the input?

**Comment by aristidesfl** [comment]
Yes, that

**Comment by yyx990803** [comment]
Then you can just use `lazy`?

**Comment by aristidesfl** [comment]
`lazy` is a great option, with the caveat you mentioned which is a problem is some situations
