### ISSUE TITLE
Possible memory leak after calling vm.$destroy(true)

### ISSUE THREAD

**Issue by boussou** [yyx990803/vue#666]
The use case (Vue.js v0.11.4): 
- create a v-repeat of 1000 divs(bootstrap tabs) in a parent div (say "main")
- on a click, call vm.$destroy(true) before replacing the parent div by another VM  w/ 1000 divs in it

using the chrome task manager, I see memory usage growing.
So I took several memory snapshots & saw a huge number of "Detached DOM tree" corresponding to the v-repeats divs

**Comment by TMiguelT** [comment]
Can you check the memory usage after Vue.nextTick()? Vue deliberately does a lot of things asynchronously to avoid blocking the UI, and it probably doesn't delete immediately. In addition, it might keep the deleted VMs for longer in case they need to [transition out](http://vuejs.org/guide/transitions.html). At any rate these DOM items should be removed eventually, it might just not be immediately.

**Comment by boussou** [comment]
Hi, here is the isolated code that end up with a memory leak.
It it even more obvious when changing max=1000
Thanks 

http://jsfiddle.net/mfyw9xrj/

**Comment by boussou** [comment]
I ended up to the conclusion that the core Vue is creating leaks. Source is $compiler, probably some closure somewhere.

**Comment by TMiguelT** [comment]
Hmm I ran your fiddle and checked in the chrome task manager and the memory usage definitely does grow, although I think it's still possible that could be an issue with your code rather than with Vue. Either way, @yyx990803 might want to have a look when he gets back.

**Comment by TMiguelT** [comment]
Hmm looking at the code I suspect the memory leak might be from your code. Why are you calling the Vue constructor multiple times? You should only run it once and then modify its data if necessary.

**Comment by boussou** [comment]
Hi, thanks for your reply.

It is a PJAX application: it corresponds to a new page display when you click on of the app menu button: then a new HTML content is loaded via ajax, put in the main content div, and the corresponding Vue object (with its related data) is initialized. I remove jquery events before, and call destroy on the previous View object before removing it.

Do you suggest that in such case I should keep the vue object and replace the "el" content dynamically?

**Comment by TMiguelT** [comment]
I can't speak for the memory usage of such a situation, but there are so many better ways of going about that. Have a read of [this page](http://vuejs.org/guide/application.html#Modularization) of the guide. If you want to make a SPA with Vue so that you can change pages etc. then you should first make your pages into modules (see that link), then use a routing library that will `require()` your module on hash change, and then you put a dynamic `v-component` directive in the page that changes the main page component when the module has loaded.

**Comment by boussou** [comment]
As you as it solve the memory leak problem, at least I can try.
I am trying to build an alternative to the heavy Angular proto I built, please help me escape this monster ;-)

**Comment by boussou** [comment]
I just read the link you provided, I don't think it will solve this, as it is mainly about packaging. 
The solution could come from the v-component usage wich I will test

**Comment by TMiguelT** [comment]
Ah sorry I meant the whole page. There's some mention of `v-component` under "Routing". Although I highly recommend packaging your pages into modules anyway, since it will allow you to lazy load them.

**Comment by boussou** [comment]
I tried this sample here that uses the deprecated v-view - because I suppose v-view is almost a v-component: I see memory leak too.
http://jsbin.com/jizegefape/2/edit

**Comment by TMiguelT** [comment]
Yeah I tried it out with the new version and it's the same: http://jsfiddle.net/844fkqeL/2/. This does seem to be a legitimate issue.

**Comment by yyx990803** [comment]
Just ran your first example locally with Chrome dev tools, both heap snapshots and heap recording shows pretty clean garbage collection... mind posting your heap snapshot/recording results?

**Comment by boussou** [comment]
I tried another way to check it: here we can see that memory grows, but it seems it is because Chrome choose not to run GC for performance reasons ? when forcing GC, memory seems to be recovered.
Still there exist "detached dom trees" that shows leak exists - I'll post another capture to show it

below each step is a click on the button

![2015-01-27_064637](https://cloud.githubusercontent.com/assets/2531688/5914137/6e276dd0-a5f0-11e4-9234-0c8370d09b1a.jpg)

**Comment by boussou** [comment]
here, the detached dom trees. After further reading about using the dubgger, I know that there should be "retainers" object in the below tab.
Then maybe the example is incorrect and my app have some bad jquery interaction.

![2015-01-27_065932](https://cloud.githubusercontent.com/assets/2531688/5914237/3048a02c-a5f2-11e4-803c-b5701c814782.jpg)

**Comment by boussou** [comment]
from the outside (task manager):
initial stage: 14,9
![2015-01-27_072005](https://cloud.githubusercontent.com/assets/2531688/5914398/4da1f0d0-a5f5-11e4-8e26-01d2421f3480.jpg)

mutliple clicks (until counter reach> 300): 28,1
![2015-01-27_072100](https://cloud.githubusercontent.com/assets/2531688/5914405/59aed172-a5f5-11e4-9fe1-cfb1f702c798.jpg)

after click on the force GC: 20
![2015-01-27_072139](https://cloud.githubusercontent.com/assets/2531688/5914414/72843e58-a5f5-11e4-944e-dd19119463bc.jpg)

It is not easy to interpret this:   
 - even after GC have we lost 5kb?  but last column shows pure JS memory is then lower (from 12,2 to 10,2 after GC)

**Comment by yyx990803** [comment]
I think the heap usage you are seeing is perfectly normal - I believe you'd see similar usage, if not more, using other frameworks. For snapshots, you probably want to take a lot of them and see if they keep growing indefinitely. When and how does V8 do the GC is complex, but as long as a GC produces proper collection and doesn't affect your user experience you will be fine.
