### ISSUE TITLE
v-ref references not updated

### ISSUE THREAD

**Issue by swannknani** [yyx990803/vue#667]
I'm experiencing a behaviour and don't know if it's the normal one or a issue.
When I'm using ```v-component``` and ```v-ref```, the ```v-ref``` array containing all my child references is not updated while datas actually are.
Thanks.
http://jsfiddle.net/biquetto/f2ouzhz6/7/

**Comment by TMiguelT** [comment]
Yep it's normal. Vue's behaviour (afaik) is to only update the DOM on the frame after the model changes. When you're checking, those components haven't been created yet but they will be in the next frame. [Fiddle](http://jsfiddle.net/s7y4030v/) (apologies for the messy code, I'm using my phone). 

If you need access to those components as soon as they're created, get them to dispatch an event on their own ready callback which the parent view model can listen for. There's a perfect example of that in the Vue guide under Component System -> Event System. Hope that helps.
