### ISSUE TITLE
v-model on select elements does not honor number attribute

### ISSUE THREAD

**Issue by sergbus** [yyx990803/vue#670]
Changing the value on the select element sets the model value as a string even when "number" attribute is specified on the select element.

Example on JSFiddle is here:
http://jsfiddle.net/5sH6A/78/

**Comment by boussou** [comment]
I think there is no problem here, value is correct & html always handle strings.

**Comment by TMiguelT** [comment]
@boussou is correct, but Vue does provide a way of automatically casting to
number: [see here](http://vuejs.org/guide/forms.html#Casting_Value_as_Number)

**Comment by TMiguelT** [comment]
I think this is actually a bug because it works for `<input>` elements (http://jsfiddle.net/3vmvmqdp/), but it doesn't look like it works for `<select>`s.

**Comment by boussou** [comment]
yep, you right. it could be a problem in case of arithemics on the value like "this.n+1"

**Comment by sergbus** [comment]
Looks like this has been fixed in dev branch for #642. I just hope it works for selects that allow multiple values. Does the _.toNumber function support arrays?
https://github.com/yyx990803/vue/blob/dev/src/directives/model/select.js

**Comment by yyx990803** [comment]
Now it does :)
