### ISSUE TITLE
Watch options

### ISSUE THREAD

**Issue by zhouzhuojie** [yyx990803/vue#672]
Notice that we can pass `[deep, immediate]` as the options to a vm's instance method `$watch`,
```
vm.$watch( expression, callback, [deep, immediate] )
```
How do we achieve the same thing if we also want `[deep, immediate]` in the instance option:
```
var vm = new Vue({
  data: {
    a: [1, 2, 3]
  },
  watch: {
    'a': function (val, oldVal) {
      console.log(val)
    }
  }
})
```

**Comment by TMiguelT** [comment]
I'm going to assume that this isn't possible. The watch object is just a convenient form of:
```javascript
ready: function(){
     this.$watch("a", function(){
     });
}
```
So you might have to do that yourself manually (it's not a *lot* more code)

**Comment by yyx990803** [comment]
Closing (inactivity)
