### ISSUE TITLE
Vue doesn't work

### ISSUE THREAD

**Issue by djyde** [yyx990803/vue#675]
**No error and no warning** but doesn't work as below screenshot:

![](http://ww1.sinaimg.cn/large/62580dd9gw1eo7q9o4k0sj20nd0jgacg.jpg)

**Comment by TMiguelT** [comment]
Your script tags should be at the bottom of the page, or the code should be wrapped in a DOM ready callback. The element `<div id="demo">` doesn't exist when you try to instantiate Vue

**Comment by djyde** [comment]
Thanks, you are right.
