### ISSUE TITLE
How to initialize a template dynamically with the result of an ajax call

### ISSUE THREAD

**Issue by Arsenalist** [yyx990803/vue#679]
I want to load the template for a VueJS component dynamically. I'd like to make an AJAX call using jQuery, and whatever the server returns should be the template of the VueJS component. Here's a simplified version of the code with the AJAX call removed since it's irrelevant where the data is coming from:

    BoardFeed = Vue.extend
        template: '<div>This should be replaced</div>'
        data: ->
                return items: null
        created: ->
            @template = "<div>Template returned from server, what I really want</div>"

In the above example I'm using the created hook which I thought would be suitable for this, but the newer template is never rendered, only the older one.

Is it possible to achieve this?

**Comment by TMiguelT** [comment]
You can't change the template after the component has been created. It's not a property on the component instances, it's just a parameter your pass into their constructor.

If your initial template is some sort of loading bar/spinner, which is then replaced with content once its loaded, the way I did that was to create a component for the spinner, and a component for the new content (once it's loaded), and then I used a [dynamic `v-component`](http://vuejs.org/guide/components.html#Dynamic_Components) in the parent template and changed the variable it was bound to when the new component has been loaded from the server, causing the component to change from the spinner to the new component. Also if you won't need scope data or functions you can also use a [dynamic [`v-partial`](http://vuejs.org/api/directives.html#v-partial)

**Comment by Arsenalist** [comment]
Thanks for the comment.  My use case is different.  I'm trying to display HTML markup that's returned from the server on the page, but that HTML markup has VueJS directives in it, e.g., v-text etc, which I want to be reactive.  I figured that if they're all part of the template, I'll be fine.   I suppose I could load that HTML data as part of a different component, and then when creating this component instance, pass it in as a template.

**Comment by TMiguelT** [comment]
I still think that's the same situation. Have a look at [this fiddle](http://jsfiddle.net/zu3kpd20/1/): (code is duplicated below):
```html
<div v-component="{{currentView}}"></div>
```
```javascript
//Create the 'default' component
Vue.component("default", {
    template: '<div>This should be replaced (and will be in 2 seconds)</div>'
});

//Create the parent ViewModel
var vm = new Vue({
    el: "body",
    data: {
        currentView: "default"
    }
});

//Pretend to load the data from the server
//This would actually be $.get("/url", data, function(){...});
window.setTimeout(function () {
    
    //Create the new component using the template we received
    Vue.component("BoardFeed", {
        template: '<div>Template returned from server, what I really want</div><br>And directives work too:<div v-repeat="items">{{$value}}</div>',
        data: function () {
            return {
                items: [1, 2, 3]
            };
        }
    });
    
    //And then change the page to that component
    vm.currentView = "BoardFeed";
}, 2000);
```

**Comment by Arsenalist** [comment]
You are absolutely right. I'm actually using "currentView" pattern as described on the main website, I just didn't think that it would also apply in this case as well.  

Thanks for showing me the light.

**Comment by Enchufadoo** [comment]
Hi guys, is there any way to achieve this with vue 1.0? the fiddle here doesn't work anymore with 1.0 version and I was wondering if there's a new way to do this?

**Comment by simplesmiler** [comment]
@Enchufadoo [async components](https://vuejs.org/guide/components.html#Async-Components).

**Comment by Enchufadoo** [comment]
@simplesmiler I think that only loads the code for the component, what I'm trying to do is render the component dinamically. In the example provided here this is how they achieve it.

`<div v-component="{{currentView}}"></div>`

When currentView changes, the component changes, as I understand it.

I've seen many people in other posts/comments say that this can be achieved by using "is"
```
data: {
  elements: [
    { type: 'component-a' },
    { type: 'component-b' }
  ]
}
<component v-repeat="elements" is="{{type}}"></component>
```

But I still haven't seen a working example, and I can't event get to work the simplest code so I was wondering if it's possible

**Comment by Enchufadoo** [comment]
@simplesmiler I just realized I can achieve this by using v-if
```
data: {
  currentView: ''
}
<component-a v-if="currentView == component-a"></component-a>
<component-b v-if="currentView == component-b"></component-b>
```

Thanks!

**Comment by simplesmiler** [comment]
@Enchufadoo well, your question has nothing to do with the original topic then :wink:
Yes, the correct way in 1.0 is `<component v-for="element in elements" :is="element.type"></component>`.

**Comment by emahuni** [comment]
@TMiguelT Ok go it!, so how do you do it for single file template syntax return by ajax like so: 

```html

<template>
	<h1 class="bg-success">{{name}}</h1>
	<div>this is the template that was loaded through ajax</div>
</template>

<style lang="sass" rel="stylesheet/css">
	
</style>

<script>
	export default {
		data () {
			return  {
				name:'ajax template'
			}
		}
	}
</script>

```

how do i make that to work with vue... I want it to work this way coz of ide support etc

**Comment by emahuni** [comment]
@TMiguelT Ok go it!, so how do you do it for single file template syntax returned by ajax like so: 

```html

<template>
	<h1 class="bg-success">{{name}}</h1>
	<div>this is the template that was loaded through ajax</div>
</template>

<style lang="sass" rel="stylesheet/css">
	
</style>

<script>
	export default {
		data () {
			return  {
				name:'ajax template'
			}
		}
	}
</script>

```

how do i make that to work with vue... I think putting a native protected runtime template compiler is something that Vue is missing and i want it to work this way coz of ide support etc. I don't want to use webpack code splitting and the like... I want to be able to load a template through Ajax and use it in the browser.

**Comment by littlexiang** [comment]
@emahuni https://www.npmjs.com/package/vue-dynamic
I think this is what we are looking for

**Comment by apptouch** [comment]
I just download templates before I ever create my Vue comps....  I'm looking into Vue native support for this but honestly, it's really simple to just download your template and then assign it to your comp when the comp is being constructed.  But, then again, I tend and prefer to do things manually, so instead of using webPack/etc, I have a MVC structure that allows me to control when my page/comps.  Not an answer, just some feedback.  There's always a simpler way....
