### ISSUE TITLE
v-with not working on a <tr> element

### ISSUE THREAD

**Issue by TMiguelT** [yyx990803/vue#680]
This is a very specific issue that only seems to be happening with `<tr>` elements. Here's a [JSFiddle](http://jsfiddle.net/oLkd7sqn/3/) showing the behaviour. Basically the value `extra` that is passed in via `v-with` is not defined in the first 3 rows, but is in the second 3 rows. The only difference between them is their templates.

Here's the code from the fiddle:
```html
<table>
    <tr v-repeat="list" v-with="extra: 300" v-component="doesnt-work"></tr>
    <tr><td><hr></td></tr>
    <tr v-repeat="list" v-with="extra: 300" v-component="does-work"></tr>
</table>
```
```javascript
new Vue({
    el: "body",
    data: {
        list: [1, 2, 3]
    },
    components: {
        "doesnt-work": {
            template: "<tr><td>Value: {{$value}}</td></tr>" +
                "<tr><td>Extra: {{extra}}</td></tr>",
            replace: true
        },
        "does-work": {
            template: "<tr><td>Extra: {{extra}}</td></tr>",
            replace: true
        }
    }
});
```

And the output is:
```
Value: 1
Extra:
Value: 2
Extra:
Value: 3
Extra:
***
Extra: 300
Extra: 300
Extra: 300
```

**Comment by cheapsteak** [comment]
Looks like it's an issue with having more than one root element in the template.
Switching the table to divs recreates the same problem:  
http://jsfiddle.net/oLkd7sqn/5/
And adding an (albeit invalid) `<div>` wrapper around it fixed it
http://jsfiddle.net/oLkd7sqn/6/

**Comment by cheapsteak** [comment]
Possible a duplicate of this:  
https://github.com/yyx990803/vue/issues/655

**Comment by TMiguelT** [comment]
Yes I think you're right that it's a duplicate of that issue. I guess I'll leave the discussion to that thread!
