### ISSUE TITLE
Uncaught TypeError: Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by fullfs** [yyx990803/vue#685]
The error points to the code

```
p.notify = function () {
  for (var i = 0, l = this.subs.length; i < l; i++) {
    this.subs[i].update()
  }
}
```

The problem occurs at the setting a big amount of data to a single property (```this.offer = offer```) in a complex component.
Can't reproduce it in fiddle, but it looks like ```subs``` array changes its length while iterating it in ```notify```.

Giving up on saving up ```subs``` length fixes the problem:
```
for (var i = 0; i < this.subs.length; i++) {
```

**Comment by bdaglish** [comment]
I've had this a couple of times, but it seems to be when there's a watched/referenced property that isn't originally specified in the data {} section. Adding the property usually cures it.

**Comment by anfinil** [comment]
This issue also repeats if you try to nullify some data property that was bind several times. For example,
```html
<div v-if='customer'>
  <div v-show='customer'>{{customer.id}}</div>
  <div v-show='customer'>{{customer.name}}</div>
</div>
```

When you try to set ```customer``` to ```null``` it will raise error because ```this.subs.length``` will be 3. But after first ```this.subs[i].update()``` run it will modify ```this.stubs``` and it will raise error on next loop.

**Comment by anfinil** [comment]
Changing to ```for (var i = 0; i < this.subs.length; i++) {``` fixes the problem.
