### ISSUE TITLE
Form handlers

### ISSUE THREAD

**Issue by markuplab** [yyx990803/vue#686]
Hey @yyx990803, please check 2 very simple examples:

http://jsfiddle.net/97a1j26t/
http://jsfiddle.net/35meacb2/

**Comment by TMiguelT** [comment]
I'm assuming your question is along the lines of "why doesn't the `handled` function get called if I call submit the form directly, but it does if I cause the submit button to be clicked"

My suspicion is that it's a JS problem, not Vue. [On MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement.submit) it says:
>The form's onsubmit event handler (for example, onsubmit="return false;") will not be triggered when invoking this method (`HTMLFormElement.submit()`) from Gecko-based applications. In general, it is not guaranteed to be invoked by HTML user agents

**Comment by yyx990803** [comment]
Basically what @TMiguelT said, this seems to be a browser behavior issue.
