### ISSUE TITLE
Different behaviors when changing the object in an array

### ISSUE THREAD

**Issue by zhouzhuojie** [yyx990803/vue#687]
http://jsfiddle.net/wtke9vnq/6/

```
<div>
    <div v-repeat="array">{{v1}} : {{v2}}</div>
</div>
```

```
new Vue({
  el: 'body',
  ready: function() {
    this.array[0].v2 = 'v2';
    this.array[1] = {
      v1: 'v1',
      v2: 'v2'
    };
  },
  data: {
    array: [
      {
        v1: 'v1',
        v2: '2'
      }, {
        v1: 'v1',
        v2: '2'
      }
    ]
  }
});
```

Expected output (Assumed, may not be intended though)
```
v1 : v2
v1 : v2
```

Actual output
```
v1 : v2
v1 : 2
```

**Comment by TMiguelT** [comment]
From the [guide](http://vuejs.org/guide/list.html#Augmented_Methods):
>You should avoid directly setting elements of a data-bound Array with indices, because those changes will not be picked up by Vue.js. Instead, use the agumented $set() method

So instead you can just use:
```javascript
this.array.$set(1, {
    v1: 'v1',
    v2: 'v2'
});
```

[Here's a fiddle](http://jsfiddle.net/wtke9vnq/9/) where I fixed it. <sub>I also fixed the CoffeeScript by getting rid of it entirely.</sub>

**Comment by agonbina** [comment]
@zhouzhuojie you should probably close this issue, seems like your question has been answered by @TMiguelT
