### ISSUE TITLE
ready not triggered on Android 4.1.1

### ISSUE THREAD

**Issue by Sirk** [yyx990803/vue#688]
It seems that the ready function of a component is never triggered in Android Browser for Android 4.1.X. While attached(), compiled() and others are well triggered, ready() is quite buggy. The only solution I found at this time is to put a setInterval in the compiled() function and check if the DOM contains an element of my template. 

Don't find out why ready() is not triggered. Could be caused by an buggy interpretation of document.contains() in Android Browser for Android 4.1.X (document.contains is used in the inDoc function of vuejs).

**Comment by yyx990803** [comment]
Yeah, older versions of Android have some quirky implementation bugs. I don't have a device with that version to test on, but glad to know you've found a workaround.
