### ISSUE TITLE
Cancelled event is continuing to traverse through DOM horizontally

### ISSUE THREAD

**Issue by Jabher** [yyx990803/vue#690]
Not quite sure if that's correct behaviour, maybe I'm wrong.

I want to break an event on first captured node by navigating through nodes, like this:

```javascript
events : {
    'node:selected' : function () {
                    this.select();
                    return false;
}
```

But last node gets selected instead of first one.
Both spawning new events (so only single thread broadcast gets cancelled) and stopping of execution (my case) are good things, however, current implementation is neither first nor second.

Possibly, this code should be altered:
```javascript
if (cbs[i].apply(this, args) === false) {
        this._eventCancelled = true
      }
```
to 
```javascript
if (cbs[i].apply(this, args) === false) {
        this._eventCancelled = true
        break
      }
```

**Comment by yyx990803** [comment]
Just to clarify the issue - are you using `$broadcast` on a list of children generated with `v-repeat`?

**Comment by Jabher** [comment]
Yes, exactly.

пн, 26 янв. 2015, 21:59, Evan You <notifications@github.com>:

**Comment by yyx990803** [comment]
There's an issue if we allow this type of horizontal cancellation: the listener order will remain the same as the order they were registered, regardless of how the children are sorted later. Basically this means the event trigger order is not guaranteed to be the same with the vm order in the array.

I think a broadcast should by definition reach all possible children on the same level, or, in other words, the behavior of a component should only be able to affect the event propagation of its own children, not its siblings.

And for your original use case, it's probably a better idea to pass down an extra argument in your broadcast call to accurately identify the matching child.
