### ISSUE TITLE
Allow specifying private assets using camelCase

### ISSUE THREAD

**Issue by mlindsten** [yyx990803/vue#693]
It would be nice if we could specify private assets that have dashes in their names (e.g. components or directives) using camelCase. That way, when moving to ES6, we can take advantage of object literal property value shorthands:

    import myComponent from "./my-component.js";
    new Vue({
        components: { myComponent }
    });

**Comment by yyx990803** [comment]
I'm not sure if this is necessary - in general I want to avoid implicit conventions since this makes the code harder to understand unless you already know that convention.

**Comment by yyx990803** [comment]
Closing (inactivity)
