### ISSUE TITLE
Using v-component with template-tag, paramAttribuets & replace options not work.

### ISSUE THREAD

**Issue by nakajmg** [yyx990803/vue#699]
Plz see these fiddles http://jsfiddle.net/fowmc814/1/ http://jsfiddle.net/87fyt57q/1/

compileParamAttributes & copyAttributes are expected element-node. But actually received document-fragment.

**Comment by agonbina** [comment]
You should probably not use v-component on a ```<template>``` tag to start with. I use a template block only when I must define a template for a component in the DOM as opposed to using a templating engine like Jade or Handlebars

**Comment by yyx990803** [comment]
`<template>` elements have a special usage in Vue: it is used as a block container for `v-if` and `v-repeat`. It doesn't work with `v-component`.

**Comment by nakajmg** [comment]
Thank you for reply!

These fiddles are minimum code for caused error. Actually, I'd like to use [v-repeat with template] and [v-component with paramAttribetus].

For explain, I created new fiddles.

http://jsfiddle.net/nakajmg/p5a3pjr9/1/

This fiddle work fine. But I wouldn't like to nested-div. Then I tryed change from div to template. But doesn't work.

http://jsfiddle.net/nakajmg/cpj5s9pa/2/

Then I tryed v-repeat with template at outside, v-component with v-with at inside & enable replace-option. But doesn't work too.

http://jsfiddle.net/nakajmg/2kpehmdb/1/

How do i implement to use paramAttributes-option without nested-div in v-repeat with v-component? Or might be wrong way?

**Comment by agonbina** [comment]
I don't think you'll be able to use both a template and then specify an ```el``` property. Seems like what you were trying to do is this: http://jsfiddle.net/2kpehmdb/2/

**Comment by nakajmg** [comment]
Oh that makes sense! But I wouldn't like write template on HTML. Actually, I use `$mount()` & `$appendTo('body')` for building large app.

After, I used custom-tag instead of v-component. Then it was expected!

http://jsfiddle.net/nakajmg/fdehy3ad/1/

**Comment by agonbina** [comment]
You can use just ```$mount('body')```, appendTo is there from an older Vue version
