### ISSUE TITLE
Is there a way to reset a component?

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#702]
Currently if there's a component I want to reinitialize, I have to include the component as an expression, set that expression to blank, then reset the expression back to the component 

```html
<div v-component="{{currentComponent}}"></div>
```
```javascript
container.currentComponent = '';
Vue.nextTick(function () {
  container.currentComponent = 'origional-component';
});
```

Is there a better way to do this?

**Comment by TMiguelT** [comment]
That's an interesting problem. Since you know that all a component's state is stored in the $data variable, you can always just override it with original data. And you can store that original data in the same module as the component, but not in the component:

```javascript
//This function is exactly the same as your data function for the component originally was
function getDefaultData() {
    return {
        a: "A",
        b: "B"
    }
}

module.exports = {
    data: getDefaultData,
    methods: {
        resetData: function () {
            this.$data = getDefaultData();
        }
    }
};
```

**Comment by cheapsteak** [comment]
This seems like it should work, thanks!

**Comment by Kaijun** [comment]
@TMiguelT @cheapsteak it doesn't work anymore in Vue 2.0

**Comment by skywalker2013** [comment]
var defaultData = {
        a: "A",
        b: "B"
    }

module.exports = {
    data: defaultData ,
    methods: {
        resetData: function () {
            this.$data = defaultData;
        }
    }
};

I write it like above, it can't work. it must be a function to get the default data when you wanna reset. why?

**Comment by thollar13** [comment]
You can do the above with `Object.assign(this.$data, getDefaultData())`. Here's a reference [http://codepen.io/CodinCat/pen/ameraP?editors=0010](url)

**Comment by dszmaj** [comment]
it works, thx :)

**Comment by shammadahmed** [comment]
You can do this: `Object.assign(this.$data, this.$options.$data())`

**Comment by frank0718** [comment]
Object.assign(this.$data, this.$options.data())  it works

**Comment by Ifnot** [comment]
Caution, `Object.assign(this.$data, this.$options.data())` does not bind the context into `data()`. So if you are using `this` into your `data` method you may want to apply the context with

    Object.assign(this.$data, this.$options.data.apply(this))

**Comment by wsw70** [comment]
@thollar13 : thank you for the solution. How would that work in a component where `data` is a function?

**Comment by shammadahmed** [comment]
@wsw70 `Object.assign(this.$data, this.$options.data())` works with components.

**Comment by joshua-s** [comment]
What about resetting to initial property values? And, running all lifecycle hooks?

**Comment by Cobertos** [comment]
@bradley-varol Because you're initially setting `$data._object` to `dataDefaults._object` via reference, then when you make changes to those properties and call `reset()`, it will only set `_object` back to the same object reference. Take a look at the [`Object.assign` documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).

**Comment by Cobertos** [comment]
For anyone stumbling upon this, I'd warn against using `this.$options.data`. It does not play nicely with mixins that add default data properties. Specifically I encountered bad behavior from [`vue-async-computed`](https://github.com/foxbenjaminfox/vue-async-computed) where my properties didn't seem to update after calling this.

**Comment by guarah** [comment]
Best way: http://michaelnthiessen.com/force-re-render/

**Comment by bradley-varol** [comment]
There's an excellent package that handles default data and resetting components with ease:

https://github.com/ianwalter/vue-component-reset#readme

**Comment by aislanmaia** [comment]
> You can do the above in Vue 2.0 with `Object.assign(this.$data, getDefaultData())`. Here's a reference [http://codepen.io/CodinCat/pen/ameraP?editors=0010](url)

This works for the data parent, but doesn't update the data passed to the child component.

**Comment by khandelwal-arpit** [comment]
> Best way, changing component key: http://michaelnthiessen.com/force-re-render/

Adding the key to the component did the trick for me.

**Comment by dhwanils95** [comment]
> Caution, `Object.assign(this.$data, this.$options.data())` does not bind the context into `data()`. So if you are using `this` into your `data` method you may want to apply the context with
> 
> ```
> Object.assign(this.$data, this.$options.data.apply(this))
> ```

This is a very good point to keep in mind while resetting like this because I use variables in data as key:value mapping for function calls for various scenarios:

```
      // Handlers are method definitions which I call dynamically on run-time
      optionModifierHandlers: {
        'option1': this.option1Handler,
        'option2': this.option2Handler,
        'option3': this.option3Handler,
      }
```

When you have variables like this, these do not reset automatically on just 
`this.$options.data()`

Doing this always gave me **'undefined'** values.

So, make sure you apply the context as mentioned by @Ifnot , This will once again bind the component's methods to the data variables.

**Comment by ClementT3** [comment]
> Best way, changing component key: http://michaelnthiessen.com/force-re-render/

Legendary !

**Comment by TokugawaTakeshi** [comment]
> Object.assign(this.$data, this.$options.data.apply(this))

Is this solution actual for Vue 3.X?
