### ISSUE TITLE
v-repeat on a component

### ISSUE THREAD

**Issue by knownasilya** [yyx990803/vue#703]
So currently you can't do something like: 

```html
<my-item v-repeat="item: items" v-with="item" class="item-{{$index}}"></my-item>
```

But have to do something like this, because `$index` is `undefined` and data isn't passed.

```html
<div v-repeat="item: items">
  <my-item v-with="item" class="item-{{$index}}"></my-item>
</div>
```

Here's a [jsfiddle](http://jsfiddle.net/knownasilya/wzehsenq/).

**Comment by cheapsteak** [comment]
I believe you're supposed to use `<template>`
```
<template v-repeat="item: items">
  <my-item v-with="item" class="item-{{$index}}"></my-item>
</template>
```

**Comment by knownasilya** [comment]
Sorry, jsfiddle ate my fiddle.. Will recreate.

**Comment by cheapsteak** [comment]
Your fiddle still doesn't seem to have a repeater?

**Comment by yyx990803** [comment]
Closing (inactivity)
