### ISSUE TITLE
Filters: is there any way to get the keyCode?

### ISSUE THREAD

**Issue by fullfs** [yyx990803/vue#704]
For example I've got a ```read-write``` filter placing spaces between numbers on `read` and removing it on `write`:
'1234567' => '1 234 567'

I'm using the filter on an input via v-model and I'm allowed to change the value.
So now I set my cursor near a space and going to remove it, expecting removed symbol to be a number before or after the space.
As expected - nothing happens, because no numbers has been removed.
If i could have and access to keyCode-s there I could handle the case understanding which number I need to remove (before or after the space) judging by removed symbol and keyCode.

Code example here: http://jsfiddle.net/4ty2v4fc/54/

**Comment by yyx990803** [comment]
So there's no way of getting the keyCode directly from within the filter, but you can use a separate `v-on="keydown:xxx"` listener to do that: http://jsfiddle.net/4ty2v4fc/55/
