### ISSUE TITLE
Cannot read property '_refID' of undefined in VueJS 0.11.5

### ISSUE THREAD

**Issue by TMiguelT** [yyx990803/vue#708]
This error occurs when have a v-component that points to a component that doesn't currently exist. This worked in 0.11.0, and is very annoying because if you're making a SPA with routing in VueJS, you  won't have loaded the current page component when the Vue instance is first created.

[JS Fiddle](http://jsfiddle.net/3omd4ow8/)

```html
<button v-on="click: change">Change</button>
<div v-component="{{currentView}}"></div>
```
```javascript
new Vue({
    el: "body",
    data: {
        currentView: "home"
    },
    methods:{
        change: function(){
            Vue.component("home", {
                template: "Template loaded!"
            });
        }
    }
});
```

**Comment by yyx990803** [comment]
This is not supposed to work by design. This is what you can do: http://jsfiddle.net/3omd4ow8/1/

**Comment by TMiguelT** [comment]
Okay thanks for the help. I think I'll add this to the list of things that need more user friendly error messages. I'll make a PR when I get the chance.
