### ISSUE TITLE
Child component's "ready" hook not fired

### ISSUE THREAD

**Issue by knownasilya** [yyx990803/vue#710]
http://jsfiddle.net/knownasilya/yLc6ek0b/9/

Basically if the parent view is attached in a different way, e.g. With Google Maps using `infoWindow.setContent(app.$el)`, neither the `ready` or the `attached` hooks are fired for the child components.

**Comment by BigBlueHat** [comment]
Interestingly neither parent nor child `ready` hooks are fired when using `$mount`--which I thought might let you get the VM into the DOM, then pass it to `setContent`.

http://jsfiddle.net/yLc6ek0b/10/

Curious...

**Comment by knownasilya** [comment]
@yyx990803 what are your thoughts on this?

**Comment by knownasilya** [comment]
My workaround was:

```js
infoWindow.setContent(vm.$el);
vm.isAttached = true;
```

In vm

```js
watch: {
  isAttached: function () {
    // have access to this.$el..
  }
}
```

**Comment by yyx990803** [comment]
Note the `ready` hook depends on `attached` hook, which in turn can only be triggered in two ways:
1. The element is already in the document when the vm is compiled;
2. The vm was inserted via Vue, either with a method like `vm.$appendTo()` or by a directive that controls a child vm, like `v-component`. Directly inserting the vm's element will not be able to trigger `attached`. This is stated in the docs: http://vuejs.org/api/options.html#attached

**Comment by knownasilya** [comment]
@yyx990803 so how would you handle this case?

**Comment by PavelPolyakov** [comment]
@knownasilya 

Hi,

Have you found a solution attaching vue to infowindow?

Regards,

**Comment by knownasilya** [comment]
@PavelPolyakov see my comment above https://github.com/yyx990803/vue/issues/710#issuecomment-73947012

**Comment by PavelPolyakov** [comment]
@knownasilya 
I thought you found another solution as well.

Anyhow, here:
http://forum.vuejs.org/topic/31/attaching-vue-js-to-infowindow-content-google-maps-api

I think it looks better.
