### ISSUE TITLE
checkbox directive source code is different between dist/vue.js and src/directives/model/checkbox.js

### ISSUE THREAD

**Issue by jetiny** [yyx990803/vue#711]
Vue.js v0.11.5 & v0.11.4

dist/vue.js
```javascript
	  update: function (value) {
	    /* jshint eqeqeq: false */
	    this.el.checked = value == this.el.value
	  },
```
and it's not work with safari ( osx 10)

src/directives/model/checkbox.js
```javascript
  update: function (value) {
    this.el.checked = !!value
  },
```
this code work better.

**Comment by yyx990803** [comment]
You are probably looking at `model/radio.js` in the dist file instead of the code for checkbox :)
