### ISSUE TITLE
Issues with the options directive for the select tag

### ISSUE THREAD

**Issue by TMiguelT** [yyx990803/vue#712]
I've notice two issues with `<select>`s in Vue recently.

1. The `options` directive cannot take filters. This is particularly annoying because it's rare that your data will already be in the format: `{text: "", value: ""}`
2. The `options` directive doesn't work without `v-model`. This is less likely to be a problem, but it still seems unnecessary. It's definitely possible to want dynamic select options without data binding.

Here's a [JSFiddle](http://jsfiddle.net/yye93s4g/1/) demonstrating the problems.

```html
A select with v-model and options works:
<select v-model="model1" options="arr"></select>
<br>But without v-model the options aren't shown:
<select options="arr"></select>
<br>Also filters don't work on the options argument:
<select v-model="model2" options="arr | doNothing"></select>
<br>
```

```javascript
new Vue({
    el: "body",
    data: {
        model1: "a",
        model2: "a",
        arr: ["a", "b", "c", "d"],
    },
    filters: {
        doNothing: function (value) {
            return value;
        }
    }
});
```

**Comment by calebboyd** [comment]
You could just use the option tag (add or remove v-model, filter, etc)
```html
<select> v-model="model1">
  <option v-repeat="arr | doNothing">{{$value}}</option>
</select>
```
This also has the advantage of being more explicit.

**Comment by TMiguelT** [comment]
The problem with `v-repeat`ing `<option>` tags is that if you have the scope data set *before* the template is compiled (for example if you pass data to a component using `v-with`) then the select's value isn't set at all. That's a big issue and it's why I'm using the `options` directive all the time now. But then there's these problems.

**Comment by calebboyd** [comment]
Hmm.. The `options` parameter isn't its own directive, just a `select` specific parameter to `v-model` hence expressions are not evaluated. What is the case where you want a `select` input with no output (`v-model`). That seems strange..

**Comment by TMiguelT** [comment]
Okay you might be right about that one. It's just a side point I noticed while investigating the first problem. I had a look at the source code though (https://github.com/yyx990803/vue/blob/master/src/directives/model/select.js#L60) and it seems to suggest that `options` does take an expression, it's just that for some reason it doesn't take a filter. Which seems strange

**Comment by calebboyd** [comment]
@TMiguelT you might try this 
https://github.com/calebboyd/vue/commit/23475d178c1fb141efa17a466ac476255ad2ac8b

@yyx990803, Not sure if this makes sense, perhaps just using a computed property would be preferable

**Comment by yyx990803** [comment]
`options` now support filters by merging #712 :)
