### ISSUE TITLE
Cannot read property 'teardown' of null

### ISSUE THREAD

**Issue by shuslav** [yyx990803/vue#716]
Hi,

When I subscribe the warcher to the NULL object property (e.g. keypath is 'Object.prop', where prop == null). The exception occures when I call unsubscriber.

Sample code:
```javascript
var unwatch = vm.$watch('keypath', function (newVal, oldVal) {
});

unwatch(); // here the exception fires
```
The cause of the exception is a following code (exports._destroy function):
```javascript
	  for (i in this._userWatchers) {
	    this._userWatchers[i].teardown()
	  }
```

**Comment by yyx990803** [comment]
Thanks, fixed.

**Comment by ayZagen** [comment]
@yyx990803 After updating to 2.5.21 from 2.5.17 this error occured again
