### ISSUE TITLE
webcomponentsjs breaks vue 0.11.5 in using link routing

### ISSUE THREAD

**Issue by zolo2013** [yyx990803/vue#724]
Looks like the webcomponentsjs (<script src="bower_components/webcomponentsjs/webcomponents.js"></script> in hearder) causing the dynamic component not being able to switch in version 0.11.5,  but tests in version 0.11.4 and before are all fine.  I checked the diff roughly between 0.11.5 to 0.11.4 but don't know what changes could be related to this broken. Any hint and fix? Thanks!

**Comment by zolo2013** [comment]
The issue didn't happen in chrome but in firefox. Also if I changed to include webcomponents-lite.js for firefox, the issue doesn't happen. I think it is related to the shadow dom and the 0.11.5 of Vue.

**Comment by yyx990803** [comment]
Can you make a simple reproduction of the issue?

**Comment by zolo2013** [comment]
Here is the test link http://jsfiddle.net/bju7u1bL/19/. Test it in chrome and click the link we, the view will be updated. Test it in firefox, the view doesn't change. Thanks.

**Comment by calebboyd** [comment]
Looks like `MutationObserver` is getting mangled...

**Comment by yyx990803** [comment]
Wow, this actually has nothing to do with Vue, it seems webcomponent.js breaks `MutationObserver` in both Safari and FF: http://jsfiddle.net/e2u6k4nc/1/

**Comment by yyx990803** [comment]
Filed issue there: https://github.com/webcomponents/webcomponentsjs/issues/213
