### ISSUE TITLE
Suggestion: v-ref with v-repeat-ing an object

### ISSUE THREAD

**Issue by fullfs** [yyx990803/vue#726]
http://jsfiddle.net/4ty2v4fc/57/

The thing is ```v-ref``` always returns an array of items, while those indexes are synthetic and have no relation with actual data object (which has key-names vs indexes), so from parent's vm I can't surely match indexes with object's keys.

Maybe in the case ```v-ref``` should return an object with matching key-names?
Would be nice to get the feature.

**Comment by yyx990803** [comment]
Implemented in https://github.com/yyx990803/vue/commit/67f017f2363c5decf1f97710b7f536e27d4dac35
