### ISSUE TITLE
Passing strings starting with "/" to directives (`v-sref="/route"`) breaks expression parser

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#727]
fiddle:  http://jsfiddle.net/gprhmm90/

Only seems to happen with "/" (also tried +-\ and those were fine)

**Comment by yyx990803** [comment]
The expressions are expected to be valid JavaScript, unless you set the `isLiteral` flag to true: http://jsfiddle.net/gprhmm90/1/

**Comment by cheapsteak** [comment]
Thank you! Sorry I missed that in the docs
