### ISSUE TITLE
Object value in <select>

### ISSUE THREAD

**Issue by shuslav** [yyx990803/vue#729]
Hi,
Assume I have following markup:
```html
<select v-model="objProp">
  <option v-repeat="objItems" v-attr="selected: objProp.value == value" value="{{value}}">{{text}}       
  </option>
</select>
```
and data:
```javascript
{
  objItems: [{value: 'a', text: 'A'}, {value: 'b', text: 'B'}],
  objProp: {value: 'b', text: 'B'} // ???
}
```
When an option is selected is it somehow possible to set into "objProp" whole object and not just 'value'?

Thanks!

**Comment by mikend** [comment]
First of all, you should do select boxes like this:

    <select v-model="objProp" options="objItems"></select>

And to your question: No, it's a html select box, the value is a string. If you want the whole object as value, you could use JSON.stringify and JSON.parse, though some people would consider it an ugly solution.

**Comment by shuslav** [comment]
Hello,
I know about options attribute but using repeat is more suitable in some cases. E.g. I can add 'empty' value first:
```html
<select v-model="objProp">
  <option value=''></option>
  <option v-repeat="objItems" v-attr="selected: objProp.value == value" value="{{value}}">{{text}}       
  </option>
</select>
```
Thank you for the explanation! 
If you add support of the whole object in the select it would be nice feature!
