### ISSUE TITLE
When display a list with v-repeat, orderBy and reverseKey, Couldn’t update DOM.

### ISSUE THREAD

**Issue by silvershell** [yyx990803/vue#730]
I use ver0.11.5.

When display a list with v-repeat, orderBy and reverseKey, Couldn’t update DOM.

I write HTML as follows.

```
<div v-repeat="ent : list | orderBy 'id' -1">
  {{ ent.id }}:{{ ent.name }}
</div>
```

And I execute JavaScript as follows.

```
this.list.$remove(0);
```

To remove entry of list is success. But Couldn’t update DOM.

But the following HTML can update DOM.

```
<div v-repeat="ent : list | orderBy 'id'">
  {{ ent.id }}:{{ ent.name }}
</div>
```
Is this bug?

Sorry for my bad English.

**Comment by kazupon** [comment]
@silvershell 
I tried in the [JSFiddle](https://jsfiddle.net/kazupon/03194qyy/3/), that issue did not occured.

Could you tell us your issue code ?

**Comment by yyx990803** [comment]
Closing (inactivity)
