### ISSUE TITLE
autoprefixer (or other css prefixer) with vueify

### ISSUE THREAD

**Issue by dsmilkov** [yyx990803/vue#732]
I want to run autoprefixer when building vue projects. My build includes browserify with vueify as transform. Can you give an example of how to include css post-processors in this setup? Thanks!

**Comment by TMiguelT** [comment]
This question doesn't really have anything to do with Vue. In this case you'd just use a build tool like gulp, and create two separate tasks, one that runs your .js files through browserify with the vueify transform, and one that runs your .css through a CSS prefixer.

**Comment by dsmilkov** [comment]
Thanks. The problem is that I don't have any explicit css files. Vueify transform extracts the styles from a .vue file, and inserts them with the insert-css module in the document's head.

**Comment by TMiguelT** [comment]
Ah sorry I misunderstood your question. I suspect a gulp plugin that prefixes HTML will work on Vue components, like this one for example: https://www.npmjs.com/package/gulp-html-autoprefixer

If that doesn't work you could always have separate CSS for your components, prefix them with gulp, and then require that CSS as the template property of your component options using Browserify (`template: require('style.css')`)

**Comment by yyx990803** [comment]
Currently the pre-processors supported in Vueify are hard-coded, I will think about how to make it more extensible.

**Comment by yyx990803** [comment]
Moving the discussion to `vue-component-compiler`.

**Comment by dsmilkov** [comment]
Thanks for the quick and great comments! gulp-html-autoprefixer will do for now.

**Comment by kzima** [comment]
quick gist for people who want to run autoprefixer using custom pre-processors:
https://gist.github.com/kzima/d0f173fc8f7f5bce9979

**Comment by dsmilkov** [comment]
Thanks!
