### ISSUE TITLE
Filter on partials?

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#735]
Would love to be able to filter on partials  

```
{{> myPartial | replace str1 str2}}
```

It's just a string right?

**Comment by itadakimas** [comment]
In which case do you need that approach ? Why don't you use data bindings ?

**Comment by yyx990803** [comment]
Personally I want to steer the usage toward components + content rather than partials.

**Comment by cheapsteak** [comment]
Thanks for the feature addition.  
The use case was for string replacement in large SVGs. (e.g. `<g fill="#{colorAlpha}">[...]</g>` and replace occurrences of `#{..}` with something else)
I didn't want to add the SVG string into the data because I knew it wasn't going to change and was worried that it might incur unnecessary overhead (I might be totally off/paranoid)  
Open to suggestions on better implementations
