### ISSUE TITLE
Filtered Dynamic Select Options

### ISSUE THREAD

**Issue by janschoenherr** [yyx990803/vue#739]
I was trying to filter the dynamic select options:

    <select v-model="myModel" options="myOptions | myFilter"></select>

Unfortunately, this does not seem to work. I receive a warning:

    [Vue warn]: Invalid options value for v-model: 0

 Is it not possible to use filters on options?

**Comment by calebboyd** [comment]
Those have been added in https://github.com/yyx990803/vue/pull/718

**Comment by janschoenherr** [comment]
Thanks!
