### ISSUE TITLE
watch handler seems not be called when watch array item

### ISSUE THREAD

**Issue by YuhangGe** [yyx990803/vue#741]
code as bellow:
![39523760-8872-4c1d-8c7c-e253004eb12c](https://cloud.githubusercontent.com/assets/663405/6571267/56c0be5e-c741-11e4-8a93-f8f254e72be9.png)
![67ec59ac-1fc7-47a6-b227-0c6fc4d6f323](https://cloud.githubusercontent.com/assets/663405/6571314/fcb997ea-c741-11e4-8850-708a9da2c83f.png)

![12c6510a-e3c1-4c59-9a12-0d95daa1c730](https://cloud.githubusercontent.com/assets/663405/6571275/6318717e-c741-11e4-991a-edfb3ee29349.png)
when click the Test button, only handler of "a[1].k" is called, but handler of "a[0].k" is ignored. but actually, "a[0].k" is also changed and it's new value is 888。

I don't know if it's a bug, or just vue.js's  watching strategy. When angularjs deal the same code, it calls both handlers of "a[0].k" and "a[1].k"

**Comment by yyx990803** [comment]
Vue cannot detect changes made by directly setting Array indices, e.g. `this.a[0] = 123` won't be detected. Instead you need to use `this.a.$set(0, 123)` to trigger the watcher.

**Comment by popsomemove** [comment]
<ul id="demo">
			  <li v-repeat="items" class="item-{{$index}}">
					<input lazy v-model="childMsg" value='{{childMsg}}'>
			    {{$index}} - {{parentMsg}} - {{childMsg}}
			  </li>
			</ul>

var demo = new Vue({
		  el: '#demo',
		  data: {
		    parentMsg: 'Hello',
		    items: [
		      { childMsg: 'Foo' },
		      { childMsg: 'Bar' }
		    ]
		  },
		  ready: function(){
		    this.$watch('items[0].childMsg', function(val, ov){
				console.log('a0', val, ov);
				
			})
		  }
		})

**Comment by henry-CJ** [comment]
As the [document](https://vuejs.org/v2/guide/list.html#Caveats) said, the problem is due to the limitations in JavaScript. But what is the limitaion? Could you please make it more sepecific? 
```
var arr = [1,2,3];
var _a = 0
Object.defineProperty(arr, 0, {
    set(newV) {
      console.log(newV)
      _a = newV
      return _a
    },
	get() {
      return _a
    }
})
```
In fact, I find it works when I try to detect an array.

**Comment by henry-CJ** [comment]
I have heard that array is not detected by defineProperty. But why not?

**Comment by henry-CJ** [comment]
@yyx990803

**Comment by subins2000** [comment]
Tried @yyx990803's solution, but I get :
```
TypeError: this.playerTurns.$set is not a function
```

Is `$set` the correct name ? Any more examples if any ?

**Comment by subins2000** [comment]
[This doc](https://vuejs.org/v2/guide/reactivity.html#For-Arrays) helped.
