### ISSUE TITLE
$set not correctly working on two dimensional array

### ISSUE THREAD

**Issue by arthurmuchir** [yyx990803/vue#742]
Hi, I think there is a problem with $set function when trying to modify an array item inside the array.

```
 this.part.$set(1, this.part[1].push(9));
```

Here is an exemple :
http://jsfiddle.net/avOff/cnu5uo20/1/

The result of part[1] should be 5, 6, 7, 8, 9 but it is 5 (which is equals to the length of the array).

The work around I find is to save the final array in a variable and not directly modify it, as so :
```
var tab = this.part[1];
tab.push(9);
this.part.$set(1, tab);
```

**Comment by yyx990803** [comment]
This is because `Array.prototype.push` doesn't return the array itself, it returns the length of the array after the push: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push
