### ISSUE TITLE
Perspective?

### ISSUE THREAD

**Issue by indus** [yyx990803/vue#747]
After the impressive number of commits 2-3 months ago, I wonder what the current silence means?
Is there some roadmap or plans for the future?

**Comment by yyx990803** [comment]
I'm just busy with other work recently, and also because the feature set has stabilized and I don't want to pack more into Vue core. I do have a few planned changes, mainly default `replace` to true, add `inline-template`, and some improvements to `v-repeat`.

**Comment by ayamflow** [comment]
Ah, good to know! I was wondering if you moving over Meteor would impact the release cycles.

**Comment by indus** [comment]
Thanks for the response. Sounds promising 👍
