### ISSUE TITLE
variable in class removes classes added by v-class

### ISSUE THREAD

**Issue by Nirazul** [yyx990803/vue#748]
I have following component:

```
<div class="portal portal__filterrows-{{ selectorGrid.numRows }}"
    v-class="
        class1: currentSection.header.visible,
        class2: currentSection.filter.visible,
        class3: currentSection.footer.visible
    "
>
    <div class="portal--wrap">
        Irrelevant component
    </div>
</div>
```

Both `currentSection` (on component) and `selectorGrid` (in a mixin) are computed attributes.

When I step through the attribute changes, first the classes get handled and are properly attached to the Node:

1. `<div class="portal portal__filterrows-0">`
2. `<div class="portal portal__filterrows-0 class1">`
3. `<div class="portal portal__filterrows-0 class1 class2">`
4. `<div class="portal portal__filterrows-0 class1 class2 class3">`

Then the computed class gets handled and kicks in the method `defaultHandler` of `./~/vue/src/directives/attr.js`:

```
function defaultHandler (value) {
  if (value || value === 0) {
    this.el.setAttribute(this.arg, value)
  } else {
    this.el.removeAttribute(this.arg)
  }
}

```

`value` being `portal portal__filterrows-3` instead of the new classlist from step 4.

Is there a gotcha I'm not aware of (class-vars and v-class don't work together) or is it a wrong implementation of the classlist?

**Comment by Nirazul** [comment]
Hey there! I guess it's kinda hard to comment the error without a fiddle. So I finally had the time to create one so you can look at the error (or tell me that it's working as intended):

http://jsfiddle.net/frontender/gdcrobw9/4/

**Comment by yyx990803** [comment]
Hmm, the class interpolation sets the class attribute to the evaluated string, which overwrites the classes added by `v-class`.

I think it maybe worth it to make `v-class` support taking an object (which you can make as a computed property)

**Comment by Nirazul** [comment]
Angular chooses what to do depending on the type received, maybe this is a good way to go:
https://docs.angularjs.org/api/ng/directive/ngClass

I'd also welcome the possibility to using an array:
```
computed: {
    classes: function() {
        return [
            'icon-octopus',
            isHidden() ? 'is-hidden' : '',
            getBorderClass('home'),
            { 'is-optional': true }
        ]
    }
}
```

**Comment by yyx990803** [comment]
objects are now supported in `v-class` via https://github.com/yyx990803/vue/commit/4e83218c0cbb85f99485c51938e510a6da2453a3

**Comment by Nirazul** [comment]
Cool, thank you very much for the great work! :)
Is there a way to help you push the project forward?

**Comment by yyx990803** [comment]
At this moment the most helpful thing is probably hanging out in the Gitter channel and vuejs/Discussions and help people out. Also writing tutorials / blog posts would be great too...
