### ISSUE TITLE
js transitions going in reverse order

### ISSUE THREAD

**Issue by wprater** [yyx990803/vue#749]
when using js transitions and setting a new array to a bound data property, the transitions seem to be added in reverse order.  is this as intended?

here is my transitions block example:
```
    transitions: {
      'show-achievements': {
        beforeEnter(el) {
          el.style.opacity = 0;
        },
        enter(el, done) {
          this.achievementsAnimation.to(el, 0.4,
              {opacity: 1, onComplete: done}, '-=0.15'
          );
        },
        leave(el, done) {
          done();
        }
      }
    },
```

and the transitioned data property is just being set to a new array `this.unlockedAchievements = collection`

**Comment by yyx990803** [comment]
Can you make a fiddle?

**Comment by wprater** [comment]
yes, use this fiddle: http://jsfiddle.net/wprater/utnxvf6n/2/

**Comment by indus** [comment]
I have also noticed that "ready"-events are called in reverse order in a v-repeat. In a list, "created"-events are called  from 0 to n followed by "ready"-events from n to 0. Maybe these behaviours are related?

**Comment by yyx990803** [comment]
Hmm, this has to do with `v-repeat`'s diff and move algorithm which ends up inserting instances in reverse order, and it might not be so easy to change. You might want to time your animations based on `this.$index` which is more reliable: http://jsfiddle.net/utnxvf6n/4/

**Comment by wprater** [comment]
yeah, that'll work.
