### ISSUE TITLE
filter 参数分隔符

### ISSUE THREAD

**Issue by cloudcome** [yyx990803/vue#750]
目前 filter 的参数分隔符是空格？结果出现了这样的问题：
```
beginTime | datetime MM-DD 周e
```

其中`datetime`是自定义的一个`filter`：
```
Vue.filter('datetime', function (value, format) {
    return date.format(format || 'YYYY-MM-DD HH:mm', value);
});
```

因为`format`中有空格，导致传值错误。是否可以改成这样：
```
beginTime | datetime("MM-DD 周e")
```

**Comment by calebboyd** [comment]
try `beginTime | datetime 'MM-DD 周e'`

**Comment by cloudcome** [comment]
@calebboyd  
`beginTime | datetime 'MM-DD 周e'` 也没用。

**Comment by calebboyd** [comment]
The string is passed literally as I said above, so you must escape it. This is probably a parser problem. You can get around it by doing this until it is fixed,
fiddle: https://jsfiddle.net/czb6pswb/

**Comment by cloudcome** [comment]
@calebboyd 

谢谢。
