### ISSUE TITLE
Iterating Through An Object in Array 

### ISSUE THREAD

**Issue by akifo** [yyx990803/vue#752]
It doesn't work.
I made a mistake?

> html

```html
<div id="demo"> 
	<p v-repeat="message: messages">
		<p v-repeat="message">
			--- {{$key}}: {{$value}}
		</p>
	</p>
</div>
```

> js

```javascript
var vm = new Vue({
	el: '#demo',
	data: {
		messages: [
			{
				value1: '1',
				value2: '2',
				value3: '3',
			}, 
			{
				value1: '4',
				value2: '5',
				value3: '6',
			}, 
			{
				value1: '7',
				value2: '8',
				value3: '9',
			}, 
		]
	},
});
```

**Comment by Witcher42** [comment]
Nested `<p>` tags are invalid, browsers will parse `<p><p></p></p>` to `<p></p><p></p>`. In fact, <p> cannot contain any block-level element.

So you should improve your html code, then you will solve your problem. For example, you can change your inner `<p>` to `<span>`. Here is a [demo](https://jsfiddle.net/xbpt291e/).

**Comment by akifo** [comment]
Thank you.
That was a very simple problem.

**Comment by akifo** [comment]
I have another expanded question.
Following html code has two tables.

> tableA

This table doesn't reflect to Vue model.

> tableB

This table reflects to Vue model.
then the focus will be out of focus.

> html

```html

<div id="demo"> 

	<pre>
		{{messages | json}}
	</pre>

	<table id="tableA">
		<tbody>
			<tr v-repeat="message: messages">
				<td v-repeat="message">
					{{$key}}: <input type="text" v-model="$value">
				</td>
			</tr>
		</tbody>
	</table>


	<table id="tableB">
		<tbody>
			<tr v-repeat="messages">
				<td v-repeat="messages[$index]" v-with="index: $index">
					{{$key}}: <input type="text" v-model="messages[index][$key]">
				</td>
			</tr>
		</tbody>
	</table>

</div>
```

or this my code is completely different, perhaps.

**Comment by Witcher42** [comment]
In the first table, `v-model="$value"` won't affect its parent's data. This is strange, and I'm wondering it's a bug or not.

In the second table, using `messages[index][$key]` will re-build all the nested repeat DOM, so your input box always loses the focus when you type.

Maybe you can try this way to complete your goal:

```javascript
var vm = new Vue({
    el: '#demo',
    data: {
        messages: [
            {
                value1: { value: '1' },
                value2: { value: '2' },
                value3: { value: '3' },
            },
            {
                value1: { value: '4' },
                value2: { value: '5' },
                value3: { value: '6' },
            },
            {
                value1: { value: '7' },
                value2: { value: '8' },
                value3: { value: '9' },
            },
        ]
    },
});
```

```html
<div id="demo"> 
    <table id="tableA">
        <tbody>
            <tr v-repeat="message: messages">
                <td v-repeat="message">
                    {{$key}}: <input type="text" v-model="value"/>
                </td>
            </tr>
        </tbody>
    </table>
</div>
```

Here is a [JSFiddle](https://jsfiddle.net/sg77b8n1/1/).

However, after giving every item a `value` property, the input stops losing its focus when if using `messages[index][$key].value`. This really makes me confused, I think I need some more time to step into the source code of Vue.

**Comment by akifo** [comment]
This is just the code I wanted.

```$key, $value``` won't affect its parent's data.
If I want to affect, I have to use some key, like ```value```
now I understood.

**Comment by yyx990803** [comment]
If you have further questions, please open an issue at https://github.com/vuejs/Discussion/issues
