### ISSUE TITLE
How to single out an item from a list?

### ISSUE THREAD

**Issue by it-s** [yyx990803/vue#758]
Hi,
Not sure if this is the right place to ask, but I couldn't find and forums or chat rooms.
I have a list of items in my Vue.js data:
```javascript
data: {
    editedItemData: null,
    items: [{
        title: 'item1',
        score: 3
    }, {
        title: 'item2',
        score: 2
    }]
},
methods: {
        editItem: function (item) {
          this.editedItemData = item;
        }
}
````
I visualize this items with v-repeat. So far so good. But now I would like to be able to click on each item and pass it's contents to a separate view. Edit the item values there, and then somehow send it back to main view and replace original item data with new data.
This is what I have so far:
````html
<li v-repeat="items"  v-on="click:editItem(this)">{{title}}</li>
````
Which successfully passes the item in Vue format over to editItem() function.
And finally I have the editor HTML
````html
<div v-with="editedItemData">
  <input type="text" v-model="title" />
  <input type="text" v-model="score" />
</div>
````
But I have no idea how to actually make the editor 'get' the item data, and then return it... I originally thought that v-with did exactly that, but after further research I found out I was wrong :(
Search as I might I could not find any example of doing that, or any explanation.
I'm sure it's very easy to do, but the solution escapes me somehow.

If this is not the right place for this type of questions - please let me know where is.
Thanks!

**Comment by Witcher42** [comment]
[`v-with`](http://vuejs.org/api/directives.html#v-with) can only be used with `v-component`.

You can change your editor HTML like this:

```html
<div>
  <input type="text" v-model="editedItemData.title" />
  <input type="text" v-model="editedItemData.score" />
</div>
```

**Comment by it-s** [comment]
OK thanks. I'll take this question to stack
