### ISSUE TITLE
<textarea>'s placeholder becomes its value inside <template> in IE10

### ISSUE THREAD

**Issue by fullfs** [yyx990803/vue#760]
Hello!
http://jsfiddle.net/4ty2v4fc/65/

Edit:
It fails without v-repeat too:
http://jsfiddle.net/4ty2v4fc/66/

**Comment by young-steveo** [comment]
@fullfs It's not happening for me in Chrome 41.

**Comment by fullfs** [comment]
@young-steveo yep, it's not. Check out the subject, please :) It occurs in IE10 (probably IE11 too).

**Comment by young-steveo** [comment]
@fullfs Whoops.  Missed that, sorry.

**Comment by liuyanghejerry** [comment]
A quick search shows that it is a fixed issue before: https://github.com/yyx990803/vue/issues/558 . 

I traced a while and found this issue may come from here: https://github.com/yyx990803/vue/blob/master/src/parsers/template.js#L131

When textarea is a child of template and a placeholder is set, the textarea already contained text which is actually its placeholder. And Vue doesn't handle this situation.

Wish it helps a little to this issue.

**Comment by fullfs** [comment]
@liuyanghejerry great work gathering the information, thanks!
By the way, when using v-attr="placeholder: " everything works fine (no wonder).

**Comment by liuyanghejerry** [comment]
@fullfs That's right. I guess this is the workaround for now.
