### ISSUE TITLE
Passing method to component changes `this`

### ISSUE THREAD

**Issue by angelathewebdev** [yyx990803/vue#763]
I am passing the component an options object that contains a callback, which should be invoked from the component and emit an event. Currently, when the method is invoked, `this.$dispatch('event_name')` do not point to the original view, and hence, do not have the `$dispatch` method.

From the view:
```
<template>
    <div v-component="fm-bind" v-with="options: bind_device_options">
    </div>
</template>
<script>
//view itself is a component
    data: function() {
        return {
            bind_device_options : {
                bindModifiedCallback : function(devices) {
                    this.$dispatch('modify_step', 3); //No longer dispatches the event
                }
            }
        };
    },
</script>
```

On the component itself
```
<script>
//somewhere in the script
    methods: {
        onComplete: function() { this.options.bindModifiedCallback(); }
    }
</script>
```

**Comment by nadirabid** [comment]
I don't think you can define a method in the data property of a Vue component, as it seems you've done.

**Comment by angelathewebdev** [comment]
@nadirabid then how can I pass a method into the component?

**Comment by angelathewebdev** [comment]
btw, I'm currently going around the problem by creating a closure and capture `this` value and save it as another variable

**Comment by nadirabid** [comment]
Could do the following:

```javascript

var PopupComponent = Vue.extend({
   methods: {
      open: function() {
         // method definition
      }
   }
});

```

Then instantiate the PopupComponent with additional methods:

```javascript

var popup = new PopupComponent({
   methods: {
      close: function() {
         //method definition
      }
  }
});

```

**Comment by yyx990803** [comment]
Vue does not auto-bind functions inside data objects. But binding it yourself is fine.
