### ISSUE TITLE
is this project still alive?

### ISSUE THREAD

**Issue by devmondo** [yyx990803/vue#765]
great framework, 
sorry to ask this, last comment i saw was dating back to last year, are there any plans to update this framework or it is going to be an abandoned project!

and if it is not, are their any plans to support object.observe, or create some kind of adapter like Rivets.js ?

thanks in advanced.

**Comment by yyx990803** [comment]
Hmm, check the pulse tab? I don't know how you got the impression that last comment is from last year.

**Comment by devmondo** [comment]
sorry i made a mistake i meant Commit, and you are right it is not last year it is from February, 
and what i exactly meant is do you still have plans to continue developing it or not:)

**Comment by azamat-sharapov** [comment]
Last commit on [dev](https://github.com/yyx990803/vue/tree/dev) branch was 4 hours ago.

**Comment by devmondo** [comment]
ohh, i did not see that, great to know this is still kicking, because it is awesome projet :)
