### ISSUE TITLE
关于打印select对象时的不便.

### ISSUE THREAD

**Issue by williambao** [yyx990803/vue#769]
最近刚从angular转用一下vue.js. 发现一个打印form的select对象时有些不方便.

如我有一个select对象要显示成这如下, 
```
<select v-model="selected" >
    <option v-repeat="item:items" value={{item.id}}>{{item.text}}</option>
</select>

// 下面的span我想显示 选中 select的text字段. 
// 我还需去创建一个 computed方法`selectedItem`去循环找到选中的对象
<span>您选择了: {selectedItem.text}} </span>

```

但以往在用angular的时候如下简单代码即可.
```
<select ng-model="selectedItem"  ng-options="m.text  for m in items"></select>

<span>您选择了: {selectedItem.text}} </span>
```

如果当面页面只有1~2个select对象时还好, 但是上10个select就会代码特别多了, 
如果我使用上还有未理解全的地方或有什么好的办法, 烦请告知, 谢谢:)

**Comment by 285858315** [comment]
http://runjs.cn/detail/ckervpxy
不知道能解答你的疑问不？

**Comment by yyx990803** [comment]
Vue 也有类似的语法：http://vuejs.org/guide/forms.html#Dynamic_Select_Options

**Comment by williambao** [comment]
@285858315  这个办法不错, 谢了. 

@yyx990803 你说这个办法, 需要把数据预先转换成你需要的 {text:'', value:''} 格式, 这样还是需要多做些转换工作.

**Comment by yyx990803** [comment]
`options` 属性支持 filter，所以只要定义一个转换的 filter 然后 `options="items | formatOptions"` 就可以
