### ISSUE TITLE
How should I detect incompatible browsers?

### ISSUE THREAD

**Issue by jcoffland** [yyx990803/vue#770]
I've created a large single page app using vue.js.  Now I would like to detect browsers which are incompatible with vue.js and display a helpful error message to the user.  I could grab one of many existing browser detection tools and make good guesses about which browsers should work but I would rather use [feature detection](https://msdn.microsoft.com/en-us/library/ie/hh273397%28v=vs.85%29.aspx) as that is the [recommend way to go](http://jibbering.com/faq/notes/detect-browser/).

Do you have any recommendations on how to detect which browsers should be able to run vue.js?  Would it be sufficient to just check for ```Object.prototype.__defineSetter__```?

**Comment by jcoffland** [comment]
Or perhaps ```Object.defineProperty``` would make more sense.

**Comment by yyx990803** [comment]
Yes, I think checking the presence of `Object.defineProperty` should be sufficient.

**Comment by jcoffland** [comment]
Thanks!

**Comment by BusyHe** [comment]
sorry ，my English is poor，
![image](https://cloud.githubusercontent.com/assets/17348825/22179950/ab794198-e09c-11e6-84cf-2c6baa698a03.png)
我用的是vue-cil ，lenova phone 渲染空白，
自带的低端浏览器，用其他的浏览器没问题，
我用了这个方法
```
var featureDetect = function () {
            var vueTest = ('__defineSetter__' in Object.prototype);
            var svgTest = !!document.createElementNS && !!document.createElementNS("http://www.w3.org/2000/svg", "svg").createSVGRect;
            var transitionTest = ('transition' in document.documentElement.style) || ('WebkitTransition' in document.documentElement.style);
            alert(vueTest + '//' + svgTest + '//' + transitionTest);
            return vueTest && svgTest && transitionTest;
        }
```
return is true，

How should I detect incompatible browsers

**Comment by pixelbacon** [comment]
Personally, after much testing, for Vue the minimum you need is the following:

```javascript
var compatibleBrowser = typeof Object['__defineSetter__'] === 'function';
```

**Comment by jimbatamang** [comment]
@pixelbacon this will return 'false' for ie10 where vue is working fine.
