### ISSUE TITLE
Dirty Checking on v-repeat

### ISSUE THREAD

**Issue by janschoenherr** [yyx990803/vue#771]
Hi, 

with 58247519a5f44efde78b2b056c6f1c0df9f2f3e5 you seem to have added a new dirty checking for _v-repeat_ directive. I have a case, where this does not seem to work. For me it is happening with nested lists (nested v-repeats), it works if i force a dirty check via an empty _v-transition=""_. Maybe you could add an attribute, like you did with the _inline-template_ to ensure a complete re-rendering?

I tried to show this with JSFiddle, but the Vue (edge) version does not seem to be the dev version  ;)

**Comment by yyx990803** [comment]
Can you make the fiddle anyway? It's fine as long as the code reproduces the issue locally.

**Comment by janschoenherr** [comment]
Unfortunately, I can't easily isolate the issue. Will reopen the issue, when I find out more. Thanks.
