### ISSUE TITLE
Modularization: extracting things into separate repos

### ISSUE THREAD

**Issue by alessioalex** [yyx990803/vue#774]
Hey there,

The fact is that I like some of Vue's features, such as the view Angular-like stuff: directives, filters.

However I don't want the extra stuff: event system, watching, dom functionality etc.

Would it be possible in the future to extract these by functionality into separate repos so that people can install them with NPM/bower? (for example this is how Mercury does it: https://github.com/Raynos/mercury/blob/master/index.js#L27-L43)

Thank you.

/cc @yyx990803

**Comment by yyx990803** [comment]
I think this is over-modularizing without real benefits. Vue's API is also already simple enough so if you don't need events/watching/dom, you can just pretend they don't exist - they are not going to get in your way. The only difference is you will probably save like 3~4k in eventual file size. Is it worth the non-trivial effort to modularize everything? I don't think so.
