### ISSUE TITLE
Different behavior when set Vue.config.debug to true/false

### ISSUE THREAD

**Issue by Baiqiang** [yyx990803/vue#775]
I'm using the latest Vue (0.11.5) and found a strange behavior when the debug is set to true or false.
Please see the following link on the jsfiddle: http://jsfiddle.net/drahhzmn/
Manually edit the `Vue.config.debug = false` line and run it. It shows two different results.
How can I solve this?

**Comment by Baiqiang** [comment]
@yyx990803 求解

**Comment by yyx990803** [comment]
When `debug` is true, Vue will be forced into synchronous mode for debug stack traces. So in debug mode the watcher fires immediately when you change `view`, before the child component's `compiled` hook fires; In normal mode the watcher is deferred and fires after the hook.

I agree this is somewhat confusing behavior, and I will think about how to improve this. For now I think you should try to avoid relying on the order of hooks/watchers being fired. Specifically for your example, the watcher for `view` is not needed at all.

**Comment by Baiqiang** [comment]
Thanks for your explanation. I've tried the example with the version 0.11.0 and found there's no different behavior.

As you suggested, I changed my code in order to avoid the relying.

**Comment by yyx990803** [comment]
If you have further questions, you can open new issues at https://github.com/vuejs/Discussion/issues
