### ISSUE TITLE
How to integrate with masonry

### ISSUE THREAD

**Issue by erikguo** [yyx990803/vue#778]
I'm using vue.js.  And I'm using masonry.js to create a waterfall page.  I can generate the first page of waterfall. However, when I want to do infinite items loading, I don't know where I should put "masonry.appended()" when finished items loading ( vuejs auto update the item list when data is changed).

**Comment by yyx990803** [comment]
Vue updates the DOM asynchronously, so right after you've changed your items array, call `Vue.nextTick(function () { ... })`, and in the callback the DOM would have been updated.
