### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#78]
### Core
    
  - v0.9.x: Animation and Transition ✓
  - v0.10.x: API and internal improvements ✓
  - v0.11.x: Consolidate API for future specs ✓
  - v0.12.x: Improve API to make it easier to ship standalone, reusable components and build larger-scale applications.

### Tooling

- Chrome dev tools extension ✓
- CSP-compliant build ✓ (See `csp` branch)
- CommonJS-based build setup ✓
  - Browserify + Vueify ✓
  - Webpack + vue-loader ✓
    - Scoped CSS ([WIP](https://github.com/vuejs/vue-loader/pull/13))
- Server-side rendering
- Starter Kit

### Plugins

  Please discuss plugin specific topics in each plugin's respective repo. The general philosophy for these plugins is to be light, self-contained, and most importantly avoid reinventing the wheel. Build on top of solid low level solutions and mostly just make them Vue-friendly.
  
  - [vue-touch](https://github.com/vuejs/vue-touch) ✓

  - [vue-resource](https://github.com/vuejs/vue-resource) ✓
  
  - [vue-router](https://github.com/vuejs/vue-router) ✓ (WIP)
  
  - [vue-validator](https://github.com/vuejs/vue-validator) ✓

### Community

  - Calling for user-contributed examples for tutorials!
  - Open for blog post submissions once the blog is set up

**Comment by boussou** [comment]
I tested several routers to route on bootstrap tabs change
- **pathJS** don't work https://github.com/mtrpcic/pathjs
-  **director** works fine of course but is big (10k minified without server code)
- **dispatch** works fine too: but it's 2500 bytes minified https://github.com/olav/dispatch.js

**Dispatch.js wins for me.**

other tested:
- crossroads.js is bigger (7,5k)
- scaleapp seems good (http://scaleapp.org/), but it is more a complete framework (has the size of director anyway)

**Comment by thelinuxlich** [comment]
@boussou I'm having great success with this one https://github.com/ramiel/router.js

**Comment by boussou** [comment]
Looks good, it has the same name "Router" as Director.

**Comment by kazupon** [comment]
Recently, I was held Vue.js Meeup events in japan.
http://connpass.com/event/10862/

We want to know about the future of VueJS.

@yyx990803 
Do you have the loadmap for the v0.12 or v1.0 ?

Sorry for my poor english ;)

**Comment by serapath** [comment]
i heard emberjs is building [HTMLbars](https://github.com/tildeio/htmlbars) and they started from [simpledom](https://github.com/krisselden/simple-dom). I think jsdom is pretty heavy weight and slow and for SSR not all the features are necessary.

**Comment by yyx990803** [comment]
@kazupon thanks for holding these events! Glad to see the community growing in Japan. At the moment I do not plan on adding any major new features, and I feel the API and feature set have reached a good state. The focus is stabilizing 0.11, mostly fixing bugs until the issue growth rate slows down, then it will probably be 1.0. Can't guarantee a date though.

**Comment by kazupon** [comment]
@yyx990803 
Thank you for your support in your busy time.
I've got it !! :)

**Comment by dominiquedutra** [comment]
@yyx990803 
Vue is great, really.

I am in the process of replacing some jquery buggy and bulky things with vue and is so easy to learn, understand and implement. It just gets it done.

One thing that could really improve is having a single place to discuss, learn and ask vuejs questions, and this place could be pointed out at the official website. Laravel has Laravel.io foruns and Laracasts which is currently doing a series on Vue. Thats the place to go if you want to clarify something Laravel, specially Laracasts forum.

Vuejs could really use something like that. Currently I am learning together with the guys at vueslack.slack.com.

Documentation is really good but sometimes things dont click right away, specially for those coming from jQuery only implementations. We need a place to ask and answer those "stupid questions" (that are not really stupid).

Best regards,

**Comment by aristidesfl** [comment]
@dominiquedutra there is this repo: https://github.com/vuejs/Discussion/
Do you need to be invited to that slack group?

**Comment by yyx990803** [comment]
@dominiquedutra there's an official Gitter channel (which I prefer over Slack because Gitter has better code formatting support, and you can just use your GitHub account): https://gitter.im/yyx990803/vue

**Comment by dominiquedutra** [comment]
@aristidesfl Thanks for the repo. Thats a first for me, but I guess it works just fine as a forum.
For the Slack group I dunno, just filled my info and was chatting 5 minutes later.
https://vueslack.slack.com/

@yyx990803 Evan, Didnt know about this gitter. Guess we should tell the guys at the vueslack. I think they dont know about it either. Since Vue is getting visibility on laracasts I think people are just kinda lost. For comunity I think you should point for this gitter chat and repo/discussion on the Vuejs Website on a session called comunity or something. Thats what I always look for.

Thanks, best regards.

**Comment by azamat-sharapov** [comment]
@dominiquedutra Actually the guy who created Slack channel called users of Gitter channel, through gitter itself, so he knows about it (and I think he knew before making that Slack channel). Not sure what he didn't like about gitter, it has much more users and it's growing everyday :) Gitter is meant to be for open source project hosted on github. It even has **Activity** sidebar which shows activity of repo in real time.  

Also, if you look at README of main repo, you will see [**Questions** section](https://github.com/yyx990803/vue#questions) telling you use Gitter [for more than 5 month already](https://github.com/yyx990803/vue/commit/dc1f4a94ef44dd7435058d7ed7439886fc0367d3).

If you are on laracasts, maybe comment under vuejs videos about gitter channel? I already did so, in first lesson (and even before vuejs videos).

**Comment by dominiquedutra** [comment]
@azamat-sharapov  Thanks. Just glad to know there is a place to chat.

I must admit I really didnt even glance at the README. Just used a CDN for vue.js and started coding. I am still going trough the docs :+1:

**Comment by fergaldoyle** [comment]
Great looking project you have here.

Would you consider 0.12 ready for production? I'm planning on using this in a large application framework which will evolve over time but will need to always maintain backward compatibility.

Would you consider the API final? As you release new versions, would maintain backward compatibility of deprecated features or remove them completely?

**Comment by yyx990803** [comment]
@fergaldoyle 0.12 is intended to be the last point release before 1.0, and yes, I think it is suitable for production now.

**Comment by Pandahisham** [comment]
just saw the angular 2 docs , i thinks their implementation of () for model methods , [] for property and {} for interpolation is quite pleasing , (just laughed seeing how angular 2 dumping gibberishes to become something simillar to vue. ) is there any thoughts on implementing such syntax ?

**Comment by yyx990803** [comment]
@Pandahisham I personally don't really like angular 2's binding syntax, they don't struck me as being very intuitive, and I'm not sure if they provide any meaningful advantage over the traditional directive syntax (or, at least not enough to warrant a breaking change).

**Comment by Pandahisham** [comment]
thanks , i am more than happy with the current syntax

**Comment by FWeinb** [comment]
Will vue be merged into the vuejs organization once it hits 1.0? It is a little confusing to have it here.

**Comment by yyx990803** [comment]
@FWeinb I've been thinking about it for a while, but there's a bunch of logistics to be sorted out. Moving after 1.0 sounds like a good plan.

**Comment by tcdona** [comment]
look forward to Server-side rendering !!!

**Comment by niallobrien** [comment]
I'd love to server-side rendering too. :)

**Comment by karevn** [comment]
Thumbs up for server-side rendering, too!

**Comment by yyx990803** [comment]
Moving this to the wiki.
