### ISSUE TITLE
nested track-by breaks when replacing the whole object

### ISSUE THREAD

**Issue by nkovacs** [yyx990803/vue#782]
I don't know if I'm doing something wrong, but this breaks if you click the button a couple times:
http://jsfiddle.net/nkovacs/c08kdyka/

The most common error is `"Uncaught TypeError: Cannot read property '__vue__' of null".`, but there are others too.

If I remove the v-repeat of subitems, or remove the outer track-by directive, it works.

**Comment by nkovacs** [comment]
More reproducible errors without the random:
The first item has 0 subitems, then gets 2 the second time you click the button: http://jsfiddle.net/nkovacs/c08kdyka/2/
The first item has 1 subitem, then gets 2 the second time you click the button: 
http://jsfiddle.net/nkovacs/c08kdyka/3/

**Comment by nkovacs** [comment]
Ok, I figured it out: [here](https://github.com/yyx990803/vue/blob/a06cd65e1c72beea48485a2a5a91c579c0752fa7/src/directives/repeat.js#L195) `vm._reused` is true, but it should be false. The reason: it inherits _reused from the parent vm, which has it because it's also using track-by.

**Comment by yyx990803** [comment]
Thanks for digging in and fixing this!
