### ISSUE TITLE
v-on doesn't work in component

### ISSUE THREAD

**Issue by HustLiuCN** [yyx990803/vue#785]
hello !

I create new dom by Vue.components , template is following : 

' input v-model="val" v-on="input: onInput" '

then I found that v-model works and v-on doesn't . I wonder how to fix this problem , thanks !

**Comment by azamat-sharapov** [comment]
what about `v-on="keyup: onInput"` ? or maybe better use watch:

```
...
watch: {
   'val': function(newVal) {
      this.onInput()
   }
}
...
```

**Comment by HustLiuCN** [comment]
not work . it's not about the event type or dom type , even click doesn't work .
I tried , and all dom created by template doesnt work in "V-ON", but v-model and others work , 
it seems like in jQuery , you cant use $(selector).on(...) when the dom is created by js.

and this is a list rendered by "v-repeat" , so I dont know how to watch the list item's  "val"  by using the watch method .....

so confused now TOT

**Comment by azamat-sharapov** [comment]
if you made a fiddle, we could play with it and maybe find solutions for you

**Comment by HustLiuCN** [comment]
hi , I'm back LOL

http://jsfiddle.net/liupd/98rkswu4/1/

thanks for helping !

**Comment by azamat-sharapov** [comment]
you are calling parent's `check()` method from component, that won't work. [Here is]( http://jsfiddle.net/liupd/98rkswu4/1/) how you can do, but that's not the right way to do it. You should use Vue events for this. [Something like this](http://jsfiddle.net/w1zk7vg8/). You also had mistake in your parent template with `v-with`, i changed it.

**Comment by HustLiuCN** [comment]
many thanks , u did help me a lot :-)

**Comment by AlanaMarie** [comment]
Would be nice to don't delete the jsfiddle's.
