### ISSUE TITLE
Can mixin have its own "data"?

### ISSUE THREAD

**Issue by gapipro** [yyx990803/vue#788]
So I wish to create a mixin that adds few extra methods to parent. But for that I need to store some data too.

What is the right solution for this? 
Creating `_private` data properties on parent `$data` or something else?

**Comment by yyx990803** [comment]
Do you need these data to be reactive? If not you can just attach it to the vm instance and prefix everything with your mixin name.

**Comment by gapipro** [comment]
Yes prefixing would kinda be most elegant solution for this.

**Comment by maiorfi** [comment]
Maybe something like privateMethods:{...}, privateData:{...}, privateComputed:{...} sections in options object would be better?

Ideally the should have same behavior of their non-private counterparts but not being exposed by vm instance.

At this time I usually add such sections with non-reactive members and refer to them through this.$options.privateXXX.YYY, but this is far from being best solution :)
