### ISSUE TITLE
$watch callback should also return changed property name

### ISSUE THREAD

**Issue by gapipro** [yyx990803/vue#789]
When you wish to use `$watch` in more generic way you get to the problem where you don't know what property has changed when callback is triggered. You only get old and new value.

Right now this can be solved like this:

```javascript
this.$watch(property, function(newVal,oldVal){
    self._onPropertyChange(property,newVal,oldVal);
});
``` 

But this solution is not optimal because of anonymous function that is always created. 

Can we get 3rd parameter to `$watch` callback with changed property name?

Similar solution was already presented by https://github.com/yyx990803/vue/pull/756 but there it only applies when watching `*`.

**Comment by yyx990803** [comment]
This has to take into consideration that `$watch` can accept nested paths and expressions. The cost of precisely tracking what property/path has changed in a composite watcher will be significantly more expensive than an extra anonymous function (which in reality is almost never a perf bottleneck).

**Comment by gapipro** [comment]
Yea you are right. I forgot about expressions.
