### ISSUE TITLE
I found a bug here

### ISSUE THREAD

**Issue by pucelle** [yyx990803/vue#791]
Hi, 尤小右, I created a big project using you vue.js, Thanks to your work.

and I may found a bug here:
When compiling a component, it has a _containerUnlinkFn used to unbind all the derectives, and when it create a inherited child, the child inherits it's  _containerUnlinkFn method, but when destroy this child, it called this container unlink fn, and unbind the directives which belongs to the component.

I tried to add a line of code here:
 el = transclude(el, options)
 this._initElement(el)
 this._containerUnlinkFn = undefined    //I inserted this line, and it works now.

Thanks.

**Comment by yyx990803** [comment]
Wow, good catch!

**Comment by pucelle** [comment]
Hi, I just found I should add the line of code to here to make it works... Certainly this is a temporary solution... I think you can solve it in a better way.

this._initElement(el)
options._linkFn(this, el)
this._containerUnlinkFn = undefined   //[HERE]

**Comment by yyx990803** [comment]
I already made a fix here: https://github.com/yyx990803/vue/commit/99f011b066f18e87c2b616ec9ed844ed1b24a38f
