### ISSUE TITLE
Changing array item

### ISSUE THREAD

**Issue by azamat-sharapov** [yyx990803/vue#792]
Following fiddle demonstrates issue: http://jsfiddle.net/z9qxmkuL/3/

**Comment by azamat-sharapov** [comment]
Sorry, it was just a typo :-)

**Comment by simplesmiler** [comment]
> You should avoid directly setting elements of a data-bound Array with indices, because those changes will not be picked up by Vue.js. Instead, use the augmented $set() method:
> ```js
> // same as `demo.items[0] = ...` but triggers view update
> demo.items.$set(0, { childMsg: 'Changed!'})
> ```

Object.observe is the one to blame.

**Comment by azamat-sharapov** [comment]
Oh here is use case for `$set()`. Thanks @simplesmiler :)
