### ISSUE TITLE
jQuery Plugins Support

### ISSUE THREAD

**Issue by crudbug** [yyx990803/vue#794]
How can we wrap jQuery plugins within a Vue component ? Having support for jQuery in the life cycle of a Component will be very useful.

**Comment by yyx990803** [comment]
The idiomatic way is to wrap it inside a custom directive: http://vuejs.org/guide/custom-directive.html

**Comment by vinhtq** [comment]
Can you make example for this?

I want to load jquery and other javascript libs that require jquery to work.

So how can i load other javascript libs (which maybe not compatible with requirejs). I mean some javasript lib cannot be use like: import [javascript] from '[lib]'. It is just pure lib for frontend

**Comment by simplesmiler** [comment]
@vinhtq your question is unrelated to Vue. You can read about using jquery with requirejs [here](http://requirejs.org/docs/jquery.html).

Also you can always resort to including `<script src="path/to/the/library.js"></script>` in the `<head>` and then accessing it as a global on `window` (make sure to include files in the proper order according to their dependencies).

**Comment by mudphilo** [comment]
take a look at this example

<script async src="//jsfiddle.net/mudphilo/sfzts6e2/embed/"></script>
