### ISSUE TITLE
Event Bus 

### ISSUE THREAD

**Issue by crudbug** [yyx990803/vue#795]
How do components communicate with each other ? 
From my understanding, components define events,  "namespace" : function () {}, and other components
emit ("namespace", event). 
Is everything kept in the global namespace, and string matching triggers the event ?  

I am looking through the documentation, but could not find it.

**Comment by crudbug** [comment]
To add: How can I declare a "global event receiver" component, which logs all the events. This will be very useful for debugging.

**Comment by yyx990803** [comment]
Events travel up or down the components tree depending on the method you use: http://vuejs.org/api/instance-methods.html#Events

To intercept all events globally you can simply monkey-patch `Vue.prototype.$emit`.

**Comment by yyx990803** [comment]
If you have further questions, please open new threads here: https://github.com/vuejs/Discussion/issues
