### ISSUE TITLE
Virtual DOM Support 

### ISSUE THREAD

**Issue by crudbug** [yyx990803/vue#796]
Two way binding is useful in very small usecases. Decoupling DOM management layer will enable pluggable DOM management backends.

How difficult will be support add v-dom support ?

**Comment by yyx990803** [comment]
Vue uses dom-based templating, and Vue directives allow direct access to DOM nodes. This gives the user more flexibility to work with the DOM, but also couples the implementation with a real DOM. Using a v-dom would break almost all existing code and that's not a direction I'm interested in going, at least for this project.

**Comment by thelinuxlich** [comment]
FWIW React is not even stable, it's always breaking API and doesn't feel yet like a natural way of developing webapps like Vue.js. I believe the Ember 2 vdom implementation will be much better, but still only time will tell if it is the way to go

**Comment by huangyingjie** [comment]
v-dom is useful in isomorphic app, maybe it's not Vue' goal.

**Comment by LinusBorg** [comment]
@huangyingjie Vue 2.0 has a virtual DOM now, and server-side rendering.
