### ISSUE TITLE
v-repeat不支持过滤器吗？我有个字段要读字典返回个对象，结果报错或者不起作用

### ISSUE THREAD

**Issue by lys623** [yyx990803/vue#797]

**Comment by yyx990803** [comment]
请提供具体代码。

**Comment by lys623** [comment]
https://jsfiddle.net/lys623/6busv6da/

**Comment by yyx990803** [comment]
v-repeat 不支持在过滤器里返回对象，因为对对象的支持本身就是通过过滤器实现的。用 computed property 吧。

**Comment by lys623** [comment]
谢谢，但是如果我这个读字典操作是很频繁的，那样的话在每个实例里要写computed会比较繁琐，有其他好的方法吗？

**Comment by yyx990803** [comment]
你可以在你的过滤器里手动把对象按这样的格式转成数组：`[{ $key: ..., $value: ... }, ...]`

**Comment by yyx990803** [comment]
If you have further questions, you can open new issues at https://github.com/vuejs/Discussion/issues
