### ISSUE TITLE
html模版里面的underscore语法用vue怎么转方便呢？

### ISSUE THREAD

**Issue by lys623** [yyx990803/vue#798]
<%if(window.info.pagetype!=='staff'&&window.info.pagetype!=='file'&&listtype!='file'&&window.info.pagetype!=='bs'){%>
	<select name="NoteType" style="margin-top:-20px;">
       </select>
<%}%>

**Comment by yyx990803** [comment]
建议是不要把这种逻辑写在模板里。直接在初始化 data 的时候作为一个常量放进去。
另外这类问题以后请发到 https://github.com/vuejs/Discussions/issues，这里都是关于 vue 实现或是 bug 的 issue。
