### ISSUE TITLE
Sorting table gets stuck in infinite loop

### ISSUE THREAD

**Issue by mikend** [yyx990803/vue#799]
I have a table with sorting using the orderBy filter. After clicking the column header, thus reversing the sort order, Vue gets stuck in an infinite loop, in the blockOp function. This happens only in 0.11.6, when I switch back to 0.11.5 everything works as usual.

Jsfiddle, will stick in infinite loop when clicking table header twice:
http://jsfiddle.net/kpq92t1x/2/

**Comment by yyx990803** [comment]
Hmm, not sure what change is causing the infinite loop yet, but your usage of `<template>` is not really supported. You should not be using `v-component` on a template tag. A version that works properly: http://jsfiddle.net/kpq92t1x/3/

**Comment by yyx990803** [comment]
Ah, found out where the issue is. Your usage is not standard but should work after the fix...
