### ISSUE TITLE
vue文件如何单独编译成单独的js文件，以方便按需加载

### ISSUE THREAD

**Issue by niluanxy** [yyx990803/vue#800]
目前做的一个项目，采用了vuejs的框架，然后设计上一个页面就是一个vue文件，一方便按需加载，但是目前遇到的问题是无法编译vue文件到一个个单独的js，不知道怎么处理。用的打包工具是 gulp+webpack

**Comment by yyx990803** [comment]
你是用的 vue-loader ?

**Comment by niluanxy** [comment]
是的，用的vueloader，这几天搜索了好久也没找到解决办法

**Comment by yyx990803** [comment]
你的意思是需要单独打包出来？那你可以直接用 https://github.com/vuejs/vue-component-compiler

**Comment by yyx990803** [comment]
If you have further questions, you can open new issues at https://github.com/vuejs/Discussion/issues

**Comment by yxuecheng** [comment]
@niluanxy 如何解决的？？
