### ISSUE TITLE
v-with not updating objects set via this.$set (breaking change from 0.11.5 to 0.11.6)

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#802]
Hi there,

Don't have the problem isolated into a fiddle yet, but just a heads up that a use case for watching objects seems to have broken from 0.11.5 to 0.11.6  (We noticed this when a developer on my team got a new computer and was using the same code as us but the app wasn't working, noticed the difference in Vue versions, downgraded back to 0.11.5 everything was good)

Component Alpha watches its own property 'foo', which is passed in to it via `v-with` from the parent component Beta.

In the template, `<div v-component="alpha" v-with="foo: parentFoo">` (not sure if this matters, but the component alpha is also in a v-repeat)

Beta sets `parentFoo` in its `compiled` hook via `this.$set('parentFoo', {key1: val1, key2: val2})`

In 0.11.6, the child component (alpha)'s `foo` will be `undefined`

Fiddle incoming (either lunch of after work)

**Comment by salazr** [comment]
Same problem here. One of our developers ran into it this morning.

In our app, removing v-with worked to get the app running again. Luckily we're just a couple of weeks of development into the app so there is not a lot that breaks by changing this.

**Comment by yyx990803** [comment]
Hmm, would love to get a jsfiddle repro of this,

**Comment by yyx990803** [comment]
Pushed a fix to `dev` branch. Please try it and see if it fixes the issue - and do let me know if there are other breaks after the upgrade! Thanks for reporting the issues.

**Comment by cheapsteak** [comment]
Sorry I'm failing google or google's failing me,  
How can I do an npm install from the dev branch?

**Comment by yyx990803** [comment]
`npm install yyx990803/vue#dev`

**Comment by cheapsteak** [comment]
That didn't seem to do the trick ("version": "0.11.7", "_from": "git://github.com/yyx990803/vue#dev")
I'll put together a fiddle when I get home :)

**Comment by cheapsteak** [comment]
Unfortunately still seems broken in 0.11.8 :(

**Comment by cheapsteak** [comment]
working in 0.11.5:
http://jsfiddle.net/5sH6A/97/

broken in 0.11.6 through 0.11.8
http://jsfiddle.net/Le3sdytu/4/

**Comment by yyx990803** [comment]
Turns out it was a small optimization attempt that wasn't carefully thought through: https://github.com/yyx990803/vue/commit/58247519a5f44efde78b2b056c6f1c0df9f2f3e5#diff-c052e1f68cd9ca32c302763fb617e335R123

It's now fixed in dev for real in branch.
