### ISSUE TITLE
TodoMVC is broken

### ISSUE THREAD

**Issue by azamat-sharapov** [yyx990803/vue#803]
1. Go to [vuejs todomvc on todomvc.com](http://todomvc.com/examples/vue/) or [on vuejs.org](http://vuejs.org/examples/todomvc.html)
2. Add several items
3. Switch to **Active** tab and check items

You should notice issue with UI. Same thing happens in Completed tab. 

This issue was originally reported by @farzher in [gitter chatroom](https://gitter.im/yyx990803/vue).

**Comment by yyx990803** [comment]
Thanks! Looks like the new inplace update algorithm for `v-repeat` still needs more tweaking. I've decided to remove it from the current codebase to ensure stability. Will probably revisit it in a later release.

**Comment by yyx990803** [comment]
Fixed with 0.11.8 release. I see that you submitted the PR that updated Vue to 0.11.6 in TodoMVC, would you like to do that for 0.11.8 as well? :)

**Comment by azamat-sharapov** [comment]
@yyx990803 sure! :) will do in couple of minutes

**Comment by farzher** [comment]
That was fast o_O :+1:

**Comment by azamat-sharapov** [comment]
[Submitted](https://github.com/tastejs/todomvc/pull/1267). Thanks for quick responses, Evan!
