### ISSUE TITLE
vue 0.11.8 子组件中第一个component不会编译bug

### ISSUE THREAD

**Issue by niluanxy** [yyx990803/vue#805]
我用  Vue.component 方法生成了一个 mg-header 的组件，然后我动态的生成了一个 vue 对象，这个对象有用到这个指令，直接使用的 <"mg-header"></"mg-header"> 的方式，然后我用 $mount 动态编译以后，发现动态生成的对象中的第一个 component 永远不会被编译

**Comment by yyx990803** [comment]
自定义标签里面不需要引号，如果不是这个问题请提供代码...

**Comment by niluanxy** [comment]
代码已经上传，将下面的图片下载下来，后缀改为 zip 解压即可，整个项目是用的 gulp + webpack 工作的，加上自己写的框架部分，所以我全部没压缩，你可以直接搜索下关键词 mg-header 就能找到出问题的组件的源码。

![vbug zip](https://cloud.githubusercontent.com/assets/7076522/7323175/526a31c0-eadf-11e4-8634-f92f22f4b8d4.jpg)

**Comment by yyx990803** [comment]
确认是 bug，正在着手修复

**Comment by yyx990803** [comment]
Fixed in dev branch. 在新版本发布前你可能需要手动 build 一下 dev 版本的 vue。
