### ISSUE TITLE
vue.js 0.11.8 not on cdnjs

### ISSUE THREAD

**Issue by jcoffland** [yyx990803/vue#807]
[This page](http://vuejs.org/guide/installation.html) has a broken link to 0.11.8 on cdnjs.  It would be great if this version was on cdnjs.

**Comment by yyx990803** [comment]
Hmm, they usually auto track the latest release from npm within 30 hours. Opened issue over there: https://github.com/cdnjs/cdnjs/issues/4580

**Comment by jcoffland** [comment]
Thanks.  Hopefully they get this fixed soon.
