### ISSUE TITLE
还是 component 的bug，还是嵌套的问题

### ISSUE THREAD

**Issue by niluanxy** [yyx990803/vue#809]
<p>这个bug和上次给你提的类似，代码和上次一样，不同的是我把具体的代码都包装了一层，然后最外层的组件就不会编译，一直如此。原来的模板是：</p>
```vue
<mg-header></mg-header>
<mg-content></mg-content>
```
<p>然后现在新的是：</p>
```vue
<mg-page>
    <mg-header></mg-header>
    <mg-content></mg-content>
</mg-page>
```
<p>然后最外层的 mg-page 就不会编译。已经用的是你上次更新了Bug得dev版本。</p>

**Comment by yyx990803** [comment]
还是得看代码重现...

**Comment by niluanxy** [comment]
代码上就是我贴出来的，额，你需要的话，我一会传一个上来，顶层的为啥不能是组件了。

**Comment by yyx990803** [comment]
我本地按你所说的嵌套测试无法重现，没有你的代码很难定位是为什么，而且你打包过的代码我看起来也很累。开 issue 的一个良好习惯是自己提供一个最简洁的 bug 重现，帮我节省了时间我才能更快地 fix。

**Comment by niluanxy** [comment]
恩，我整理了下，上传上来了，方式和上次一样，还是图片改后缀。
![vbug zip](https://cloud.githubusercontent.com/assets/7076522/7367226/7e68527c-edd0-11e4-961c-b7322e5a9971.jpg)

**Comment by yyx990803** [comment]
原因是你的组件在 loadView 里面都被设置成了 `replace:true`，所以 `<mg-page>` 就变成了 user 组件的根元素；这样的话它就即得是 user 的根元素，又得是 mg-page 的根元素，编译的时候会跳过后者。

办法有几个：

1. user 组件和其他页面组件定义为 `MgPage.extend({ ... })`
2. 把 mg-page 作为一个 mixin
3. 不要用 `replace: true`（外面留一层）

**Comment by niluanxy** [comment]
行，我试试吧

在2015年04月29日 22:15，Evan You 写道:

原因是你的组件在 loadView 里面都被设置成了 replace:true，所以 <mg-page> 就变成了 user 组件的根元素；这样的话它就即得是 user 的根元素，又得是 mg-page 的根元素，编译的时候会跳过后者。

办法有几个：

user 组件和其他页面组件定义为 MgPage.extend({ ... })
把 mg-page 作为一个 mixin
不要用 replace: true（外面留一层）
