### ISSUE TITLE
Suggestion: new v-component option - replace

### ISSUE THREAD

**Issue by fullfs** [yyx990803/vue#810]
I'm used to use ```v-component``` with ```<template>``` sometimes when I want to keep all related elements inside the component's template.
So now 0.11.8 is out and using ```v-component``` on ```<template>``` is broken: ```$``` object of the component is always empty, regardless of how many times ```v-ref``` is used.
I remember ```<template>``` is not supposed to be used with ```v-component``` to begin with (could we add warnings for the case?), so now I'm asking for some kind of replacement:
Add a new ```v-component``` option - ```replace``` 
Using ```<div class="holder" v-component="name" replace></div>``` will result ```.holder``` to be completely replaced by component's template elements (instead of getting inside) ```.holder```  so the ```$el``` will not be ```.holder``` but a top-level element inside component's template. If there are more then one top-level element - lets throw a warning.

I mean something like this:
```
new Vue({
    el: 'body',
    components: {
        name: {
            template: '<article></article>'
        }
    }
});


<body>
    <div class="holder" v-component="name" replace></div>
</body>
```
will be compiled to

```
<body>
    <article></article>
</body>
```

**Comment by azamat-sharapov** [comment]
> So now 0.11.8 is out and using v-component on <template> is broken: $ object of the component is always empty, regardless of how many times v-ref is used.


It is working: http://jsfiddle.net/azamatsharapov/v8r4yepd/ or did I misunderstand you?

**Comment by fullfs** [comment]
@azamat-sharapov 
Aye, right. Looks like the case in not that simple. Maybe its when its ```<template>``` inside ```<template>```. Need to check it out more carefully

**Comment by yyx990803** [comment]
Why don't you use the `replace` option?

**Comment by fullfs** [comment]
@yyx990803 Oooops. Looks like I've been missing something reeeeaaaly important for so daaaamn long...
Thanks man. Going to cry now :D
Need some eye examination o something -_-

**Comment by azamat-sharapov** [comment]
You simply need to change your glasses to another one, like Evan's.

**Comment by yyx990803** [comment]
;)
