### ISSUE TITLE
"t.parentNode is null" with component in template content

### ISSUE THREAD

**Issue by jcoffland** [yyx990803/vue#811]
I ran into a strange bug that took me awhile to isolate.  Here's a fiddle demonstrating the bug:

  http://jsfiddle.net/nt5hhvje/3/

The issue is that components inside of triple curly braces are normally not instantiated.  However, if the component is inside template content, reference with a ```<content>``` tag, then it does get instantiated, but incorrectly.  When you try to remove the incorrectly instantiated component Vue.js crashes with the error ```TypeError: t.parentNode is null```.  Or at least that is the error message in Firefox.

Ideally, component instantiation would be allowed in triple curly braces but if this is not feasible then it should be treated the same everywhere.  In my case, the template was much higher up in the hierarchy of my application.  When I ran into this problem it was not at all clear that the template higher up had changed semantics for the components underneath it.

**Comment by jcoffland** [comment]
BTW, the error exists in 0.11.8 and at least back to 0.11.5.

**Comment by yyx990803** [comment]
Yeah, triple curly braces should be static everywhere. I'll look into the issue, but in general a good idea to avoid using directives inside it though.

**Comment by yyx990803** [comment]
This error is fixed in `dev` branch now - all triple-curly HTML are now always static (i.e. its content are never compiled).

**Comment by jcoffland** [comment]
Ok, thanks.
