### ISSUE TITLE
Tries to trigger setters of string expressions, resulting in `Left side of assignment is not a reference` or `Invalid setter function body`

### ISSUE THREAD

**Issue by cheapsteak** [yyx990803/vue#813]
fiddle: http://jsfiddle.net/xjbnttw7/1/

in Chrome: this warning is given `Invalid setter function body: 'bar'`

in Safari and IE, we get `ReferenceError: Left side of assignment is not a reference.`

![image](https://cloud.githubusercontent.com/assets/743976/7418112/4f2411c6-ef39-11e4-8e71-e99f00a8b2b8.png)

This causes IE10 apps to break, but other browsers seem to be fine ignoring it

**Comment by cheapsteak** [comment]
I wonder if this is the same issue as https://github.com/yyx990803/vue/issues/776

**Comment by yyx990803** [comment]
Fixed now on `dev` branch.
