### ISSUE TITLE
$index on v-repeat with orderBy

### ISSUE THREAD

**Issue by rogierborst** [yyx990803/vue#814]
When using `v-repeat`, I understand you can use `$index` inside the loop to get the array index of the current object. If you'd use `v-repeat` on say, a list item, this means that the top / first `<li>` has `$index = 0`, the second `$index = 1`, etc.
But when you use an `orderBy` filter on that `v-repeat`, there is absolutely no guarantee that the first `<li>` has `$index = 0`, because `$index` is pointing to the index of the original array, not the *re-ordered* array.

What I'd like to do, is inside the `v-repeat` compare the currently processed object with the previously processed object, i.e.:
```html
<ul>
    <template v-repeat="objects | orderBy 'date' | filterBy search 'title'">
    <!-- $index-1 might not be the previously processed object -->
    <li v-if="objects[$index -1].date !== objects[$index].date">---</li>
    <li>{{title}} - {{date}}</li>
    </template>
</ul>
```

This works great when the original array was already ordered by date, but if it was not - and let's, for the sake of the argument, assume that it wasn't - this becomes a mess. `v-repeat` first orders the array by date, then loops over the array in that new order, but inside each loop `$index` refers to the position in the unordered array.

Here's what worked for me in Angular, to illustrate how it could be handled:
```html
<ul>
    <li ng-repeat-start="object in (orderedObjects = (objects | orderBy: 'date' | filter:title))"
        ng-if="object.date != orderedObjects[$index-1].month">
    <li ng-repeat-end>{{object.title}} - {{object.date}}</li>
</ul>
```

Here a new, temporary array is created (`orderedObjects`) with the correct order and now $index points to the index in that ordered array, instead of the original one (`objects`).

Any way to achieve this with Vue?

**Comment by yyx990803** [comment]
You can define a filter `as`:

``` js
Vue.filter('as', function (list, key) {
  this[key] = list
  return list
})
```
``` html
<template v-repeat="objects | orderBy 'date' | filterBy search 'title' | as orderedObjects">
  ...
</template>
```

**Comment by rogierborst** [comment]
Ah yes, simple but effective! Thanks!

**Comment by timavo** [comment]
I got a list of `users` which are displayed with `v-repeat`. 

HTML: 
```
<ul id="vue">
    <li v-repeat="users | orderBy 'name'" v-on="click: onClick($index)">@{{ name }} | @{{ phone }}</li>
</ul>
```

JavaScript:
```
new Vue({
    el: '#vue',

    data: {
        users: [
            { name: 'Berta', phone: '555-123-4567' },
            { name: 'Delta', phone: '999-123-4567' },
            { name: 'Anton', phone: '888-123-4567' },
            { name: 'Echo', phone: '333-123-4567' },
            { name: 'Charlie', phone: '444-123-4567' }
        ]
    },

    methods: {
        onClick: function(index) {
            this.users.$remove(index);
        }
    }
});
```

If I just use `v-repeat="users"`, I can access the original user with `this.users[$index]`. However, if I manipulate the list by ordering and/or filtering (e.g. `v-repeat="users | orderBy 'name'"`), `$index` points to the element in the ordered list.

What I'd like to do is removing an element from the original `users` array. As stated above `this.users.$remove($index)` only works on the original `v-repeat`, not on filtered or ordered lists.

**Comment by blogui91** [comment]
This was done with Vue 0.* But how do you achieve this with Vue 1.0.*?? 
@yyx990803 
Thanks in advance
