### ISSUE TITLE
Replacing component $data from parent

### ISSUE THREAD

**Issue by azamat-sharapov** [yyx990803/vue#815]
While coding super urgent thing quick at late night, hoping that I could replace component's `$data` from parent, I failed to get the thing working: http://jsfiddle.net/azamatsharapov/9kw9bpo4/1/

The code doesn't look ideal, but I don't know why it doesn't work. I'm thinking, that `this` is being in parent's context, but maybe I'm wrong.

**Comment by yyx990803** [comment]
Instead of `this.$.childRef.$options.methods.refresh();` you should just call `this.$.childRef..refresh();`. The former will not have the correct `this` context.

**Comment by azamat-sharapov** [comment]
I swear I was going to write like that, but didn't, can't remember why :smile: 
Thanks Evan!
