### ISSUE TITLE
v-repeat with v-component and paramAttributes 

### ISSUE THREAD

**Issue by holic** [yyx990803/vue#816]
http://jsfiddle.net/rynrj5Ls/

When using `v-component` in a `v-repeat`, I'm able to compile a statement using the properties of each item in the `v-repeat` directive:

```js
data: {
  items: [ { view: 'someComponent', value: 'someValue' } ]
}
```

```html
<div v-repeat="item: items" v-component="{{ item.view }}"></div>
```

However, I cannot use `paramAttributes` or `v-with` values from the items within the `v-repeat` for compiling the component, like this:

```html
<div v-repeat="item: items" v-component="{{ item.view }}" v-with="value: item.value"></div>
```

Is this intended?

**Comment by holic** [comment]
I've worked around this by wrapping the component in a `v-repeat` to separate the contexts:

```html
<template v-repeat="item: items">
  <div v-component="{{ item.view }}" value="{{ item.value }}"></div>
</template>
```

**Comment by holic** [comment]
I should note that my specific use-case is using a property name defined in each item to access a property on its parent data.

**Comment by yyx990803** [comment]
Yeah, the dynamic v-component being able to access the repeated context is a special convenience (although possibly a confusing one); when using a component, other directives on the repeat container will be compiled in parent scope. Using a wrapper in this case is the recommended solution.

**Comment by holic** [comment]
Thanks for the clarification @yyx990803.
