### ISSUE TITLE
Cannot use comments in view templates when using `replace: true`

### ISSUE THREAD

**Issue by zfedoran** [yyx990803/vue#817]
The transcludeTemplate() function tries to add attributes to comment nodes. I believe it should check whether the node is a comment.

![image](https://cloud.githubusercontent.com/assets/623790/7457977/88734bf4-f25e-11e4-9097-60ed7adeb60c.png)

I may be doing something wrong here so feel free to correct me.

**Comment by yyx990803** [comment]
Yeah, this is a known bug and this part has been refactored in the `dev` branch (and will be fixed with 0.11.9 release)
