### ISSUE TITLE
官方文档里没有提到v-on能够监听的event的列表

### ISSUE THREAD

**Issue by AMAID** [yyx990803/vue#823]
example中提到了click和keyup两个事件 这显然不是标准的dom事件 建议把能够监听的事件补全

**Comment by yyx990803** [comment]
就是标准的 dom 事件啊...

**Comment by AMAID** [comment]
标准的dom event名是onclick和onkeyup吧，如果支持所有的标准dom event的话可能是我代码的问题，谢谢！

**Comment by yyx990803** [comment]
onclick 不是事件名，而是让你添加事件侦听的 attribute。click 才是事件名。

**Comment by AMAID** [comment]
基本功不扎实 见笑了！
