### ISSUE TITLE
Component inline-template with v-repeat in <template>

### ISSUE THREAD

**Issue by qrotux** [yyx990803/vue#824]
After updating from 0.11.8 to 0.11.10 catch up a bug with inline templates: 
Vue doesn't handle component variables in template when using **template** tag with v-repeat and v-component. But with **div** tag and *replace* option anything is ok.

Example: https://jsfiddle.net/nj7L5pg4/1/

**Comment by dalphyx** [comment]
从0.11.8升级到0.11.9和0.11.10也发生了类似的bug。
定义一个component test-a如下：
```javascript
Vue.component('test-a', {
    template:
        '<div v-on="click: onClick">aaaa</div>',

    methods: {
        onClick: function(e) {
            console.log("aaa");
        }
    }
});
````
再定义一个component test-b如下：
```javascript
Vue.component('test-b', {
    template:
        '<test-a v-repeat="list"></test-a>',

    data: function() {
        return {
            list: [{time: 1}, {time: 2}, {time: 3}],
        }
    }
});
````
在0.11.8中点击test-a的div里正常触发事件，在0.11.9和0.11.10中不会触发事件，只有把test-b中的template改成：
```javascript
'<div v-component="test-a" v-repeat="list"></div>'
````
才能得到正常结果

**Comment by yyx990803** [comment]
@dalphyx 你说的情况我没法重现，能不能提供个 jsfiddle?
