### ISSUE TITLE
Can I use the dynamic arg in v-style?

### ISSUE THREAD

**Issue by canjianx** [yyx990803/vue#826]
Like this: 
```html
<div v-style="{{dir}}: pos.y"></div>
```
https://jsfiddle.net/5hfc0zhm/

I know I can use computed value.  But there is issue in IE.
```html
<div style="{{computedValue}}"></div>
```

Thanks,

**Comment by yyx990803** [comment]
You can just do
``` html
<div v-style="computedValue"></div>
```
`v-style` accepts a string of inline CSS.

**Comment by canjianx** [comment]
It works.  The css are split by ";" not ",".

Thank you very much.
