### ISSUE TITLE
v-attr doesn't set paramAttributes (regression from 0.11.8)

### ISSUE THREAD

**Issue by nkovacs** [yyx990803/vue#827]
With 0.11.10 and 0.11.9: http://jsfiddle.net/nkovacs/1y88paqc/

With 0.11.8: http://jsfiddle.net/nkovacs/ne0s266e/

Also, with 0.11.8, when the expression in v-attr changes, the value in the component is not updated, see the first "click me" example. Using v-with (the second "click me") fixes it, I'm not sure if it's intended that way, but it would be great if v-attr worked there, since it works with normal html elements (e.g. the class updates on the true/false div and causes it to change its color).

**Comment by yyx990803** [comment]
Hmm, `v-attr` is supposed to work with normal attributes only. Although this happened to worked in the past versions, I don't really recommend such usage.

Instead of `v-attr` you can simply do this:

``` html
<app-foo footext="{{foo ? 'you clicked me' : 'click me'}}"></app-foo>
```

**Comment by nkovacs** [comment]
You're right, I got so used to v-attr that I didn't even think to just use the normal attribute syntax.
But what I'm saying is, components are essentially custom elements, and it would be great if they worked the same as normal elements.
