### ISSUE TITLE
Priority of v-with and v-repeat

### ISSUE THREAD

**Issue by zhongqf** [yyx990803/vue#829]
When using both `v-repeat` and `v-with` on a component, it seem that `v-with` is processed first. But in angular, ng-repeat has a higher priority as I know.

http://jsfiddle.net/xefvfsgy/1/

**Comment by yyx990803** [comment]
This is not a priority issue.
In the second case, `item` is only available as a property of the component itself, but `v-with` can only bind `name` to a parent scope property.
The first case works because the outer `v-repeat` provides an extra layer of scope in between.

**Comment by zhongqf** [comment]
means that the proper way to combine `v-with` and `v-repeat` on component should be using the `template` tag?  like this: http://jsfiddle.net/xefvfsgy/2/

a little weird, but acceptable. close it.
