### ISSUE TITLE
v-repeat $index param

### ISSUE THREAD

**Issue by guzz** [yyx990803/vue#831]
Hello, since the lasts commits the param $index is not working with v-repeat class.

If I use like this `<div v-repeat="users" class="user-{{$index}}"></div>` it always shows undefined as the `$index`, but when I use it com the style... it works.

It is strange becase befoure I was using a parameter from the users itself, like: `<div v-repeat="users" class="user-{{id}}"></div>` where `{{id}}` is a user parameter, and it worked.

**Comment by yyx990803** [comment]
This has been fixed in `dev`.
