### ISSUE TITLE
Mixins use?

### ISSUE THREAD

**Issue by maiorfi** [yyx990803/vue#832]
Hi. Could you please elaborate a little mixins sample? I'd like to use it in order to inherit some common viewmodels behavior, but did'n get how to do that.

Thanks!

**Comment by yyx990803** [comment]
Have you read the example here? http://vuejs.org/guide/extending.html#Extend_with_Mixins
Let me know if you feel the example wasn't clear enough, I can work on improving the doc.

**Comment by maiorfi** [comment]
I spotted that code snippet on guide, but I can't understand if, for
example, I can leverage that way in order to add a private section (both
for hidden data members and methods) to my viewmodels.

Also, where module.export and require api shown in your sample come from?

Thanks.
Il 12/mag/2015 00:22, "Evan You" <notifications@github.com> ha scritto:

**Comment by yyx990803** [comment]
Every field inside a mixin will be mixed into your component's `$options` object, not the component instance itself. If the component's own options contains the same fields, then those fields will be merged together.

For example, you may have multiple components that need the same `created` and `destroyed` hooks. It's tedious to define the same hooks for all of them, so you can extract those hooks into a mixin and just let those components all use the same mixin.

I'm not sure what do you mean by a hidden section, but you can always add an object to the vm instance and use that as the namespace for your private stuff. e.g. in the created hook, set `this._myPrivateStuff = {}`. Just make sure the key is unlikely to conflict with other people's code.

The `module.export` and `require` assumes you are using a CommonJS module bundler to build your app (which was explained in the section before, "Building Larger Apps").

**Comment by maiorfi** [comment]
I got it: thanks!
