### ISSUE TITLE
Resetting forms

### ISSUE THREAD

**Issue by Ahmad-Ibrahim** [yyx990803/vue#833]
It clears the inputs but data is still there

http://jsfiddle.net/5a6z6xmk/

**Comment by yyx990803** [comment]
You'll have to add a `reset` listener to the form element and reset data there. This might be a bit inconvenient but it gives you the flexibility to reset to a set of non-empty default values.

**Comment by Ahmad-Ibrahim** [comment]
Oh I thought it should empty the data automatically, I just figured out that resetting a form doesn't fire it's inputs change events.

**Comment by jimmywarting** [comment]
bummer

**Comment by YUN-RU-TSENG** [comment]
> You'll have to add a `reset` listener to the form element and reset data there. This might be a bit inconvenient but it gives you the flexibility to reset to a set of non-empty default values.

nice
