### ISSUE TITLE
"replace: true" component with v-repeat on root node

### ISSUE THREAD

**Issue by zhongqf** [yyx990803/vue#835]
```javascript
var app = new Vue({
    el: '#app',
    template: '<div v-component="child"></div>',
    components: {
        "child": {
            replace: true,
            template: '<div v-repeat="item: items">{{item}}</div>',
            data: function(){
                return {
                    items: [1,2,3]
                }
            }
        }
    }
});
```

In the above case, child component can not be rendered properly. ( vuejs version: 0.11.10 )
            
I created a fiddle for this: http://jsfiddle.net/xefvfsgy/7/

By the way, in the fiddle, when I do
 * switch a class by toggle v-class condition's value.
 * do some heavy calculation in child component.

the transition on the class will be blocked until the calculation completed.
 
I know this may not be a bug, but how can I fix it?

**Comment by zhongqf** [comment]
@yyx990803 thanks to fix it.

About the second problem, I can only reproduct it in Yosemite + chrome(41.0.2272.118).
In Yosemite + Safari, or in Win7 +  chrome(41.0.2272.118),  or Win7 + IE11
it looks OK.

"OK" means that the browser wait until calculation completed then start to transition.
But in Yosemite + Chrome, it looks that transition started when button clicked, but not refreshed until calculation completed.
It is difficult to describe this behavior. Maybe put a video or animated gif will be helpful.

**Comment by yyx990803** [comment]
This probably has to do with how Chrome handles CSS transitions.
But why are you doing heavy computations in a computed property? It doesn't sound like a good idea in the first place.

**Comment by yyx990803** [comment]
Closing since the `v-repeat` on root node issue has been fixed in `dev` branch.
