### ISSUE TITLE
Possible Digest bug

### ISSUE THREAD

**Issue by knownasilya** [yyx990803/vue#838]
https://github.com/yyx990803/vue/blob/master/src/instance/scope.js#L117

If length is 1, the index will be `1` and the result will be `undefined`.

**Comment by yyx990803** [comment]
If length is 1, `i` will be 0 because `i--` was evaluated before the while block is executed. This is a common pattern.

**Comment by knownasilya** [comment]
Yeah, but somehow it doesn't work always, so I updated that pr to just check if the result is truthy before calling `update`.

**Comment by yyx990803** [comment]
Closing for now - the error might be thrown by some other bug, but the line mentioned here is not the source of the problem.
