### ISSUE TITLE
Is there something like vm.$once('viewUpdated', callback)?

### ISSUE THREAD

**Issue by fenivana** [yyx990803/vue#840]
Sometimes we need to use a jQuery plugin or dependency-free library after a view update, which will read attributes and properties of a element, for example, a form validation plugin. But at that point, the view hasn't been updated. Now I'm wrapping the code in setTimeout(), it is tricky and no guarantee it will work. Is there a better method to achieve this?

**Comment by fenivana** [comment]
OK, I saw Vue.nextTick().
http://vuejs.org/api/global-api.html#Vue-nextTick\(_callback_\)

**Comment by azamat-sharapov** [comment]
also, if this helps you somehow, [from docs](http://vuejs.org/api/instance-methods.html#vm-\$watch\(_expression\,_callback\,_\[deep\,_immediate\]_\)):

> vm.$watch returns an unwatch function that stops firing the callback
