### ISSUE TITLE
$watch multiple properties for single callback

### ISSUE THREAD

**Issue by nadirabid** [yyx990803/vue#844]
What do you think about being able to `$watch` over an array of data properties for a given callback? 

```javascript
$watch(['x', 'y', 'z'], function() { 
  // do something 
});

// or 

$watch('x', 'y', 'z', function() { 
  // do something
});
```

Not exactly pressing as I can easily make do with multiple `$watch` statements.

**Comment by yyx990803** [comment]
I don't think this is an improvement significant enough for further complicating the API, but thanks for the suggestion :)

**Comment by devinfd** [comment]
I know this is an old request but I've just encountered this "need" and it would be super nice to have. Rather than doing:
```js
$watch('x', function() { 
  this.doSomething(); 
});
$watch('y', function() { 
  this.doSomething(); 
});
$watch('z', function() { 
  this.doSomething(); 
});
```

**Comment by Nirazul** [comment]
You could easily do something like this:

```
...
methods: {
    baywatch: function(arr, cb) {
        var self = this;
        arr.forEach(function(val) {
            self.$watch(val, cb.bind(self));
        })
    }
},
...
```

...and then do: `this.baywatch(['a', 'b', 'c'], this.doSomething);`.
You could even make a mixin out of it, so you can use it everywhere you want.

**Comment by young-steveo** [comment]
@Nirazul 's solution is good, but you should maybe leave the context binding to the calling code to be more useful as a ixin:

```js
methods : {
    baywatch : function(props, watcher) {
    	var iterator = function(prop) {
            this.$watch(prop, watcher);
        };
        props.forEach(iterator, this);
    }
},

//...

this.baywatch(['a', 'b', 'c'], this.doSomething.bind(this));
```

**Comment by devinfd** [comment]
Yes this is a viable solution.

**Comment by Gubbi** [comment]
How can the above be done during extend and not on per instance basis?

**Comment by ThatTomPerson** [comment]
You could look into making a plugin
http://vuejs.org/guide/plugins.html

I can't write an example at the moment but look at some of the other plugins on that page and see how they add methods to the `Vue.prototype`

**Comment by PeppeL-G** [comment]
I was looking for this feature as well.

I have three `data` variables binded to three input elements in a form, and I need to listen for changes to any of these three `data` variables and then update a canvas through a third party library. Using `watch` and pass it an array of `data` variables that should trigger my single `watch` function does seem like the simplest solution to me. Does anyone has another solution? I don't want to rely on a plugin/own code modifying `Vue` for this simple case.

**Comment by just-nobody** [comment]
```js
$watch('x', 'y', 'z', function() { 
  // do something
})
```
This form seems sensible enough to implement. If it's not hard to document, I'm for it.

**Comment by sirlancelot** [comment]
For this, I would just build a computed property which is derived from your desired properties, then watch that:

```javascript
const $app = new Vue({
    computed: {
        compoundProperty() {
            // `.join()` because we don't care about the return value.
            return [this.x, this.y, this.z].join()
        }
    },
    watch: {
        compundProperty() {
            // do something
        }
    }
})
```

**Comment by amirrustam** [comment]
@sirlancelot Very nice solution. 

Whenever I need a computed property to accomplish this, I append `Watchable` to the computed property name. So a computed `myProperty` would become `myPropertyWatchable`. This is personal convention, and I'm sharing in case someone out there finds it useful.

**Comment by fnlctrl** [comment]
It can be made simpler to just reference the reactive properties, and then return a value that's guaranteed to be different every time.
This way we avoid a performance overhead of an array operation in the original example by @sirlancelot, though it should be trivial in most cases.

```js
new Vue({
    computed: {
        compoundProperty() {
            // it's only required to reference those properties
            this.x;
            this.y;
            this.z;
            // and then return a different value every time
            return performance.now()

            // object literals also work but we don't need that overhead
            // return {}
            // return []
        }
    },
    watch: {
        compoundProperty() {
            // do something
        }
    }
})
```

**Comment by simplesmiler** [comment]
Here's my two cents.

In 1.x watchers supported expressions, so you could globally mix in a `$touch` method that would just return `Date.now()` (or in other way generate unique value), and then define a watcher for `$touch(x, y, z)`, and it would be called every time `x`, `y` or `z` were changed. Demo: https://jsfiddle.net/pdjygyhg/3/

In 2.x you can not just watch an expression, and have to define a computed prop to watch instead. So the best way I can think of is to ease the creation of computed field: https://jsfiddle.net/kmj6Lsae/2/

**Comment by ndabAP** [comment]
Just wanted to also add my two cents.

I got a situation where I also have to watch for two variables. But as already mentioned: I don't think that if it would be possible naively this would be a significant improvement, too.

**Comment by g8up** [comment]
and how to debounce the callback function ?

**Comment by cimenx** [comment]
I also encounter a similar situation when I need to watch multiple state change in some component.
```javascript
computed: {
    ...mapGetters('bim', [
      'folders',
      'items'
    ]),
    ...mapState('bim', [
      'projects',
      'activeProject'
    ])
  },
  watch: {
    // wait listProjects action to be completed before listing folder
    projects: function (projectObj) {
      this.listFolders()
      this.listItems()
    },
    activeProject: function (projectName) {
      this.listFolders()
      this.listItems()
    },
    items: function (itemObj) {
      this.listRelations()
    },
    folders: function (folderObj) {
      this.listItems()
    },
  },
```

**Comment by SergioCrisostomo** [comment]
@sirlancelot very interesting solution! `+1`
 
A small suggestion would be to use `new Date();` as return value, since `Date.now();` is _Number_ and can give same result if things happens fast.

Buggy example: https://jsfiddle.net/Sergio_fiddle/hdqgyLvx/
Consistent example: https://jsfiddle.net/Sergio_fiddle/hdqgyLvx/1/

**Comment by bigsee** [comment]
@sirlancelot thanks for a nice solution! +1

**Comment by yyx990803** [comment]
FYI you can directly watch a getter via `$watch` without the need for a separate computed property:

``` js
this.$watch(vm => [vm.x, vm.y, vm.z].join(), val => {
  // ...
})
```

**Comment by btoo** [comment]
i think @sirlancelot and @yyx990803 's solutions pose risks to performance because you have to construct an entirely new object just for the sake of hashing multiple watchers, which is particularly dangerous when you want to hash a large number of watchers together. wouldnt it be safer to define all the watchers at build time? with the spread operator and a simple reducer, this can be done with relatively little clutter (my guess is this is pretty similar to how vuex does it):
```js
watch: {
  ...['form.application', 'form.team', 'form.market'].reduce((acc, key) => {
    acc[key] =  function(val){
      console.log('updated', this, key, val)
    }
    return acc
  }, {}),
}
```
it would be nice if a utility function to map watchers were provided too:
```js
import { mapWatchers } from 'vue'

...

watch: {
  ...mapWatchers([
    'key1',
    'key2',
    'key3'
  ], function(newVal, oldVal){ // maybe add key as the third param?
    ...
  })
}

**Comment by denwerboy** [comment]
This solution worked pretty well for me without dealing performance issues that may be caused by computed props.
```javascript
Vue.prototype.$watchAll = function(props, callback) {
  props.forEach(prop => {
    this.$watch(prop, callback);
  });
};
```

and then in any component I can use it, for instance, like this
```javascript
this.$watchAll(["state.price", "state.amount"], this.onStateChange);
```

**Comment by guillermovs** [comment]
Based on @denwerboy's solution - pass the watched property name to the callback function.
Useful to save changes to localState automatically
```
Vue.prototype.$watchAll = function(props, callback) {
  props.forEach(prop => {
    // Pass the prop as the first argument to our callback
    this.$watch(prop, callback.bind(null, prop));
  });
};
```
Then call `$watchAll` on mount and inspect the arguments
```
this.$watchAll(["field1", "field2"], function(){ console.log("change @", arguments) });
```

**Comment by matthew-dean** [comment]
Ractive solves watching multiple paths with the asterisk, so you could do things like:
```js
this.$watch('*', function() { ... });
this.$watch('root.*', function() { ... });  // passes in individual sub-properties when they change, and not `root`
```
Seems strange you can't easily define a single callback watcher for multiple properties in Vue.

**Comment by Christilut** [comment]
I wanted to watch all my data props because I emit them as v-model together in a single object. I ended up going for this:
```js
    Object.keys(this._data).forEach(key => {
      this.$watch(key, () => {
        this.emit()
      })
    })
```

**Comment by ctf0** [comment]
maybe another solution could be
```js
updated() {
        this.$nextTick(() => {
            if (this.first || this.second) {
                this.doSomething()
            }
        })
    },
```

**Comment by sirlancelot** [comment]
Evan's solution is already the best. Here's my slight adaptation to avoid array construction:

```javascript
this.$watch(
    (vm) => (vm.x, vm.y, vm.z, Date.now()),
    function () {
        // Executes if `x`, `y`, or `z` have changed.
    }
)
```

**Comment by posva** [comment]
This thread seems to have bikeshed a lot while answers have been already provided. Let's stop it here so this doesn't get worse and to prevent spamming around 20 people 😛 

See https://github.com/vuejs/vue/issues/844#issuecomment-335026928 and https://github.com/vuejs/vue/issues/844#issuecomment-390498696 for solutions
