### ISSUE TITLE
v-html 里加 v-on 可以么？我试的好像不行

### ISSUE THREAD

**Issue by 285858315** [yyx990803/vue#846]
v-html 里加 v-on 可以么？我试的好像不行，有解决这种需求的其它方案没？

**Comment by 285858315** [comment]
改用原生的怎么样？

**Comment by yyx990803** [comment]
v-html 只用于输出静态 html，不支持指令编译。这样设计是因为不建议基于模板组织应用，而是应该合理运用组件。
