### ISSUE TITLE
载入html模版有没有简单类似angular的cache机制呢

### ISSUE THREAD

**Issue by hepking** [yyx990803/vue#847]
感觉现在使用.vue的办法有点麻烦，定义了一种新的模版格式，还得去熟悉它，无疑增加了学习成本；一般html编辑器也无法智能提示了，写起来太麻烦，增加了使用成本。angularjs那种put，get获取缓存的方式不是更好吗？
能加一下联系方式吗，我QQ 99186610 微信 hepking

**Comment by hepking** [comment]
组件中如何支持templateUrl呢？

**Comment by hepking** [comment]
查看源代码发现template支持＃id，为啥文档中没有呢，感觉还是这种办法方便。总体来说这个库还是很方便的啊...

**Comment by 285858315** [comment]
智能提示和编辑器有关，和.vue没关系吧？你用的什么编辑器？

**Comment by hepking** [comment]
phpstorm，唉，可能不熟悉这东西，很多东西不知道怎么解决，我还是不用这个框架了。Vue 有事件通知吗？ 如何利用jquery,zepto这些来处理事件呢？头疼

**Comment by hepking** [comment]
其实这东西就个简单的模版替换，但是因为不知道渲染完成的回调，对接个东西真是太麻烦了...

**Comment by 285858315** [comment]
看文档没？cn.vuejs.org 看完再问好么？

**Comment by hepking** [comment]
使用#id 传入模版的时候，怎么避免id重复呢？ 如果组件跟模版在同一个文件？

**Comment by 285858315** [comment]
我现在基本不设 ID ,只把 body 挂上就行了。

**Comment by hepking** [comment]
加我一下QQ聊吧，这样费劲啊
