### ISSUE TITLE
npm install 0.12.0-beta2

### ISSUE THREAD

**Issue by loranger** [yyx990803/vue#854]
I was wondering why my components were not working locally but perfectly on JSFiddle : 
```bash
npm install vue
```
Installs the 0.12.0-beta2 version instead of 0.11.10

**Comment by yyx990803** [comment]
0.12 brings some breaking changes (see release notes: https://github.com/yyx990803/vue/releases)
You can just pin it to a specific version: `npm install vue@0.11.10`

**Comment by yyx990803** [comment]
I've also tagged 0.11.10 as the default installed version.

**Comment by loranger** [comment]
That's exactly what I did, once I figured out what happened, but I thought it would be useful to warn you the newbies (like me) may be messed up with the doc ;)

Now I see the release notes and I wonder what are the official replacements for v-component and v-with which I beacome to be fond of.

By the way, thank you so much for this awesome library !

**Comment by yyx990803** [comment]
0.12 is still in development, you can follow along the discussion here: https://github.com/vuejs/Discussion/issues/158
