### ISSUE TITLE
入门文档 列表展示  {{$index}}没有输出索引呀

### ISSUE THREAD

**Issue by zb188** [yyx990803/vue#858]
我们程序是thinkphp， 模版里使用 {{$index}}，我怀疑页面当成php模版标签解析了
 thinkphp的模版标签是这样 {$xxxx}
页面上显示是这样 的 {}-Bar
我把我的页面完全写成静态的打开是可以显示 索引的
@yyx990803 在不改php模版引擎的情况下这个问题怎么解决？
````html
<ul id="demo">
  <li v-repeat="items" class="item-{{$index}}">
    {{$index}} - {{parentMsg}} {{childMsg}}
  </li>
</ul>
````
````js
var demo = new Vue({
  el: '#demo',
  data: {
    parentMsg: 'Hello',
    items: [
      { childMsg: 'Foo' },
      { childMsg: 'Bar' }
    ]
  }
})
````

**Comment by ppq1991** [comment]
这个没问题吧

https://jsfiddle.net/x7jtunn4/

**Comment by yyx990803** [comment]
http://cn.vuejs.org/api/global-api.html#Vue-config
`Vue.config.delimiters = ['[[', ']]']`
