### ISSUE TITLE
Plugins: vue-resource, vue-validator

### ISSUE THREAD

**Issue by steffans** [yyx990803/vue#859]
Hi Evan,

First thanks for creating this great framework! I have been using it actively over a few months now, building the upcoming release of our open source CMS called Pagekit. While developing it we needed some extra features which are not available right now. So we started to create our own Vue plugins.

https://github.com/pagekit/pagekit/tree/develop/vendor/assets/vue-resource
https://github.com/pagekit/pagekit/tree/develop/vendor/assets/vue-validator

Both plugins work similar like their Angular counterparts. I know those plugins were mentioned in some discussions already, so we want to share our efforts with the Vue community.

Let me know what you think!

**Comment by yyx990803** [comment]
Wow, really nice! I had plans for these very early on, but obviously never had enough bandwidth to actually get to them myself. I would love having these as standalone projects and help them get more exposure/contribution.

**Comment by yyx990803** [comment]
There is currently another vue-validator project maintained by @kazupon, but vue-resource definitely could fill in a gap that's been missing.

**Comment by kazupon** [comment]
@steffans 
>we want to share our efforts with the Vue community.

:+1: 
Welcome your efforts.
I hope that VueJS community users to increase more.

**Comment by steffans** [comment]
Yes, sure standalone projects for the plugins would be nice. The vue-validator plugin implementation differs from the current one. It works without a `v-model` and provides form events for `valid` and `invalid`. @kazupon might take a look at the plugin and maybe some features can be merged?

**Comment by azamat-sharapov** [comment]
Cool! I would test/use vue-resource for almost all apps using vue, if you ship it as standalone plugin (+ npm, if possible). Many thanks for sharing!

**Comment by 285858315** [comment]
@steffans 
<img src='https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png' />

**Comment by kazupon** [comment]
@steffans 
I looked at the vue-validator plugin implementation of your project.
I maybe merge some features (built-in validators, `valid` or `invalid` event).

But i cannot merge forms `name` attribute based validation.
Because the design philosophy of validation is different in vuejs/vue-validator and vue-validator of your project.
(We can't tell which is better...)

**Comment by kazupon** [comment]
I looked at the vue-resource of pagekit/pagekit project.
cool !!

I think that we should share as the standalone project of vuejs/vue-resource maintained by @steffans .

**Comment by steffans** [comment]
@kazupon Yes, the validator plugin is based on the current Angular implementation, which uses the name attribute. I like the idea of moving the resource plugin to vuejs/vue-resource. Just add me to the repo and i will move the current code.

**Comment by yyx990803** [comment]
@steffans I've invited you to the vue-resource team under the vuejs org :)

**Comment by okoala** [comment]
:+1:
