### ISSUE TITLE
How to delete a model in a recursive component

### ISSUE THREAD

**Issue by jasonvarga** [yyx990803/vue#860]
I'm trying to build a page tree similar to your [tree view example](http://vuejs.org/examples/tree-view.html).

How would you go about adding a way to delete a node? For example an `x` button that would just delete itself on click.

The example code looks like:

```
Vue.component('item', {
  template: '#item-template',
  // ...
  methods: {
    addChild: function () {
      this.model.children.push({
        name: 'new stuff'
      });
    }
  }
  // ...
});
```

Adding a `deletePage` method makes sense there, but I don't know how you'd reference that particular model from the root model.

Any help would be appreciated.

**Comment by yyx990803** [comment]
You can just do `this.$parent.model.children.$remove(this.model)`

**Comment by jasonvarga** [comment]
Great, I missed `this.$parent` somehow. Thanks!

I'm now seeing `Uncaught TypeError: elem.getAttribute is not a function` when I delete the node, but something tells me that's unrelated.

**Comment by yyx990803** [comment]
Directly accessing `this.$parent` is usually not recommended, but in this case of recursive components, it makes things easier. Otherwise, you could use the event system to send an event to the parent to make it more decoupled.

**Comment by layanto** [comment]
Does this still work with latest vuejs? I tried replacing $remove with $delete but getting this,$parent.model.children.$delete is not a function error.

In the jsfiddle for tree view example, I changed the @dblclick to call "delItem" method and I added delItem method as follows:
```
methods: {
  delItem: function () {
    this.$parent.model.children.$delete(this.model)
  }
}
