### ISSUE TITLE
Uncaught TypeError: Cannot read property 'entry**deep**' of null

### ISSUE THREAD

**Issue by holic** [yyx990803/vue#864]
https://github.com/yyx990803/vue/blob/dev/src/api/data.js#L74

I'll attempt to reproduce this in a JSFiddle, but this happens when navigation (with `vue-router`) before I'm able to load external data (`entry`) into the VM. The same component had a deep watcher set up on `entry`, then `entry` is unset before trying to load a new entry (caused by navigation).

**Comment by yyx990803** [comment]
Let's move this to `vue-router`, since this is more likely caused by the router implementation.
