### ISSUE TITLE
filter parameters with spaces

### ISSUE THREAD

**Issue by nkovacs** [yyx990803/vue#865]
I'm writing a filter to do date formatting. I'm using vue 0.12.0-beta3 and moment.js.
If I do this: `{{today | date YYYY MM DD}}`, the parameters are split by space, so my filter only uses the first part. If I do this: `{{today | date 'YYYY MM DD'}}`, the filter parameter will be a string that contains the single quote marks, so the date will be rendered like this: '2015-05-24'.

**Comment by nkovacs** [comment]
jsfiddle with the workaround: http://jsfiddle.net/nkovacs/k8ra0mn3/

**Comment by azamat-sharapov** [comment]
I can confirm this, quote were passed for me too, once upon a time (from 0.11.[something]). I thought that's ok behaviour, so just removed quotes manually. 

BTW, i was doing the same thing, but without moment.js :)

**Comment by nkovacs** [comment]
Yeah, I think most of the time you don't want quotes, so it would make more sense for vue to strip them. And if you do need them, you can use alternating quotes.

**Comment by yyx990803** [comment]
The reason it contains quotes is so that the filter can differentiate between raw strings vs. dynamic bindings. e.g. in `filterBy 'key'` vs. `filterBy key`

**Comment by nkovacs** [comment]
Ah, I see. The problem with this though is that if someone writes a filter without using stripQuotes, it will not be able to accept parameters with spaces. For example, using pluralize: http://jsfiddle.net/nkovacs/q1ash4Le/

**Comment by yyx990803** [comment]
Hmm, good point. There two options:

1. Auto-strip quotes in built-in filters. Although this means every custom filter also need to do that.
2. Make filter syntax more consistent - all strings should be in quotes, and if not they are treated as a data property on the vm.

I think it may be a good opportunity to introduce the second in 0.12.

**Comment by nkovacs** [comment]
My filter now sometimes receives an object instead of a simple string:
```js
{
  dynamic: false,
  value: "YYYY-MM-DD"
}
```

Other times it's just a string. Is this normal?
```
<a href="/{{day.date | date 'YYYY-MM-DD'}}">
    <strong>{{day.date | date 'dddd'}}</strong>
    <date>{{day.date | date 'D MMM'}}</date>
</a>
```

The one in the href receives an object, the other two receive strings.

**Comment by nkovacs** [comment]
Looks like attributes cause it to become an object: http://jsfiddle.net/nkovacs/fybr2tvw/

**Comment by yyx990803** [comment]
@nkovacs noted, will fix in next beta release.

**Comment by nkovacs** [comment]
Thanks
