### ISSUE TITLE
有没有配套的html编辑器可用呢？

### ISSUE THREAD

**Issue by hepking** [yyx990803/vue#867]
一般数据不同步，不知道怎么调整才合适

**Comment by yyx990803** [comment]
完全不明白你的意思...

**Comment by hepking** [comment]
textarea 设置为一个html编辑器的话，如何同步vue的数据与编辑器里面的数据

**Comment by hepking** [comment]
vue中如何使用kindeditor这样的编辑器，并且能自动的同步数据？

**Comment by yyx990803** [comment]
写一个自定义指令 (custom directive)，自己在指令里做同步。

**Comment by hepking** [comment]
好的，有什么不懂的再请教一下
