### ISSUE TITLE
Setting a property to an array after it was initialized to an empty object causes mayhem

### ISSUE THREAD

**Issue by dhruvio** [yyx990803/vue#869]
Hi, thanks for your great work.

Have a look at this fiddle: https://jsfiddle.net/mjgd383x/4/

Imagine you create a Vue instance where some attribute in the data hash is initialized to an empty object. Then, the attribute is rewritten to an array full of data. One would expect directives like v-repeat (etc) to pick up on this. However, the bindings seem to get messed up and some directives don't work as expected.

The fiddle above should exemplify this issue.

Let me know if you need any further info.

-Dhruv

**Comment by yyx990803** [comment]
The fix has landed in 0.12 beta, however in general I would advice against such usage; try to use consistent data format for the same `v-repeat` block.

**Comment by dhruvio** [comment]
Thanks
