### ISSUE TITLE
What is the order life-cycle events are fired relative to child components?

### ISSUE THREAD

**Issue by sjoerdvisscher** [yyx990803/vue#871]
In particular I'd like to know if the `ready` events on child components are fired and handled before it is fired on the parent component.

**Comment by yyx990803** [comment]
life-cycle events fire from bottom up, so child components' hooks fire first.

**Comment by sjoerdvisscher** [comment]
Cool, thanks. Is this documented somewhere?

**Comment by yyx990803** [comment]
Hmm I don't think this is explicitly documented, I'll add them when updating the docs for 0.12.
