### ISSUE TITLE
Pagination with filterBy issue

### ISSUE THREAD

**Issue by korymarks** [yyx990803/vue#872]
How am I able to update my pagination (which are data properties and computed properties), when I use the filterBy filter? I have 1,283 students as a property but when I use the filterBy I want to be able to change my computed properties to reflect my search. Does that make sense?

**Comment by lucacri** [comment]
I have precisely the same question

**Comment by yyx990803** [comment]
Not quite sure if I get what you mean... maybe a code snippet?

**Comment by mcallan83** [comment]
I believe I am having a similar issue. I have an array of objects in my data that I am using to populate a list on the front end using `v-repeat`. It works great, but there doesn't seem to be a way to access just the filtered records from within the javascript to make calculations or perform other actions.

If I have 30 records total, but then I filter them with a filterBy and only 5 show in my <ul>, is there an easy way to get an array with just those 5 filtered records?

**Comment by azamat-sharapov** [comment]
@mcallan83 using [`v-ref`](http://vuejs.org/api/directives.html#v-ref): 
http://jsfiddle.net/azamatsharapov/r8gL4c65/

**Comment by mcallan83** [comment]
Wow... exactly what I was looking for. Thank you!

**Comment by yyx990803** [comment]
Closing because original author hasn't provided further explanation. Also this is a non-bug which should be moved to vuejs/Discussion if anyone wishes to continue the discussion.
