### ISSUE TITLE
$add problem

### ISSUE THREAD

**Issue by butsalt** [yyx990803/vue#873]
```html
<div id="app"></div>
<div id="app2"></div>
````

```javascript
var Vue = require("vue");

var data = global.data = {
	foo: {
		bar: "something"
	}
};

var app = global.app = new Vue({
	data: data,
	template: "<div>{{foo.bar}}</div><div>{{foo.bao}}</div>"
}).$mount("#app");

var app2 = global.app2 = new Vue({
	data: data.foo,
	template: "<div>{{bar}}</div>"
}).$mount("#app2");
```
Then I invoke $add in console
```javascript
data.foo.$add("bao","koo")
```
Nothing happened.
I think that might because  data.foo has been observed as app2's root $data. So when I invoke $add, it is helpfull with app2, but it will not trigger the deps that on data.foo.

**Comment by OEvgeny** [comment]
Yes, seems not work correctly. Fiddle for this http://jsfiddle.net/Lh6h0Ly0/

**Comment by azamat-sharapov** [comment]
So `app.$add('bao', 'koo')` won't work for you case?

**Comment by azamat-sharapov** [comment]
Actually it should be `data.$add('foo.bao', 'koo')` instead of `data.foo.$add('bao', 'koo')`.
