### ISSUE TITLE
如何注入原生的指令，比如 v-repeat

### ISSUE THREAD

**Issue by niluanxy** [yyx990803/vue#875]
我现在的项目是依赖于vue的，然后我自己为VUE写了一套UI组件，现在有个问题时，有一个scroll的组件，需要在每次repeat后重新初始化一下，然后我想直接注入原生的v-reapt方法，在每次repeat以后执行下我的代码，请问如何做到？

**Comment by yyx990803** [comment]
在 repeat 依赖的数据变动之后，调用 `Vue.nextTick`。

**Comment by niluanxy** [comment]
Vue.nextTick我原来用过，感觉不是很精确，不能直接注入 v-reapt ，v-if 之类的指令中吗？

**Comment by yyx990803** [comment]
除非你加了 transition，不然我想不出有什么理由 nextTick 会不精确... 不过我也听别人说过类似的问题，所以如果你能提供个 nextTick 不能满足需求的例子最好了。

**Comment by yyx990803** [comment]
先关了，注意是在改动了数据之后立刻 Vue.nextTick 哦。如果还是有问题再重开好了。
