### ISSUE TITLE
How to bind DOM stuff with v-el to Vue objects

### ISSUE THREAD

**Issue by dejan7** [yyx990803/vue#876]
Might be a noobish question, but i don't see how can i can do this:
  
    <div class="app">
        <input type="radio" v-on="click: clickRadio"> 
        <div class="test {{selected ? '' : 'hidden'}} v-el="test">...</div>
    </div>

        var app = new Vue({
            el: '.app',
            methods: {
                clickRadio: function() {
                    this.$$.test.selected = true;
                }
            }
        });

I would expect this to add/remove class "hidden" to the div ".test" when you toggle the radio button, but that's not the case because, as far as i can tell, this.$$ is an array of DOM objects, not vue object. 
So how can i bind a DOM object to Vue object? I hope that this makes some sense.

**Comment by yyx990803** [comment]
`v-el` simply gives you a reference to the raw DOM node. Also, you should use `v-model="selected"` on the radio. I would suggest reading through the whole guide if you haven't done so.
