### ISSUE TITLE
v-model not working without default values

### ISSUE THREAD

**Issue by uwe** [yyx990803/vue#877]
http://jsfiddle.net/5sH6A/101/

Only if an initial value is set (for checkbox three), the output is working properly. For the other checkboxes the selected Object is changed, but nothing changes on the output.

**Comment by uwe** [comment]
There seems to be a general problem with new properties in $set: http://jsfiddle.net/5sH6A/102/

**Comment by yyx990803** [comment]
This is a limitation of the current path parser, which doesn't handle dynamic path segments, thus not being able to call `$add` for keys that do not exist.

This will be improved in the future, but the best practice is to prefer always providing default values, and only use `$set` sparingly.

**Comment by uwe** [comment]
Ok, I understand. But in my second fiddle, if I change the $set to $add - it also does not change the output. Or is this the bug you fixed yesterday in https://github.com/yyx990803/vue/commit/5a0de87805540c7c4128341c84e2e7d6fc9fcea2 ?

**Comment by azamat-sharapov** [comment]
Interesting, if you `$add` before `$set`, it works: http://jsfiddle.net/azamatsharapov/5sH6A/103/ (using 0.12.0-beta5).

**Comment by yyx990803** [comment]
@uwe that's an unrelated fix. `$set` simply calls `$add` under the hood if a key is not present, but only when the path is static and can be checked "step by step". If the path is dynamic, `$set` will just evaluate it as an expression.

**Comment by yyx990803** [comment]
This is now supported in `dev` branch via https://github.com/yyx990803/vue/commit/34da031bdc6a01f276a2d3482174323ea00ab8b7. However there will also be a warning suggesting you to pre-initialize the fields.
