### ISSUE TITLE
filterBy's IN searches all fields all the time (beta-5)

### ISSUE THREAD

**Issue by BrandonSurowiec** [yyx990803/vue#880]
So I have an object inside of another object in my data:

```
    data: {
        employees: [
            { name: 'John', age: 50, company: { name: 'Paul Ice'} },
            { name: 'Paul', age: 34, company: { name: 'John Deere'} }
        ]
    }

```

Trying to filter by only the employee name, but not the company name. It doesn't work. It seems like the entire array is searched.

JS Fiddle:
https://jsfiddle.net/ousthgdp/2/

1. Searching for 'Paul' should only show 'Paul', not 'Paul' & 'John'
2. Searching for an age shouldn't return anyone

Am I doing something wrong or is this a bug?

**Comment by azamat-sharapov** [comment]
You need to wrap `name` with quotes, otherwise Vue will look up for data property of vm. So, instead of `filterBy searchText in name` you need to write `filterBy searchText in 'name'`.

**Comment by BrandonSurowiec** [comment]
Thank you! I didn't realize I had to pass it in as a literal string, I thought I was in the employee scope. :)
