### ISSUE TITLE
failed to resolve component

### ISSUE THREAD

**Issue by mark-hahn** [yyx990803/vue#883]
I've had a moderate size app working for some time and I somehow broke it.  I stripped the app down to find out what change broke it and I got all the way down to this small example.  But even this is getting `[Vue warn]: Failed to resolve directive: component`.  Can someone please tell me why this doesn't work?

```
Vue = require 'vue'

Vue.component 'header', 
  template: '<div>Hello World</div>'

document.body.innerHTML = 
  '<div v-component="header"></div>'

new Vue
  el: 'body'
```

**Comment by mark-hahn** [comment]
Some more info: When I select this line in the Elements tab of the selector ...
```
<div v-component="header"></div>
```

I see this ...

![screenshot 2015-05-30 at 4 02 22 pm](https://cloud.githubusercontent.com/assets/811455/7899753/577ee09e-06e5-11e5-92cc-52c389f0ad35.png)

**Comment by mark-hahn** [comment]
And, I'm running ...

vue@0.12.0-beta5
chromeos browser
  Version 42.0.2311.153 (64-bit)
  Platform 6812.88.0 (Official Build) stable-channel samus
  Firmware Google_Samus.6300.103.0
ubuntu 14.0.4

**Comment by mark-hahn** [comment]
This was a problem with Vue in the beta version.  I had the package.json dependency set as `"vue":"*"` and accidentally got the beta version (which I didn't expect).  When I set it to `"vue": "^0.11.0"` I got `vue@0.11.10` and everything worked.

Was this an intentional change or a bug?

**Comment by yyx990803** [comment]
Please refer to this thread for the upcoming breaking changes in 0.12: https://github.com/vuejs/Discussion/issues/158
