### ISSUE TITLE
Vue & polymer?

### ISSUE THREAD

**Issue by maiorfi** [yyx990803/vue#884]
Hi.

Did anybody try using Vue together with Polymer, for example by designing a view containing some Polymer components bound to a Vue viewmodel?

Is there any technical limitation in that sense that could make two "layers" clash?

Thx!

**Comment by azamat-sharapov** [comment]
I think this is not appropriate place for your question. There is [vuejs/Discussion](https://github.com/vuejs/Discussion/) repo for that.

**Comment by yyx990803** [comment]
^ what azamat said

Polymer is based on Web Components spec, most importantly, custom elements. To use Vue components as custom elements, see https://github.com/vuejs/vue-element

**Comment by kristianmandrup** [comment]
Now find it at [vue-custom-element](https://github.com/karol-f/vue-custom-element)

**Comment by yordis** [comment]
@yyx990803 why you deprecated that package? I would love to see Vue Core Team supporting Custom Elements in the ecosystem ❤️

**Comment by JAugustoGuimaraes** [comment]
Polymer 3 is the best path for WebComponents.  
Vue should accept any WebComponent from any library.  
WebComponents is W3C Standard!

**Comment by Justineo** [comment]
As I understand it’s already supported if you correctly configured [`ignoredElements`](https://vuejs.org/v2/api/#ignoredElements) in Vue.
