### ISSUE TITLE
v-model not properly updated when used in v-repeat

### ISSUE THREAD

**Issue by nevsnode** [yyx990803/vue#886]
Hi,

I'm currently running against an issue I have with Vue (latest stable version).

Basically I have a variable list of input fields with a dynamic v-model like this:
```
<div v-repeat="mails">
    <input type="email" v-model="mails[$index]" />
</div>
```

I'm facing the issue that the values from the input fields do not get updated immediately when changed.
But it does happen when using a method that pushes a string to the mails array.

Here's a jsfiddle: http://jsfiddle.net/qyrjwn9e/
When entering values to the input fields, nothing happens but as soon as you press 'add', another input field appears and the current values are shown.

If its just me who's doing something wrong I'd love to hear that, too ;-)

**Comment by yyx990803** [comment]
In general you should avoid binding `v-model` like this to an Array of primitive values. Use objects so that `v-model` can mutate the object: http://jsfiddle.net/yyx990803/qyrjwn9e/1/

**Comment by nevsnode** [comment]
Ah, I see, thanks for taking the time and the heads-up :+1: 
Works as it should now.

Looking forward for 0.12!
