### ISSUE TITLE
filter write is not detected correctly by checkFilters (warning from v-model that filter is read-only, when it's not)

### ISSUE THREAD

**Issue by nkovacs** [yyx990803/vue#887]
[This](https://github.com/yyx990803/vue/blob/5a0de87805540c7c4128341c84e2e7d6fc9fcea2/src/directives/model/index.js#L68) code is buggy. If a filter has both read and write, only hasRead will be set, and you'll get a warning from v-model that the filter is read-only.

**Comment by nkovacs** [comment]
http://jsfiddle.net/nkovacs/37evcnq7/

**Comment by yyx990803** [comment]
good catch!
