### ISSUE TITLE
Passing v-models as arguments to filters not working

### ISSUE THREAD

**Issue by dejan7** [yyx990803/vue#888]
Judging by this page http://vuejs.org/guide/custom-filter.html#Filter_Context it appears that it is possible to pass v-models as arguments to filter functions. 
However it is not working. Here is a working example: http://jsbin.com/juwekoleva/2/edit?html,js,output

It is expected to see values of those 2 inputs combined. However you get the value of the first input (name) + the string "lname" returned always. It appears that the filter parameter "lname" is passed as a string, and not as  v-model with an actual value.

**Comment by yyx990803** [comment]
The doc example indicates it **is** passed in as a string, and is retrieving the value as `this[key]`.
You example fixed: http://jsbin.com/yuwocukiqu/2/edit

Note in 0.12 the filter syntax has changed and it will behave like what you expected in the original fiddle.
