### ISSUE TITLE
staggered v-repeat transitions

### ISSUE THREAD

**Issue by nkovacs** [yyx990803/vue#889]
I'd like to do staggered animations like [angular's ng-repeat](https://docs.angularjs.org/api/ngAnimate#css-staggering-animations).
I've tried to implement it using transition-delay: http://jsfiddle.net/nkovacs/7Ltwhhgm/

Getting the index for the transition-delay in the enter animation is a really ugly hack, and it also doesn't look right if the first animation has not finished yet (e.g. click "add items", then click "add three items" before the first ten are finished animating). I also don't know how to calculate the index for the leave animation. I think I could get to the repeat directive and check oldVms, but that's another ugly hack.

Another problem is if you click "add items", then click "empty" before the transitions finish, some elements will remain stuck forever in the dom. It looks like the transitionend event is never called, because the transition is cancelled before it can start.

**Comment by yyx990803** [comment]
You can use `this.$index` inside hooks (`this` points to the instance being animated). But yeah, staggering is tricky to get right. I'll take a look at how this can be improved.

**Comment by nkovacs** [comment]
If the list already has 10 elements and I add another one, I don't want to delay the transition by 10 * 200ms. That's why I can't use this.$index. I need the element's index in the array of the newly added elements only.

**Comment by Nirazul** [comment]
@nkovacs 
I don't think this is a task for javascript. I managed to achieve the effect you wanted by writing (I confess, it's ugly) custom css selectors.
It looks like a tedious approach, but it's quite manageable with a preprocessor. Mostly it's even unwanted to animate more than 10 such classes after each other.

http://jsfiddle.net/7Ltwhhgm/11/

**Comment by Nirazul** [comment]
@nkovacs 
I don't think this is a task for javascript. I managed to achieve the effect you wanted by writing (I confess, it's ugly) custom css selectors.
It looks like a tedious approach, but it's quite manageable with a preprocessor. Mostly it's even unwanted to animate more than 10 such classes after each other.

http://jsfiddle.net/7Ltwhhgm/12/

**Comment by yyx990803** [comment]
Here's an interesting thing about those items stuck on leave: it's because `.fade-enter` and `.fade-leave` are applying exactly the same opacity, so no CSS transition is triggered at all if an item is removed before its transition delay has passed. You can fix that behavior by giving `.fade-leave` a very small, but non-zero opacity, e.g. `0.01`.

**Comment by yyx990803** [comment]
Did some experiments in the `stagger` branch: http://jsfiddle.net/yyx990803/wecczx24/
Simply add `stagger="xxx"` to the `v-repeat` container.

Looks like It's working alright. It's possible to add finer-grained control with `enter-stagger`, `leave-stagger`, and maybe reverse order. e.g. `leave-stagger="200 reverse"`

**Comment by OEvgeny** [comment]
Looks pretty good! Exactly what I'm looking for. Will this be in 0.12?

**Comment by nkovacs** [comment]
Awesome!
I played around with it a bit, and added an animation to reorder by first emptying the array, then repopulating it in nextTick: http://jsfiddle.net/nkovacs/dg419t3s/1/
It's not perfect, I'll try to pin the elements in place during the animation so they don't jump around.
I also ran into a bug: Click add items, then click empty before it finishes (try adding more items to give you more time). You'll get "Uncaught TypeError: Cannot read property 'removeChild' of null" in vue.js:931.

**Comment by nkovacs** [comment]
One more suggestion/wish: a hook to control the staggering, e.g. to speed it up or slow it down with each element, instead of it being constant. Not really that important, but it would be nice to have.

**Comment by nkovacs** [comment]
Fixed the jumping around by giving the leaving elements absolute position: http://jsfiddle.net/nkovacs/dg419t3s/4/
The reorder animation looks good, but "remove some items" is broken, because it assumes every element after the current one in beforeLeave is going to leave, so it gives them an absolute position.

**Comment by nkovacs** [comment]
Alternative solution that fixes "remove some items", but makes reorder look bad: http://jsfiddle.net/nkovacs/dg419t3s/7/

**Comment by nkovacs** [comment]
Ok, managed to get it look the way I want: http://jsfiddle.net/nkovacs/dg419t3s/11/
I think what I need is a hook that runs when the stagger setTimeout is started, so I can give all the elements that are going to be removed an absolute position before any animation starts (so these hooks need to run before any beforeLeave hooks).

**Comment by yyx990803** [comment]
Made a bunch of improvement, the fiddle should work without errors now.

**Comment by yyx990803** [comment]
You can now define custom stagger amount by providing the `stagger`, `enterStagger` or `leaveStagger` hooks in your transition object:

``` js
transitions: {
  fade: {
    stagger: function (i) {
      return Math.min(300, i * 50) // limit the maximum delay to 300ms
    }
  }
}
```

**Comment by yyx990803** [comment]
Will ship as part of 0.12.

**Comment by nkovacs** [comment]
Thanks
