### ISSUE TITLE
<content> dynamic select attr

### ISSUE THREAD

**Issue by gapipro** [yyx990803/vue#890]
So I am writing a component where content is dynamic. 
It would be great to have support for expressions inside `select` attribute on `<content>` tag.

For example:

Template:
```HTML
<div>
	<div v-el="header" class="ui top attached tabular menu">
		<a class="item" v-class="active:$index == 0" data-tab="{{tab.id}}" v-repeat="tab:tabs">{{tab.text}}</a>
	</div>
	<div class="ui bottom attached tab" v-class="active:$index == 0" data-tab="{{tab.id}}" v-repeat="tab:tabs">
		<content select="tab:nth-child($index)">
		</content>
	</div>
</div>
```

Usage:
```HTML
<ui-tabs tabs="{{userTabs}}">
 <tab>Content 1</tab>
 <tab>Content 2</tab>
</ui-tabs>
```

```Javascript
 var userTabs = [
  {'id':'tab1','text':'Test'}, 
  {'id':'tab2','text':'Test2'}
];
```

Or is there any other way to make components dynamic like that?

Also is it possible to access components content (in my case   `<tab>Content 1</tab>` and   `<tab>Content 1</tab> `) inside components  `$vm`?

**Comment by yyx990803** [comment]
Sounds like a useful improvement. I think this is possible, but requires some changes to the current content resolution algorithm (which is static).

**Comment by yyx990803** [comment]
Wow, turns out it just works. You can do this now: https://github.com/yyx990803/vue/blob/dev/test/unit/specs/compiler/content_spec.js#L146-L159
