### ISSUE TITLE
url routing?

### ISSUE THREAD

**Issue by villanus** [yyx990803/vue#891]
what is the proper way to route values from url or hash and respond to url changes?

**Comment by azamat-sharapov** [comment]
If you are using vue version 0.11, refer to "Routing" section of [this guide page](http://vuejs.org/guide/application.html). 
If you are on 0.12, there is [vue-router](https://github.com/vuejs/vue-router) which is in progress yet, but should already work. 

*Check out [issue reporting guidelines](https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) to report only appropriate issues to this repo.*

**Comment by villanus** [comment]
Thanks! Exactly what i was looking for.  
For the 1.2 will it also support hashbang?
