### ISSUE TITLE
Trigger animation when dynamic v-component is exchanged.

### ISSUE THREAD

**Issue by Nirazul** [yyx990803/vue#895]
I have several components that live as exchangeable pages within the same container:

```
    <div class="portal--wrap"
        v-component="{{ currentSection.name }}"
        v-transition="portal--wrap__anim"
        keep-alive>
        This should never be displayed.
    </div>
```

Is there a way to trigger the v-transition behaviour when switching out the component? This would be usable to implement page transitions.

**Comment by azamat-sharapov** [comment]
When you change component (`currentSection.name`), vue fires transition. Or I misunderstood?

**Comment by Nirazul** [comment]
Ah, I ended up with a transition that didn't actually do anything. You're right, it works as expected :)
