### ISSUE TITLE
关于模板中调用调用数组 length 的Bug

### ISSUE THREAD

**Issue by niluanxy** [yyx990803/vue#896]
我的代码里有一个 info 的数据，默认我给的是一个 [] 空数组，然后再 event 对象中赋值，然后在模板中调用 info.length 来做一下判断，然后就报错 length 找不到，这个问题麻烦看看

**Comment by 285858315** [comment]
没代码看啥？

**Comment by yyx990803** [comment]
麻烦看下开 issue 须知：https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines

**Comment by niluanxy** [comment]
行，好的，我整理下吧，这两天敢进度，太忙了，我完了把代码给PULL上来

**Comment by yyx990803** [comment]
不要再像上次那样上传整个代码了... 最好做成一个小的重现，放在 jsfiddle 上。直接看整个项目太麻烦了。

**Comment by niluanxy** [comment]
恩，行

**Comment by yyx990803** [comment]
暂时先关了，有重现了再开
