### ISSUE TITLE
Question regarding components' data and scoping

### ISSUE THREAD

**Issue by thasmo** [yyx990803/vue#897]
Got a question regarding components' data and scoping and I hope this is the right place to ask.

I got a root Vue instance and two Vue components instantiated via `Vue.component('component-a', {...});` and `Vue.component('component-b', {...});`. Component A has an array called `items` and is responsible for creating and showing this items. But component B is responsible for deleting items from the array.

How would I access the list in component A from component B to delete an item?

**Comment by yyx990803** [comment]
https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines

Please post questions to vuejs/Discussion, thanks!
