### ISSUE TITLE
$key not set when repeating an object

### ISSUE THREAD

**Issue by thasmo** [yyx990803/vue#898]
I've got an object called `objects` like this:
```js
{
	a: {
		name: 'A',
		types: [1,2]
	},
	b: {
		name: 'B',
		types: [2,3]
	},
	c: {
		name: 'C',
		types: [1,3]
	}
}
```
Repeating it like this:
```html
<a href="/objects/{{$key}}" v-repeat="object: objects">
	<i class="icon {{$key}}"/>
	{{objects.name}}
</a>
```
Results in this:
```html
<a href="/objects/a">
	<i class="icon undefined"/>
	A
</a>
<a href="/objects/b">
	<i class="icon undefined"/>
	B
</a>
<a href="/objects/c">
	<i class="icon undefined"/>
	C
</a>
```
The key in the root element is working fine, but in the descendent element it's undefined. It would be really nice to have access to the key inside the repeated element as well. Is this possible?

**Comment by yyx990803** [comment]
Can you make a jsfiddle?

**Comment by yyx990803** [comment]
`<i>` is not a self closing tag, and the `<i/>` syntax is XHTML, not HTML5. You need to close it properly in templates as `<i></i>`.
