### ISSUE TITLE
Proposed changes for prop to work with computed setters

### ISSUE THREAD

**Issue by dgerber** [yyx990803/vue#899]
Hi,

I am trying to build components ([here](https://github.com/dgerber/vue-formidable)) which use a settable computed property bound to the parent vm with `prop`. These components may also need to set a default value for it, calling the property setter during compilation.

Rather than setting up custom events which duplicate the role of `prop`, it seemed cleaner to make [these changes](https://github.com/dgerber/vue/tree/prop-bindings) to vue. What do you think?

**Comment by yyx990803** [comment]
Can you demonstrate the use case where this change is necessary?

**Comment by dgerber** [comment]
The full context is in [vue-formidable](http://dgerber.github.io/vue-formidable/) (built with the vue branch above).

Here is a scenario without these changes:
1. in compile, the parent vm passes the value `undefined` to child
2. the child's computed property setter does some type casting / sets a default value
3. Issues:
- as the watcher does not fire during compilation, the value on parent stays out of sync
- also, if the component casting set `null`, the watcher will not fire anyway because props missing on data are initialized to `null` rather than `undefined` (which seems more appropriate, the problem being here that JSON Schema has `null` as a primitive type).

**Comment by yyx990803** [comment]
Is it possible for your plugin to work without the proposed changes? I ran the tests with these changes and there are a few prop test cases failing. I agree initializing props to `undefined` would be a reasonable change though.

**Comment by dgerber** [comment]
Yes, it can work in less straightforward ways, using custom events or maybe adding one level of nesting to the data model.

Initializing props to `undefined` would already help some way.

**Comment by yyx990803** [comment]
Thanks, props are now initialized to `undefined`. I think the initial set order needs to be maintained for behavior consistency with past versions.
