### ISSUE TITLE
vue on devdocs

### ISSUE THREAD

**Issue by mark-hahn** [yyx990803/vue#900]
I posted a suggestion to include VUE in the devdocs site, https://trello.com/b/6BmTulfx/devdocs-documentation.  The best way to get on the site is to provide the docs in a format they can understand.  It is open-source so you can just do a PR.

Is there already some form of the API docs that can be machine-read, like in a json file?

**Comment by yyx990803** [comment]
Hmm the doc source is in Markdown: https://github.com/vuejs/vuejs.org/tree/master/source. Does that work?

**Comment by mark-hahn** [comment]
I don't know. I haven't studied the contribution guidelines.  Surely
markdown would be easier to port than html or plain text.

I use the Atom editor which lets you bring up devdocs from a selection in
the source so I am just selfishly asking for it.  If no one more
experienced in this area is willing to do this then I may take a stab at it.

**Comment by krisak** [comment]
There is this https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/VueJS#readme docset for Dash (osx app). I asume it should be very easy to apply to devdocs but i have no experience with devdocs.

**Comment by yjeroen** [comment]
Good idea :)

Here's the [guidelines](https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#contributing-code-and-features).
Here's the [documentation of using the scraper](https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs).

**Comment by kikyous** [comment]
@krisak  @yjeroen @mark-hahn 
if no one work on this, i will do it.

**Comment by mark-hahn** [comment]
> if no one work on this, i will do it.

That would be great.

**Comment by kikyous** [comment]
https://github.com/Thibaut/devdocs/pull/228

**Comment by kikyous** [comment]
looks great :smile: 

![image](https://cloud.githubusercontent.com/assets/818616/8495181/068c45e0-219e-11e5-8536-e1d4e3f790ce.png)

**Comment by yyx990803** [comment]
:+1: Thanks @kikyous !

**Comment by azamat-sharapov** [comment]
@kikyous thanks a lot! I also use devdocs.

**Comment by mark-hahn** [comment]
Thanks mucho.

**Comment by Thibaut** [comment]
Looking at this now.
@yyx990803 would you mind adding a LICENSE file to https://github.com/vuejs/vuejs.org? It's not clear if https://github.com/yyx990803/vue/blob/dev/LICENSE applies to it or not. Thanks!

**Comment by yyx990803** [comment]
@Thibaut added.

**Comment by Thibaut** [comment]
@yyx990803 Thanks! Docs are up: http://devdocs.io/vue/

**Comment by yyx990803** [comment]
@Thibaut cheers!
