### ISSUE TITLE
揪心的bug，VUE无法在 cordova 环境中运行

### ISSUE THREAD

**Issue by niluanxy** [yyx990803/vue#904]
用 VUE.JS 搭配自己写的框架做的一个 SPA 应用，浏览器一切正常，今天准备打包一个APP，用于给客户展示的时候，结果悲剧的发现 VUE 没法在 cordova 打包的APP中运行，测试后感觉是自定义 compontent 的问题，因为我所有的东西都放在自定义的 mg-view 的conpontent中，但是貌似没有编译。

环境，android5.0 的机器，cordova 是4.0的版本。

**Comment by yyx990803** [comment]
没有任何报错？

**Comment by yyx990803** [comment]
我刚用 cordova 5.0.0 + cordova android 4.0 在模拟器里跑一切正常啊。

**Comment by niluanxy** [comment]
这就奇怪了，我是在 HTC ONE上跑的，我一会在模拟器中跑下看看，看有没有可能是机器问题
在2015年06月07日 04:43，Evan You 写道:

我刚用 cordova 5.0.0 + cordova android 4.0 在模拟器里跑一切正常啊。

**Comment by niluanxy** [comment]
抱歉，找到问题了，没VUE啥事，是我自己路由问题，可以关闭这个了


在2015年06月07日 04:43，Evan You 写道:

我刚用 cordova 5.0.0 + cordova android 4.0 在模拟器里跑一切正常啊。
