### ISSUE TITLE
v-repeat requires $data for properties create using Object.defineProperty()

### ISSUE THREAD

**Issue by ronnieoverby** [yyx990803/vue#907]
Demonstration:

http://codepen.io/ronnieoverby/pen/jPmwRM

See that `{{name}}` doesn't render.

**Comment by yyx990803** [comment]
See the second section of the FAQ: http://vuejs.org/guide/faq.html

Vue.js doesn't support custom getter/setters in your data objects. However you can use computed properties instead.

**Comment by ronnieoverby** [comment]
Well... That completely rules Vue out. Im using breezejs to get data from
the server and it uses getters and setters for everything.

**Comment by yyx990803** [comment]
I'm surprised a client data management solution doesn't offer some sort of "unwrap to plain JSON" functionality. I guess it's just a bad match.

**Comment by ronnieoverby** [comment]
Unwrapping the objects to a plain javascript object would defeat the purpose of breezejs. It's objects (entities) have lots of nice behavior built in. 

I did find this http://breeze.github.io/doc-js/model-library.html about getting breezejs entities working with your mvvm library of choice, but I'm not keen on writing one. ( I'd rather be working on my app, instead of fighting my tools. )

It's a shame about getters/setters... Vue was supposed to be the chosen one... https://www.youtube.com/watch?v=QiZNSzWIaLo

**Comment by yyx990803** [comment]
Well, it is possible for Vue to wrap the original property descriptor to support objects with getter/setters, but it has some performance implications to take into account. I was aware that this could become a potential issue but it was a very rare use case and I decided not to implement that.
