### ISSUE TITLE
v-repeat="[singleItem]" errors when track-by

### ISSUE THREAD

**Issue by alchen** [yyx990803/vue#908]
JSFiddle: http://jsfiddle.net/alchen/rjqt2x91/3/

Though this is probably not a good way to write things (constructing an array on the fly with a single item for `v-repeat`), it throws `Uncaught TypeError: Cannot read property '__v_trans' of null`.

**Comment by yyx990803** [comment]
This is... indeed not recommended usage, but the error is fixed in https://github.com/yyx990803/vue/commit/523389b85c0cd7948d63931f0d713754dfe404a0 anyway.

Btw, you can expose `$data` as a prop and use `<component $data="{{someData}}">`.
