### ISSUE TITLE
Not able to access data in JSON array with v-repeat

### ISSUE THREAD

**Issue by slickorange** [yyx990803/vue#910]
I have an array of JSON items. I am trying to use v-repeat to output it as a series of table rows:

    <tr v-repeat="items">
        <td>{{code}} </td>
        <td> {{description}}</td>
        <td> {{price}}</td>
        <td><input v-model="quantity" type="text" size="4"/></td>
        <td> {{total = price * quantity}}</td>
    </tr>

A row with empty cells is output for every item in the JSON - so Vue.js is not getting the property values, even though I have confirmed that they are definitely exist and I can get the values in the v-repeat if I do something like this:

`{{items[$index].code}}`

I am getting no errors or warnings.

This is the JSON output of my Vue data object:

 `{
  "items": [{
    "id": "408",
    "product_id": "6",
    "description": " item description here... ",
    "price": "1210.26",
    "created_at": "2015-06-04 15:10:14",
    "updated_at": "2015-06-04 15:10:14",
    "quote_id": "32",
    "quantity": "1",
    "code": "PI0055"
  }]}`

**Comment by slickorange** [comment]
Update:
I did not initialize the items array:

`data: {items: []}`

Strange that I did not get any errors though, and that the empty rows were still output, and that I could access the data with `items[$index]`.

**Comment by yyx990803** [comment]
Vue works by converting data fields into ES5 getter/setters. If you don't initialize the field and want to add it later, you'll have to call `vm.$set(key, val)`.

This was mentioned in the Model section of the guide: http://vuejs.org/guide/index.html#Model

**Comment by teckel12** [comment]
Where would one do vm.$set(key, val)?  Vue is working, but reporting errors:

```
vue.js:2574[Vue warn]: Error when rendering root instance: 
vue.js:2217 Uncaught TypeError: Cannot read property '0' of undefined
```

When I'm simply trying to display a value from a JSON file like this:

`{{ board.units[0].name }}`

For Vue trying to be easy, it's the most complicated and confusing thing I've ever tried to use to do something even simple.
