### ISSUE TITLE
sort v-model value don't update

### ISSUE THREAD

**Issue by hggq** [yyx990803/vue#911]
<!DOCTYPE html>
<html>
    <head>

		<script src="js/jquery.min.js"></script>
		<script src="js/vue.min.js"></script>	
    </head>
    <body class="skin-blue">
		<ul id="menulist">
		<li v-repeat="mdata" id="m{{$index}}">{{name}}  <span v-on="click: movedown(this,$event)">down</span> <span v-on="click: moveup(this,$event)">up</span><input type="hidden" v-model="sort" name="sort"></li>
		</ul>
		<script type="text/javascript">

			  var mlist=new Vue({
				el:"#menulist",
				data:{
					mdata:null
				},
				methods: {
					movedown:function(obj,e){
					
						
							jQuery(obj.$el).next().slideDown('1500',function(){
								
								jQuery(obj.$el).slideUp('1500',function(){
									jQuery(obj.$el).next().show();
									jQuery(obj.$el).show();
									jQuery(obj.$el).next().after(obj.$el);									
								})

							});
							
						
						jQuery(obj.$el).parent().children().each(function(index){
							
							
							jQuery(this).find("input[name=sort]").val(index);
							console.log(jQuery(this).prop("id")+"="+jQuery(this).find("input[name=sort]").val());
						});
						
						console.log(JSON.stringify(this.$data.mdata));
					},
					moveup:function(obj,e){
					
						jQuery(obj.$el).prev().slideUp('1500',function(){
							
							jQuery(obj.$el).slideDown('1500',function(){
								jQuery(obj.$el).prev().show();
								jQuery(obj.$el).show();
								jQuery(obj.$el).prev().before(obj.$el);		
														
							})

						});
						jQuery(obj.$el).parent().children().each(function(index){
							
							
							jQuery(this).find("input[name=sort]").val(index);
							console.log(jQuery(this).prop("id")+"="+jQuery(this).find("input[name=sort]").val());
						});
						console.log(JSON.stringify(this.$data.mdata));
					}
				}
			});

			jQuery(document).ready(function(){
				
					 mlist.$data.mdata=[{"sort":"0","name":"\u67e5\u770b\u53c2\u89c2\u5217\u8868","url":"zhanhui\/index.php\/zhan\/index","icons":"<i class=\"fa fa-bars\"><\/i>","sub":[]},{"sort":"1","name":"\u67e5\u770b\u5382\u5546\u5217\u8868","url":"zhanhui\/index.php\/zhan\/shang","icons":"<i class=\"fa fa-shield\"><\/i>","sub":[]}];

			})
		</script>
    </body>
</html>

**Comment by yyx990803** [comment]
你这个 `v-model` 是想干啥... 不是这么用的啊

**Comment by hggq** [comment]
我想更新排序，想不到怎么作用进去改{{sort}}值，我意思是那个change没起作用，而且我用了v-model,再用{{sort}}没有作用了，还有 jsfiddle注册不了，

**Comment by yyx990803** [comment]
改动数据的顺序，Vue 就会改变 DOM 的顺序。你这样手动移动 DOM nodes 是不推荐的做法。可以考虑在 jQuery 动画完成的时候修改数组顺序.

**Comment by yyx990803** [comment]
你这个不属于 bug，请转移到 https://github.com/vuejs/Discussion/issues
