### ISSUE TITLE
Directive parser doesn't properly parse regular expression as directive's expression if it contains a "|"

### ISSUE THREAD

**Issue by davidkhess** [yyx990803/vue#912]
This is with 0.12rc2. You can recreate in the console:

```javascript
> Vue.parsers.directive.parse("pattern: /ab/")[0].expression
< "/ab/"
> Vue.parsers.directive.parse("pattern: /a|b/")[0].expression
< "/a"
```

It seems like this should work. At least vue-validator expects it to work.

And this seems like a reasonable workaround:

```javascript
> Vue.parsers.directive.parse("pattern: new RegExp('a|b')")[0].expression
< "new RegExp('a|b')"
```

But it doesn't work with vue-validator because it's coded to work from the directive's literal expression instead of its value (even though `isLiteral` is not being set on the directive definition). Not sure why. Opened https://github.com/vuejs/vue-validator/issues/17 over there.

**Comment by yyx990803** [comment]
It is very tricky to parse regex literals inside directives, because it can be easily confused with the division operator.

I think a reasonable change should be making vue-validator accept a string instead of regex literal for the pattern validator.

**Comment by davidkhess** [comment]
Sounds like a reasonable solution.

So, that means that regexp literals should not be used inside of directive expressions? Is this documented?

**Comment by yyx990803** [comment]
Yes. It's a very rare use case since validation is probably the only use case where this would happen. In most cases it's possible to use a filter or computed property to avoid it. I'll add a note in docs.

**Comment by davidkhess** [comment]
Sounds good. Thanks!

**Comment by yyx990803** [comment]
Closing (to be resolved in `vue-validator`)
