### ISSUE TITLE
possibly silly request

### ISSUE THREAD

**Issue by mark-hahn** [yyx990803/vue#915]
I don't like mustache bindings.  I think they are noisy and hurt readability.  I have managed to avoid them in my Vue app except for one place.  That is where the component can be dynamically bound.

```
    <div id='page-comp' v-component='{{curPage}}' keepAlive>
```

Is there any logical way to remove the need for this?  I would only suggest this if the change made things more orthogonal/consistent overall. 

Maybe an argument, like ...

```
    <div id='page-comp' v-component='select: curPage' keepAlive>
```

**Comment by young-steveo** [comment]
@mark-hahn Not sure if this helps, but you can always change the delimiters to something you prefer.  e.g.

```js
Vue.config.delimiters = ['(%', '%)'];
```

**Comment by yyx990803** [comment]
Hmm, I think in 0.12 you'll see more of them because in 0.12 there's no more `v-with` and you'd have to pass in dynamic props as `prop="{{something}}"`. The dynamic component syntax, although different, still needs to mustaches too: `<component is="{{something}}"></component>`.

I think these tags are somewhat necessary when an attribute does not start with `v-`, since otherwise we have no way to tell if it is data-bound or just a plain string attribute.

**Comment by mark-hahn** [comment]
Thanks for the tip on replacing the mustaches.

> necessary when an attribute does not start with v-

Well, that's another request of mine.  I wish all Vue components used v-.

**Comment by mark-hahn** [comment]
I've chosen something much less noisy ...

```
v-component=".`curPage`."> .`text`.
```

**Comment by mark-hahn** [comment]
BTW, if I don't use mustaches will I have a problem including modules that do use them?

**Comment by yyx990803** [comment]
Hmm the interpolation config is global, so there might be issues if you use a third-party component with template. I should probably add a component-level option for delimiters too.

**Comment by mark-hahn** [comment]
>  I should probably add a component-level option for delimiters too.

That would be cool.  It seems to me that a global one is useless and should
be deprecated.  I think modules are an important issue.  Is there any other
global like this?  In general, globals suck.  :-)
