### ISSUE TITLE
Data inheritance with <content> tag

### ISSUE THREAD

**Issue by itadakimas** [yyx990803/vue#916]
Hi !

I am trying to create a generic form component which handles a bunch of stuff, like validation, formatting, etc. To do so, I tried to mix Vue components with the use of the <content> tag. 

This is the structure : 
1 x Root view > 1 x custom-form component (with <content> tag) > n x custom-form-input component

Here is an example of markup:
```html
<custom-form legend="my form legend">
    <custom-form-input type="email" label="Your email" name="email"></custom-form-input>
</custom-form>
```
The problem is that I can't access data in the custom-form component from the custom-form-input component, probably because "transcluded contents are compiled in the parent component’s scope, not in the child’s scope.". 

Is there a way to do this without polluting the data in the root view ?

**Comment by yyx990803** [comment]
Please only report bugs here - questions should be posted at `vuejs/Discussions`.

This seems to be similar to https://github.com/vuejs/Discussion/issues/179 and I think this should be further discussed there.
