### ISSUE TITLE
Use {!! safeHTMLString !!} syntax

### ISSUE THREAD

**Issue by BrandonSurowiec** [yyx990803/vue#917]
Currently the syntax to not escape HTML is to use triple mustache like {{{ safeHTMLString }}}. It would be really neat to change it to be {!! variable !!} like Laravel. 

It's easier to see unescaped variables and also emphasizes the potential danger. Thoughts? I'd make a pull request, but I've only found the normal delimiters in the `config.js` so far.

**Comment by yyx990803** [comment]
When you change normal delimiters, the triple changes too. `{! !}` would turn triple into `{{! !}}`.
In general I want to avoid breaking changes for stylistic preferences.

**Comment by BrandonSurowiec** [comment]
I like the `{{ }}` syntax for escaped variables.  Would you be opposed to adding another config option to specify the escaped delimiters in the config? Then it could still default to the triple `{{{ }}}`.

**Comment by yyx990803** [comment]
This sounds like a good idea. I'll probably consider that as part of #918.

**Comment by BrandonSurowiec** [comment]
Awesome, thanks!

**Comment by yyx990803** [comment]
In 1.0.0 it will be configurable separately as `Vue.config.unsafeDelimiters`. (Implemented in 1.0.0-alpha branch)
