### ISSUE TITLE
suggestion: support string as paramAttributes value

### ISSUE THREAD

**Issue by mark-hahn** [yyx990803/vue#921]
It would be nice to have strings and have much less noise and typing.

```
  paramAttributes: 'cur-page'
  paramAttributes: 'cur-page, cur-heading'
  paramAttributes: 'curPage'   // auto-conversion from camel-case
```

**Comment by yyx990803** [comment]
I don't think this is a good idea - it opens up possible typing errors, e.g. missing a comma, and adds internal overhead of converting to an array, while all we get from this is purely stylistic preference.

**Comment by mark-hahn** [comment]
>  it opens up possible typing errors,

Many fewer than the current typing requirement.

>  adds internal overhead of converting to an array,

That kind of conversion is very fast.  Maybe 10s of usecs?  And only at Vue
compile time.  This isn't a hot-spot by any means.

> while all we get from this is purely stylistic preference.

Isn't there precedence where it is done elsewhere in Vue?

I personally don't see any need for the current array syntax.

**Comment by yyx990803** [comment]
See https://github.com/yyx990803/vue/issues/920

Re: typing errors:

``` js
"prop-a, prop-b prop-c"
['prop-a', 'prop-b' 'prop-c']
```
The latter would throw. The former would result in unknown run time behavior.

**Comment by mark-hahn** [comment]
I understand now.  Also I can't find any similar examples.

I use coffeescript and teacup (a coffeescript-based template) and noisy things like this and mustaches really stand out.  Here is what typical Vue code looks like to me.  Note how the ` ['cur-show-dex', 'all-shows']` looks compared to the rest.

```
Vue.component 'show-list', 
  paramAttributes: ['cur-show-idx', 'all-shows']
  
  template: render ->
    div '.show-list', ->
      div '.show-list-inner', ->
        div '.show', 
          vRepeat:'show: allShows'
          vText:'show.title'
          vClass:'selected: show.show-idx == cur-show-idx'
```

Is there a way for me to do this with a plug-in?  If not with the current `paramAttributes` option, then maybe with a different name that is converted to `paramAttributes`, like `pAttrs: 'allShows'`?  I could do multiple things like this and call the plug-in `stylish` or `low-noise`.

**Comment by yyx990803** [comment]
It is possible to implement a mixin that does this:

``` js
var propRewriteMixin = {
  created: function () {
    var props = this.$options.props
    if (typeof props === 'string') {
      this.$options.props = props.split(/,\s?/)
    }
  }
}
```

**Comment by mark-hahn** [comment]
That looks like an easy solution.  I'm lucky that `created` will run before `this.$options.props` is used.

Vue's expandability is impressive.  And it is impressive that my my code is so small and clean to begin with.

I notice you used `this.$options.props` instead of `paramAttributes`.  Is that a planned change?  I like it.

P.S.  The Atom editor is currently trying to decide on a recommended framework.  I have been arguing to use Vue for some time.  https://github.com/atom/atom/issues/5756

**Comment by yyx990803** [comment]
Yes, `paramAttributes` have been renamed in 0.12. You can checkout all the upcoming changes in 0.12 in the beta and rc release notes: https://github.com/yyx990803/vue/releases

**Comment by yyx990803** [comment]
@mark-hahn unfortunately, I just realized my mixin example would not work properly, because the data initialization process relies on `this.$options.props` to initialize the props, and it happens before the `created` hook.

However, I think it's easier to just write a small helper function (similar to how you are using `render` to pre-process your template):

``` js
Vue.component 'show-list', 
  props: parseProps 'cur-show-idx, all-shows'
```

**Comment by mark-hahn** [comment]
Thanks for thinking about this.  It is educational.

I was being greedy to want it exactly my way.  I've grown to appreciate Vue
more and more and I have no complaints now.
