### ISSUE TITLE
Improve communication with transcluded components

### ISSUE THREAD

**Issue by yyx990803** [yyx990803/vue#923]
Ref: https://github.com/vuejs/Discussion/issues/179

It would be nice to expose formal APIs for a component to work with child components in transcluded content.

**Comment by zfedoran** [comment]
I'd love to see this happen. Perhaps something like this:

```
<my-component v-exports="foo">
    <li v-repeat="item: foo"></li>
</my-component>
```
Where the template for `my-component` might look like this:

```
<ul>

<ul>
```
If this is not something you'd want to support, do you think its possible to do this with a custom directive?

**Comment by TerenceZ** [comment]
What about the `context / childContext` mechanism in `React`, which restricts the parent and its children on the context signatures? (In some situation, e.g. menu and sub menu, it's a good way to communicate between parent and its children).

**Comment by yyx990803** [comment]
In latest `dev` branch there are some changes related to this issue:

Transcluded components are now considered "children" of their host component. This means in the following case:

``` html
<tabs>
  <tab>{{msg}}</tab>
</tabs>
```

`<tabs>` will be `<tab>`'s `$parent`. So the two can use the event system to communicate. The `{{msg}}` content is still properly compiled in the parent scope of `<tabs>`.

**Comment by azamat-sharapov** [comment]
> The `{{msg}}` content is still properly compiled in the parent scope of `<tabs>`.

Currently (on 12.04) `{{msg}}` would be compiled in `<tab>` scope. Is this changing on next release? or did I misunderstand?

**Comment by yyx990803** [comment]
@azamat-sharapov no, even in current version it is compiled in `<tabs>`'s parent scope, or, the scope that the template belongs to.

**Comment by azamat-sharapov** [comment]
Oh, of course! :D I was thinking `<tab inline-template>` instead of `<tab>`. Get it now.
