### ISSUE TITLE
Mustache evaluation fails on props attribute if it contains a newline

### ISSUE THREAD

**Issue by davidkhess** [yyx990803/vue#924]
See this fiddle:

https://jsfiddle.net/davidkhess/vh1uzs5h/3/

For formatting purposes, it would be nice to be able to use newlines in the formatting of the attribute value.

**Comment by yyx990803** [comment]
Could you give an example where this is necessary? Mustache tags / directive values can only contain one expression/statement.

**Comment by davidkhess** [comment]
A large constant. In this particular case, for documentation purposes the value is best kept out of the model and in the template.

```
attribute="{{
    [
        {
            "key": "a",
            "value": "b"
        },
        {
            "key": "c",
            "value": "d"
        },
        {
            "key": "e",
            "value": "f"
        }
    ]
}}"
```

**Comment by davidkhess** [comment]
Thanks!
