### ISSUE TITLE
should I switch to RC version now?

### ISSUE THREAD

**Issue by mark-hahn** [yyx990803/vue#925]
I'm about 20% done with a Vue app using the stable documented version.  I'm considering jumping to the latest RC version now rather that finishing the app and then converting it.

- Is it stable enough to develop with?
- Are the features stable enough that I wouldn't have to rewrite things again?
- Are others switching now?
- Can I figure out the feature (documentation) differences from an issue or two here?  Are new docs in progress?

I've already pulled the `v-with` attributes and switched to `paramAttributes`.  What are the other big changes?

Thanks in advance.

**Comment by azamat-sharapov** [comment]
Don't wanna upset anyone here, but I think it's worth reading issue reporting guidelines and following them: https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines

**Comment by mark-hahn** [comment]
Sorry.  Is there a forum somewhere for general discussion?

**Comment by yyx990803** [comment]
You can post non feature/bug related issues to https://github.com/vuejs/Discussion/issues

**Comment by yyx990803** [comment]
BTW, changes so far are documented in the release notes, and 0.12 will be officially out later this week. There might be some breakage, but since you are still early in your project I think you should switch.

**Comment by mark-hahn** [comment]
Thanks.

Suggestion: https://github.com/vuejs/Discussion/issues should be on the home page.
