### ISSUE TITLE
v-if multiple conditions

### ISSUE THREAD

**Issue by deathwebo** [yyx990803/vue#927]
I couldn't find in any part of the documentation this. That's why I wanted to ask: Is there a way to have v-if evaluated by a multiple condition ?

Something like ```<div v-repeat="item: items" v-if="item.firstCondition && item.secondCondition"></div>```

**Comment by yyx990803** [comment]
This should just work, have you tried it?

Also, please read the issue guidelines before opening one: https://github.com/yyx990803/vue#questions

Questions should be opened at vuejs/Discussion.

**Comment by deathwebo** [comment]
Thank you very much! It worked, sorry about not posting on Discussion, it's a great library you have in here and I'm just getting my hands wet! :)
