### ISSUE TITLE
More than a single class for v-class

### ISSUE THREAD

**Issue by jbruni** [yyx990803/vue#930]
I need to add two classes based on a condition. The classes are `has-error` and `has-feedback`.

Currently I have:

    v-class="'has-error': hasError('field')"

I'd like to also add the `has-feedback` class, without adding another `v-class` attribute, and without appending `, 'has-feedback': hasError('field')` to the current value above.

In fact, I expected the following to work:

    v-class="'has-error,has-feedback': hasError('field')"

**Comment by viktorivanov** [comment]
Hi jbruni,
this should do the trick: 
```
v-class="has-error: hasError, has-feedback: hasFeedback"
```

**Comment by jbruni** [comment]
Yes, you are correct. But I mentioned (and discarded) this solution - just read again with care.

Note that the condition is the same for both classes: `hasError('field')`.

It would be performance-wise to perform the condition check only once, instead of twice.

**Comment by viktorivanov** [comment]
Yes, sorry I wasn't paying attention enough.

**Comment by yyx990803** [comment]
In most cases this is not going to cause any performance issues, unless your `hasError` method takes more than 10ms, then there must be some serious problem in how you implemented it.

That said, you can directly pass `v-style` an object, which can be returned from a computed property. Inside the computed property you can call `hasError()` only once.
