### ISSUE TITLE
$data $delete method bug

### ISSUE THREAD

**Issue by hggq** [yyx990803/vue#931]
for(key in mlist.$data.mdata){
	  							if(mlist.$data.mdata[key].mid==data.mid){
	  								mlist.$data.mdata.$delete(key);
									console.log(JSON.stringify(mlist.$data.mdata));	
	  								break;
	  							}
	  						}

this key item don't remove
output:   ....,null,......

**Comment by hggq** [comment]
i user  splice(key,1); method  is right

for(key in mlist.$data.mdata){
	  							if(mlist.$data.mdata[key].mid==data.mid){
	  								//mlist.$data.mdata.$delete(key);
									mlist.$data.mdata.splice(key,1);
									console.log(JSON.stringify(mlist.$data.mdata));	
	  								break;
	  							}
	  						}

**Comment by yyx990803** [comment]
`$delete` only work on Objects. You need to use `$remove` for Arrays.
