### ISSUE TITLE
pass one time value as props and not watch them

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#933]
I find that as long as I pass a variable (no matter of if it is one time) as prop into component, it will always create a `prop` directive and a watcher. But in fact, when I pass one time binding, I just want the compiler to resolve its value without watching, especially the case to pass callbacks.

**Comment by yyx990803** [comment]
In the official 0.12 release `prop="{{* parentProp }}` is in fact one time. The one way syntax now uses a different syntax.
