### ISSUE TITLE
Keep v-events as a special way to pass callbacks for hooks

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#934]
I know the most of callbacks can be passed as props, but in some cases we use `v-events` as a simple way to listen hook events (like ready) for dynamic components (like controlled by `v-if`).

Of course, we can expose a property to accept the hook callback and call it explicitly in component, but this will couple and the component have to check the callback.

**Comment by yyx990803** [comment]
I'd like the communication between the parent and the child to be more explicit. Passing a callback down may mean having to check the presence of the callback, but it makes the possible side effects of the child component's actions very explicit: you just look at the callback passed in from the parent. The problem with events is that although it's very decoupled, you have no idea how many listeners could be triggered and what the side effects are when you emit something.

On the other hand, I'd like to reduce the amount of APIs that serve similar purposes. If you feel that `v-events` fit your use case better, you can check out how it was implemented in the past commits and use it as a custom directive.
