### ISSUE TITLE
DocumentFragment is undefined in IE8

### ISSUE THREAD

**Issue by victorwpbastos** [yyx990803/vue#935]
I'm trying to make Vue work in IE8. After all the necessary shims and polyfills I'm facing troubles with this line: https://github.com/yyx990803/vue/blob/dev/dist/vue.js#L4774

Is there something to do in this case?

**Comment by yyx990803** [comment]
I'm sorry, but Vue will never work in IE8 because there's no way to polyfill `Object.defineProperty`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

**Comment by victorwpbastos** [comment]
I did use these:

https://github.com/es-shims/es5-shim
https://github.com/inexorabletash/polyfill

I'm only having troubles with the DocumentFragment part.

**Comment by yyx990803** [comment]
Non of these polyfill can make `Object.defineProperty` work in IE8 on non-DOM objects, it's just the limitation of the browser. Even if you get past the fragment error it still won't work properly.

**Comment by victorwpbastos** [comment]
:cry:
