### ISSUE TITLE
Multiple transclusions changed in 0.12.0-rc2

### ISSUE THREAD

**Issue by noirbizarre** [yyx990803/vue#936]
Hi !

I was trying to port my app to vue.js 0.12.0-rc2 and I have some unexpected behaviors with components and transclusion.

### Multiple content insertion points and selectors
**In Vue 0.11:**
When you have multiple content insertion point with selectors and one without, elements matched by selectors are removed from selector-less content:
http://jsfiddle.net/noirbizarre/zm2cfgpf/1/

**In Vue 0.12:**
Component matched by other selectors are not removed from selector-less content:
https://jsfiddle.net/noirbizarre/ae3aec5j/1/

### Star operator
**In Vue 0.11:**
It was possible to use the star operator.
http://jsfiddle.net/noirbizarre/ehucvuc0/2/

**In Vue 0.12:**
Not anymore
http://jsfiddle.net/noirbizarre/ouyLnkpj/1/

### `:not()` operator
**In Vue 0.11:**
It was possible to use the negation operator `:not()`.
https://jsfiddle.net/noirbizarre/gmyfkktd/4/

**In Vue 0.12:**
Not anymore.
http://jsfiddle.net/noirbizarre/bjv1zfpq/1/

For the last 2 points (operators behavior), it seems to only match the first element in 0.12.0-rc2.

**Comment by yyx990803** [comment]
Thanks for reporting the issue! Will fix asap.

**Comment by noirbizarre** [comment]
Thanks, it works great now!
