### ISSUE TITLE
dynamic component in v-repeat with alias breaks computed properties

### ISSUE THREAD

**Issue by johannes-z** [yyx990803/vue#938]
I needed a computed property on a v-repeat with an alias (to check if the data is available), and came across the following problem. Without an alias, the computed property works perfectly, but when I add an alias to the v-repeat variable, I can't access the computed property on the alias anymore.

## (Working) Example WITHOUT alias:
JSFiddle: https://jsfiddle.net/a4gr6f6q/
### Javascript
```javascript 
new Vue({
    el: '#messages',
    data: {
		messages: [
			{ text: "entry 1", created_at: "2015-06-12 22:50:18" },
			{ text: "entry 2", created_at: "2015-06-13 22:50:20" },
		]},
    components: {
        message: {
            computed: {
                timestamp: function () {
                    // Uses of momentjs to format date
                    return this.created_at;
                }
            }
        }
    }
});
```
### HTML
```html
<div id="messages">
    <message class="message" v-repeat="messages" v-transition="expand">
        <blockquote class="text">
            {{ text }}
            <footer class="footnote">
                {{ timestamp }}
            </footer>
        </blockquote>
    </message>
</div>
```

## (NOT WORKING) Example WITH alias:
JSFiddle: https://jsfiddle.net/zx4vg1jh/
### HTML
```html
<div id="messages">
	<message class="message" v-repeat="msg: messages" v-transition="expand">
		<blockquote class="text">
			{{ msg.text }}
			<footer class="footnote">
				{{ msg.timestamp }}
			</footer>
		</blockquote>
	</message>
</div>
```

As mentioned, the reason for adding an alias is to reference the item in a v-class directive.
```html
<message class="message hidden" v-repeat="msg: messages" v-transition="expand" v-class="hidden: !msg">
```

**Comment by johannes-z** [comment]
getting the property like this works:
```javascript
timestamp: function () {
    return this.msg.created_at;
}
```
shouldn't this be equal to msg, since it's only an alias?

**Comment by yyx990803** [comment]
What the v-repeat identifier is doing here is: instead of passing the repeated object in as the component's `$data`, pass it in as a `msg` prop instead.

It should be noted that this actually is a bug that your code is working without `inline-template`. The content inside `<message>` here should be compiled as parent content without `inline-template`, and it will be discarded because your `message` component doesn't have a template itself.

**Comment by yyx990803** [comment]
Computed properties are behaving as expected.

The mentioned bug has been fixed in https://github.com/yyx990803/vue/commit/942e2bb56ff2898c7c002c8ab508db7f0ae96fc2.
