### ISSUE TITLE
还是component嵌套的bug，又重现了

### ISSUE THREAD

**Issue by niluanxy** [yyx990803/vue#939]
上次提过，多个 component 嵌套的话，里面的 conponent 不会编译，就忽略了，上次你改了，在dev的分支让我自己编译暂时用着，你0.12正式版会修复，然后刚才升级到0.12，这个又重现了。。。

**Comment by yyx990803** [comment]
升级到 0.12.1 看下

**Comment by niluanxy** [comment]
升级到了 0.12.1 了，还是有这个Bug

**Comment by yyx990803** [comment]
是这个？#805

**Comment by yyx990803** [comment]
https://github.com/yyx990803/vue/commit/5e9694037c91605b54c58d1b23efee7ef045da22

**Comment by niluanxy** [comment]
恩，是这个，代码结构和上次没什么区别，如果需要重现的话我整理一个出来

**Comment by yyx990803** [comment]
更新到最新的 dev 看下

**Comment by niluanxy** [comment]
问题解决了，是由于 replace 属性的问题，这个好像在 0.11 和 0.12 中表现有点不同，貌似 0.12 中更合理点，我针对 0.12 换了种写法弄好了，可以关闭了。

**Comment by qbaty** [comment]
是什么replace 的问题？ @niluanxy 我也发现了一样的问题
