### ISSUE TITLE
Suggestion: v-transition - done callback vs transitionend

### ISSUE THREAD

**Issue by Nirazul** [yyx990803/vue#940]
In the docs, the done callback is described as following:

<blockquote>
Finally, the enter and leave can optionally take a second callback argument. When you do so, you are indicating that you want to explicitly control when the transition should end, so instead of waiting for the CSS transitionend event, Vue.js will expect you to eventually call the callback to finish the transition.
</blockquote>

I would have loved to use the done callback as a fallback method to failed or inexistent transitionend events. Is there any chance you could implement it as a concurrent handling? So the end of the transition is marked either with the transitionend event or the done callback, whatever comes first?

If no, what's the easiest way to patch the current behaviour? Something like that?

```
enter: function (el, done) {
  $(el).on('transitionend', function() {
    done();
  });
  setTimeout(function fallback() {
    done();
  }, 300);
}
```

**Comment by yyx990803** [comment]
You can do that, but you'd want to prevent `done` from being called twice by using a flag variable.

**Comment by Nirazul** [comment]
Good catch, I'll implement it like that. If anyone looks for a working solution, I'd use this one:

```
Vue.transition('fade', {
    leave: function (el, done) {
        var isDone = false;

        $(el).on('transitionend', function() {
            isDone || done();
            isDone = true;
        });

        setTimeout(function fallback() {
            isDone || done();
            isDone = true;
        }, 300);
    }
}
```
