### ISSUE TITLE
Mustache evaluation does not work on directives unless they have isLiteral=true

### ISSUE THREAD

**Issue by davidkhess** [yyx990803/vue#942]
A fiddle that demonstrates the problem: https://jsfiddle.net/bgbcomb2/1/

This is related to #279 where it is indicated that mustache evaluation should work on directives in general. Apparently, it is currently restricted to directives that are marked "isLiteral":

https://github.com/yyx990803/vue/blob/dev/src/directive.js#L114

Note, I'm not trying to achieve dynamic two-way binding - I would just like the same one-time mustache evaluation on other directives that "isLiteral" directives enjoy. (i.e. directive has _isDynamicLiteral = false / no update function case).

**Comment by davidkhess** [comment]
Well, I tried my own patch to that method:

```javascript
	p._checkDynamicLiteral = function () {
	  var expression = this.expression
	  if (expression) {
	    var tokens = textParser.parse(expression)
	    if (tokens) {
	      var exp = textParser.tokensToExp(tokens)
	      this.expression = this.vm.$get(exp)
          if (this.isLiteral) {
              this._watcherExp = exp
              this._isDynamicLiteral = true            
          }
	    }
	  }
	}
```

And I immediately ran into a situation where since I was passing the value I needed in as a prop, it did not have the proper value when the expression was evaluated once. So, I may need to be asking for two way dynamic binding after all. Sigh.

**Comment by yyx990803** [comment]
I think I misread your code sample in #279 - mustaches are not supported and I don't recommend such usage either. The reason being that the appearance of interpolation tags explicitly indicates the while thing is being evaluated as a string. Mixing interpolation inside expressions makes it difficult to read and understand whether something is a string or an expression.

What I meant over there is this following usage is now supported:

``` html
<input v-model="index[id]">
```

**Comment by davidkhess** [comment]
Completely agree on all of the drawbacks – just struggling to find a good way to deal with these dynamic binding issues.

I just tested this in my jsfiddle and it worked:

```
<input v-model="$data[id]">
```

https://jsfiddle.net/bgbcomb2/3/

Is that safe for top level attribute binding?

**Comment by yyx990803** [comment]
Yes, it should be fine.

**Comment by davidkhess** [comment]
Great - I think that gives me what I need to deal to solve this.
