### ISSUE TITLE
v-if is not reevaluated for nested components.

### ISSUE THREAD

**Issue by TeffenEllis** [yyx990803/vue#943]
Given a setup like following, a container and an avatar components, `v-if` is not reevaluated after the root data is updated.

A fiddle that demonstrates the problem in 0.12.1: http://jsfiddle.net/91fwjo1j/

The console outputs, `[Vue warn]: Error when evaluating expression "profile.image"` despite the `v-if` in the template tag. The DOM updates after the warning as expected.

The same code working in 0.11.10: http://jsfiddle.net/c0xht555/1/

Thank you.

**Comment by yyx990803** [comment]
What do you mean by not re-evaluated? I can't see the difference between the fiddles except for the warning.

The warning was simply suppressed in 0.11 - I decided to make it more explicit in 0.12.

**Comment by TeffenEllis** [comment]
The `v-if` wrapper prevents "signed-in only" content from appearing. 

Consider the following,

```javascript
// The initial on load application state.
root.data = {
  profile: null
}

// User authenticates. UI now updates to reflect this.
root.profile = {
  username: "foobar"
  image: "http://example.com/foo.png"
}

// User signs out. UI now updates to reflect this.
// ....[Vue warn]: Error when evaluating expression "profile.image"
```

The warning implies that something was done incorrectly. Is the approach of replacing a logged out user's `profile` object with `null` incorrect, or is the warning misleading?

Thank you for your help! :)

**Comment by yyx990803** [comment]
This is due to some internal changes relating the order in which prop changes are synced. In practice this should not affect how your app behaves, you can safely ignore those warnings. The next release will restore the old behavior and no longer throw warnings in this case.
