### ISSUE TITLE
is keep-alive the same in 0.12?

### ISSUE THREAD

**Issue by mark-hahn** [yyx990803/vue#944]
I'm using keep-alive but when I switch to a different component and back a scrolling (overflow:auto) div in the component always appears scrolled back to the top.  Is this the expected behavior?  Has it changed on 0.12?   I can show some code if you need it.

**Comment by mark-hahn** [comment]
I realized there was an easy way of showing my template before it was compiled ...
```
<div id="page">
  <component id="page-comp" 
             keep-alive="keep-alive" 
             is="{{curPage}}" 
             all-shows="{{allShows}}" 
             cur-show-idx="{{curShowIdx}}" 
             cur-show="{{curShow}}" 
             cur-episode-idx="{{curEpisodeIdx}}" 
             cur-episode="{{curEpisode}}">
  </component>
</div>
```

**Comment by yyx990803** [comment]
`keep-alive` simply removes the instance from the DOM and re-inserts it later. This will most likely reset the scrolling position. Is this behavior different from 0.11?

**Comment by mark-hahn** [comment]
>  Is this behavior different from 0.11?

I didn't implement this until after I upgraded.  I guess I'll just save the
position(s) when I leave a page and restore it when I return.

This isn't a big deal.  I was thinking that maybe the way to use keep-alive
had changed.

Maybe I'll make a plugin.

**Comment by yyx990803** [comment]
Yeah, this is a common issue for SPAs and I don't think it has to do with `keep-alive`. `vue-router` could potentially offer an option for this behavior.

**Comment by mark-hahn** [comment]
My application has no need for a router.

**Comment by mark-hahn** [comment]
Do you think a "dom-fragment state preservation" plugin should be an alternative directive to keep-alive?  If so should it replace it using the same name or be a new directive?

Or should it be something different than a directive?  Should it be a PR to the core code to enhance keep-alive?  I don't think it will be a performance problem since it only happens on component changes.  And the code to set a scroll position should be fast.

**Comment by mark-hahn** [comment]
The code below works and is fast.  Notice that this functionality has to be placed on each scrolling element.  I can't figure out how to add this to all scrollable elements in the entire page.  So replacing the keep-alive is not an option.  

I'm guessing the proper way to add this feature is to make a new directive that needs to be added to each scrollable element.  Although this is more work for the developer than I hoped for, it does give more control to choose the elements to fix.

Now I just need to develop the new directive, maybe called "v-keep-scroll", that adds the `attached` and `onScroll` functionality to the element.  I assume I can put the two handler functions in some global code.  I haven't studied how to write a directive.

```
  template: '<div class="show-list" v-on="scroll: onScroll"></div>'

  methods:
    onScroll: (e) ->
      ele = e.target
      ele.setAttribute 'data-vuescrllft', ele.scrollLeft
      ele.setAttribute 'data-vuescrltop', ele.scrollTop

  attached: ->
    for ele in @$el.querySelectorAll '[data-vuescrllft]'
      ele.scrollLeft = ele.getAttribute 'data-vuescrllft'
      ele.scrollTop  = ele.getAttribute 'data-vuescrltop'
```

Let me know if I'm posting to much detail here.  I thought that maybe someone would let me know if I'm heading down the wrong path.

**Comment by yyx990803** [comment]
Custom directives are pretty easy: http://vuejs.org/guide/custom-directive.html
