### ISSUE TITLE
动态组件使用疑问

### ISSUE THREAD

**Issue by chenboxiang** [yyx990803/vue#945]
@yyx990803 我在使用vue的动态组件时，碰到个问题，我按官方指引通过一个currentView属性来切换到不同的视图，这种方式在currentView属性有变更时是没问题的。但如果我设置的currentView和上次的值一样，组件不会重新refresh，这种需求有别的办法能实现么？

**Comment by 285858315** [comment]
弱弱的问下，设置和上次的值一样 ，这和没设置有区别么？

**Comment by yyx990803** [comment]
你可以用这样的方法：

``` js
this.currentView = '' // 销毁当前的 view
Vue.nextTick(function () {
  this.currentView = 'my-view'
}.bind(this))
```

这里需要用 `nextTick` 来等到之前设置的空值触发更新。

**Comment by chenboxiang** [comment]
@285858315 我遇到的场景是，渲染一个订单列表，然后这个订单列表支持分类型查询，这个时候路由是要切换的，但是view是用的同一个view

**Comment by chenboxiang** [comment]
@yyx990803 GET，多谢
