### ISSUE TITLE
Nested v-repeat: How to access parent $index inside child?

### ISSUE THREAD

**Issue by abhijitghogre** [yyx990803/vue#947]
I am unable to do this.
```
<ul>
	<li v-repeat="candy: candies">
		<ul>
			<li v-repeat="flavour: candy.flavours">
				{{ candy.$index }}
			</li>
		</ul>
	</li>
</ul>
```

**Comment by yyx990803** [comment]
You can use `$parent.$index`.

Please read the [Issue Reporting Guidelines](https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue, thanks!
