### ISSUE TITLE
Cannot read property 'previousSibling' of null

### ISSUE THREAD

**Issue by jdanino** [yyx990803/vue#948]
After upgrading to 0.12 I get a weird error after I update data which is shown in a v-repeat with a filter:

Uncaught TypeError: Cannot read property 'previousSibling' of nullfindPrevVm @ vue.js:7020module.exports.diff @ vue.js:6645module.exports.realUpdate @ vue.js:6540module.exports.update @ vue.js:6529p._bind.update._update @ vue.js:8256p.run @ vue.js:3194run @ vue.js:4402flush @ vue.js:4386handle @ vue.js:669

first two updates(clicks) work fine, third time it throws an error.

**Comment by yyx990803** [comment]
Please make sure to upgrade to 0.12.1, and provide a jsfiddle reproduction of the issue.

**Comment by jdanino** [comment]
The fiddle can be found here: https://jsfiddle.net/mepat0n2/1/

If you click the more/less link, the first two times it works, the third time it throws the error mentioned above.
