### ISSUE TITLE
MAX_UPDATE_COUNT = 10 is causing false positives

### ISSUE THREAD

**Issue by davidkhess** [yyx990803/vue#950]
This constant:

https://github.com/yyx990803/vue/blob/dev/src/batcher.js#L2

is causing false positive reports for me. Is there a way to adjust it?

**Comment by yyx990803** [comment]
Can you provide more context? I'd be curious to know what use case would need to recursively update the same watcher more than 10 times.

**Comment by davidkhess** [comment]
This is an "editor" of arbitrary JSON data with "widgets" (components) that are responsible for various subsections of the JSON data. Widgets can appear in an editor's template many times. Each widget is responsible for it's own subsection of JSON (via a key) and defines what the JSON looks like within that subsection and creates and manages it's own UI. Each widget updates the editor's overall document JSON in real-time via a watcher. (I've tried two-way binding for this but it doesn't work well in the bootstrap scenario - i.e. the JSON document is blank and a widget needs to initialize its subsection.)

The problem is coming up during initialization. I'm not sure the exact path of execution, but basically when the editor template is compiled, each widget is initializing it's subsection of JSON in the overall JSON document managed by the editor. This overall JSON document is the one getting so many updates, one from each widget as each widget initializes and finds that it needs to initialize it's subsection of JSON - which causes an update on the editor's document JSON.

I've been wrestling with this for a while trying to come up with the most elegant way to implement this in Vue. Any suggestions are welcome.

**Comment by yyx990803** [comment]
Are you saying you have a top-level JSON object, and you are passing sub trees of it into child components. Each child component modifies the sub tree it gets during initialization?

**Comment by davidkhess** [comment]
Yep.

**Comment by yyx990803** [comment]
I don't quite understand why the component needs to mutate the sub tree it gets though. Can you give an example of what the initialization does?

**Comment by davidkhess** [comment]
For instance, a widget manages an address. street_1, street_2, city, etc.

I don't want the editor to know or understand how to create a proper default value for the widget. If I start with a blank (i.e. {}) overall document, I want the widget to initialize its subsection with a sane default and then let the bindings to the inputs in the UI take over.

**Comment by yyx990803** [comment]
I guess I can make that number configurable. Does lifting the max update count make your app work as intended?

**Comment by davidkhess** [comment]
Yes, my templates should have a max complexity of tens of widgets. I would probably set it around 50.

**Comment by davidkhess** [comment]
Thanks! BTW, really appreciate and admire your work on Vue.

**Comment by yyx990803** [comment]
You're welcome :)
