### ISSUE TITLE
Force update data

### ISSUE THREAD

**Issue by laskos** [yyx990803/vue#951]
I have below method in my vue js component:

```
relativeDate: function(date) {
    return moment(date).fromNow();
},

// HTML
<div class="date">{{ relativeDate(notification. datetime) }}</div>
```

I would like to update this every 1s for obviously reason. Is there any way to do it wit vuejs?

**Comment by azamat-sharapov** [comment]
Try [computed property](http://vuejs.org/guide/computed.html), so that view is synced with property. 

Also check out [this](https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines).

**Comment by yyx990803** [comment]
Vue cannot track external data sources that are not observed. Where does your `notification` object come from?

**Comment by stepbeta** [comment]
Hi, I have a pretty similar situation, but I've got a list. Consider this:
```
<!-- HTML -->
<div v-for="(c, index) in conversations">
    <div v-if="c.messages && c.messages.length > 0">
        {{ lastMsgDate(c) }}
    </div>
</div>

// javascript
lastMsgDate: function(c) {
    return moment(c.messages[c.messages.length - 1].ts).fromNow();
}
```

I don't think a computed property is the answer here, since the property itself (the timestamp of the message) doesn't change.

**Comment by laskos** [comment]
@stepbeta just make `verboseTime` var in the `data` and update it with `setInterval`

**Comment by laskos** [comment]
@stepbeta in your case u must iterate `c.messages` and set `verboseTime` for every message individually. The better option is make separated component like `<verbose-time>`.

**Comment by stepbeta** [comment]
I'm not sure I understand. 
I have a list of "conversations", each with a list of "messages". 

I have a component showing the list of conversations where for each one I show an ID and the timestamp of the last message in that conversation. That's the code I wrote in my previous message.

Where would you put that `verboseTime` var?
