### ISSUE TITLE
Sub-components

### ISSUE THREAD

**Issue by emilklindt** [yyx990803/vue#952]
I ran in to the following problem:
```html
<challenge>
	<question q-text="Please select..." q-type="dropdown">
		<answer a-value="A" a-text="Elephants"></answer>
		<answer a-value="B" a-text="Tigers"></answer>
		<answer a-value="C" a-text="Giraffes"></answer>
	</question>
</challenge>
```
It's not possible to access any of the data being passed inside the components, except the <challenge> component. Isn't this possible at all if you add sub-components inside components, or am i missing out on something? 

The code above is of course just an example, but i hope you get the point.

**Comment by emilklindt** [comment]
Or is there any other possible way to pass data (i.e. JSON) directly to Vue – in the initial request (to prevent multiple requests from the server).

**Comment by yyx990803** [comment]
I don't think I'm understanding what you mean.

**Comment by yyx990803** [comment]
Closing (inactivity). Feel free to reopen if you could provide a jsfiddle demonstrating the issue more clearly.
