### ISSUE TITLE
using vue data in html image source

### ISSUE THREAD

**Issue by elsodev** [yyx990803/vue#956]
Hi,

I have a html tag
```
<div id="content">
<img src="{{ imageLink }}"/>
</div>
```

```
var content = new Vue({
    el: '#content',
    data: {
        imageLink: 'http://somedomain/someimage.jpg'
    }
});
```

As you can see i am biding data imageLink to the html image src tag, it works, image is displayed as normal, but Chrome shows a 404 not found on the image link since its checking on the html img src syntax.

Is the way i'm doing correct or there is a better way?

**Comment by caibinterry** [comment]
so, how do you solve this problem? i

**Comment by elsodev** [comment]
http://vuejs.org/api/#v-bind

**Comment by dskaiser82** [comment]
Same problem.  Solved by putting images in the public folder
