### ISSUE TITLE
orderBy using natural sort

### ISSUE THREAD

**Issue by jfsullivan** [yyx990803/vue#957]
Is there any way to achieve natural sorting with the OOTB orderBy filter?  The default sort works like this...
* Item 1
* Item 10
* Item 11
* Item 2

Instead of the expected....
* Item 1
* Item 2
* Item 10
* Item 11

**Comment by yyx990803** [comment]
You can always write a custom sort filter. Just make sure to call `.sort()` on a copy of the array.
