### ISSUE TITLE
Components not registering

### ISSUE THREAD

**Issue by dabiddo** [yyx990803/vue#962]
I'm new to this VueJS library, while creating a little example, I can't get components to work correctly, I have even tried copying an example from the Net with no progress, this is the example that I'm trying to replicate

Page Code:----
<html>
<thats-cool></thats-cool>

<script id="myOwnTemplate" type="x-template">
    <p>{{ helloWorld }}</p>
</script>
</html>
--------

App Script JS

Vue.component('thats-cool', {

      template: '#myOwnTemplate',
      replace : true,

      data: function() {
        return {
           helloWorld: 'thats cool',
        };
      }
});

var demo = new Vue({
  el: '#demo',
  data: {
    name: 'Richard Griffin',
    ubicacion: 'Tijuana B.C.',
    foto:'https://randomuser.me/api/portraits/med/men/29.jpg',
  }
});

I'm using the DEMO object on another DIV, and tha loads correctly, just the component part not working, I;m using the lates Dev version of VueJS.

Any help appreciated.

**Comment by azamat-sharapov** [comment]
*[Please use](https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) [vuejs/Discussions](https://github.com/vuejs/Discussion/issues) repo for such questions.*

Your code looks fine (although you didn't post template of the component). Please make jsfiddle to show problem.
