### ISSUE TITLE
v-on="change" not triggered with filters

### ISSUE THREAD

**Issue by theshaunwalker** [yyx990803/vue#964]
Hey,

I'm working with form fields, I want to fire a method when the input is changed, this is working as expected on fields without a filter, but when the input is changed by a filter, the `change` event isnt working (while searching for other events that might work, have also tried `input` and `broadcast` to no avail).
Below are 2 example form inputs:
```
<input type="text"
	name="items[@{{ $index }}][rate]" 
	v-model="rate | decimalPlaces 2" 
	number 
	debounce="500"
	v-on="change: listItemsChanged">

<input type="text"
	name="items[@{{ $index }}][quantity]" 
	v-model="quantity" 
	number 
	v-on="change: listItemsChanged">
```

The first doesnt work when the filter changes the input and I exit the field, but it does work if I exit the field before the debounce kicks in (so as expected.
The second field works fine.

Not sure if this is expected behaviour or not, if it is, why? And what's the recommended workaround?

Thanks!

**Comment by yyx990803** [comment]
The `change` listener simply listens to the native change event, which does not fire until you blur the input.

`v-on="input: onChange"` should work as you type, if not you need to provide a jsfiddle reproduction.

Finally, if you want to react to the data changes, don't rely on DOM listeners, the better way to do it is just use `$watch()` on the underlying data directly.

**Comment by faraazahmad** [comment]
Where can i find the documentation on this? It would be really helpful
