### ISSUE TITLE
wait-for not rendering child components even if they emit the correct event

### ISSUE THREAD

**Issue by dhruvio** [yyx990803/vue#965]
I've created a fiddle illustrating my experience with `wait-for` in v0.12.1.

http://jsfiddle.net/xqncyyeh/1/

ideally, if `app.activeView = "a"` or `"b"`, their templates should be rendered into the `<component>` block. However, nothing happens.

Any advice?

**Comment by dhruvio** [comment]
Also, the rendering works if you take of the `wait-for="loaded"` attribute from the `<component>` block.

**Comment by dhruvio** [comment]
So, I played around with this a little, and it seems like if the event is run in the current tick, it's not picked up by `wait-for` .

I updated the previous fiddle to illustrate this: http://jsfiddle.net/xqncyyeh/2/.

Seems like a bug, do you think you will support synchronous event-firing for `wait-for` ?

**Comment by dhruvio** [comment]
I read this link: http://vuejs.org/guide/best-practices.html#Understanding_Async_Updates

Seems like `this.$nextTick(callback)` will solve the problem. I'm going to close this issue. Apologies for the spam! Hope this helps someone else.

**Comment by TylerBre** [comment]
@dhruvio can you provide an example of your code working with this.$nextTick?

Struggling over here, and that article is not that helpful

**Comment by dhruvio** [comment]
Hey Breland, wait-for listens to events after the end of the current event loop iteration. So, if `wait-for="event"`, you should run your logic inside your Vue instance as follows:

```
this.$nextTick(function() {
  this.$emit("event");
});
```

If you just say `this.$emit("event")` in the current event loop, the listener won't pick up the event as wait-for won't be listening yet.

I wrote this on my phone, so apologies if the formatting is weird. I hope this answers your question. If you don't understand any of this, I recommend googling how process.nextTick works. Vue's $nextTick method is analogous to that.

Cheers
