### ISSUE TITLE
Prevent propagation of lifecycle hooks to super Vue.extend() classes ?

### ISSUE THREAD

**Issue by dhruvio** [yyx990803/vue#966]
I have a base class:

    var Base = Vue.extend({
      compiled: function () { /* do something */ }
    });

If I create a subclass:

    var Sub = Base.extend({
      compiled: function () { /* do something else */ }
    });

When I instantiate and compile the subclass, normal behaviour shows that the `Base` and `Sub` classes' `compiled` methods will be called. Is there anyway to force **only** the `Sub`class' `compiled` method to be called, such that the `Base` class' compiled method has been overridden?

Thanks

**Comment by yyx990803** [comment]
The point of extension is that subclass will inherit everything the superclass has. It looks like in your case you should use [mixins](http://vuejs.org/guide/extending.html#Extend_with_Mixins) instead.
