### ISSUE TITLE
vue中能否在 compiled 暂停渲染，直到某一任务完成后继续渲染，从而起到 resolve 效果

### ISSUE THREAD

**Issue by niluanxy** [yyx990803/vue#967]
原来用 ng 的时候，原生有 resolve 的实现，就是可以在页面渲染前执行类似获取数据的动作，然后直接返回一个 defer ，程序获取后自动把数据注入进去，但是VUE没有注入的方法。所以我想能不能在内容渲染前，先获取数据，获取后再赋值到data中，或者说，能不能提前获取到渲染后的this的实例句柄，因为VUE没有注入功能，也不能和 NG 一样把数据暴漏出来，我现在都是 hook:compiled 中得，但是这样有问题，有些组件，比如我写的slider组件，根据里面的图片来初始化，用了 v-repeat，但一开始没有数据，组件初始化就会失败。

**Comment by yyx990803** [comment]
vue-router 会提供类似功能。还是说你想要每个组件都有这样的功能？

**Comment by niluanxy** [comment]
不是每个组件，每个组件都写一个这个功能太浪费了，组件渲染就应该是数据绝对加载完才渲染，这样组件也好写，只不过是我现在自己的项目需要这个 resolve 功能，因为vue-router还没发布，我就想问问现在的 vue 0.12.1 版本有没有能实现的可能，有的话我先自己实现一个简单地版本

**Comment by yyx990803** [comment]
简单的办法就是加个 `v-show="loaded"` 呗，等到数据拿到了把 `loaded` 设成 true。

**Comment by niluanxy** [comment]
v-show 不行，我刚试了，只不过是不显示页面，但是渲染已经渲染好了，我的组件全部是全局的组件，用的时 Vue.component("mg-slider", {}) 的方式创建的，我看组件渲染周期了，是在 page 页面beforeComplete 后进入渲染阶段的，你说的这个不行，有其他方法没。

**Comment by niluanxy** [comment]
额，暂时解决了，我在每个自己写的 loadView 方法中加了段代码，然后每个page都有一个resolve方法，resolve方法接受两个参数，最后一个是 loadView 传进去的一个 defer 对象，defer对象对page的原始对象的data字段赋值，功能是实现了，就是看起来代码好丑。。。

**Comment by yyx990803** [comment]
这个就跟 vue-router 做的事情差不多嘛。不过这个本来就不应该是组件本身来实现，而是管理组件的机制来实现。

**Comment by niluanxy** [comment]
恩，这个东西确实应该是管理组件的机制来实现，因为我每个页面就是一个组件，然后组件渲染有一个 loadView 方法，我在这里实现的。我刚看了你的vue-router了，信息不多，不知道你写的时候有没有考虑异步加载的方式。

**Comment by yyx990803** [comment]
当然得是异步的啦...

**Comment by niluanxy** [comment]
你 readme.md 里面我没看到。。。好，期待中，话说有时间也可以写个异步的例子，我可以挂到我自己的框架和项目中，给你捉捉 bug

**Comment by yyx990803** [comment]
看 `/examples` 里面。还没来得及写文档

**Comment by niluanxy** [comment]
恩，我看看
