### ISSUE TITLE
Reserved word 'char' breaks minification

### ISSUE THREAD

**Issue by edmelly** [yyx990803/vue#968]
I think that the use of 'char' as an identifier (in the getPathCharType function) is causing yuimin and other minifiers to break because it is [reserved for a possible future keyword](http://mattsnider.com/reserved-words-in-javascript/) by the ECMAScript specification.

Swapping it out with 'character' fixes the issue for me.

**Comment by yyx990803** [comment]
I'll change the variable name, but I don't really see why this would break things. Maybe you should update your minifier and use UglifyJS instead ;)
