### ISSUE TITLE
Handle an array of checkboxes input

### ISSUE THREAD

**Issue by evographics** [yyx990803/vue#970]
I need the same result of multiple select tag but using and array of input checkboxes http://jsfiddle.net/kputLa4j/5/

I'd like the post_types field of each box should be an array that contains the values of related checked checkboxes.

**Comment by Nirazul** [comment]
This is an issue tracker and no help platform. Please go to [stackoverflow](https://stackoverflow.com) for receiving help.

If you find a bug, please make sure to read the [Contribution Guidelines](https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md) first.

**Comment by Nirazul** [comment]
This is an issue tracker, no help platform. Please go to [stackoverflow](https://stackoverflow.com) for receiving help with your code.

If you think you've found a bug, please make sure to read the [Contribution Guidelines](https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md) first and describe the bug you are experiencing.

**Comment by evographics** [comment]
In the Vue documentation there is no an example how to handle an array of input checkboxes and the solution I tried does not work correctly. I already posted my issue in different place but nobody give me a solution.

**Comment by yyx990803** [comment]
As suggested, please use https://github.com/vuejs/Discussion/issues for questions.

Here's an example anyway: http://jsfiddle.net/yyx990803/2jpLk0d4/

**Comment by evographics** [comment]
Thank you very much! And apologies for posting in wrong section.
