### ISSUE TITLE
Two-way component binding is broken in 0.12.2

### ISSUE THREAD

**Issue by mrix** [yyx990803/vue#972]
Please check demos on jsfiddle:
* [version 0.12.1](http://jsfiddle.net/evtushenko/x8ogjjou/)
* [version 0.12.2](http://jsfiddle.net/evtushenko/q42edb3h/)

Click parent checkbox and component switcher. In v0.12.1 child changes are passed to parent view. And in v0.12.2 it does not.
Both examples have the same code. Only Vue version is chnaged.

**Comment by yyx990803** [comment]
Thanks for the fast catch and detailed repro. Fixed. Will release 0.12.3 soon.

**Comment by mrix** [comment]
[Yeah!](http://jsfiddle.net/evtushenko/1pw4m58c/) Thanks!
