### ISSUE TITLE
Please Provide a Forum

### ISSUE THREAD

**Issue by Armangh** [yyx990803/vue#976]
Hi, i'm new and noob to vuejs and javascript please provide a forum just for asking simple questions. like how can i add data using json with remote url. thanks a lot and sorry for my bad english

**Comment by OEvgeny** [comment]
You can use [vuejs/discussion](https://github.com/vuejs/Discussion/issues) or [Gitter chat](https://gitter.im/yyx990803/vue) to ask questions. Also check out [contribution guide](https://github.com/yyx990803/vue/blob/dev/CONTRIBUTING.md).
