### ISSUE TITLE
Is there a LifeCycle hooks like componentDidUpdate let me refresh my iScroll ?

### ISSUE THREAD

**Issue by Huxpro** [yyx990803/vue#977]
I am working on sth like change a filter, then view update (insert or remove some nodes), then refresh iScroll to make iScroll work.

In React things, I use `componentDidUpdate` as the hook to refresh iScroll.
But in Vue, I have tried that:

```
// watch filter to refresh IScroll
this.$watch('activeFilter', function(_filter){
    if(BWScroll){
        Vue.nextTick(function(){ 
             BWScroll.refresh();
        })  
    }
})
```

I am sure both the `_filter` and `BWScroll` are there, but it did not work.
normally `Vue.nextTick()` or `setTimeout(fn, 0)` leave enough rest, but only I try refresh iScroll with something like `setTimeout(fn, 1000)`  it works...

**Comment by yyx990803** [comment]
Does any of your list items have async transitions?

**Comment by Huxpro** [comment]
Oh u r right, there is `v-transition` actually, so I can use `afterLeave` hooks to that?

**Comment by yyx990803** [comment]
If there are transitions it gets a bit tricky... you need 2 nested nextTicks because the transitions are buffered for another tick (so that only 1 reflow happens). I'll think about how to make this less ugly but for now it's what you have to do.

**Comment by Huxpro** [comment]
Well...I tried nested nextTicks, but it did not work for me..

So I have to back to `setTimeout(fn, _transitionDuration)`

**Comment by Hucy** [comment]
@Huxpro 麻烦问下  `_transitionDuration`的时间间隔 是怎么 确定的? 还是是一个固定值.


谢谢

**Comment by PerseveranceZ** [comment]
@Hucy _transitionDuration css里面自己定义的
不过用setTimeout(fn, _transitionDuration)的方式也并不能保证每次都能滚动

我一般ready时候实例化iscroll
用watch来监听里面data的变化 每次变化都执行refresh()

**Comment by Hucy** [comment]
@PerseveranceZ 好像是没有一个钩子函数可以明确指出DOM结构是否完全插入(在浏览器渲染完毕),这导致无法确定`scrollTo`的时机.
我遇到问题是,在使用`vue-router`切换组件时希望可以保存之前一个页面的浏览位置,虽然有`saveScrollPosition`配置但是有时候不奏效,于是我想在dom结构渲染完毕的时候`scrollTo`之前的保存的滚动高度,就遇到问题了,我尝试使用`watch isScroll`,无论在`ready`还是`afterEnter`设置`isScroll`值,由于dom结构未渲染完毕,它在执行`watch`回调的`scrollTo`后还是会滚动...我也尝试了监听`scroll`事件设置`isScroll`,这导致的问题是页面会不停上下滚动,而且什么时候取消事件监听也成了一个问题..

我的解决方法是setTimeout(fn, _maxTime),设置一个足够长的定时器,等DOM渲染完毕后,再去设置`isScroll`的值,或者直接`scrollTo`.

不知道我的理解对不对,刚用Vue可能有些地方理解不是很对.还请多多指教...
谢谢你的回复

**Comment by PerseveranceZ** [comment]
恩 渲染完毕是没有明确出来，不过你可以试试transition 自己设置过度特效的时间 并设置transition-mode:out-in     在ready中实例化iscroll并scrollTo相对应的位置 我试了下是可以滚动的 我把代码贴出来看看能不能对你有帮助

js:
ready: function() {
        this.scroll = new IScroll('#js-scroll');  //实例化
        this.scroll && this.scroll.scrollTo(0, -100, 1000);  //滚
    },
    watch: {
        list: function() {  //监听滚动区域数据的变化
            this.$nextTick(function() {
                this.scroll && this.scroll.refresh();
            });
        },
        isCol: function() {
            this.scroll && this.scroll.refresh();
        }
    } 

html

<router-view transition="fade" transition-mode="out-in" style="position: absolute; left:0; right:0; top: 40px; bottom:0; overflow: hidden;"></router-view>


css: 
.fade-transition {
  transition: opacity .2s ease;
}
.fade-enter, .fade-leave {
  opacity: 0;
}
