### ISSUE TITLE
There is someway easy to know if some objects exists on the array.

### ISSUE THREAD

**Issue by socieboy** [yyx990803/vue#979]
So currently do that for my project this validation.
```
startConversation: function(user){
            var exists = false;
            this.conversations.forEach(function(conversation){
               if (conversation.id == user.id) exists = true;
            });
            if(! exists) this.conversations.push(user);
        }
```

Would be cool to have something like
```
if ( ! this.conversations.$has(user)){
   this.conversations.push(user);
} 
```

**Comment by yyx990803** [comment]
Vue only extends observed objects to ensure change detection; `$has` does not help with that, and therefore is not part of Vue's responsibility.

**Comment by socieboy** [comment]
So what can I do? Am I right on my way to do it?

**Comment by yyx990803** [comment]
You can use `Array.prototype.some`:

``` js
var exists = this.converstaions.some(function (conv) {
  return conv.id == user.id
})
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

**Comment by socieboy** [comment]
How to share variables trough all componentes?
```
new Vue({
    ready: function(){

        this.io = require('socket.io-client');
        this.socket = io('http://localhost:6001')
    },
    components: {
        'custom': require('./custom')
    },
```
How I have access to the socket variable on the component? I don't want to repeat code
```
module.exports = {
ready: function(){
        this.io = require('socket.io-client');
        this.socket = io('http://localhost:6001')
    },
};

**Comment by yyx990803** [comment]
`this.$root.io`

**Comment by socieboy** [comment]
it doesn't work.... if  i print on the console the object this.$root, it show me the io object right there.
but once i have to use it it show me undefined!
