### ISSUE TITLE
Surprising behavior when using a filter on a object inside v-repeat

### ISSUE THREAD

**Issue by thelinuxlich** [yyx990803/vue#980]
I don't know if it's intentional, if it is it should be better documented that the object passed to v-repeat gets transformed into a array containing objects with $key and $value before passing into the filter.

**Comment by yyx990803** [comment]
Yeah, this should be documented somewhere. It's pre-processed into an Array so that the array filters can work on `v-repeat` of an Object as well.

**Comment by Jerskouille** [comment]
@yyx990803 Hi, regarding this, couldn't there be some syntax to force the application of the filter on the object? Like `v-repeat="key: (obj | myFilter)"`?

See http://stackoverflow.com/questions/31396637/vue-js-force-a-filter-application/31454671
