### ISSUE TITLE
Two-way directive/v-model

### ISSUE THREAD

**Issue by asivaneswaran** [yyx990803/vue#984]
I got a question/issue. I have a hidden form input that gets updated via a jquery function (it's part of an autocomplete). I tried putting a v-model on that form input but I learned that it won't update. So I tried adding a custom directive:

```
Vue.directive("member-id", {
    "twoWay": true,
    bind: function () {
        this.handler = function () {
            console.log(this.el.value);
            console.log($(this).val());
            this.set(this.el.value);
        }.bind(this)
        this.el.addEventListener('change', this.handler);
    },
    unbind: function () {
        this.el.removeEventListener('change', this.handler);
    }
});
```
And I added this: v-member-id="newMember.id" to the form input. But the newMember.id is not getting updated....

Thanks,

**Comment by yyx990803** [comment]
Is the `console.log` getting called?

**Comment by asivaneswaran** [comment]
No which is weird. If I put a `console.log('test')` right before `this.handler` it shows once when the page gets loaded.

**Comment by yyx990803** [comment]
Note when you are setting the value programmatically, either via `input.value = ...` or `$(input).val(...)`, it does not trigger a `chagne` or `input` event. If you can, you should update your model directly without relying on hidden inputs.

Closing as this is not a Vue bug, feel free to continue the discussion though.

**Comment by asivaneswaran** [comment]
Oh, that make sense. Thanks. Is there a way you recommend me? Is there a way for me to set the model directly but via jquery function?
Thanks,

**Comment by yyx990803** [comment]
Setting the model is just `this.newMember.id = ...`. You don't have to do it via a jquery function.

**Comment by asivaneswaran** [comment]
Well the thing is that I have a autocomplete function to chose the member. Depending on what they chose, the id is set. I use a jquery plugin to do the autocomplete (That's before I learned about vuejs). So this is how I set it:

``` 
$('.autocomplete').autocomplete({
			serviceUrl: url,
			onSelect: function (suggestion) {
				var hidden_input = $(this).attr('name') + '_id';
				$("input[name='" + hidden_input + "'").val(suggestion.data);
			}
		});
```

**Comment by yyx990803** [comment]
Initialize autocomplete in the lifecycle hooks of the component that needs it, so that you have a reference to the component instance:

``` js
// ... your component
ready: function () {
  var self = this
  $('.autocomplete', this.$el).autocomplete({
     // ...
     onSelect: function (suggestion) {
       self.newMember.id = suggestion.data
     }
  })
}
```

And a good practice is to also teardown the autocomplete in the component's `beforeDestroy` hook.

**Comment by asivaneswaran** [comment]
Of course... -.- Thanks a lot!
