### ISSUE TITLE
Memory leak and uncleared ref for static components.

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#985]
In brief, when `unbuild()` the static component (e.g., caused by the `v-if`), it won't invoke the `unsetCurrent()` to clean the ref in its context, which leads to the situation that the component's destroyed or being destroyed (because the deferred cleanup) but its context can still manipulate it by its ref, which is unexpected. For example and more detail, check the [demo](http://jsfiddle.net/p8xx6cf8/2/).

**Comment by yyx990803** [comment]
Thanks for the detailed report, really appreciated!
