### ISSUE TITLE
sub-components

### ISSUE THREAD

**Issue by abstractFlo** [yyx990803/vue#986]
is there a way to create nested components in vue.js?

```
<newform>
    <field></field>
    <field></field>
    <field></field>
    <field></field>
    <submit></submit>
</newform>

```
In my case, only the newform component is rendered, but not the nested components.

[My files][1]

  [1]: http://laravel.io/bin/8Kww7

**Comment by Jinjiang** [comment]
See here: http://vuejs.org/guide/components.html#Content_Insertion
use `<content>` tag to insert content

**Comment by abstractFlo** [comment]
-_- sorry i don't see this before in den documentation.

It's working thanks
