### ISSUE TITLE
Watcher behavior

### ISSUE THREAD

**Issue by thelinuxlich** [yyx990803/vue#988]
I've created a watcher for a binding and was also using a computed property that was dependent on the value watched. Was positively surprised that the computed property was executed before the watcher. Is this standard behavior? I think it should be better documented on the watcher section.

**Comment by yyx990803** [comment]
Yep, computed properties and directives are considered "internal" watchers, and they always get notified before "user" watchers.

Closing and opened issue in the docs repo.
