### ISSUE TITLE
Child Component data to parent Component

### ISSUE THREAD

**Issue by abstractFlo** [yyx990803/vue#991]
Is there a way to get the data from an input component back to the form component?

Here is my html markup

```
<new-form action="#" method="POST" novalidate>
            <form-group>
                <label name="E-Mail"></label>
                <input-field name="email" type="email" get-data="@{{ getChildData }}"></input-field>
            </form-group>

            <form-group>
                <label name="Password"></label>
                <input-field name="password" type="password"></input-field>
            </form-group>

            <form-group>
                <div class="checkbox">
                    <bootstrap-checkbox name="remember" text="Remember me"></bootstrap-checkbox>
                </div>
            </form-group>

            <form-group>
                <submit classname="btn btn-primary">Sign In</submit>
            </form-group>
        </new-form>
```

Or is it a bad practice to separate all of the elements?

**Comment by nadirabid** [comment]
You can use props to communicate data between child/parent components. The website has some [documentation on communicating between instances](http://vuejs.org/guide/best-practices.html#Communication_Between_Instances).

> Or is it a bad practice to separate all of the elements?

Thats up to you. I only employ modularity when it helps simplify.

**Comment by yyx990803** [comment]
Use two-way props: http://vuejs.org/guide/components.html#Prop_Binding_Types

Also, please use vuejs/Discussions for such questions.
