### ISSUE TITLE
$add() adds empty rows

### ISSUE THREAD

**Issue by asivaneswaran** [yyx990803/vue#993]
Hi,

I have a little bug. I have this code:

` this.roster.$add(this.newMember.id, this.newMember.role); `

where id = 88 and role = player.
Then I use vuejs resource to send a post like this:

```
        submitNewMember: function() {
            this.$http.post(url,
                {
                    roster: this.roster
                }
            );
        }
```

But when I dump out the request on the server side of the roster,  I get this:
```
array:89 [
  0 => null
  1 => null
  2 => null
  3 => null
  4 => null
  5 => null
  6 => null
...
88 => 'player'
]
```

I tried passing it as a string by doing this: 

` this.roster.$add(this.newMember.id + '', this.newMember.role); `

But it's not working either... any ideas why?

**Comment by yyx990803** [comment]
For arrays you should use `$set` instead of `$add`: http://vuejs.org/guide/best-practices.html#Adding_and_Deleting_Properties

**Comment by asivaneswaran** [comment]
Ah alright. But a question about that, I have an api that returns a json format arrays. But when I set it in vue either by doing: this.roster = data or this.$set('roster', data) it converts it to an object. Why is that? and how can I avoid it.
