### ISSUE TITLE
Vue Component Binding Issue

### ISSUE THREAD

**Issue by 12wrigja** [yyx990803/vue#994]
JSBin which partially explains the issue.

http://jsbin.com/sewuwaqevi/edit?html,js,output

If you change the linked version of Vue from 12.0 to 12.4, you will notice that all the bindings change to use the parent's data binding, not the binding from the custom components. It appears that Vue is binding the parent's bindings instead of the component's bindings. Is this an issue, and if not is there a way to get the previous behaviour back?

**Comment by yyx990803** [comment]
0.12.4 has the correct and intended behavior. Read more about this: http://vuejs.org/guide/components.html#Content_Insertion and http://vuejs.org/guide/best-practices.html#Component_Scope

**Comment by 12wrigja** [comment]
Ah ok. Thanks. 

For anyone looking here in the future, the simple solution is to add ``` inline-template``` to the component tag.
