### ISSUE TITLE
How to programmatically add a component?

### ISSUE THREAD

**Issue by thelinuxlich** [yyx990803/vue#997]
I have a "metric" component which can be used inside a funnel as a series of steps. When the user clicks "New Step" a new metric component should be instantiated and when he clicks "Remove", the corresponding metric component should be removed.

With v-repeat and v-ref I'm lost on how to do this.

**Comment by yyx990803** [comment]
Please move this to vuejs/Discussion and leave main repo with only feature/bug related issues.

Sounds like you need an Array data structure representing your "steps", and the operations would simply be pushing and removing from the Array?
