### ISSUE TITLE
模板继承？

### ISSUE THREAD

**Issue by jianghai** [yyx990803/vue#998]
比如某一个DateGrid有一个特殊的click事件，就需要重新写一遍模板。

**Comment by yyx990803** [comment]
开 issue 前请阅读 readme，问题请发到 https://github.com/vuejs/Discussion/issues

模板的继承意义不大，而且我也并不是推荐组件之间有复杂的继承关系。如果有必要，重写模板在我看来可以接受。大量重复的部分可以用 partials。
